local AL = AceLibrary("AceLocale-2.1")
AL:RegisterTranslation("OneCore", "enUS", function() return {["Quiver"]=true,["Soul Bag"]=true,["Container"]=true,["Bag"]=true} end)
AL:RegisterTranslation("OneCore", "zhCN", function() return {["Quiver"]="箭袋",["Soul Bag"]="灵魂袋",["Container"]="背包",["Bag"]="包裹"} end)

AL:RegisterTranslation("OneBag", "enUS", function() return {
["Frame"]="Frame",["Frame Options"]="Frame Options",["Columns"]="Columns",["Sets the number of columns to use"]="Sets the number of columns to use",
["Scale"]="Scale",["Sets the scale of the frame"]="Sets the scale of the frame",["Strata"]="Strata",["Sets the strata of the frame"]="Sets the strata of the frame",
["Alpha"]="Alpha",["Sets the alpha of the frame"]="Sets the alpha of the frame",["Locked"]="Locked",["Toggles the ability to move the frame"]="Toggles the ability to move the frame",
["Clamped"]="Clamped",["Toggles the ability to drag the frame off screen."]="Toggles the ability to drag the frame off screen.",["Bag Break"]="Bag Break",
["Sets wether to start a new row at the beginning of a bag."]="Sets wether to start a new row at the beginning of a bag.",["Vertical Alignment"]="Vertical Alignment",
["Sets wether to have the extra spaces on the top or bottom."]="Sets wether to have the extra spaces on the top or bottom.",["Top"]="Top",["Bottom"]="Bottom",
["Sets the locale to use.  Will not take effect until you reload your UI."]="Sets the locale to use.  Will not take effect until you reload your UI.",["Show"]="Show",
["Various Display Options"]="Various Display Options",["Counts"]="Counts",["Toggles showing the counts for special bags."]="Toggles showing the counts for special bags.",
["Direction"]="Direction",["Forward"]="Forward",["Toggles direction the bags are shown"]="Toggles direction the bags are shown",["|cffff0000Reverse|r"]="|cffff0000Reverse|r",
["|cff00ff00Forward|r"]="|cff00ff00Forward|r",["Ammo Bag"]="Ammo Bag",["Turns display of ammo bags on and off."]="Turns display of ammo bags on and off.",
["Soul Bag"]="Soul Bag",["Turns display of soul bags on and off."]="Turns display of soul bags on and off.",["Profession Bag"]="Profession Bag",
["Turns display of profession bags on and off."]="Turns display of profession bags on and off.",["Backpack"]="Backpack",["Turns display of your backpack on and off."]="Turns display of your backpack on and off.",
["First Bag"]="First Bag",["Turns display of your first bag on and off."]="Turns display of your first bag on and off.",["Second Bag"]="Second Bag",
["Turns display of your second bag on and off."]="Turns display of your second bag on and off.",["Third Bag"]="Third Bag",["Turns display of your third bag on and off."]="Turns display of your third bag on and off.",
["Fourth Bag"]="Fourth Bag",["Turns display of your fourth bag on and off."]="Turns display of your fourth bag on and off.",["Fifth Bag"]="Fifth Bag",
["Turns display of your fifth bag on and off."]="Turns display of your fifth bag on and off.",["Sixth Bag"]="Sixth Bag",["Turns display of your sixth bag on and off."]="Turns display of your sixth bag on and off.",
["Bags"]="Bags",["Bank Bags"]="Bank Bags",["First Bank Bag"]="First Bank Bag",["Second Bank Bag"]="Second Bank Bag",["Third Bank Bag"]="Third Bank Bag",
["Fourth Bank Bag"]="Fourth Bank Bag",["Fifth Bank Bag"]="Fifth Bank Bag",["Sixth Bank Bag"]="Sixth Bank Bag",["Colors"]="Colors",["Different color code settings."]="Different color code settings.",
["Mouseover Color"]="Mouseover Color",["Changes the highlight color for when you mouseover a bag slot."]="Changes the highlight color for when you mouseover a bag slot.",
["Ammo Bag Color"]="Ammo Bag Color",["Changes the highlight color for Ammo Bags."]="Changes the highlight color for Ammo Bags.",["Soul Bag Color"]="Soul Bag Color",
["Changes the highlight color for Soul Bags."]="Changes the highlight color for Soul Bags.",["Profession Bag Color"]="Profession Bag Color",
["Changes the highlight color for Profession Bags."]="Changes the highlight color for Profession Bags.",["Background Color"]="Background Color",
["Changes the background color for the frame."]="Changes the background color for the frame.",["Highlight Glow"]="Highlight Glow",["Turns hightlight glow on and off."]="Turns hightlight glow on and off.",
["Rarity Coloring"]="Rarity Coloring",["Turns rarity coloring on and off."]="Turns rarity coloring on and off.",["Reset"]="Reset",["Reset the different colors."]="Reset the different colors.",
["Mouseover Color"]="Mouseover Color",["Returns your mouseover color to the default."]="Returns your mouseover color to the default.",["Ammo Slot Color"]="Ammo Slot Color",
["Returns your ammo slot color to the default."]="Returns your ammo slot color to the default.",["Soul Slot Color"]="Soul Slot Color",["Returns your soul slot color to the default."]="Returns your soul slot color to the default.",
["Profession Slot Color"]="Profession Slot Color",["Returns your profession slot color to the default."]="Returns your profession slot color to the default.",["Background"]="Background",
["Returns your frame background to the default."]="Returns your frame background to the default.",["Plow!"]="Plow!",["Organizes your bags."]="Organizes your bags.",
["- Note: This option only appears if you have MrPlow installed"]="- Note: This option only appears if you have MrPlow installed",["Pick Locale"]="Pick Locale",
["%s ran in %s"]="%s ran in %s",["Checking if bag %s is open"]="Checking if bag %s is open",["Opening bag %s"]="Opening bag %s",["Closing bag %s"]="Closing bag %s",
["Normal used: %s, Soul used: %s, Prof used: %s, Ammo used %s, Ammo quantity %s."]="Normal used: %s, Soul used: %s, Prof used: %s, Ammo used %s, Ammo quantity %s.",
["%s/%s Slots"]="%s/%s Slots",["%s/%s Ammo"]="%s/%s Ammo",["%s/%s Soul Shards"]="%s/%s Soul Shards",["%s/%s Profession Slots"]="%s/%s Profession Slots",
["Menu"]="Menu",["packup"]="packup",["Keyring"]="Keyring",["Turns display of your keyring on and off."]="Turns display of your keyring on and off.",
["Turns display of your first bank bag on and off."]="Turns display of your first bank bag on and off.",["Turns display of your second bank bag on and off."]="Turns display of your second bank bag on and off.",
["Turns display of your third bank bag on and off."]="Turns display of your third bank bag on and off.",["Turns display of your fourth bank bag on and off."]="Turns display of your fourth bank bag on and off.",
["Turns display of your fifth bank bag on and off."]="Turns display of your fifth bank bag on and off.",["Turns display of your sixth bank bag on and off."]="Turns display of your sixth bank bag on and off.",
["Search"]="Search",
["Category Filters"]="Category Filters",
["Toggles visibility of category filter modules"]="Toggles visibility of category filter modules",
} end)

AL:RegisterTranslation("OneBag", "zhCN", function() return {
["Frame"]="框体",["Frame Options"]="框体设置",["Columns"]="栏数",["Sets the number of columns to use"]="设置每行的背包格子数量",
["Scale"]="缩放",["Sets the scale of the frame"]="设置框体缩放比例",["Strata"]="层级",["Sets the strata of the frame"]="设置框体显示优先级",
["Alpha"]="透明度",["Sets the alpha of the frame"]="设置框体透明度",["Locked"]="锁定",["Toggles the ability to move the frame"]="切换是否锁定框体位置",
["Clamped"]="限制",["Toggles the ability to drag the frame off screen."]="切换是否限制框体位置使其不能被拖动到屏幕边缘之外。",["Bag Break"]="背包分隔",
["Sets wether to start a new row at the beginning of a bag."]="设置是否在背包的起始位置前增加一格。",["Vertical Alignment"]="垂直对齐",
["Sets wether to have the extra spaces on the top or bottom."]="设置是否在顶端或底端显示额外的空间。",["Top"]="顶端",["Bottom"]="底端",
["Sets the locale to use.  Will not take effect until you reload your UI."]="设置要使用的语言。需要重新加载界面后才能生效。",["Show"]="显示",
["Various Display Options"]="各种显示设置",["Counts"]="计数",["Toggles showing the counts for special bags."]="切换是否显示特殊背包的格子计数。",
["Direction"]="方向",["Forward"]="正向",["Toggles direction the bags are shown"]="切换背包显示顺序",["|cffff0000Reverse|r"]="|cffff0000反向|r",
["|cff00ff00Forward|r"]="|cff00ff00正向|r",["Ammo Bag"]="弹药袋",["Turns display of ammo bags on and off."]="切换是否显示弹药袋。",
["Soul Bag"]="灵魂袋",["Turns display of soul bags on and off."]="切换是否显示灵魂袋。",["Profession Bag"]="专业袋",
["Turns display of profession bags on and off."]="切换是否显示专业袋。",["Backpack"]="背包",["Turns display of your backpack on and off."]="切换是否显示背包。",
["First Bag"]="第一个包",["Turns display of your first bag on and off."]="切换是否显示第一个包。",["Second Bag"]="第二个包",
["Turns display of your second bag on and off."]="切换是否显示第二个包。",["Third Bag"]="第三个包",["Turns display of your third bag on and off."]="切换是否显示第三个包。",
["Fourth Bag"]="第四个包",["Turns display of your fourth bag on and off."]="切换是否显示第四个包。",["Fifth Bag"]="第五个包",
["Turns display of your fifth bag on and off."]="切换是否显示第五个包。",["Sixth Bag"]="第六个包",["Turns display of your sixth bag on and off."]="切换是否显示第六个包。",
["Bags"]="背包",["Bank Bags"]="银行",["First Bank Bag"]="第一个银行包",["Second Bank Bag"]="第二个银行包",["Third Bank Bag"]="第三个银行包",
["Fourth Bank Bag"]="第四个银行包",["Fifth Bank Bag"]="第五个银行包",["Sixth Bank Bag"]="第六个银行包",["Colors"]="颜色",["Different color code settings."]="各种颜色设置。",
["Mouseover Color"]="鼠标悬浮颜色",["Changes the highlight color for when you mouseover a bag slot."]="变更鼠标悬浮于背包格子上时的高亮颜色。",
["Ammo Bag Color"]="弹药袋颜色",["Changes the highlight color for Ammo Bags."]="变更弹药袋的高亮颜色。",["Soul Bag Color"]="灵魂袋颜色",
["Changes the highlight color for Soul Bags."]="变更灵魂袋的高亮颜色。",["Profession Bag Color"]="专业袋颜色",["Changes the highlight color for Profession Bags."]="变更专业袋的高亮颜色。",
["Background Color"]="背景颜色",["Changes the background color for the frame."]="变更框体背景颜色。",["Highlight Glow"]="高亮发光",
["Turns hightlight glow on and off."]="开关高亮发光。",["Rarity Coloring"]="品质颜色",["Turns rarity coloring on and off."]="开关品质颜色。",
["Reset"]="重置",["Reset the different colors."]="重置各种颜色设置",["Mouseover Color"]="鼠标悬浮颜色",["Returns your mouseover color to the default."]="重置鼠标悬浮颜色为默认设置。",
["Ammo Slot Color"]="弹药格颜色",["Returns your ammo slot color to the default."]="重置弹药格颜色为默认设置。",["Soul Slot Color"]="灵魂格颜色",
["Returns your soul slot color to the default."]="重置灵魂格颜色为默认设置。",["Profession Slot Color"]="专业格颜色",["Returns your profession slot color to the default."]="重置专业格颜色为默认设置。",
["Background"]="背景",["Returns your frame background to the default."]="重置背景颜色为默认设置。",["Plow!"]="整理！",["Organizes your bags."]="整理你的背包。",
["- Note: This option only appears if you have MrPlow installed"]="- 注意：只有当你安装了Mr.Plow插件时才会出现此设置",["Pick Locale"]="选择语言",
["%s ran in %s"]="%s运行于%s下",["Checking if bag %s is open"]="检测背包%s是否是打开状态",["Opening bag %s"]="打开背包%s",["Closing bag %s"]="关闭背包%s",
["Normal used: %s, Soul used: %s, Prof used: %s, Ammo used %s, Ammo quantity %s."]="普通背包已用：%s，灵魂袋已用：%s，专业袋已用：%s，弹药袋已用：%s，弹药品质：%s。",
["%s/%s Slots"]="%s/%s背包",["%s/%s Ammo"]="%s/%s弹药",["%s/%s Soul Shards"]="%s/%s灵魂碎片",["%s/%s Profession Slots"]="%s/%s专业袋",
["Menu"]="背包设置",["packup"]="整理",["Keyring"]="钥匙链",["Turns display of your keyring on and off."]="切换是否显示钥匙链。",
["Turns display of your first bank bag on and off."]="切换是否显示第一个银行包。",["Turns display of your second bank bag on and off."]="切换是否显示第二个银行包。",
["Turns display of your third bank bag on and off."]="切换是否显示第三个银行包。",["Turns display of your fourth bank bag on and off."]="切换是否显示第四个银行包。",
["Turns display of your fifth bank bag on and off."]="切换是否显示第五个银行包。",["Turns display of your sixth bank bag on and off."]="切换是否显示第六个银行包。",
["Search"]="搜索",
["Category Filters"]="分类过滤模块",
["Toggles visibility of category filter modules"]="切换分类过滤模块的显示/隐藏",
} end)

-- 添加 OneView 的翻译注册
AL:RegisterTranslation("OneView", "enUS", function() return {
["%s's Bank Bags"] = "%s's Bank Bags",
["%s's Bags"] = "%s's Bags",
["Backpack"] = "Backpack",
["First Bag"] = "First Bag",
["Second Bag"] = "Second Bag",
["Third Bag"] = "Third Bag",
["Fourth Bag"] = "Fourth Bag",
["First Bank Bag"] = "First Bank Bag",
["Second Bank Bag"] = "Second Bank Bag",
["Third Bank Bag"] = "Third Bank Bag",
["Fourth Bank Bag"] = "Fourth Bank Bag",
["Fifth Bank Bag"] = "Fifth Bank Bag",
["Sixth Bank Bag"] = "Sixth Bank Bag",
["Turns display of your backpack on and off."] = "Turns display of your backpack on and off.",
["Turns display of your first bag on and off."] = "Turns display of your first bag on and off.",
["Turns display of your second bag on and off."] = "Turns display of your second bag on and off.",
["Turns display of your third bag on and off."] = "Turns display of your third bag on and off.",
["Turns display of your fourth bag on and off."] = "Turns display of your fourth bag on and off.",
["Turns display of your first bag on and off."] = "Turns display of your first bag on and off.",
["Turns display of your second bag on and off."] = "Turns display of your second bag on and off.",
["Turns display of your third bag on and off."] = "Turns display of your third bag on and off.",
["Turns display of your fourth bag on and off."] = "Turns display of your fourth bag on and off.",
["Turns display of your fifth bag on and off."] = "Turns display of your fifth bag on and off.",
["Turns display of your sixth bag on and off."] = "Turns display of your sixth bag on and off.",
["Remember"] = "Remember",
["Remember Selection"] = "Remember Selection",
["Toggles wether to remember which was the last character you selected."] = "Toggles wether to remember which was the last character you selected.",
["Search"] = "Search",
["Characters on "] = "Characters on ",  -- 添加这一行
} end)

AL:RegisterTranslation("OneView", "zhCN", function() return {
["%s's Bank Bags"] = "%s的银行",
["%s's Bags"] = "%s的背包",
["Backpack"] = "背包",
["First Bag"] = "第一个包",
["Second Bag"] = "第二个包",
["Third Bag"] = "第三个包",
["Fourth Bag"] = "第四个包",
["First Bank Bag"] = "第一个银行包",
["Second Bank Bag"] = "第二个银行包",
["Third Bank Bag"] = "第三个银行包",
["Fourth Bank Bag"] = "第四个银行包",
["Fifth Bank Bag"] = "第五个银行包",
["Sixth Bank Bag"] = "第六个银行包",
["Turns display of your backpack on and off."] = "切换是否显示背包。",
["Turns display of your first bag on and off."] = "切换是否显示第一个包。",
["Turns display of your second bag on and off."] = "切换是否显示第二个包。",
["Turns display of your third bag on and off."] = "切换是否显示第三个包。",
["Turns display of your fourth bag on and off."] = "切换是否显示第四个包。",
["Turns display of your first bag on and off."] = "切换是否显示第一个银行包。",
["Turns display of your second bag on and off."] = "切换是否显示第二个银行包。",
["Turns display of your third bag on and off."] = "切换是否显示第三个银行包。",
["Turns display of your fourth bag on and off."] = "切换是否显示第四个银行包。",
["Turns display of your fifth bag on and off."] = "切换是否显示第五个银行包。",
["Turns display of your sixth bag on and off."] = "切换是否显示第六个银行包。",
["Remember"] = "记住",
["Remember Selection"] = "记住选择",
["Toggles wether to remember which was the last character you selected."] = "切换是否记住上次选择的角色。",
["Search"] = "搜索",
["Characters on "] = "服务器：",  -- 添加这一行，中文翻译为"服务器："
} end)