local L = AceLibrary("AceLocale-2.2"):new("MikScrollingBattleText")

L:RegisterTranslations("zhCN", function()
    return {
		["Debug mode has been enabled."] = "调试模式已启用",
		["Debug mode has been disabled."] = "调试模式已被禁用",
		["Event search mode has been enabled.  Searching for: "] = "事件搜索模式已启用。寻找",
		["Event search mode has been disabled."] = "事件搜索模式已被禁用",
		["The mod is now disabled."] = "模式禁用",
		["The mod is now enabled."] = "模式开启",
		["Hits"] = "击中",
		["Crit"] = "暴击",
		["Crits"] = "暴击数",
		["Multiple"] = "多重",
		[" (%d vulnerability)"] = "(%d 弱点)",
		[" <\124cff00b37e\124h%d\124h\124r>"] = " <\124cff00b37e\124h%d\124h\124r>",
		["Profile Reset"] = "简介复位",
		["Drowning"] = "溺水",
		["Falling"] = "坠落",
		["Fatigue"] = "疲劳",
		["Fire"] = "火焰",
		["Lava"] = "熔岩",
		["Slime"] = "粘液",
		["Windfury!"]="风怒!",
		["Low Mana! (%1)"]="低法力值! (%1)",
		["Low Pet Health! (%1)"]="宠物低血量! (%1)",
		["%a CP Finish It!"]="%a CP 完成!",
		["+Combat"]="+进入战斗",
		["-Combat"]="-脱离战斗",
		["%a CP"]="%a CP",
		["Pet "]="宠物 ",
		["Pet %a (%s)"]="宠物 %a (%s)",
		["Pet %a"]="宠物 %a",
		["-%a (Pet)"]="-%a (宠物)",
		["! (Pet)"]="! (宠物)",
		["+%a (%n) (Pet)"]="+%a (%n) (宠物)",
		["Killing Blow! (%s)"]="击杀! (%s)",
		["Low Health! (%1)"]="低血量! (%1)",
		["SPELL_SCHOOL1_CAP"]="神圣",
		["SPELL_SCHOOL2_CAP"]="火焰",
		["SPELL_SCHOOL3_CAP"]="自然",
		["SPELL_SCHOOL4_CAP"]="冰霜",
		["SPELL_SCHOOL5_CAP"]="暗影",
		["SPELL_SCHOOL6_CAP"]="奥术";
    }
end)