IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "bm\\"

local BM = {}

BM.Name = IJ_DB_DUNGEON_BM_NAME
BM.Story = IJ_DB_DUNGEON_BM_STORY
BM.Type = IJLib.InstanceType.Dungeon
BM.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
BM.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
BM.MapId = IMI.TheBlackMorass
BM.ZoneId = IZI.BM2
BM.IconScale = 1.0
BM.MinLevel = 60
BM.MaxLevel = 60
BM.Entrances = {
    [1] = {
        MapContinentId = IMI.Kalimdor,
        MapZoneId = IZI.CavernsOfTime,
        MapCoordinateX = 34.3,
        MapCoordinateY = 85.2,
        MapDestinationZoneId = IZI.BM2
    },
}
BM.Links = {
    [1] = {
        OriginMapContinentId = IMI.TheBlackMorass,
        OriginMapZoneId = IZI.BM2,
        OriginMapCoordinateX = 18.3,
        OriginMapCoordinateY = 39.7,
        DestinationMapContinentId = IMI.TheBlackMorass,
        DestinationMapZoneId = IZI.BM1,
        Type = IJLib.EntranceIconType.Down,
        Name = IJ_DB_DUNGEON_BM_LINK_BM,
    },
    [2] = {
        OriginMapContinentId = IMI.TheBlackMorass,
        OriginMapZoneId = IZI.BM1,
        OriginMapCoordinateX = 50.2,
        OriginMapCoordinateY = 16.9,
        DestinationMapContinentId = IMI.TheBlackMorass,
        DestinationMapZoneId = IZI.BM2,
        Type = IJLib.EntranceIconType.Up,
        Name = IJ_DB_DUNGEON_BM_LINK_BM,
    },
}
BM.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "65113",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "chronar" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "chronar" .. IMPF,
        Name = IJ_DB_DUNGEON_BM_BOSS_NAME_65113,
        Story = IJ_DB_DUNGEON_BM_BOSS_STORY_65113,
        MapCoordinateX = 32.0,
        MapCoordinateY = 27.4,
        MapId = IZI.BM2,
        MapIsBelow = true,
        Loot = {
            [1] = {
                Id = "61016",
                Icon = "INV_Sword_10",
                Name = IJ_LOOT_NAME_61016,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "61018",
                Icon = "INV_Misc_Cape_02",
                Name = IJ_LOOT_NAME_61018,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "61019",
                Icon = "INV_Wand_05",
                Name = IJ_LOOT_NAME_61019,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "61036",
                Icon = "INV_Boots_01",
                Name = IJ_LOOT_NAME_61036,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "61047",
                Icon = "INV_Helmet_22",
                Name = IJ_LOOT_NAME_61047,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "61048",
                Icon = "INV_Belt_10",
                Name = IJ_LOOT_NAME_61048,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "70226",
                Icon = "INV_Misc_Bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
            },
        },
    },
    [2] = { -- NOTE: Missing abilities
        Id = "61575",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "epidamu" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "epidamu" .. IMPF,
        Name = IJ_DB_DUNGEON_BM_BOSS_NAME_61575,
        Story = IJ_DB_DUNGEON_BM_BOSS_STORY_61575,
        MapCoordinateX = 26.1,
        MapCoordinateY = 17.2,
        MapId = IZI.BM2,
        MapIsBelow = true,
        Loot = {
            [1] = {
                Id = "50431",
                Icon = "INV_Bracer_13",
                Name = IJ_LOOT_NAME_50431,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "61032",
                Icon = "INV_Jewelry_Ring_48Naxxramas",
                Name = IJ_LOOT_NAME_61032,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "61041",
                Icon = "INV_Belt_28",
                Name = IJ_LOOT_NAME_61041,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "61045",
                Icon = "INV_Shoulder_07",
                Name = IJ_LOOT_NAME_61045,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "61055",
                Icon = "INV_Misc_Book_01",
                Name = IJ_LOOT_NAME_61055,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "61056",
                Icon = "INV_Boots_07",
                Name = IJ_LOOT_NAME_61056,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "61698",
                Icon = "INV_QirajIdol_Life",
                Name = IJ_LOOT_NAME_61698,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Totem,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "61700",
                Icon = "inv_fabric_celestial_cloth",
                Name = IJ_LOOT_NAME_61700,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 12,
                LevelRequirement = 60,
            },
        },
    },
    [3] = { -- NOTE: Missing abilities
        Id = "61316",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "avatar" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "avatar" .. IMPF,
        Name = IJ_DB_DUNGEON_BM_BOSS_NAME_61316,
        Story = IJ_DB_DUNGEON_BM_BOSS_STORY_61316,
        MapCoordinateX = 32.8,
        MapCoordinateY = 12.9,
        MapId = IZI.BM2,
        Loot = {
            [1] = {
                Id = "61015",
                Icon = "INV_Jewelry_Necklace_04",
                Name = IJ_LOOT_NAME_61015,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "61020",
                Icon = "INV_Wand_02",
                Name = IJ_LOOT_NAME_61020,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 2,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "61024",
                Icon = "INV_Boots_01",
                Name = IJ_LOOT_NAME_61024,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "61033",
                Icon = "INV_Pants_06",
                Name = IJ_LOOT_NAME_61033,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "61038",
                Icon = "inv_misc_desecrated_plateshoulder",
                Name = IJ_LOOT_NAME_61038,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "61042",
                Icon = "INV_Gauntlets_11",
                Name = IJ_LOOT_NAME_61042,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.FistWeapon,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "61044",
                Icon = "INV_Hammer_04",
                Name = IJ_LOOT_NAME_61044,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "61057",
                Icon = "INV_Gauntlets_24",
                Name = IJ_LOOT_NAME_61057,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "70226",
                Icon = "INV_Misc_Bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
            },
        },
    },
    [4] = { -- NOTE: Missing abilities
        Id = "65116",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "epochronos" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "epochronos" .. IMPF,
        Name = IJ_DB_DUNGEON_BM_BOSS_NAME_65116,
        Story = IJ_DB_DUNGEON_BM_BOSS_STORY_65116,
        MapCoordinateX = 29.0,
        MapCoordinateY = 25.2,
        MapId = IZI.BM2,
        Loot = {
            [1] = {
                Id = "50428",
                Icon = "INV_Belt_06",
                Name = IJ_LOOT_NAME_50428,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "50430",
                Icon = "INV_Misc_Cape_16",
                Name = IJ_LOOT_NAME_50430,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "61017",
                Icon = "inv_shoulder_16",
                Name = IJ_LOOT_NAME_61017,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "61021",
                Icon = "INV_Bracer_09",
                Name = IJ_LOOT_NAME_61021,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "61022",
                Icon = "INV_Weapon_Shortblade_38",
                Name = IJ_LOOT_NAME_61022,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Dagger,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "61028",
                Icon = "inv_shield_05",
                Name = IJ_LOOT_NAME_61028,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "61049",
                Icon = "INV_Sword_19",
                Name = IJ_LOOT_NAME_61049,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 1,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "61054",
                Icon = "INV_Pants_03",
                Name = IJ_LOOT_NAME_61054,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "61058",
                Icon = "INV_Pants_04",
                Name = IJ_LOOT_NAME_61058,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "70226",
                Icon = "INV_Misc_Bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
            },
        },
    },
    [5] = { -- NOTE: Missing abilities
        Id = "65124",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "mossheart" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "mossheart" .. IMPF,
        Name = IJ_DB_DUNGEON_BM_BOSS_NAME_65124,
        Story = IJ_DB_DUNGEON_BM_BOSS_STORY_65124,
        MapCoordinateX = 69.1,
        MapCoordinateY = 51.0,
        MapId = IZI.BM1,
        Loot = {
            [1] = {
                Id = "61050",
                Icon = "INV_Gauntlets_11",
                Name = IJ_LOOT_NAME_61050,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 16,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "61051",
                Icon = "INV_Misc_Root_01",
                Name = IJ_LOOT_NAME_61051,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 16,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "61059",
                Icon = "INV_Misc_Gem_Stone_01",
                Name = IJ_LOOT_NAME_61059,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 16,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "61060",
                Icon = "INV_Helmet_32",
                Name = IJ_LOOT_NAME_61060,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 16,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "61061",
                Icon = "INV_Chest_Cloth_01",
                Name = IJ_LOOT_NAME_61061,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 16,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "61062",
                Icon = "INV_Belt_21",
                Name = IJ_LOOT_NAME_61062,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 16,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "70226",
                Icon = "INV_Misc_Bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
            },
        },
    },
    [6] = { -- NOTE: Missing abilities
        Id = "65125",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "antnormi" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "antnormi" .. IMPF,
        Name = IJ_DB_DUNGEON_BM_BOSS_NAME_65125,
        Story = IJ_DB_DUNGEON_BM_BOSS_STORY_65125,
        MapCoordinateX = 48.0,
        MapCoordinateY = 74.6,
        MapId = IZI.BM1,
        Loot = {
            [1] = {
                Id = "50427",
                Icon = "INV_Chest_Leather_08",
                Name = IJ_LOOT_NAME_50427,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 50,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "61053",
                Icon = "INV_Helmet_24",
                Name = IJ_LOOT_NAME_61053,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Mail,
                DropChance = 50,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "50429",
                Icon = "INV_Spear_07",
                Name = IJ_LOOT_NAME_50429,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 33,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "61037",
                Icon = "inv_chest_plate02",
                Name = IJ_LOOT_NAME_61037,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 33,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "61046",
                Icon = "INV_Axe_08",
                Name = IJ_LOOT_NAME_61046,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Axe,
                DropChance = 33,
            },
            [6] = {
                Id = "51217",
                Icon = "INV_Misc_Ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [7] = {
                Id = "61014",
                Icon = "INV_Enchant_EssenceAstralLarge",
                Name = IJ_LOOT_NAME_61014,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 1,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "61027",
                Icon = "INV_Shoulder_24",
                Name = IJ_LOOT_NAME_61027,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "61031",
                Icon = "INV_Staff_07",
                Name = IJ_LOOT_NAME_61031,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 33,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "61040",
                Icon = "INV_Gauntlets_05",
                Name = IJ_LOOT_NAME_61040,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "61043",
                Icon = "Spell_Shadow_SoulGem",
                Name = IJ_LOOT_NAME_61043,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 1,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "70226",
                Icon = "INV_Misc_Bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 3,
            },
        },
    },
    [7] = { -- NOTE: Missing abilities
        Id = "65122",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "rotmaw" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "rotmaw" .. IMPF,
        Name = IJ_DB_DUNGEON_BM_BOSS_NAME_65122,
        Story = IJ_DB_DUNGEON_BM_BOSS_STORY_65122,
        MapCoordinateX = 25.0,
        MapCoordinateY = 79.6,
        MapId = IZI.BM1,
        Loot = {
            [1] = {
                Id = "61023",
                Icon = "INV_Chest_Leather_08",
                Name = IJ_LOOT_NAME_61023,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "61025",
                Icon = "INV_Misc_Lantern_01",
                Name = IJ_LOOT_NAME_61025,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "61029",
                Icon = "INV_Jewelry_Necklace_22",
                Name = IJ_LOOT_NAME_61029,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "61030",
                Icon = "INV_Fishingpole_02",
                Name = IJ_LOOT_NAME_61030,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "61034",
                Icon = "INV_Jewelry_Ring_12",
                Name = IJ_LOOT_NAME_61034,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "61063",
                Icon = "INV_Misc_MonsterFang_01",
                Name = IJ_LOOT_NAME_61063,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "61699",
                Icon = "INV_QirajIdol_War",
                Name = IJ_LOOT_NAME_61699,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Idol,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "61701",
                Icon = "INV_Helmet_41",
                Name = IJ_LOOT_NAME_61701,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "70226",
                Icon = "INV_Misc_Bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
            },
        },
    },
}

IJDB.DG.BM = BM
