IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "brd\\"

local BRD = {}

BRD.Name = IJ_DB_DUNGEON_BRD_NAME
BRD.Story = IJ_DB_DUNGEON_BRD_STORY
BRD.Type = IJLib.InstanceType.Dungeon
BRD.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
BRD.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
BRD.MapId = IMI.BlackrockDepths
BRD.IconScale = 0.6
BRD.MinLevel = 50
BRD.MaxLevel = 60
BRD.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.BlackrockMountain,
        MapCoordinateX = 24.6,
        MapCoordinateY = 12.6,
    },
}
BRD.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "9018",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "gerstahn" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "gerstahn" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9018,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9018,
        MapCoordinateX = 51.3,
        MapCoordinateY = 93.6,
        Loot = {
            [1] = {
                Id = "11624",
                Icon = "inv_shoulder_25",
                Name = IJ_LOOT_NAME_11624,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 47,
            },
            [2] = {
                Id = "11625",
                Icon = "inv_misc_orb_03",
                Name = IJ_LOOT_NAME_11625,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [3] = {
                Id = "11626",
                Icon = "inv_misc_cape_18",
                Name = IJ_LOOT_NAME_11626,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [4] = {
                Id = "22240",
                Icon = "inv_boots_chain_04",
                Name = IJ_LOOT_NAME_22240,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [5] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [6] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [2] = { -- NOTE: Missing abilities
        Id = "9025",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "roccor" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "roccor" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9025,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9025,
        MapCoordinateX = 54.3,
        MapCoordinateY = 77.9,
        IsRare = true,
        Loot = {
            [1] = {
                Id = "11624",
                Icon = "inv_shoulder_25",
                Name = IJ_LOOT_NAME_11624,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 47,
            },
            [2] = {
                Id = "11625",
                Icon = "inv_misc_orb_03",
                Name = IJ_LOOT_NAME_11625,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [3] = {
                Id = "11626",
                Icon = "inv_misc_cape_18",
                Name = IJ_LOOT_NAME_11626,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [4] = {
                Id = "22240",
                Icon = "inv_boots_chain_04",
                Name = IJ_LOOT_NAME_22240,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [5] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [6] = {
                Id = "11631",
                Icon = "inv_shield_02",
                Name = IJ_LOOT_NAME_11631,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 25,
                LevelRequirement = 47,
            },
            [7] = {
                Id = "11632",
                Icon = "inv_shoulder_26",
                Name = IJ_LOOT_NAME_11632,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 47,
            },
            [8] = {
                Id = "22234",
                Icon = "inv_shoulder_09",
                Name = IJ_LOOT_NAME_22234,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [9] = {
                Id = "22397",
                Icon = "inv_relics_idolofferocity",
                Name = IJ_LOOT_NAME_22397,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Idol,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [10] = {
                Id = "11813",
                Icon = "inv_misc_note_01",
                Name = IJ_LOOT_NAME_11813,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 15,
            },
            [11] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [12] = {
                Id = "11630",
                Icon = "inv_ammo_bullet_02",
                Name = IJ_LOOT_NAME_11630,
                Quality = IQ.Rare,
                ItemSlot = IS.Projectile,
                ItemType = IT.Bullet,
                DropChance = 16,
                LevelRequirement = 47,
            },
        }
    },
    [3] = { -- NOTE: Missing abilities
        Id = "9319",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "grebmar" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "grebmar" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9319,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9319,
        MapCoordinateX = 56.3,
        MapCoordinateY = 69.1,
        Loot = {
            [1] = {
                Id = "11623",
                Icon = "inv_misc_cape_20",
                Name = IJ_LOOT_NAME_11623,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 47,
            },
            [2] = {
                Id = "11627",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_11627,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [3] = {
                Id = "11628",
                Icon = "inv_weapon_bow_04",
                Name = IJ_LOOT_NAME_11628,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [4] = {
                Id = "11629",
                Icon = "inv_weapon_rifle_07",
                Name = IJ_LOOT_NAME_11629,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Gun,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [5] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [6] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [4] = { -- NOTE: Missing abilities
        Id = "9031",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "ring" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "ring" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9031,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9031,
        MapCoordinateX = 53.7,
        MapCoordinateY = 71.7,
        Loot = {
            [1] = {
                Id = "11675",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_11675,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 33,
                LevelRequirement = 50,
            },
            [2] = {
                Id = "11677",
                Icon = "inv_misc_cape_19",
                Name = IJ_LOOT_NAME_11677,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 50,
            },
            [3] = {
                Id = "11731",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_11731,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 33,
                LevelRequirement = 52,
            },
            [4] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [5] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [6] = {
                Id = "11678",
                Icon = "inv_chest_plate08",
                Name = IJ_LOOT_NAME_11678,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 15,
                LevelRequirement = 50,
            },
            [7] = {
                Id = "11679",
                Icon = "inv_bracer_13",
                Name = IJ_LOOT_NAME_11679,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 50,
            },
            [8] = {
                Id = "11685",
                Icon = "inv_shoulder_13",
                Name = IJ_LOOT_NAME_11685,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 50,
            },
            [9] = {
                Id = "11686",
                Icon = "inv_belt_12",
                Name = IJ_LOOT_NAME_11686,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 50,
            },
            [10] = {
                Id = "11730",
                Icon = "inv_gauntlets_04",
                Name = IJ_LOOT_NAME_11730,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [11] = {
                Id = "22257",
                Icon = "inv_jewelry_ring_36",
                Name = IJ_LOOT_NAME_22257,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 30,
                LevelRequirement = 52,
            },
            [12] = {
                Id = "22271",
                Icon = "inv_pants_leather_21",
                Name = IJ_LOOT_NAME_22271,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 30,
                LevelRequirement = 52,
            },
            [13] = {
                Id = "22266",
                Icon = "inv_spear_01",
                Name = IJ_LOOT_NAME_22266,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [14] = {
                Id = "11726",
                Icon = "inv_chest_chain_15",
                Name = IJ_LOOT_NAME_11726,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 15,
                LevelRequirement = 52,
            },
            [15] = {
                Id = "11610",
                Icon = "inv_scroll_03",
                Name = IJ_LOOT_NAME_11610,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 100,
            },
            [16] = {
                Id = "11702",
                Icon = "inv_axe_12",
                Name = IJ_LOOT_NAME_11702,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Axe,
                DropChance = 25,
                LevelRequirement = 50,
            },
            [17] = {
                Id = "11703",
                Icon = "inv_belt_16",
                Name = IJ_LOOT_NAME_11703,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 50,
            },
            [18] = {
                Id = "11722",
                Icon = "inv_shoulder_30",
                Name = IJ_LOOT_NAME_11722,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 50,
            },
            [19] = {
                Id = "22270",
                Icon = "inv_boots_plate_02",
                Name = IJ_LOOT_NAME_22270,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 50,
            },
            [20] = {
                Id = "11633",
                Icon = "inv_chest_plate02",
                Name = IJ_LOOT_NAME_11633,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 49,
            },
            [21] = {
                Id = "11634",
                Icon = "inv_gauntlets_12",
                Name = IJ_LOOT_NAME_11634,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 49,
            },
            [22] = {
                Id = "11635",
                Icon = "inv_weapon_shortblade_10",
                Name = IJ_LOOT_NAME_11635,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 25,
                LevelRequirement = 49,
            },
            [23] = {
                Id = "11729",
                Icon = "inv_helmet_01",
                Name = IJ_LOOT_NAME_11729,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [24] = {
                Id = "11662",
                Icon = "inv_belt_29",
                Name = IJ_LOOT_NAME_11662,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 49,
            },
            [25] = {
                Id = "11665",
                Icon = "inv_gauntlets_15",
                Name = IJ_LOOT_NAME_11665,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 49,
            },
            [26] = {
                Id = "11728",
                Icon = "inv_pants_03",
                Name = IJ_LOOT_NAME_11728,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [27] = {
                Id = "11824",
                Icon = "inv_jewelry_ring_08",
                Name = IJ_LOOT_NAME_11824,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 49,
            },
        }
    },
    [5] = { -- NOTE: Missing abilities
        Id = "9024",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "loregrain" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "loregrain" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9024,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9024,
        MapCoordinateX = 57.1,
        MapCoordinateY = 76.0,
        IsRare = true,
        Loot = {
            [1] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [2] = {
                Id = "11207",
                Icon = "inv_misc_note_01",
                Name = IJ_LOOT_NAME_11207,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 16,
            },
            [3] = {
                Id = "11750",
                Icon = "inv_staff_18",
                Name = IJ_LOOT_NAME_11750,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [4] = {
                Id = "11749",
                Icon = "inv_pants_03",
                Name = IJ_LOOT_NAME_11749,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [5] = {
                Id = "11748",
                Icon = "inv_staff_13",
                Name = IJ_LOOT_NAME_11748,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [6] = {
                Id = "11747",
                Icon = "inv_chest_cloth_07",
                Name = IJ_LOOT_NAME_11747,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 48,
            },
        }
    },
    [6] = { -- NOTE: Missing abilities
        Id = "9041",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "stilgiss" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "stilgiss" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9041,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9041,
        MapCoordinateX = 60.6,
        MapCoordinateY = 53.0,
        IsRare = true,
        Loot = {
            [1] = {
                Id = "11782",
                Icon = "inv_shoulder_02",
                Name = IJ_LOOT_NAME_11782,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [2] = {
                Id = "11783",
                Icon = "inv_belt_33",
                Name = IJ_LOOT_NAME_11783,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [3] = {
                Id = "11784",
                Icon = "inv_sword_23",
                Name = IJ_LOOT_NAME_11784,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Sword,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [4] = {
                Id = "22241",
                Icon = "inv_shoulder_07",
                Name = IJ_LOOT_NAME_22241,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [5] = {
                Id = "11755",
                Icon = "inv_misc_bandage_14",
                Name = IJ_LOOT_NAME_11755,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 13,
                LevelRequirement = 51,
            },
            [6] = {
                Id = "22242",
                Icon = "inv_belt_18",
                Name = IJ_LOOT_NAME_22242,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 13,
                LevelRequirement = 51,
            },
            [7] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [7] = { -- NOTE: Missing abilities
        Id = "9476",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "vault" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "vault" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9476,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9476,
        MapCoordinateX = 61.8,
        MapCoordinateY = 54.6,
        Loot = {
            [1] = {
                Id = "22256",
                Icon = "inv_gauntlets_17",
                Name = IJ_LOOT_NAME_22256,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 2,
                LevelRequirement = 52,
            },
            [2] = {
                Id = "22205",
                Icon = "inv_bracer_14",
                Name = IJ_LOOT_NAME_22205,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 2,
                LevelRequirement = 52,
            },
            [3] = {
                Id = "22254",
                Icon = "inv_wand_02",
                Name = IJ_LOOT_NAME_22254,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 1,
                LevelRequirement = 52,
            },
        }
    },
    [8] = { -- NOTE: Missing abilities
        Id = "9056",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "darkvire" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "darkvire" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9056,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9056,
        MapCoordinateX = 62.8,
        MapCoordinateY = 41.2,
        Loot = {
            [1] = {
                Id = "11839",
                Icon = "inv_helmet_44",
                Name = IJ_LOOT_NAME_11839,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 50,
            },
            [2] = {
                Id = "11841",
                Icon = "inv_pants_09",
                Name = IJ_LOOT_NAME_11841,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 50,
            },
            [3] = {
                Id = "11842",
                Icon = "inv_shoulder_15",
                Name = IJ_LOOT_NAME_11842,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 50,
            },
            [4] = {
                Id = "22223",
                Icon = "inv_helmet_20",
                Name = IJ_LOOT_NAME_22223,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 50,
            },
            [5] = {
                Id = "56098",
                Icon = "inv_misc_note_06",
                Name = IJ_LOOT_NAME_56098,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Jewelcrafting,
                DropChance = 9,
                LevelRequirement = 50,
            },
            [6] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [7] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [8] = {
                Id = "11840",
                Icon = "inv_shirt_black_01",
                Name = IJ_LOOT_NAME_11840,
                Quality = IQ.Common,
                ItemSlot = IS.Shirt,
                DropChance = 5,
            },
        }
    },
    [9] = { -- NOTE: Missing abilities
        Id = "9017",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "incendius" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "incendius" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9017,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9017,
        MapCoordinateX = 57.8,
        MapCoordinateY = 48.5,
        Loot = {
            [1] = {
                Id = "11764",
                Icon = "inv_bracer_02",
                Name = IJ_LOOT_NAME_11764,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [2] = {
                Id = "11765",
                Icon = "inv_bracer_18",
                Name = IJ_LOOT_NAME_11765,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [3] = {
                Id = "11766",
                Icon = "inv_bracer_05",
                Name = IJ_LOOT_NAME_11766,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [4] = {
                Id = "11767",
                Icon = "inv_bracer_18",
                Name = IJ_LOOT_NAME_11767,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [5] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [6] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [10] = { -- NOTE: Missing abilities
        Id = "9016",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "baelgar" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "baelgar" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9016,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9016,
        MapCoordinateX = 35.1,
        MapCoordinateY = 64.6,
        Loot = {
            [1] = {
                Id = "11802",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_11802,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 53,
            },
            [2] = {
                Id = "11803",
                Icon = "inv_hammer_09",
                Name = IJ_LOOT_NAME_11803,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 25,
                LevelRequirement = 51,
            },
            [3] = {
                Id = "11805",
                Icon = "inv_hammer_09",
                Name = IJ_LOOT_NAME_11805,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 25,
                LevelRequirement = 51,
            },
            [4] = {
                Id = "11807",
                Icon = "inv_belt_11",
                Name = IJ_LOOT_NAME_11807,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 53,
            },
            [5] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [6] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [11] = { -- NOTE: Missing abilities
        Id = "9033",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "angerforge" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "angerforge" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9033,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9033,
        MapCoordinateX = 42.7,
        MapCoordinateY = 66.2,
        Loot = {
            [1] = {
                Id = "11810",
                Icon = "inv_jewelry_amulet_01",
                Name = IJ_LOOT_NAME_11810,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [2] = {
                Id = "11816",
                Icon = "inv_weapon_halberd_06",
                Name = IJ_LOOT_NAME_11816,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 20,
                LevelRequirement = 51,
            },
            [3] = {
                Id = "11817",
                Icon = "inv_sword_25",
                Name = IJ_LOOT_NAME_11817,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Sword,
                DropChance = 20,
                LevelRequirement = 51,
            },
            [4] = {
                Id = "11820",
                Icon = "inv_chest_plate04",
                Name = IJ_LOOT_NAME_11820,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [5] = {
                Id = "11821",
                Icon = "inv_pants_09",
                Name = IJ_LOOT_NAME_11821,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [6] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [7] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [12] = { -- NOTE: Missing abilities
        Id = "8983",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "argelmach" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "argelmach" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_8983,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_8983,
        MapCoordinateX = 42.4,
        MapCoordinateY = 52.1,
        Loot = {
            [1] = {
                Id = "11669",
                Icon = "inv_jewelry_ring_05",
                Name = IJ_LOOT_NAME_11669,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 54,
            },
            [2] = {
                Id = "11819",
                Icon = "inv_jewelry_talisman_06",
                Name = IJ_LOOT_NAME_11819,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 25,
                LevelRequirement = 54,
            },
            [3] = {
                Id = "11822",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_11822,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 54,
            },
            [4] = {
                Id = "11823",
                Icon = "inv_pants_13",
                Name = IJ_LOOT_NAME_11823,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 54,
            },
            [5] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [6] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [13] = { -- NOTE: Missing abilities
        Id = "9537",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "blackbreath" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "blackbreath" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9537,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9537,
        MapCoordinateX = 51.2,
        MapCoordinateY = 47.8,
        Loot = {
            [1] = {
                Id = "11735",
                Icon = "inv_helmet_46",
                Name = IJ_LOOT_NAME_11735,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [2] = {
                Id = "18043",
                Icon = "inv_boots_08",
                Name = IJ_LOOT_NAME_18043,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [3] = {
                Id = "18044",
                Icon = "inv_drink_04",
                Name = IJ_LOOT_NAME_18044,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [4] = {
                Id = "22275",
                Icon = "inv_boots_08",
                Name = IJ_LOOT_NAME_22275,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [5] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [14] = { -- NOTE: Missing abilities
        Id = "9543",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "ribbly" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "ribbly" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9543,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9543,
        MapCoordinateX = 51.9,
        MapCoordinateY = 51.3,
        Loot = {
            [1] = {
                Id = "2663",
                Icon = "inv_misc_ammo_bullet_01",
                Name = IJ_LOOT_NAME_2663,
                Quality = IQ.Uncommon,
                ItemSlot = IS.AmmoPouch,
                DropChance = 25,
                LevelRequirement = 50,
            },
            [2] = {
                Id = "2662",
                Icon = "inv_misc_quiver_06",
                Name = IJ_LOOT_NAME_2662,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Quiver,
                DropChance = 25,
                LevelRequirement = 50,
            },
            [3] = {
                Id = "11742",
                Icon = "inv_misc_bag_20",
                Name = IJ_LOOT_NAME_11742,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Bag,
                DropChance = 25,
            },
            [4] = {
                Id = "11612",
                Icon = "inv_scroll_03",
                Name = IJ_LOOT_NAME_11612,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 3,
            },
        }
    },
    [15] = { -- NOTE: Missing abilities
        Id = "9502",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "phalanx" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "phalanx" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9502,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9502,
        MapCoordinateX = 54.5,
        MapCoordinateY = 50.6,
        Loot = {
            [1] = {
                Id = "11744",
                Icon = "inv_gauntlets_11",
                Name = IJ_LOOT_NAME_11744,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.FistWeapon,
                DropChance = 33,
                LevelRequirement = 51,
            },
            [2] = {
                Id = "11745",
                Icon = "inv_gauntlets_22",
                Name = IJ_LOOT_NAME_11745,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 33,
                LevelRequirement = 51,
            },
            [3] = {
                Id = "22212",
                Icon = "inv_shoulder_16",
                Name = IJ_LOOT_NAME_22212,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 33,
                LevelRequirement = 51,
            },
            [4] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [16] = { -- NOTE: Missing abilities
        Id = "9499",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "spazzring" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "spazzring" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9499,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9499,
        MapCoordinateX = 53.1,
        MapCoordinateY = 49.4,
        Loot = {
            [1] = {
                Id = "18653",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_18653,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Engineering,
                DropChance = 18,
            },
            [2] = {
                Id = "12793",
                Icon = "inv_chest_leather_01",
                Name = IJ_LOOT_NAME_12793,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 18,
                LevelRequirement = 50,
            },
            [3] = {
                Id = "12791",
                Icon = "inv_drink_10",
                Name = IJ_LOOT_NAME_12791,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Dagger,
                DropChance = 18,
                LevelRequirement = 50,
            },
        }
    },
    [17] = { -- NOTE: Missing abilities
        Id = "9156",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "flamelash" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "flamelash" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9156,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9156,
        MapCoordinateX = 56.2,
        MapCoordinateY = 39.5,
        Loot = {
            [1] = {
                Id = "11809",
                Icon = "inv_spear_01",
                Name = IJ_LOOT_NAME_11809,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 25,
                LevelRequirement = 51,
            },
            [2] = {
                Id = "11812",
                Icon = "inv_misc_cape_18",
                Name = IJ_LOOT_NAME_11812,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 53,
            },
            [3] = {
                Id = "11814",
                Icon = "inv_gauntlets_04",
                Name = IJ_LOOT_NAME_11814,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 53,
            },
            [4] = {
                Id = "11832",
                Icon = "inv_jewelry_amulet_07",
                Name = IJ_LOOT_NAME_11832,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 25,
                LevelRequirement = 53,
            },
            [5] = {
                Id = "11808",
                Icon = "spell_fire_fire",
                Name = IJ_LOOT_NAME_11808,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 2,
                LevelRequirement = 54,
            },
            [6] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [7] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
        }
    },
    [18] = { -- NOTE: Missing abilities
        Id = "8923",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "panzor" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "panzor" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_8923,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_8923,
        MapCoordinateX = 50.6,
        MapCoordinateY = 29.2,
        IsRare = true,
        Loot = {
            [1] = {
                Id = "11785",
                Icon = "inv_shield_06",
                Name = IJ_LOOT_NAME_11785,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 25,
                LevelRequirement = 53,
            },
            [2] = {
                Id = "11786",
                Icon = "inv_sword_47",
                Name = IJ_LOOT_NAME_11786,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 25,
                LevelRequirement = 51,
            },
            [3] = {
                Id = "11787",
                Icon = "inv_boots_plate_01",
                Name = IJ_LOOT_NAME_11787,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 53,
            },
            [4] = {
                Id = "22245",
                Icon = "inv_boots_cloth_05",
                Name = IJ_LOOT_NAME_22245,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 51,
            },
        }
    },
    [19] = { -- NOTE: Missing abilities
        Id = "9040",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "seven" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "seven" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9040,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9040,
        MapCoordinateX = 55.9,
        MapCoordinateY = 20.7,
        Loot = {
            [1] = {
                Id = "11920",
                Icon = "inv_axe_13",
                Name = IJ_LOOT_NAME_11920,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Axe,
                DropChance = 25,
                LevelRequirement = 51,
            },
            [2] = {
                Id = "11923",
                Icon = "inv_hammer_07",
                Name = IJ_LOOT_NAME_11923,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [3] = {
                Id = "11929",
                Icon = "inv_pants_11",
                Name = IJ_LOOT_NAME_11929,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [4] = {
                Id = "11926",
                Icon = "inv_chest_chain_07",
                Name = IJ_LOOT_NAME_11926,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [5] = {
                Id = "11921",
                Icon = "inv_hammer_08",
                Name = IJ_LOOT_NAME_11921,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [6] = {
                Id = "11922",
                Icon = "inv_weapon_shortblade_15",
                Name = IJ_LOOT_NAME_11922,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [7] = {
                Id = "11925",
                Icon = "inv_helmet_41",
                Name = IJ_LOOT_NAME_11925,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 52,
            },
            [8] = {
                Id = "11927",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_11927,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 52,
            },
        }
    },
    [20] = { -- NOTE: Missing abilities
        Id = "9938",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "magmus" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "magmus" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9938,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9938,
        MapCoordinateX = 76.8,
        MapCoordinateY = 10.4,
        Loot = {
            [1] = {
                Id = "11746",
                Icon = "inv_helmet_23",
                Name = IJ_LOOT_NAME_11746,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 51,
            },
            [2] = {
                Id = "11935",
                Icon = "inv_misc_orb_05",
                Name = IJ_LOOT_NAME_11935,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [3] = {
                Id = "22208",
                Icon = "inv_hammer_10",
                Name = IJ_LOOT_NAME_22208,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [4] = {
                Id = "22395",
                Icon = "inv_relics_totemofrage",
                Name = IJ_LOOT_NAME_22395,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Totem,
                DropChance = 20,
                LevelRequirement = 52,
            },
            [5] = {
                Id = "22400",
                Icon = "inv_relics_libramoftruth",
                Name = IJ_LOOT_NAME_22400,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Libram,
                DropChance = 20,
                LevelRequirement = 52,
            },
            [6] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [7] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
        }
    },
    [21] = { -- NOTE: Missing abilities
        Id = "9019",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "emperor" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "emperor" .. IMPF,
        Name = IJ_DB_DUNGEON_BRD_BOSS_NAME_9019,
        Story = IJ_DB_DUNGEON_BRD_BOSS_STORY_9019,
        MapCoordinateX = 85.6,
        MapCoordinateY = 10.4,
        Loot = {
            [1] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [2] = {
                Id = "56104",
                Icon = "inv_misc_note_04",
                Name = IJ_LOOT_NAME_56104,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Jewelcrafting,
                DropChance = 30,
                LevelRequirement = 50,
            },
            [3] = {
                Id = "11924",
                Icon = "inv_chest_cloth_16",
                Name = IJ_LOOT_NAME_11924,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [4] = {
                Id = "11928",
                Icon = "inv_mace_13",
                Name = IJ_LOOT_NAME_11928,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [5] = {
                Id = "11932",
                Icon = "inv_staff_30",
                Name = IJ_LOOT_NAME_11932,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [6] = {
                Id = "11934",
                Icon = "inv_jewelry_ring_24",
                Name = IJ_LOOT_NAME_11934,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [7] = {
                Id = "22207",
                Icon = "inv_belt_28",
                Name = IJ_LOOT_NAME_22207,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [8] = {
                Id = "11815",
                Icon = "inv_jewelry_talisman_01",
                Name = IJ_LOOT_NAME_11815,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [9] = {
                Id = "11930",
                Icon = "inv_misc_cape_20",
                Name = IJ_LOOT_NAME_11930,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [10] = {
                Id = "11931",
                Icon = "inv_axe_22",
                Name = IJ_LOOT_NAME_11931,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [11] = {
                Id = "11933",
                Icon = "inv_misc_gem_sapphire_01",
                Name = IJ_LOOT_NAME_11933,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [12] = {
                Id = "22204",
                Icon = "inv_bracer_10",
                Name = IJ_LOOT_NAME_22204,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [13] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 3,
            },
            [14] = {
                Id = "11684",
                Icon = "spell_frost_frostbrand",
                Name = IJ_LOOT_NAME_11684,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 1,
                LevelRequirement = 55,
            },
            [15] = {
                Id = "12553",
                Icon = "inv_boots_02",
                Name = IJ_LOOT_NAME_12553,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 54,
                Note = IJ_NOTES_EMP,
            },
            [16] = {
                Id = "12554",
                Icon = "inv_gauntlets_32",
                Name = IJ_LOOT_NAME_12554,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 54,
                Note = IJ_NOTES_EMP,
            },
            [17] = {
                Id = "12556",
                Icon = "inv_boots_wolf",
                Name = IJ_LOOT_NAME_12556,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 54,
                Note = IJ_NOTES_EMP,
            },
            [18] = {
                Id = "12557",
                Icon = "inv_shoulder_25",
                Name = IJ_LOOT_NAME_12557,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 54,
                Note = IJ_NOTES_EMP,
            },
        }
    },
}

IJDB.DG.BRD = BRD
