IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IC = IJLib.Challenges
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "deadmines\\"

local DEADMINES = {}

DEADMINES.Name = IJ_DB_DUNGEON_DEADMINES_NAME
DEADMINES.Story = IJ_DB_DUNGEON_DEADMINES_STORY
DEADMINES.Type = IJLib.InstanceType.Dungeon
DEADMINES.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
DEADMINES.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
DEADMINES.MapId = IMI.TheDeadmines
DEADMINES.IconScale = 0.9
DEADMINES.MinLevel = 16
DEADMINES.MaxLevel = 24
DEADMINES.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.TheDeadmines,
        MapCoordinateX = 25.0,
        MapCoordinateY = 51.0,
    },
}
DEADMINES.Bosses = {
    [1] = { -- NOTE: Probably has abilities, none are listed on the database
        Id = "61961",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "jared" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "jared" .. IMPF,
        Name = IJ_DB_DUNGEON_DEADMINES_BOSS_NAME_61961,
        Story = IJ_DB_DUNGEON_DEADMINES_BOSS_STORY_61961,
        MapCoordinateX = 28.5,
        MapCoordinateY = 30.8,
        Loot = {
            [1] = {
                Id = "55377",
                Icon = "INV_Misc_Cape_09",
                Name = IJ_LOOT_NAME_55377,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 50,
                LevelRequirement = 16,
            },
            [2] = {
                Id = "55375",
                Icon = "INV_Drink_06",
                Name = IJ_LOOT_NAME_55375,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 25,
                LevelRequirement = 17,
            },
            [3] = {
                Id = "55376",
                Icon = "INV_Weapon_ShortBlade_02",
                Name = IJ_LOOT_NAME_55376,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 25,
                LevelRequirement = 17,
            },
        },
    },
    [2] = {
        Id = "644",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "rhahk" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "rhahk" .. IMPF,
        Name = IJ_DB_DUNGEON_DEADMINES_BOSS_NAME_644,
        Story = IJ_DB_DUNGEON_DEADMINES_BOSS_STORY_644,
        MapCoordinateX = 17.6,
        MapCoordinateY = 53.4,
        Abilities = {
            [1] = {
                Id = "6304",
                Icon = "INV_Gauntlets_05",
                Name = IJ_DB_DUNGEON_DEADMINES_BOSS_644_ABILITY_NAME_6304,
                Effect = IJ_DB_DUNGEON_DEADMINES_BOSS_644_ABILITY_EFFECT_6304,
            },
        },
        Loot = {
            [1] = {
                Id = "9496",
                Icon = "INV_Misc_Cape_12",
                Name = IJ_LOOT_NAME_9496,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 100,
                ChallengeRestriction = {
                    IC.LevelOneLunatic,
                },
            },
            [2] = {
                Id = "872",
                Icon = "INV_ThrowingAxe_01",
                Name = IJ_LOOT_NAME_872,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 33,
                LevelRequirement = 16,
            },
            [3] = {
                Id = "5187",
                Icon = "INV_Hammer_09",
                Name = IJ_LOOT_NAME_5187,
                Quality = IQ.Uncommon,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 33,
                LevelRequirement = 16,
            },
            [4] = {
                Id = "80706",
                Icon = "INV_Gauntlets_04",
                Name = IJ_LOOT_NAME_80706,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 33,
                LevelRequirement = 16,
            },
        },
    },
    [3] = {
        Id = "3586",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "miner" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "miner" .. IMPF,
        Name = IJ_DB_DUNGEON_DEADMINES_BOSS_NAME_3586,
        Story = IJ_DB_DUNGEON_DEADMINES_BOSS_STORY_3586,
        MapCoordinateX = 31.0,
        MapCoordinateY = 43.8,
        IsRare = true,
        Abilities = {
            [1] = {
                Id = "6016",
                Icon = "Spell_Shadow_VampiricAura",
                Name = IJ_DB_DUNGEON_DEADMINES_BOSS_3586_ABILITY_NAME_6016,
                Effect = IJ_DB_DUNGEON_DEADMINES_BOSS_3586_ABILITY_EFFECT_6016,
            },
        },
        Loot = {
            [1] = {
                Id = "5444",
                Icon = "INV_Misc_Cape_11",
                Name = IJ_LOOT_NAME_5444,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 65,
                LevelRequirement = 14,
            },
            [2] = {
                Id = "5443",
                Icon = "INV_Shield_02",
                Name = IJ_LOOT_NAME_5443,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 35,
                LevelRequirement = 15,
            },
        },
    },
    [4] = {
        Id = "643",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "sneed" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "sneed" .. IMPF,
        Name = IJ_DB_DUNGEON_DEADMINES_BOSS_NAME_643,
        Story = IJ_DB_DUNGEON_DEADMINES_BOSS_STORY_643,
        MapCoordinateX = 29.8,
        MapCoordinateY = 74.5,
        Abilities = {
            [1] = {
                Id = "6713",
                Icon = "Ability_Warrior_Disarm",
                Name = IJ_DB_DUNGEON_DEADMINES_BOSS_643_ABILITY_NAME_6713,
                Effect = IJ_DB_DUNGEON_DEADMINES_BOSS_643_ABILITY_EFFECT_6713,
                Flags = { IMAF.Tank, },
            },
        },
        Loot = {
            [1] = {
                Id = "50256",
                Icon = "INV_Sword_06",
                Name = IJ_LOOT_NAME_50256,
                Quality = IQ.Common,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 100,
                ChallengeRestriction = {
                    IC.LevelOneLunatic,
                },
            },
            [2] = {
                Id = "5195",
                Icon = "INV_Gauntlets_23",
                Name = IJ_LOOT_NAME_5195,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 65,
                LevelRequirement = 17,
            },
            [3] = {
                Id = "80707",
                Icon = "INV_Boots_03",
                Name = IJ_LOOT_NAME_80707,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 60,
                LevelRequirement = 17,
            },
            [4] = {
                Id = "5194",
                Icon = "INV_ThrowingAxe_06",
                Name = IJ_LOOT_NAME_5194,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 35,
                LevelRequirement = 18,
            },
        },
    },
    [5] = {
        Id = "1763",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "gilnid" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "gilnid" .. IMPF,
        Name = IJ_DB_DUNGEON_DEADMINES_BOSS_NAME_1763,
        Story = IJ_DB_DUNGEON_DEADMINES_BOSS_STORY_1763,
        MapCoordinateX = 38.8,
        MapCoordinateY = 51.4,
        Abilities = {
            [1] = {
                Id = "5213",
                Icon = "Spell_Fire_Fireball",
                Name = IJ_DB_DUNGEON_DEADMINES_BOSS_1763_ABILITY_NAME_5213,
                Effect = IJ_DB_DUNGEON_DEADMINES_BOSS_1763_ABILITY_EFFECT_5213,
            },
        },
        Loot = {
            [1] = {
                Id = "5199",
                Icon = "INV_Pants_02",
                Name = IJ_LOOT_NAME_5199,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 55,
                LevelRequirement = 16,
            },
            [2] = {
                Id = "1156",
                Icon = "INV_Jewelry_Ring_09",
                Name = IJ_LOOT_NAME_1156,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 45,
                LevelRequirement = 17,
            },
        },
    },
    [6] = { -- NOTE: Probably has abilities, none are listed on the database
        Id = "61963",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "harvester" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "harvester" .. IMPF,
        Name = IJ_DB_DUNGEON_DEADMINES_BOSS_NAME_61963,
        Story = IJ_DB_DUNGEON_DEADMINES_BOSS_STORY_61963,
        MapCoordinateX = 36.8,
        MapCoordinateY = 25.2,
        Loot = {
            [1] = {
                Id = "55380",
                Icon = "INV_Pants_06",
                Name = IJ_LOOT_NAME_55380,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 50,
                LevelRequirement = 17,
            },
            [2] = {
                Id = "55378",
                Icon = "INV_Gauntlets_27",
                Name = IJ_LOOT_NAME_55378,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 18,
            },
            [3] = {
                Id = "55379",
                Icon = "INV_Weapon_Rifle_03",
                Name = IJ_LOOT_NAME_55379,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Gun,
                DropChance = 25,
                LevelRequirement = 18,
            },
        },
    },
    [7] = {
        Id = "646",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "smite" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "smite" .. IMPF,
        Name = IJ_DB_DUNGEON_DEADMINES_BOSS_NAME_646,
        Story = IJ_DB_DUNGEON_DEADMINES_BOSS_STORY_646,
        MapCoordinateX = 71.3,
        MapCoordinateY = 11.6,
        Abilities = {
            [1] = {
                Id = "6264",
                Icon = "Ability_MeleeDamage",
                Name = IJ_DB_DUNGEON_DEADMINES_BOSS_646_ABILITY_NAME_6264,
                Effect = IJ_DB_DUNGEON_DEADMINES_BOSS_646_ABILITY_EFFECT_6264,
            },
            [2] = {
                Id = "6435",
                Icon = "INV_Gauntlets_05",
                Name = IJ_DB_DUNGEON_DEADMINES_BOSS_646_ABILITY_NAME_6435,
                Effect = IJ_DB_DUNGEON_DEADMINES_BOSS_646_ABILITY_EFFECT_6435,
            },
            [3] = {
                Id = "6432",
                Icon = "Ability_WarStomp",
                Name = IJ_DB_DUNGEON_DEADMINES_BOSS_646_ABILITY_NAME_6432,
                Effect = IJ_DB_DUNGEON_DEADMINES_BOSS_646_ABILITY_EFFECT_6432,
                Flags = { IMAF.Important, IMAF.Deadly, },
            },
            [4] = {
                Id = "3417",
                Icon = "Ability_GhoulFrenzy",
                Name = IJ_DB_DUNGEON_DEADMINES_BOSS_646_ABILITY_NAME_3417,
                Effect = IJ_DB_DUNGEON_DEADMINES_BOSS_646_ABILITY_EFFECT_3417,
            },
        },
        Loot = {
            [1] = {
                Id = "5192",
                Icon = "INV_Sword_24",
                Name = IJ_LOOT_NAME_5192,
                Quality = IQ.Uncommon,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 30,
                LevelRequirement = 17,
            },
            [2] = {
                Id = "5196",
                Icon = "INV_Axe_22",
                Name = IJ_LOOT_NAME_5196,
                Quality = IQ.Uncommon,
                ItemSlot = IS.OneHand,
                ItemType = IT.Axe,
                DropChance = 30,
                LevelRequirement = 17,
            },
            [3] = {
                Id = "81007",
                Icon = "INV_Misc_Bandana_03",
                Name = IJ_LOOT_NAME_81007,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 16,
            },
            [4] = {
                Id = "7230",
                Icon = "INV_Hammer_09",
                Name = IJ_LOOT_NAME_7230,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 20,
                LevelRequirement = 18,
            },
        },
    },
    [8] = {
        Id = "647",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "captain" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "captain" .. IMPF,
        Name = IJ_DB_DUNGEON_DEADMINES_BOSS_NAME_647,
        Story = IJ_DB_DUNGEON_DEADMINES_BOSS_STORY_647,
        MapCoordinateX = 75.6,
        MapCoordinateY = 22.4,
        Abilities = {
            [1] = {
                Id = "5208",
                Icon = "Ability_Poisons",
                Name = IJ_DB_DUNGEON_DEADMINES_BOSS_647_ABILITY_NAME_5208,
                Effect = IJ_DB_DUNGEON_DEADMINES_BOSS_647_ABILITY_EFFECT_5208,
                Flags = { IMAF.Poison, },
            },
            [2] = {
                Id = "845",
                Icon = "Ability_Warrior_Cleave",
                Name = IJ_DB_DUNGEON_DEADMINES_BOSS_647_ABILITY_NAME_845,
                Effect = IJ_DB_DUNGEON_DEADMINES_BOSS_647_ABILITY_EFFECT_845,
            },
        },
        Loot = {
            [1] = {
                Id = "5201",
                Icon = "INV_Staff_13",
                Name = IJ_LOOT_NAME_5201,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 40,
                LevelRequirement = 18,
            },
            [2] = {
                Id = "5200",
                Icon = "INV_Spear_07",
                Name = IJ_LOOT_NAME_5200,
                Quality = IQ.Uncommon,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 30,
                LevelRequirement = 17,
            },
            [3] = {
                Id = "10403",
                Icon = "INV_Belt_26",
                Name = IJ_LOOT_NAME_10403,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 30,
                LevelRequirement = 17,
            },
        },
    },
    [9] = {
        Id = "639",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "vancleef" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "vancleef" .. IMPF,
        Name = IJ_DB_DUNGEON_DEADMINES_BOSS_NAME_639,
        Story = IJ_DB_DUNGEON_DEADMINES_BOSS_STORY_639,
        MapCoordinateX = 75.7,
        MapCoordinateY = 28.1,
        Abilities = {
            [1] = {
                Id = "3417",
                Icon = "Ability_GhoulFrenzy",
                Name = IJ_DB_DUNGEON_DEADMINES_BOSS_639_ABILITY_NAME_3417,
                Effect = IJ_DB_DUNGEON_DEADMINES_BOSS_639_ABILITY_EFFECT_3417,
            },
            [2] = {
                Id = "5200",
                Icon = "Ability_Warrior_BattleShout",
                Name = IJ_DB_DUNGEON_DEADMINES_BOSS_639_ABILITY_NAME_5200,
                Effect = IJ_DB_DUNGEON_DEADMINES_BOSS_639_ABILITY_EFFECT_5200,
                Flags = { IMAF.Important, IMAF.Tank, },
            },
        },
        Loot = {
            [1] = {
                Id = "29980",
                Icon = "INV_Jewelry_Ring_22",
                Name = IJ_LOOT_NAME_29980,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Finger,
                DropChance = 100,
            },
            [2] = {
                Id = "5193",
                Icon = "INV_Misc_Cape_08",
                Name = IJ_LOOT_NAME_5193,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 30,
                LevelRequirement = 20,
            },
            [3] = {
                Id = "5202",
                Icon = "INV_Shirt_08",
                Name = IJ_LOOT_NAME_5202,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 30,
                LevelRequirement = 19,
            },
            [4] = {
                Id = "5191",
                Icon = "INV_Sword_24",
                Name = IJ_LOOT_NAME_5191,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 20,
                LevelRequirement = 19,
            },
            [5] = {
                Id = "10399",
                Icon = "INV_Chest_Leather_08",
                Name = IJ_LOOT_NAME_10399,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 19,
            },
            [6] = {
                Id = "81005",
                Icon = "INV_shoulder_11",
                Name = IJ_LOOT_NAME_81005,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 8,
                LevelRequirement = 20,
            },
        },
    },
    [10] = {
        Id = "645",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "cookie" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "cookie" .. IMPF,
        Name = IJ_DB_DUNGEON_DEADMINES_BOSS_NAME_645,
        Story = IJ_DB_DUNGEON_DEADMINES_BOSS_STORY_645,
        MapCoordinateX = 81.0,
        MapCoordinateY = 24.5,
        Abilities = {
            [1] = {
                Id = "6306",
                Icon = "INV_Drink_06",
                Name = IJ_DB_DUNGEON_DEADMINES_BOSS_645_ABILITY_NAME_6306,
                Effect = IJ_DB_DUNGEON_DEADMINES_BOSS_645_ABILITY_EFFECT_6306,
                Flags = { IMAF.Poison, },
            },
            [2] = {
                Id = "5174",
                Icon = "Spell_Holy_Heal",
                Name = IJ_DB_DUNGEON_DEADMINES_BOSS_645_ABILITY_NAME_5174,
                Effect = IJ_DB_DUNGEON_DEADMINES_BOSS_645_ABILITY_EFFECT_5174,
                Flags = { IMAF.Interruptible, },
            },
        },
        Loot = {
            [1] = {
                Id = "9338",
                Icon = "INV_Misc_Eye_01",
                Name = IJ_LOOT_NAME_9338,
                Quality = IQ.Common,
                ItemSlot = IS.Neck,
                DropChance = 100,
                ChallengeRestriction = {
                    IC.LevelOneLunatic,
                },
            },
            [2] = {
                Id = "5197",
                Icon = "INV_Fabric_Silk_02",
                Name = IJ_LOOT_NAME_5197,
                Quality = IQ.Uncommon,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 65,
                LevelRequirement = 16,
            },
            [3] = {
                Id = "80708",
                Icon = "INV_Chest_Cloth_04",
                Name = IJ_LOOT_NAME_80708,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 60,
                LevelRequirement = 18,
            },
            [4] = {
                Id = "5198",
                Icon = "INV_Staff_02",
                Name = IJ_LOOT_NAME_5198,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 35,
                LevelRequirement = 17,
            },
            [5] = {
                Id = "8490",
                Icon = "INV_Box_PetCarrier_01",
                Name = IJ_LOOT_NAME_8490,
                Quality = IQ.Common,
                ItemSlot = IS.Pet,
                DropChance = 15,
            },
        },
    },
}

IJDB.DG.DEADMINES = DEADMINES
