IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "dme\\"

local DME = {}

DME.Name = IJ_DB_DUNGEON_DME_NAME
DME.Story = IJ_DB_DUNGEON_DME_STORY
DME.Type = IJLib.InstanceType.Dungeon
DME.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
DME.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
DME.MapId = IMI.DireMaul
DME.IconScale = 0.7
DME.MinLevel = 55
DME.MaxLevel = 60
DME.Entrances = {
    [1] = {
        MapContinentId = IMI.Kalimdor,
        MapZoneId = IZI.DireMaul,
        MapCoordinateX = 81.5,
        MapCoordinateY = 40.7,
    },
    [2] = {
        MapContinentId = IMI.Kalimdor,
        MapZoneId = IZI.DireMaul,
        MapCoordinateX = 94.3,
        MapCoordinateY = 66.4,
    },
}
DME.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "14354",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "pusillin" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "pusillin" .. IMPF,
        Name = IJ_DB_DUNGEON_DME_BOSS_NAME_14354,
        Story = IJ_DB_DUNGEON_DME_BOSS_STORY_14354,
        MapCoordinateX = 70.1,
        MapCoordinateY = 66.5,
        Loot = {
            [1] = {
                Id = "18267",
                Icon = "inv_scroll_03",
                Name = IJ_LOOT_NAME_18267,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Cooking,
                DropChance = 100,
            },
            [2] = {
                Id = "18356",
                Icon = "inv_misc_book_06",
                Name = IJ_LOOT_NAME_18356,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Rogue, },
            },
            [3] = {
                Id = "18357",
                Icon = "inv_misc_book_07",
                Name = IJ_LOOT_NAME_18357,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warrior, },
            },
            [4] = {
                Id = "18358",
                Icon = "inv_misc_book_01",
                Name = IJ_LOOT_NAME_18358,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Mage, },
            },
            [5] = {
                Id = "18359",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18359,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Paladin, },
            },
            [6] = {
                Id = "18360",
                Icon = "inv_misc_book_05",
                Name = IJ_LOOT_NAME_18360,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warlock, },
            },
            [7] = {
                Id = "18361",
                Icon = "inv_misc_book_02",
                Name = IJ_LOOT_NAME_18361,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Hunter, },
            },
            [8] = {
                Id = "18362",
                Icon = "inv_misc_book_08",
                Name = IJ_LOOT_NAME_18362,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Priest, },
            },
            [9] = {
                Id = "18363",
                Icon = "inv_misc_book_04",
                Name = IJ_LOOT_NAME_18363,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Shaman, },
            },
            [10] = {
                Id = "18364",
                Icon = "inv_misc_book_10",
                Name = IJ_LOOT_NAME_18364,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Druid, },
            },
            [11] = {
                Id = "18401",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18401,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Paladin, },
            },
        }
    },
    [2] = { -- NOTE: Missing abilities
        Id = "13280",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "hydrospawn" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "hydrospawn" .. IMPF,
        Name = IJ_DB_DUNGEON_DME_BOSS_NAME_13280,
        Story = IJ_DB_DUNGEON_DME_BOSS_STORY_13280,
        MapCoordinateX = 76.4,
        MapCoordinateY = 75.0,
        MapIsBelow = true,
        Loot = {
            [1] = {
                Id = "18305",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_18305,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [2] = {
                Id = "18307",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_18307,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [3] = {
                Id = "18317",
                Icon = "inv_jewelry_necklace_03",
                Name = IJ_LOOT_NAME_18317,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [4] = {
                Id = "18322",
                Icon = "inv_boots_08",
                Name = IJ_LOOT_NAME_18322,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [5] = {
                Id = "18324",
                Icon = "inv_axe_17",
                Name = IJ_LOOT_NAME_18324,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [6] = {
                Id = "18356",
                Icon = "inv_misc_book_06",
                Name = IJ_LOOT_NAME_18356,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Rogue, },
            },
            [7] = {
                Id = "18357",
                Icon = "inv_misc_book_07",
                Name = IJ_LOOT_NAME_18357,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warrior, },
            },
            [8] = {
                Id = "18358",
                Icon = "inv_misc_book_01",
                Name = IJ_LOOT_NAME_18358,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Mage, },
            },
            [9] = {
                Id = "18359",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18359,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Paladin, },
            },
            [10] = {
                Id = "18360",
                Icon = "inv_misc_book_05",
                Name = IJ_LOOT_NAME_18360,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warlock, },
            },
            [11] = {
                Id = "18361",
                Icon = "inv_misc_book_02",
                Name = IJ_LOOT_NAME_18361,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Hunter, },
            },
            [12] = {
                Id = "18362",
                Icon = "inv_misc_book_08",
                Name = IJ_LOOT_NAME_18362,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Priest, },
            },
            [13] = {
                Id = "18363",
                Icon = "inv_misc_book_04",
                Name = IJ_LOOT_NAME_18363,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Shaman, },
            },
            [14] = {
                Id = "18364",
                Icon = "inv_misc_book_10",
                Name = IJ_LOOT_NAME_18364,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Druid, },
            },
            [15] = {
                Id = "18401",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18401,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Paladin, },
            },
            [16] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [17] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [3] = { -- NOTE: Missing abilities
        Id = "11490",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "zevrim" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "zevrim" .. IMPF,
        Name = IJ_DB_DUNGEON_DME_BOSS_NAME_11490,
        Story = IJ_DB_DUNGEON_DME_BOSS_STORY_11490,
        MapCoordinateX = 76.4,
        MapCoordinateY = 79.4,
        Loot = {
            [1] = {
                Id = "18306",
                Icon = "inv_gauntlets_22",
                Name = IJ_LOOT_NAME_18306,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [2] = {
                Id = "18308",
                Icon = "inv_helmet_51",
                Name = IJ_LOOT_NAME_18308,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [3] = {
                Id = "18313",
                Icon = "inv_helmet_19",
                Name = IJ_LOOT_NAME_18313,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [4] = {
                Id = "18319",
                Icon = "inv_helmet_38",
                Name = IJ_LOOT_NAME_18319,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [5] = {
                Id = "18323",
                Icon = "inv_weapon_bow_03",
                Name = IJ_LOOT_NAME_18323,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [6] = {
                Id = "18356",
                Icon = "inv_misc_book_06",
                Name = IJ_LOOT_NAME_18356,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Rogue, },
            },
            [7] = {
                Id = "18357",
                Icon = "inv_misc_book_07",
                Name = IJ_LOOT_NAME_18357,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warrior, },
            },
            [8] = {
                Id = "18358",
                Icon = "inv_misc_book_01",
                Name = IJ_LOOT_NAME_18358,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Mage, },
            },
            [9] = {
                Id = "18359",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18359,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Paladin, },
            },
            [10] = {
                Id = "18360",
                Icon = "inv_misc_book_05",
                Name = IJ_LOOT_NAME_18360,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warlock, },
            },
            [11] = {
                Id = "18361",
                Icon = "inv_misc_book_02",
                Name = IJ_LOOT_NAME_18361,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Hunter, },
            },
            [12] = {
                Id = "18362",
                Icon = "inv_misc_book_08",
                Name = IJ_LOOT_NAME_18362,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Priest, },
            },
            [13] = {
                Id = "18363",
                Icon = "inv_misc_book_04",
                Name = IJ_LOOT_NAME_18363,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Shaman, },
            },
            [14] = {
                Id = "18364",
                Icon = "inv_misc_book_10",
                Name = IJ_LOOT_NAME_18364,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Druid, },
            },
            [15] = {
                Id = "18401",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18401,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Paladin, },
            },
            [16] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [17] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
        }
    },
    [4] = { -- NOTE: Missing abilities
        Id = "14327",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "lethtendris" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "lethtendris" .. IMPF,
        Name = IJ_DB_DUNGEON_DME_BOSS_NAME_14327,
        Story = IJ_DB_DUNGEON_DME_BOSS_STORY_14327,
        MapCoordinateX = 88.0,
        MapCoordinateY = 75.1,
        Loot = {
            [1] = {
                Id = "18301",
                Icon = "inv_wand_06",
                Name = IJ_LOOT_NAME_18301,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 25,
                LevelRequirement = 53,
            },
            [2] = {
                Id = "18302",
                Icon = "inv_jewelry_ring_20",
                Name = IJ_LOOT_NAME_18302,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 53,
            },
            [3] = {
                Id = "18311",
                Icon = "inv_staff_14",
                Name = IJ_LOOT_NAME_18311,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 25,
                LevelRequirement = 53,
            },
            [4] = {
                Id = "18325",
                Icon = "inv_helmet_31",
                Name = IJ_LOOT_NAME_18325,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 53,
            },
            [5] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [6] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [7] = {
                Id = "18356",
                Icon = "inv_misc_book_06",
                Name = IJ_LOOT_NAME_18356,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Rogue, },
            },
            [8] = {
                Id = "18357",
                Icon = "inv_misc_book_07",
                Name = IJ_LOOT_NAME_18357,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warrior, },
            },
            [9] = {
                Id = "18358",
                Icon = "inv_misc_book_01",
                Name = IJ_LOOT_NAME_18358,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Mage, },
            },
            [10] = {
                Id = "18359",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18359,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Paladin, },
            },
            [11] = {
                Id = "18360",
                Icon = "inv_misc_book_05",
                Name = IJ_LOOT_NAME_18360,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warlock, },
            },
            [12] = {
                Id = "18361",
                Icon = "inv_misc_book_02",
                Name = IJ_LOOT_NAME_18361,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Hunter, },
            },
            [13] = {
                Id = "18362",
                Icon = "inv_misc_book_08",
                Name = IJ_LOOT_NAME_18362,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Priest, },
            },
            [14] = {
                Id = "18363",
                Icon = "inv_misc_book_04",
                Name = IJ_LOOT_NAME_18363,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Shaman, },
            },
            [15] = {
                Id = "18364",
                Icon = "inv_misc_book_10",
                Name = IJ_LOOT_NAME_18364,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Druid, },
            },
            [16] = {
                Id = "18401",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18401,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Paladin, },
            },
        }
    },
    [5] = { -- NOTE: Missing abilities
        Id = "11492",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "alzzin" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "alzzin" .. IMPF,
        Name = IJ_DB_DUNGEON_DME_BOSS_NAME_11492,
        Story = IJ_DB_DUNGEON_DME_BOSS_STORY_11492,
        MapCoordinateX = 75.8,
        MapCoordinateY = 55.3,
        Loot = {
            [1] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [2] = {
                Id = "18309",
                Icon = "inv_gauntlets_20",
                Name = IJ_LOOT_NAME_18309,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 10,
                LevelRequirement = 54,
            },
            [3] = {
                Id = "18310",
                Icon = "inv_sword_18",
                Name = IJ_LOOT_NAME_18310,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 10,
                LevelRequirement = 54,
            },
            [4] = {
                Id = "18312",
                Icon = "inv_chest_plate11",
                Name = IJ_LOOT_NAME_18312,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 10,
                LevelRequirement = 54,
            },
            [5] = {
                Id = "18314",
                Icon = "inv_jewelry_ring_31",
                Name = IJ_LOOT_NAME_18314,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 10,
                LevelRequirement = 54,
            },
            [6] = {
                Id = "18315",
                Icon = "inv_jewelry_ring_28",
                Name = IJ_LOOT_NAME_18315,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 10,
                LevelRequirement = 54,
            },
            [7] = {
                Id = "18318",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_18318,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 10,
                LevelRequirement = 54,
            },
            [8] = {
                Id = "18321",
                Icon = "inv_mace_13",
                Name = IJ_LOOT_NAME_18321,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 10,
                LevelRequirement = 54,
            },
            [9] = {
                Id = "18326",
                Icon = "inv_gauntlets_31",
                Name = IJ_LOOT_NAME_18326,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 10,
                LevelRequirement = 54,
            },
            [10] = {
                Id = "18327",
                Icon = "inv_belt_17",
                Name = IJ_LOOT_NAME_18327,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 54,
            },
            [11] = {
                Id = "18328",
                Icon = "inv_misc_cape_17",
                Name = IJ_LOOT_NAME_18328,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 54,
            },
            [12] = {
                Id = "18356",
                Icon = "inv_misc_book_06",
                Name = IJ_LOOT_NAME_18356,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Rogue, },
            },
            [13] = {
                Id = "18357",
                Icon = "inv_misc_book_07",
                Name = IJ_LOOT_NAME_18357,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warrior, },
            },
            [14] = {
                Id = "18358",
                Icon = "inv_misc_book_01",
                Name = IJ_LOOT_NAME_18358,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Mage, },
            },
            [15] = {
                Id = "18359",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18359,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Paladin, },
            },
            [16] = {
                Id = "18360",
                Icon = "inv_misc_book_05",
                Name = IJ_LOOT_NAME_18360,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warlock, },
            },
            [17] = {
                Id = "18361",
                Icon = "inv_misc_book_02",
                Name = IJ_LOOT_NAME_18361,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Hunter, },
            },
            [18] = {
                Id = "18362",
                Icon = "inv_misc_book_08",
                Name = IJ_LOOT_NAME_18362,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Priest, },
            },
            [19] = {
                Id = "18363",
                Icon = "inv_misc_book_04",
                Name = IJ_LOOT_NAME_18363,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Shaman, },
            },
            [20] = {
                Id = "18364",
                Icon = "inv_misc_book_10",
                Name = IJ_LOOT_NAME_18364,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Druid, },
            },
            [21] = {
                Id = "18401",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18401,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Paladin, },
            },
            [22] = {
                Id = "47413",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_47413,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [23] = {
                Id = "47415",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_47415,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [24] = {
                Id = "83574",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_83574,
                Quality = IQ.Rare,
                ItemSlot = IS.Ability,
                DropChance = 10,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Druid, },
            },
            [25] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 3,
            },
        }
    },
}

IJDB.DG.DME = DME
