IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "dmn\\"

local DMN = {}

DMN.Name = IJ_DB_DUNGEON_DMN_NAME
DMN.Story = IJ_DB_DUNGEON_DMN_STORY
DMN.Type = IJLib.InstanceType.Dungeon
DMN.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
DMN.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
DMN.MapId = IMI.DireMaul
DMN.IconScale = 0.7
DMN.MinLevel = 57
DMN.MaxLevel = 60
DMN.Entrances = {
    [1] = {
        MapContinentId = IMI.Kalimdor,
        MapZoneId = IZI.DireMaul,
        MapCoordinateX = 70.2,
        MapCoordinateY = 13.5,
    },
}
DMN.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "14326",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "moldar" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "moldar" .. IMPF,
        Name = IJ_DB_DUNGEON_DMN_BOSS_NAME_14326,
        Story = IJ_DB_DUNGEON_DMN_BOSS_STORY_14326,
        MapCoordinateX = 52.4,
        MapCoordinateY = 44.5,
        Loot = {
            [1] = {
                Id = "18450",
                Icon = "inv_chest_cloth_24",
                Name = IJ_LOOT_NAME_18450,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [2] = {
                Id = "18451",
                Icon = "inv_belt_16",
                Name = IJ_LOOT_NAME_18451,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [3] = {
                Id = "18458",
                Icon = "inv_bracer_03",
                Name = IJ_LOOT_NAME_18458,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Wrist,
                ItemType = IT.Mail,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [4] = {
                Id = "18459",
                Icon = "inv_bracer_19",
                Name = IJ_LOOT_NAME_18459,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [5] = {
                Id = "18460",
                Icon = "inv_weapon_rifle_07",
                Name = IJ_LOOT_NAME_18460,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Ranged,
                ItemType = IT.Gun,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [6] = {
                Id = "18462",
                Icon = "inv_gauntlets_13",
                Name = IJ_LOOT_NAME_18462,
                Quality = IQ.Uncommon,
                ItemSlot = IS.MainHand,
                ItemType = IT.FistWeapon,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [7] = {
                Id = "18463",
                Icon = "inv_sword_04",
                Name = IJ_LOOT_NAME_18463,
                Quality = IQ.Uncommon,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [8] = {
                Id = "18464",
                Icon = "inv_jewelry_ring_06",
                Name = IJ_LOOT_NAME_18464,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Finger,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [9] = {
                Id = "18493",
                Icon = "inv_shoulder_26",
                Name = IJ_LOOT_NAME_18493,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [10] = {
                Id = "18494",
                Icon = "inv_shoulder_15",
                Name = IJ_LOOT_NAME_18494,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [11] = {
                Id = "18496",
                Icon = "inv_misc_cape_02",
                Name = IJ_LOOT_NAME_18496,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [12] = {
                Id = "18497",
                Icon = "inv_bracer_13",
                Name = IJ_LOOT_NAME_18497,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [13] = {
                Id = "18498",
                Icon = "inv_axe_11",
                Name = IJ_LOOT_NAME_18498,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Axe,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [14] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [15] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [2] = { -- NOTE: Missing abilities
        Id = "14322",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "kreeg" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "kreeg" .. IMPF,
        Name = IJ_DB_DUNGEON_DMN_BOSS_NAME_14322,
        Story = IJ_DB_DUNGEON_DMN_BOSS_STORY_14322,
        MapCoordinateX = 46.3,
        MapCoordinateY = 38.5,
        Loot = {
            [1] = {
                Id = "18425",
                Icon = "inv_drink_05",
                Name = IJ_LOOT_NAME_18425,
                Quality = IQ.Uncommon,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 40,
                LevelRequirement = 55,
            },
            [2] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [3] = { -- NOTE: Missing abilities
        Id = "14321",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "fengus" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "fengus" .. IMPF,
        Name = IJ_DB_DUNGEON_DMN_BOSS_NAME_14321,
        Story = IJ_DB_DUNGEON_DMN_BOSS_STORY_14321,
        MapCoordinateX = 39.2,
        MapCoordinateY = 45.4,
        Loot = {
            [1] = {
                Id = "18450",
                Icon = "inv_chest_cloth_24",
                Name = IJ_LOOT_NAME_18450,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 13,
                LevelRequirement = 55,
            },
            [2] = {
                Id = "18451",
                Icon = "inv_belt_16",
                Name = IJ_LOOT_NAME_18451,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 13,
                LevelRequirement = 55,
            },
            [3] = {
                Id = "18458",
                Icon = "inv_bracer_03",
                Name = IJ_LOOT_NAME_18458,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Wrist,
                ItemType = IT.Mail,
                DropChance = 13,
                LevelRequirement = 55,
            },
            [4] = {
                Id = "18459",
                Icon = "inv_bracer_19",
                Name = IJ_LOOT_NAME_18459,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 13,
                LevelRequirement = 55,
            },
            [5] = {
                Id = "18460",
                Icon = "inv_weapon_rifle_07",
                Name = IJ_LOOT_NAME_18460,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Ranged,
                ItemType = IT.Gun,
                DropChance = 13,
                LevelRequirement = 55,
            },
            [6] = {
                Id = "18462",
                Icon = "inv_gauntlets_13",
                Name = IJ_LOOT_NAME_18462,
                Quality = IQ.Uncommon,
                ItemSlot = IS.MainHand,
                ItemType = IT.FistWeapon,
                DropChance = 13,
                LevelRequirement = 55,
            },
            [7] = {
                Id = "18463",
                Icon = "inv_sword_04",
                Name = IJ_LOOT_NAME_18463,
                Quality = IQ.Uncommon,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 13,
                LevelRequirement = 55,
            },
            [8] = {
                Id = "18464",
                Icon = "inv_jewelry_ring_06",
                Name = IJ_LOOT_NAME_18464,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Finger,
                DropChance = 13,
                LevelRequirement = 55,
            },
            [9] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [10] = {
                Id = "18356",
                Icon = "inv_misc_book_06",
                Name = IJ_LOOT_NAME_18356,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Rogue, },
            },
            [11] = {
                Id = "18357",
                Icon = "inv_misc_book_07",
                Name = IJ_LOOT_NAME_18357,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warrior, },
            },
            [12] = {
                Id = "18358",
                Icon = "inv_misc_book_01",
                Name = IJ_LOOT_NAME_18358,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Mage, },
            },
            [13] = {
                Id = "18359",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18359,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Paladin, },
            },
            [14] = {
                Id = "18360",
                Icon = "inv_misc_book_05",
                Name = IJ_LOOT_NAME_18360,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warlock, },
            },
            [15] = {
                Id = "18361",
                Icon = "inv_misc_book_02",
                Name = IJ_LOOT_NAME_18361,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Hunter, },
            },
            [16] = {
                Id = "18362",
                Icon = "inv_misc_book_08",
                Name = IJ_LOOT_NAME_18362,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Priest, },
            },
            [17] = {
                Id = "18363",
                Icon = "inv_misc_book_04",
                Name = IJ_LOOT_NAME_18363,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Shaman, },
            },
            [18] = {
                Id = "18364",
                Icon = "inv_misc_book_10",
                Name = IJ_LOOT_NAME_18364,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Druid, },
            },
            [19] = {
                Id = "18401",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18401,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Paladin, },
            },
        }
    },
    [4] = { -- NOTE: Missing abilities
        Id = "14323",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "slipkik" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "slipkik" .. IMPF,
        Name = IJ_DB_DUNGEON_DMN_BOSS_NAME_14323,
        Story = IJ_DB_DUNGEON_DMN_BOSS_STORY_14323,
        MapCoordinateX = 21.8,
        MapCoordinateY = 37.5,
        Loot = {
            [1] = {
                Id = "18450",
                Icon = "inv_chest_cloth_24",
                Name = IJ_LOOT_NAME_18450,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [2] = {
                Id = "18451",
                Icon = "inv_belt_16",
                Name = IJ_LOOT_NAME_18451,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [3] = {
                Id = "18458",
                Icon = "inv_bracer_03",
                Name = IJ_LOOT_NAME_18458,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Wrist,
                ItemType = IT.Mail,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [4] = {
                Id = "18459",
                Icon = "inv_bracer_19",
                Name = IJ_LOOT_NAME_18459,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [5] = {
                Id = "18460",
                Icon = "inv_weapon_rifle_07",
                Name = IJ_LOOT_NAME_18460,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Ranged,
                ItemType = IT.Gun,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [6] = {
                Id = "18462",
                Icon = "inv_gauntlets_13",
                Name = IJ_LOOT_NAME_18462,
                Quality = IQ.Uncommon,
                ItemSlot = IS.MainHand,
                ItemType = IT.FistWeapon,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [7] = {
                Id = "18463",
                Icon = "inv_sword_04",
                Name = IJ_LOOT_NAME_18463,
                Quality = IQ.Uncommon,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [8] = {
                Id = "18464",
                Icon = "inv_jewelry_ring_06",
                Name = IJ_LOOT_NAME_18464,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Finger,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [9] = {
                Id = "18493",
                Icon = "inv_shoulder_26",
                Name = IJ_LOOT_NAME_18493,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [10] = {
                Id = "18494",
                Icon = "inv_shoulder_15",
                Name = IJ_LOOT_NAME_18494,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [11] = {
                Id = "18496",
                Icon = "inv_misc_cape_02",
                Name = IJ_LOOT_NAME_18496,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [12] = {
                Id = "18497",
                Icon = "inv_bracer_13",
                Name = IJ_LOOT_NAME_18497,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [13] = {
                Id = "18498",
                Icon = "inv_axe_11",
                Name = IJ_LOOT_NAME_18498,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Axe,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [14] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [15] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [16] = {
                Id = "18356",
                Icon = "inv_misc_book_06",
                Name = IJ_LOOT_NAME_18356,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Rogue, },
            },
            [17] = {
                Id = "18357",
                Icon = "inv_misc_book_07",
                Name = IJ_LOOT_NAME_18357,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warrior, },
            },
            [18] = {
                Id = "18358",
                Icon = "inv_misc_book_01",
                Name = IJ_LOOT_NAME_18358,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Mage, },
            },
            [19] = {
                Id = "18359",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18359,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Paladin, },
            },
            [20] = {
                Id = "18360",
                Icon = "inv_misc_book_05",
                Name = IJ_LOOT_NAME_18360,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warlock, },
            },
            [21] = {
                Id = "18362",
                Icon = "inv_misc_book_08",
                Name = IJ_LOOT_NAME_18362,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Priest, },
            },
            [22] = {
                Id = "18361",
                Icon = "inv_misc_book_02",
                Name = IJ_LOOT_NAME_18361,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Hunter, },
            },
            [23] = {
                Id = "18363",
                Icon = "inv_misc_book_04",
                Name = IJ_LOOT_NAME_18363,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Shaman, },
            },
            [24] = {
                Id = "18364",
                Icon = "inv_misc_book_10",
                Name = IJ_LOOT_NAME_18364,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Druid, },
            },
            [25] = {
                Id = "18401",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18401,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Paladin, },
            },
        }
    },
    [5] = { -- NOTE: Missing abilities
        Id = "14325",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "kromcrush" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "kromcrush" .. IMPF,
        Name = IJ_DB_DUNGEON_DMN_BOSS_NAME_14325,
        Story = IJ_DB_DUNGEON_DMN_BOSS_STORY_14325,
        MapCoordinateX = 27.5,
        MapCoordinateY = 28.4,
        Loot = {
            [1] = {
                Id = "18502",
                Icon = "inv_weapon_halberd_09",
                Name = IJ_LOOT_NAME_18502,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 25,
                LevelRequirement = 57,
            },
            [2] = {
                Id = "18503",
                Icon = "inv_chest_chain_14",
                Name = IJ_LOOT_NAME_18503,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 57,
            },
            [3] = {
                Id = "18505",
                Icon = "inv_belt_02",
                Name = IJ_LOOT_NAME_18505,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 57,
            },
            [4] = {
                Id = "18507",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_18507,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 57,
            },
            [5] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [6] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [7] = {
                Id = "18356",
                Icon = "inv_misc_book_06",
                Name = IJ_LOOT_NAME_18356,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Rogue, },
            },
            [8] = {
                Id = "18357",
                Icon = "inv_misc_book_07",
                Name = IJ_LOOT_NAME_18357,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warrior, },
            },
            [9] = {
                Id = "18358",
                Icon = "inv_misc_book_01",
                Name = IJ_LOOT_NAME_18358,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Mage, },
            },
            [10] = {
                Id = "18359",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18359,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Paladin, },
            },
            [11] = {
                Id = "18360",
                Icon = "inv_misc_book_05",
                Name = IJ_LOOT_NAME_18360,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warlock, },
            },
            [12] = {
                Id = "18361",
                Icon = "inv_misc_book_02",
                Name = IJ_LOOT_NAME_18361,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Hunter, },
            },
            [13] = {
                Id = "18362",
                Icon = "inv_misc_book_08",
                Name = IJ_LOOT_NAME_18362,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Priest, },
            },
            [14] = {
                Id = "18363",
                Icon = "inv_misc_book_04",
                Name = IJ_LOOT_NAME_18363,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Shaman, },
            },
            [15] = {
                Id = "18364",
                Icon = "inv_misc_book_10",
                Name = IJ_LOOT_NAME_18364,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Druid, },
            },
            [16] = {
                Id = "18401",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18401,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Paladin, },
            },
        }
    },
    [6] = { -- NOTE: Missing abilities
        Id = "11501",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "gordok" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "gordok" .. IMPF,
        Name = IJ_DB_DUNGEON_DMN_BOSS_NAME_11501,
        Story = IJ_DB_DUNGEON_DMN_BOSS_STORY_11501,
        MapCoordinateX = 27.8,
        MapCoordinateY = 11.8,
        Loot = {
            [1] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [2] = {
                Id = "18520",
                Icon = "inv_sword_11",
                Name = IJ_LOOT_NAME_18520,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 13,
                LevelRequirement = 58,
            },
            [3] = {
                Id = "18522",
                Icon = "inv_jewelry_ring_32",
                Name = IJ_LOOT_NAME_18522,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 13,
                LevelRequirement = 58,
            },
            [4] = {
                Id = "18521",
                Icon = "inv_boots_plate_01",
                Name = IJ_LOOT_NAME_18521,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 13,
                LevelRequirement = 58,
            },
            [5] = {
                Id = "18523",
                Icon = "inv_misc_orb_01",
                Name = IJ_LOOT_NAME_18523,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 13,
                LevelRequirement = 58,
            },
            [6] = {
                Id = "18524",
                Icon = "inv_pants_03",
                Name = IJ_LOOT_NAME_18524,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 13,
                LevelRequirement = 58,
            },
            [7] = {
                Id = "18525",
                Icon = "inv_bracer_12",
                Name = IJ_LOOT_NAME_18525,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 13,
                LevelRequirement = 58,
            },
            [8] = {
                Id = "18526",
                Icon = "inv_crown_01",
                Name = IJ_LOOT_NAME_18526,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 13,
                LevelRequirement = 58,
            },
            [9] = {
                Id = "18527",
                Icon = "inv_gauntlets_10",
                Name = IJ_LOOT_NAME_18527,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 13,
                LevelRequirement = 58,
            },
            [10] = {
                Id = "47413",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_47413,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [11] = {
                Id = "47415",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_47415,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [12] = {
                Id = "18780",
                Icon = "inv_misc_note_06",
                Name = IJ_LOOT_NAME_18780,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 9,
                LevelRequirement = 50,
            },
            [13] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 3,
            },
            [14] = {
                Id = "18356",
                Icon = "inv_misc_book_06",
                Name = IJ_LOOT_NAME_18356,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Rogue, },
            },
            [15] = {
                Id = "18357",
                Icon = "inv_misc_book_07",
                Name = IJ_LOOT_NAME_18357,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warrior, },
            },
            [16] = {
                Id = "18358",
                Icon = "inv_misc_book_01",
                Name = IJ_LOOT_NAME_18358,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Mage, },
            },
            [17] = {
                Id = "18359",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18359,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Paladin, },
            },
            [18] = {
                Id = "18360",
                Icon = "inv_misc_book_05",
                Name = IJ_LOOT_NAME_18360,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warlock, },
            },
            [19] = {
                Id = "18361",
                Icon = "inv_misc_book_02",
                Name = IJ_LOOT_NAME_18361,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Hunter, },
            },
            [20] = {
                Id = "18362",
                Icon = "inv_misc_book_08",
                Name = IJ_LOOT_NAME_18362,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Priest, },
            },
            [21] = {
                Id = "18363",
                Icon = "inv_misc_book_04",
                Name = IJ_LOOT_NAME_18363,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Shaman, },
            },
            [22] = {
                Id = "18364",
                Icon = "inv_misc_book_10",
                Name = IJ_LOOT_NAME_18364,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Druid, },
            },
            [23] = {
                Id = "18401",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18401,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Paladin, },
            },
            [24] = {
                Id = "18538",
                Icon = "inv_axe_10",
                Name = IJ_LOOT_NAME_18538,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 1,
                LevelRequirement = 58,
                Note = IJ_NOTES_TRIBUTE,
            },
            [25] = {
                Id = "18655",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_18655,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Engineering,
                DropChance = 11,
                Note = IJ_NOTES_TRIBUTE,
            },
            [26] = {
                Id = "18482",
                Icon = "inv_weapon_bow_05",
                Name = IJ_LOOT_NAME_18482,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 11,
                LevelRequirement = 55,
                Note = IJ_NOTES_TRIBUTE,
            },
            [27] = {
                Id = "18481",
                Icon = "inv_mace_05",
                Name = IJ_LOOT_NAME_18481,
                Quality = IQ.Uncommon,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 11,
                LevelRequirement = 55,
                Note = IJ_NOTES_TRIBUTE,
            },
            [28] = {
                Id = "18480",
                Icon = "inv_helmet_23",
                Name = IJ_LOOT_NAME_18480,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 55,
                Note = IJ_NOTES_TRIBUTE,
            },
            [29] = {
                Id = "18479",
                Icon = "inv_helmet_11",
                Name = IJ_LOOT_NAME_18479,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Head,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 55,
                Note = IJ_NOTES_TRIBUTE,
            },
            [30] = {
                Id = "18478",
                Icon = "inv_chest_leather_06",
                Name = IJ_LOOT_NAME_18478,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 55,
                Note = IJ_NOTES_TRIBUTE,
            },
            [31] = {
                Id = "18477",
                Icon = "inv_pants_14",
                Name = IJ_LOOT_NAME_18477,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 55,
                Note = IJ_NOTES_TRIBUTE,
            },
            [32] = {
                Id = "18476",
                Icon = "inv_boots_07",
                Name = IJ_LOOT_NAME_18476,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 55,
                Note = IJ_NOTES_TRIBUTE,
            },
            [33] = {
                Id = "18475",
                Icon = "inv_belt_07",
                Name = IJ_LOOT_NAME_18475,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 55,
                Note = IJ_NOTES_TRIBUTE,
            },
            [34] = {
                Id = "18532",
                Icon = "inv_chest_cloth_29",
                Name = IJ_LOOT_NAME_18532,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 23,
                LevelRequirement = 57,
                Note = IJ_NOTES_TRIBUTE,
            },
            [35] = {
                Id = "18531",
                Icon = "inv_hammer_22",
                Name = IJ_LOOT_NAME_18531,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 23,
                LevelRequirement = 57,
                Note = IJ_NOTES_TRIBUTE,
            },
            [36] = {
                Id = "18530",
                Icon = "inv_chest_chain_12",
                Name = IJ_LOOT_NAME_18530,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 23,
                LevelRequirement = 57,
                Note = IJ_NOTES_TRIBUTE,
            },
            [37] = {
                Id = "18499",
                Icon = "inv_shield_10",
                Name = IJ_LOOT_NAME_18499,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 23,
                LevelRequirement = 57,
                Note = IJ_NOTES_TRIBUTE,
            },
            [38] = {
                Id = "18537",
                Icon = "inv_stone_02",
                Name = IJ_LOOT_NAME_18537,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 25,
                LevelRequirement = 58,
                Note = IJ_NOTES_TRIBUTE,
            },
            [39] = {
                Id = "18534",
                Icon = "inv_staff_32",
                Name = IJ_LOOT_NAME_18534,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 25,
                LevelRequirement = 58,
                Note = IJ_NOTES_TRIBUTE,
            },
            [40] = {
                Id = "18533",
                Icon = "inv_bracer_14",
                Name = IJ_LOOT_NAME_18533,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 58,
                Note = IJ_NOTES_TRIBUTE,
            },
            [41] = {
                Id = "18495",
                Icon = "inv_misc_cape_21",
                Name = IJ_LOOT_NAME_18495,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 58,
                Note = IJ_NOTES_TRIBUTE,
            },
            [42] = {
                Id = "18529",
                Icon = "inv_belt_18",
                Name = IJ_LOOT_NAME_18529,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 33,
                LevelRequirement = 56,
                Note = IJ_NOTES_TRIBUTE,
            },
            [43] = {
                Id = "18528",
                Icon = "inv_shoulder_26",
                Name = IJ_LOOT_NAME_18528,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 33,
                LevelRequirement = 56,
                Note = IJ_NOTES_TRIBUTE,
            },
            [44] = {
                Id = "18500",
                Icon = "inv_jewelry_ring_13",
                Name = IJ_LOOT_NAME_18500,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 33,
                LevelRequirement = 56,
                Note = IJ_NOTES_TRIBUTE,
            },
        }
    },
}

IJDB.DG.DMN = DMN
