IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "dmr\\"

local DMR = {}

DMR.Name = IJ_DB_DUNGEON_DMR_NAME
DMR.Story = IJ_DB_DUNGEON_DMR_STORY
DMR.Type = IJLib.InstanceType.Dungeon
DMR.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
DMR.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
DMR.MapId = IMI.DragonmawRetreat
DMR.IconScale = 0.9
DMR.MinLevel = 26
DMR.MaxLevel = 35
DMR.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.Wetlands,
        MapCoordinateX = 67.3,
        MapCoordinateY = 63.3,
    },
}
DMR.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "62057",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "gowlfang" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "gowlfang" .. IMPF,
        Name = IJ_DB_DUNGEON_DMR_BOSS_NAME_62057,
        Story = IJ_DB_DUNGEON_DMR_BOSS_STORY_62057,
        MapCoordinateX = 12.1,
        MapCoordinateY = 36.6,
        Loot = {
            [1] = {
                Id = "41571",
                Icon = "inv_axe_03",
                Name = IJ_LOOT_NAME_41571,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Axe,
                DropChance = 20,
                LevelRequirement = 25,
            },
            [2] = {
                Id = "41572",
                Icon = "inv_jewelry_necklace_22",
                Name = IJ_LOOT_NAME_41572,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 25,
            },
            [3] = {
                Id = "41573",
                Icon = "inv_pants_06",
                Name = IJ_LOOT_NAME_41573,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 25,
            },
            [4] = {
                Id = "41574",
                Icon = "inv_gauntlets_24",
                Name = IJ_LOOT_NAME_41574,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 25,
            },
            [5] = {
                Id = "41575",
                Icon = "inv_bracer_05",
                Name = IJ_LOOT_NAME_41575,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 25,
            },
        }
    },
    [2] = { -- NOTE: Missing abilities
        Id = "62066",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "broodmother" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "broodmother" .. IMPF,
        Name = IJ_DB_DUNGEON_DMR_BOSS_NAME_62066,
        Story = IJ_DB_DUNGEON_DMR_BOSS_STORY_62066,
        MapCoordinateX = 33.1,
        MapCoordinateY = 46.3,
        Loot = {
            [1] = {
                Id = "58039",
                Icon = "inv_weapon_shortblade_01",
                Name = IJ_LOOT_NAME_58039,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 20,
                LevelRequirement = 24,
            },
            [2] = {
                Id = "58040",
                Icon = "inv_bracer_06",
                Name = IJ_LOOT_NAME_58040,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Wrist,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 24,
            },
            [3] = {
                Id = "58041",
                Icon = "inv_misc_bone_03",
                Name = IJ_LOOT_NAME_58041,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 24,
            },
            [4] = {
                Id = "58042",
                Icon = "inv_gauntlets_19",
                Name = IJ_LOOT_NAME_58042,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 24,
            },
            [5] = {
                Id = "58043",
                Icon = "inv_pants_01",
                Name = IJ_LOOT_NAME_58043,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 24,
            },
            [6] = {
                Id = "37009",
                Icon = "inv_misc_monsterspidercarapace_01",
                Name = IJ_LOOT_NAME_37009,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Pet,
                DropChance = 10,
            },
        }
    },
    [3] = { -- NOTE: Missing abilities
        Id = "62067",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "torkon" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "torkon" .. IMPF,
        Name = IJ_DB_DUNGEON_DMR_BOSS_NAME_62067,
        Story = IJ_DB_DUNGEON_DMR_BOSS_STORY_62067,
        MapCoordinateX = 37.5,
        MapCoordinateY = 63.7,
        Loot = {
            [1] = {
                Id = "41874",
                Icon = "inv_misc_stonetablet_02",
                Name = IJ_LOOT_NAME_41874,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Quest,
                DropChance = 100,
            },
            [2] = {
                Id = "41566",
                Icon = "inv_jewelry_ring_22",
                Name = IJ_LOOT_NAME_41566,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 26,
            },
            [3] = {
                Id = "41567",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_41567,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 26,
            },
            [4] = {
                Id = "41568",
                Icon = "inv_belt_03",
                Name = IJ_LOOT_NAME_41568,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 26,
            },
            [5] = {
                Id = "41569",
                Icon = "inv_misc_cape_07",
                Name = IJ_LOOT_NAME_41569,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Back,
                DropChance = 20,
                LevelRequirement = 26,
            },
            [6] = {
                Id = "41570",
                Icon = "inv_misc_orb_01",
                Name = IJ_LOOT_NAME_41570,
                Quality = IQ.Uncommon,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 20,
                LevelRequirement = 26,
            },
        }
    },
    [4] = { -- NOTE: Missing abilities
        Id = "62071",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "garlok" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "garlok" .. IMPF,
        Name = IJ_DB_DUNGEON_DMR_BOSS_NAME_62071,
        Story = IJ_DB_DUNGEON_DMR_BOSS_STORY_62071,
        MapCoordinateX = 42.0,
        MapCoordinateY = 64.7,
        Loot = {
            [1] = {
                Id = "41578",
                Icon = "inv_chest_cloth_25",
                Name = IJ_LOOT_NAME_41578,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 27,
            },
            [2] = {
                Id = "41579",
                Icon = "inv_belt_02",
                Name = IJ_LOOT_NAME_41579,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 27,
            },
            [3] = {
                Id = "41580",
                Icon = "inv_jewelry_amulet_06",
                Name = IJ_LOOT_NAME_41580,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 25,
                LevelRequirement = 27,
            },
            [4] = {
                Id = "41581",
                Icon = "inv_sword_07",
                Name = IJ_LOOT_NAME_41581,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Sword,
                DropChance = 25,
                LevelRequirement = 27,
            },
        }
    },
    [5] = { -- NOTE: Missing abilities
        Id = "62069",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "halgan" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "halgan" .. IMPF,
        Name = IJ_DB_DUNGEON_DMR_BOSS_NAME_62069,
        Story = IJ_DB_DUNGEON_DMR_BOSS_STORY_62069,
        MapCoordinateX = 34.8,
        MapCoordinateY = 92.5,
        Loot = {
            [1] = {
                Id = "58044",
                Icon = "inv_staff_28",
                Name = IJ_LOOT_NAME_58044,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 25,
                LevelRequirement = 28,
            },
            [2] = {
                Id = "58045",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_58045,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 28,
            },
            [3] = {
                Id = "58046",
                Icon = "inv_shield_03",
                Name = IJ_LOOT_NAME_58046,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 25,
                LevelRequirement = 28,
            },
            [4] = {
                Id = "58047",
                Icon = "inv_wand_12",
                Name = IJ_LOOT_NAME_58047,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 25,
                LevelRequirement = 28,
            },
            [5] = {
                Id = "76",
                Icon = "inv_misc_note_01",
                Name = IJ_LOOT_NAME_76,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Jewelcrafting,
                DropChance = 6,
            },
            [6] = {
                Id = "77",
                Icon = "inv_misc_note_01",
                Name = IJ_LOOT_NAME_77,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Jewelcrafting,
                DropChance = 6,
            },
        }
    },
    [6] = { -- NOTE: Missing abilities
        Id = "62068",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "slagfist" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "slagfist" .. IMPF,
        Name = IJ_DB_DUNGEON_DMR_BOSS_NAME_62068,
        Story = IJ_DB_DUNGEON_DMR_BOSS_STORY_62068,
        MapCoordinateX = 52.4,
        MapCoordinateY = 80.9,
        Loot = {
            [1] = {
                Id = "41558",
                Icon = "inv_staff_11",
                Name = IJ_LOOT_NAME_41558,
                Quality = IQ.Uncommon,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 25,
                LevelRequirement = 27,
            },
            [2] = {
                Id = "41559",
                Icon = "inv_axe_12",
                Name = IJ_LOOT_NAME_41559,
                Quality = IQ.Uncommon,
                ItemSlot = IS.MainHand,
                ItemType = IT.Axe,
                DropChance = 25,
                LevelRequirement = 27,
            },
            [3] = {
                Id = "41560",
                Icon = "inv_misc_stonetablet_01",
                Name = IJ_LOOT_NAME_41560,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 25,
                LevelRequirement = 27,
            },
            [4] = {
                Id = "41719",
                Icon = "inv_pants_03",
                Name = IJ_LOOT_NAME_41719,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 27,
            },
        }
    },
    [7] = { -- NOTE: Missing abilities
        Id = "62070",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "blackheart" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "blackheart" .. IMPF,
        Name = IJ_DB_DUNGEON_DMR_BOSS_NAME_62070,
        Story = IJ_DB_DUNGEON_DMR_BOSS_STORY_62070,
        MapCoordinateX = 52.4,
        MapCoordinateY = 66.7,
        Loot = {
            [1] = {
                Id = "41724",
                Icon = "inv_shoulder_24",
                Name = IJ_LOOT_NAME_41724,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 28,
            },
            [2] = {
                Id = "41725",
                Icon = "genbow_twow3f",
                Name = IJ_LOOT_NAME_41725,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 25,
                LevelRequirement = 28,
            },
            [3] = {
                Id = "41726",
                Icon = "inv_gauntlets_15",
                Name = IJ_LOOT_NAME_41726,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 28,
            },
            [4] = {
                Id = "41727",
                Icon = "inv_chest_leather_02",
                Name = IJ_LOOT_NAME_41727,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 28,
            },
            [5] = {
                Id = "74",
                Icon = "inv_scroll_05",
                Name = IJ_LOOT_NAME_74,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Leatherworking,
                DropChance = 6,
            },
        }
    },
    [8] = { -- NOTE: Missing abilities
        Id = "62038",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "hollowblood" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "hollowblood" .. IMPF,
        Name = IJ_DB_DUNGEON_DMR_BOSS_NAME_62038,
        Story = IJ_DB_DUNGEON_DMR_BOSS_STORY_62038,
        MapCoordinateX = 56.9,
        MapCoordinateY = 55.8,
        Loot = {
            [1] = {
                Id = "41720",
                Icon = "inv_pants_13",
                Name = IJ_LOOT_NAME_41720,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 28,
            },
            [2] = {
                Id = "41721",
                Icon = "genshield_1f",
                Name = IJ_LOOT_NAME_41721,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 25,
                LevelRequirement = 28,
            },
            [3] = {
                Id = "41722",
                Icon = "inv_bracer_08",
                Name = IJ_LOOT_NAME_41722,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 28,
            },
            [4] = {
                Id = "41723",
                Icon = "inv_hammer_08",
                Name = IJ_LOOT_NAME_41723,
                Quality = IQ.Uncommon,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 25,
                LevelRequirement = 28,
            },
            [5] = {
                Id = "31",
                Icon = "inv_misc_note_01",
                Name = IJ_LOOT_NAME_31,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 6,
            },
        }
    },
    [9] = { -- NOTE: Missing abilities
        Id = "62072",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "searistrasz" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "searistrasz" .. IMPF,
        Name = IJ_DB_DUNGEON_DMR_BOSS_NAME_62072,
        Story = IJ_DB_DUNGEON_DMR_BOSS_STORY_62072,
        MapCoordinateX = 52.9,
        MapCoordinateY = 36.2,
        Loot = {
            [1] = {
                Id = "41561",
                Icon = "spell_fire_fire",
                Name = IJ_LOOT_NAME_41561,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 29,
            },
            [2] = {
                Id = "41562",
                Icon = "inv_weapon_halberd_04",
                Name = IJ_LOOT_NAME_41562,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 20,
                LevelRequirement = 29,
            },
            [3] = {
                Id = "41563",
                Icon = "inv_boots_02",
                Name = IJ_LOOT_NAME_41563,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 29,
            },
            [4] = {
                Id = "41564",
                Icon = "gensword1h_4",
                Name = IJ_LOOT_NAME_41564,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 20,
                LevelRequirement = 29,
            },
            [5] = {
                Id = "41565",
                Icon = "inv_chest_cloth_16",
                Name = IJ_LOOT_NAME_41565,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 29,
            },
        }
    },
    [10] = { -- NOTE: Missing abilities
        Id = "62037",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "zuluhed" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "zuluhed" .. IMPF,
        Name = IJ_DB_DUNGEON_DMR_BOSS_NAME_62037,
        Story = IJ_DB_DUNGEON_DMR_BOSS_STORY_62037,
        MapCoordinateX = 41.9,
        MapCoordinateY = 47.1,
        Loot = {
            [1] = {
                Id = "41845",
                Icon = "inv_weapon_halberd_05",
                Name = IJ_LOOT_NAME_41845,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 20,
                LevelRequirement = 29,
            },
            [2] = {
                Id = "41846",
                Icon = "inv_pants_07",
                Name = IJ_LOOT_NAME_41846,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 29,
            },
            [3] = {
                Id = "41847",
                Icon = "inv_wand_06",
                Name = IJ_LOOT_NAME_41847,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 20,
                LevelRequirement = 29,
            },
            [4] = {
                Id = "41848",
                Icon = "inv_jewelry_ring_20",
                Name = IJ_LOOT_NAME_41848,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 29,
            },
            [5] = {
                Id = "58099",
                Icon = "inv_misc_bone_taurenskull_01",
                Name = IJ_LOOT_NAME_58099,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 29,
            },
            [6] = {
                Id = "69",
                Icon = "inv_scroll_03",
                Name = IJ_LOOT_NAME_69,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Leatherworking,
                DropChance = 5,
            },
            [7] = {
                Id = "71",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_71,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 5,
            },
            [8] = {
                Id = "41895",
                Icon = "inv_enchant_shardbrilliantlarge",
                Name = IJ_LOOT_NAME_41895,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 2,
                LevelRequirement = 30,
            },
        }
    },
}

IJDB.DG.DMR = DMR
