IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "dmw\\"

local DMW = {}

DMW.Name = IJ_DB_DUNGEON_DMW_NAME
DMW.Story = IJ_DB_DUNGEON_DMW_STORY
DMW.Type = IJLib.InstanceType.Dungeon
DMW.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
DMW.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
DMW.MapId = IMI.DireMaul
DMW.IconScale = 0.7
DMW.MinLevel = 57
DMW.MaxLevel = 60
DMW.Entrances = {
    [1] = {
        MapContinentId = IMI.Kalimdor,
        MapZoneId = IZI.DireMaul,
        MapCoordinateX = 57.4,
        MapCoordinateY = 39.2,
    },
    [2] = {
        MapContinentId = IMI.Kalimdor,
        MapZoneId = IZI.DireMaul,
        MapCoordinateX = 57.4,
        MapCoordinateY = 49.9,
    },
}
DMW.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "11489",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "tendris" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "tendris" .. IMPF,
        Name = IJ_DB_DUNGEON_DMW_BOSS_NAME_11489,
        Story = IJ_DB_DUNGEON_DMW_BOSS_STORY_11489,
        MapCoordinateX = 28.1,
        MapCoordinateY = 75.0,
        Loot = {
            [1] = {
                Id = "18352",
                Icon = "inv_shield_18",
                Name = IJ_LOOT_NAME_18352,
                Quality = IQ.Uncommon,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 25,
                LevelRequirement = 56,
            },
            [2] = {
                Id = "18353",
                Icon = "inv_staff_08",
                Name = IJ_LOOT_NAME_18353,
                Quality = IQ.Uncommon,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 25,
                LevelRequirement = 56,
            },
            [3] = {
                Id = "18390",
                Icon = "inv_pants_14",
                Name = IJ_LOOT_NAME_18390,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 57,
            },
            [4] = {
                Id = "18393",
                Icon = "inv_belt_34",
                Name = IJ_LOOT_NAME_18393,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 56,
            },
            [5] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [6] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [7] = {
                Id = "18356",
                Icon = "inv_misc_book_06",
                Name = IJ_LOOT_NAME_18356,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Rogue, },
            },
            [8] = {
                Id = "18357",
                Icon = "inv_misc_book_07",
                Name = IJ_LOOT_NAME_18357,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warrior, },
            },
            [9] = {
                Id = "18358",
                Icon = "inv_misc_book_01",
                Name = IJ_LOOT_NAME_18358,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Mage, },
            },
            [10] = {
                Id = "18359",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18359,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Paladin, },
            },
            [11] = {
                Id = "18360",
                Icon = "inv_misc_book_05",
                Name = IJ_LOOT_NAME_18360,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warlock, },
            },
            [12] = {
                Id = "18361",
                Icon = "inv_misc_book_02",
                Name = IJ_LOOT_NAME_18361,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Hunter, },
            },
            [13] = {
                Id = "18362",
                Icon = "inv_misc_book_08",
                Name = IJ_LOOT_NAME_18362,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Priest, },
            },
            [14] = {
                Id = "18363",
                Icon = "inv_misc_book_04",
                Name = IJ_LOOT_NAME_18363,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Shaman, },
            },
            [15] = {
                Id = "18364",
                Icon = "inv_misc_book_10",
                Name = IJ_LOOT_NAME_18364,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Druid, },
            },
            [16] = {
                Id = "18401",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18401,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Paladin, },
            },
        }
    },
    [2] = { -- NOTE: Missing abilities
        Id = "11488",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "ravenoak" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "ravenoak" .. IMPF,
        Name = IJ_DB_DUNGEON_DMW_BOSS_NAME_11488,
        Story = IJ_DB_DUNGEON_DMW_BOSS_STORY_11488,
        MapCoordinateX = 24.4,
        MapCoordinateY = 81.5,
        Loot = {
            [1] = {
                Id = "18347",
                Icon = "inv_axe_11",
                Name = IJ_LOOT_NAME_18347,
                Quality = IQ.Uncommon,
                ItemSlot = IS.OneHand,
                ItemType = IT.Axe,
                DropChance = 25,
                LevelRequirement = 56,
            },
            [2] = {
                Id = "18349",
                Icon = "inv_gauntlets_12",
                Name = IJ_LOOT_NAME_18349,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 56,
            },
            [3] = {
                Id = "18383",
                Icon = "inv_gauntlets_09",
                Name = IJ_LOOT_NAME_18383,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "18386",
                Icon = "inv_pants_06",
                Name = IJ_LOOT_NAME_18386,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 56,
            },
            [5] = {
                Id = "55580",
                Icon = "inv_misc_book_09",
                Name = IJ_LOOT_NAME_55580,
                Quality = IQ.Rare,
                ItemSlot = IS.Ability,
                DropChance = 17,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Priest, },
            },
            [6] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [7] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [8] = {
                Id = "18356",
                Icon = "inv_misc_book_06",
                Name = IJ_LOOT_NAME_18356,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Rogue, },
            },
            [9] = {
                Id = "18357",
                Icon = "inv_misc_book_07",
                Name = IJ_LOOT_NAME_18357,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warrior, },
            },
            [10] = {
                Id = "18358",
                Icon = "inv_misc_book_01",
                Name = IJ_LOOT_NAME_18358,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Mage, },
            },
            [11] = {
                Id = "18359",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18359,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Paladin, },
            },
            [12] = {
                Id = "18360",
                Icon = "inv_misc_book_05",
                Name = IJ_LOOT_NAME_18360,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warlock, },
            },
            [13] = {
                Id = "18361",
                Icon = "inv_misc_book_02",
                Name = IJ_LOOT_NAME_18361,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Hunter, },
            },
            [14] = {
                Id = "18362",
                Icon = "inv_misc_book_08",
                Name = IJ_LOOT_NAME_18362,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Priest, },
            },
            [15] = {
                Id = "18363",
                Icon = "inv_misc_book_04",
                Name = IJ_LOOT_NAME_18363,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Shaman, },
            },
            [16] = {
                Id = "18364",
                Icon = "inv_misc_book_10",
                Name = IJ_LOOT_NAME_18364,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Druid, },
            },
            [17] = {
                Id = "18401",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18401,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Paladin, },
            },
        }
    },
    [3] = { -- NOTE: Missing abilities
        Id = "11487",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "kalendris" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "kalendris" .. IMPF,
        Name = IJ_DB_DUNGEON_DMW_BOSS_NAME_11487,
        Story = IJ_DB_DUNGEON_DMW_BOSS_STORY_11487,
        MapCoordinateX = 24.4,
        MapCoordinateY = 68.7,
        Loot = {
            [1] = {
                Id = "18350",
                Icon = "inv_misc_cape_18",
                Name = IJ_LOOT_NAME_18350,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [2] = {
                Id = "18351",
                Icon = "inv_bracer_18",
                Name = IJ_LOOT_NAME_18351,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [3] = {
                Id = "18371",
                Icon = "inv_battery_02",
                Name = IJ_LOOT_NAME_18371,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "18374",
                Icon = "inv_shoulder_24",
                Name = IJ_LOOT_NAME_18374,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 57,
            },
            [5] = {
                Id = "18397",
                Icon = "inv_jewelry_necklace_07",
                Name = IJ_LOOT_NAME_18397,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [6] = {
                Id = "22309",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_22309,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Tailoring,
                DropChance = 15,
            },
            [7] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [8] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [9] = {
                Id = "18356",
                Icon = "inv_misc_book_06",
                Name = IJ_LOOT_NAME_18356,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Rogue, },
            },
            [10] = {
                Id = "18357",
                Icon = "inv_misc_book_07",
                Name = IJ_LOOT_NAME_18357,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warrior, },
            },
            [11] = {
                Id = "18358",
                Icon = "inv_misc_book_01",
                Name = IJ_LOOT_NAME_18358,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Mage, },
            },
            [12] = {
                Id = "18359",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18359,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Paladin, },
            },
            [13] = {
                Id = "18360",
                Icon = "inv_misc_book_05",
                Name = IJ_LOOT_NAME_18360,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warlock, },
            },
            [14] = {
                Id = "18361",
                Icon = "inv_misc_book_02",
                Name = IJ_LOOT_NAME_18361,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Hunter, },
            },
            [15] = {
                Id = "18362",
                Icon = "inv_misc_book_08",
                Name = IJ_LOOT_NAME_18362,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Priest, },
            },
            [16] = {
                Id = "18363",
                Icon = "inv_misc_book_04",
                Name = IJ_LOOT_NAME_18363,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Shaman, },
            },
            [17] = {
                Id = "18364",
                Icon = "inv_misc_book_10",
                Name = IJ_LOOT_NAME_18364,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Druid, },
            },
            [18] = {
                Id = "18401",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18401,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Paladin, },
            },
        }
    },
    [4] = { -- NOTE: Missing abilities
        Id = "11467",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "tsuzee" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "tsuzee" .. IMPF,
        Name = IJ_DB_DUNGEON_DMW_BOSS_NAME_11467,
        Story = IJ_DB_DUNGEON_DMW_BOSS_STORY_11467,
        MapCoordinateX = 29.1,
        MapCoordinateY = 66.5,
        Loot = {
            [1] = {
                Id = "18345",
                Icon = "inv_jewelry_ring_15",
                Name = IJ_LOOT_NAME_18345,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Finger,
                DropChance = 33,
                LevelRequirement = 55,
            },
            [2] = {
                Id = "18346",
                Icon = "inv_pants_09",
                Name = IJ_LOOT_NAME_18346,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 55,
            },
            [3] = {
                Id = "18387",
                Icon = "inv_gauntlets_16",
                Name = IJ_LOOT_NAME_18387,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 55,
            },
        }
    },
    [5] = { -- NOTE: Missing abilities
        Id = "11496",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "immolthar" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "immolthar" .. IMPF,
        Name = IJ_DB_DUNGEON_DMW_BOSS_NAME_11496,
        Story = IJ_DB_DUNGEON_DMW_BOSS_STORY_11496,
        MapCoordinateX = 10.2,
        MapCoordinateY = 78.8,
        Loot = {
            [1] = {
                Id = "18370",
                Icon = "inv_misc_stonetablet_04",
                Name = IJ_LOOT_NAME_18370,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [2] = {
                Id = "18372",
                Icon = "inv_weapon_shortblade_18",
                Name = IJ_LOOT_NAME_18372,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Dagger,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [3] = {
                Id = "18377",
                Icon = "inv_gauntlets_21",
                Name = IJ_LOOT_NAME_18377,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [4] = {
                Id = "18379",
                Icon = "inv_boots_plate_06",
                Name = IJ_LOOT_NAME_18379,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [5] = {
                Id = "18381",
                Icon = "inv_misc_eye_01",
                Name = IJ_LOOT_NAME_18381,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [6] = {
                Id = "18384",
                Icon = "inv_shoulder_17",
                Name = IJ_LOOT_NAME_18384,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [7] = {
                Id = "18385",
                Icon = "inv_chest_cloth_51",
                Name = IJ_LOOT_NAME_18385,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [8] = {
                Id = "18389",
                Icon = "inv_misc_cape_01",
                Name = IJ_LOOT_NAME_18389,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [9] = {
                Id = "18391",
                Icon = "inv_belt_26",
                Name = IJ_LOOT_NAME_18391,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [10] = {
                Id = "18394",
                Icon = "inv_bracer_05",
                Name = IJ_LOOT_NAME_18394,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Mail,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [11] = {
                Id = "47413",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_47413,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [12] = {
                Id = "47415",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_47415,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [13] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [14] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [15] = {
                Id = "18356",
                Icon = "inv_misc_book_06",
                Name = IJ_LOOT_NAME_18356,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Rogue, },
            },
            [16] = {
                Id = "18357",
                Icon = "inv_misc_book_07",
                Name = IJ_LOOT_NAME_18357,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warrior, },
            },
            [17] = {
                Id = "18358",
                Icon = "inv_misc_book_01",
                Name = IJ_LOOT_NAME_18358,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Mage, },
            },
            [18] = {
                Id = "18359",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18359,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Paladin, },
            },
            [19] = {
                Id = "18360",
                Icon = "inv_misc_book_05",
                Name = IJ_LOOT_NAME_18360,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Warlock, },
            },
            [20] = {
                Id = "18361",
                Icon = "inv_misc_book_02",
                Name = IJ_LOOT_NAME_18361,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Hunter, },
            },
            [21] = {
                Id = "18362",
                Icon = "inv_misc_book_08",
                Name = IJ_LOOT_NAME_18362,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Priest, },
            },
            [22] = {
                Id = "18363",
                Icon = "inv_misc_book_04",
                Name = IJ_LOOT_NAME_18363,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Shaman, },
            },
            [23] = {
                Id = "18364",
                Icon = "inv_misc_book_10",
                Name = IJ_LOOT_NAME_18364,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 54,
                ClassRestriction = { IMCL.Druid, },
            },
            [24] = {
                Id = "18401",
                Icon = "inv_misc_book_11",
                Name = IJ_LOOT_NAME_18401,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 1,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Paladin, },
            },
        }
    },
    [6] = { -- NOTE: Missing abilities
        Id = "11486",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "prince" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "prince" .. IMPF,
        Name = IJ_DB_DUNGEON_DMW_BOSS_NAME_11486,
        Story = IJ_DB_DUNGEON_DMW_BOSS_STORY_11486,
        MapCoordinateX = 20.9,
        MapCoordinateY = 65.7,
        Loot = {
            [1] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [2] = {
                Id = "18373",
                Icon = "inv_chest_leather_08",
                Name = IJ_LOOT_NAME_18373,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [3] = {
                Id = "18375",
                Icon = "inv_bracer_07",
                Name = IJ_LOOT_NAME_18375,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [4] = {
                Id = "18376",
                Icon = "inv_mace_07",
                Name = IJ_LOOT_NAME_18376,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [5] = {
                Id = "18378",
                Icon = "inv_pants_03",
                Name = IJ_LOOT_NAME_18378,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [6] = {
                Id = "18380",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_18380,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [7] = {
                Id = "18382",
                Icon = "inv_misc_cape_14",
                Name = IJ_LOOT_NAME_18382,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [8] = {
                Id = "18388",
                Icon = "inv_weapon_crossbow_08",
                Name = IJ_LOOT_NAME_18388,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Crossbow,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [9] = {
                Id = "18392",
                Icon = "inv_weapon_shortblade_05",
                Name = IJ_LOOT_NAME_18392,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Dagger,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [10] = {
                Id = "18395",
                Icon = "inv_jewelry_ring_11",
                Name = IJ_LOOT_NAME_18395,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [11] = {
                Id = "18396",
                Icon = "inv_weapon_shortblade_22",
                Name = IJ_LOOT_NAME_18396,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Sword,
                DropChance = 10,
                LevelRequirement = 57,
            },
            [12] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 3,
            },
        }
    },
}

IJDB.DG.DMW = DMW
