IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "gc\\"

local GC = {}

GC.Name = IJ_DB_DUNGEON_GC_NAME
GC.Story = IJ_DB_DUNGEON_GC_STORY
GC.Type = IJLib.InstanceType.Dungeon
GC.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
GC.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
GC.MapId = IMI.GilneasCity
GC.IconScale = 0.9
GC.MinLevel = 43
GC.MaxLevel = 52
GC.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.Gilneas,
        MapCoordinateX = 27.4,
        MapCoordinateY = 30.1,
    },
}
GC.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "61419",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "holtz" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "holtz" .. IMPF,
        Name = IJ_DB_DUNGEON_GC_BOSS_NAME_61419,
        Story = IJ_DB_DUNGEON_GC_BOSS_STORY_61419,
        MapCoordinateX = 75.8,
        MapCoordinateY = 40.5,
        Loot = {
            [1] = {
                Id = "61305",
                Icon = "inv_pants_02",
                Name = IJ_LOOT_NAME_61305,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 41,
            },
            [2] = {
                Id = "61304",
                Icon = "inv_bracer_16",
                Name = IJ_LOOT_NAME_61304,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Wrist,
                ItemType = IT.Mail,
                DropChance = 33,
                LevelRequirement = 41,
            },
            [3] = {
                Id = "61306",
                Icon = "inv_gauntlets_03",
                Name = IJ_LOOT_NAME_61306,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 33,
                LevelRequirement = 41,
            },
            [4] = {
                Id = "61307",
                Icon = "inv_weapon_rifle_twow_02_ironblack",
                Name = IJ_LOOT_NAME_61307,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Gun,
                DropChance = 2,
                LevelRequirement = 41,
            },
        }
    },
    [2] = { -- NOTE: Missing abilities
        Id = "61420",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "ragetooth" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "ragetooth" .. IMPF,
        Name = IJ_DB_DUNGEON_GC_BOSS_NAME_61420,
        Story = IJ_DB_DUNGEON_GC_BOSS_STORY_61420,
        MapCoordinateX = 84.6,
        MapCoordinateY = 63.5,
        Loot = {
            [1] = {
                Id = "61300",
                Icon = "inv_gauntlets_21",
                Name = IJ_LOOT_NAME_61300,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 33,
                LevelRequirement = 41,
            },
            [2] = {
                Id = "61301",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_61301,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 41,
            },
            [3] = {
                Id = "61302",
                Icon = "inv_jewelry_necklace_13",
                Name = IJ_LOOT_NAME_61302,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Neck,
                DropChance = 33,
                LevelRequirement = 41,
            },
            [4] = {
                Id = "61303",
                Icon = "inv_misc_orb_04",
                Name = IJ_LOOT_NAME_61303,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 2,
                LevelRequirement = 41,
            },
        }
    },
    [3] = { -- NOTE: Missing abilities
        Id = "61421",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "sutherland" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "sutherland" .. IMPF,
        Name = IJ_DB_DUNGEON_GC_BOSS_NAME_61421,
        Story = IJ_DB_DUNGEON_GC_BOSS_STORY_61421,
        MapCoordinateX = 77.2,
        MapCoordinateY = 84.1,
        Loot = {
            [1] = {
                Id = "61308",
                Icon = "inv_hammer_05",
                Name = IJ_LOOT_NAME_61308,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 25,
                LevelRequirement = 43,
            },
            [2] = {
                Id = "61309",
                Icon = "inv_shoulder_24",
                Name = IJ_LOOT_NAME_61309,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 43,
            },
            [3] = {
                Id = "61310",
                Icon = "inv_belt_15",
                Name = IJ_LOOT_NAME_61310,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 43,
            },
            [4] = {
                Id = "61311",
                Icon = "inv_bracer_07",
                Name = IJ_LOOT_NAME_61311,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 43,
            },
            [5] = {
                Id = "61312",
                Icon = "inv_jewelry_necklace_17",
                Name = IJ_LOOT_NAME_61312,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 2,
                LevelRequirement = 43,
            },
        }
    },
    [4] = { -- NOTE: Missing abilities
        Id = "61422",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "dustivan" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "dustivan" .. IMPF,
        Name = IJ_DB_DUNGEON_GC_BOSS_NAME_61422,
        Story = IJ_DB_DUNGEON_GC_BOSS_STORY_61422,
        MapCoordinateX = 57.6,
        MapCoordinateY = 83.2,
        Loot = {
            [1] = {
                Id = "61330",
                Icon = "inv_knife_1h_draenei_a_03",
                Name = IJ_LOOT_NAME_61330,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 25,
                LevelRequirement = 43,
            },
            [2] = {
                Id = "61331",
                Icon = "inv_belt_17",
                Name = IJ_LOOT_NAME_61331,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 43,
            },
            [3] = {
                Id = "61332",
                Icon = "inv_jewelry_ring_35",
                Name = IJ_LOOT_NAME_61332,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 43,
            },
            [4] = {
                Id = "61333",
                Icon = "inv_sword_36",
                Name = IJ_LOOT_NAME_61333,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 25,
                LevelRequirement = 43,
            },
            [5] = {
                Id = "61334",
                Icon = "inv_misc_cape_19",
                Name = IJ_LOOT_NAME_61334,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 5,
                LevelRequirement = 43,
            },
        }
    },
    [5] = { -- NOTE: Missing abilities
        Id = "61423",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "magnus" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "magnus" .. IMPF,
        Name = IJ_DB_DUNGEON_GC_BOSS_NAME_61423,
        Story = IJ_DB_DUNGEON_GC_BOSS_STORY_61423,
        MapCoordinateX = 46.3,
        MapCoordinateY = 44.7,
        Loot = {
            [1] = {
                Id = "61313",
                Icon = "inv_helmet_02",
                Name = IJ_LOOT_NAME_61313,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 24,
                LevelRequirement = 44,
            },
            [2] = {
                Id = "61314",
                Icon = "inv_shield_06",
                Name = IJ_LOOT_NAME_61314,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 24,
                LevelRequirement = 44,
            },
            [3] = {
                Id = "61315",
                Icon = "inv_jewelry_ring_27",
                Name = IJ_LOOT_NAME_61315,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 24,
                LevelRequirement = 44,
            },
            [4] = {
                Id = "61316",
                Icon = "inv_misc_cape_02",
                Name = IJ_LOOT_NAME_61316,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 24,
                LevelRequirement = 44,
            },
            [5] = {
                Id = "61368",
                Icon = "inv_shirt_guildtabard_01",
                Name = IJ_LOOT_NAME_61368,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Tabard,
                DropChance = 5,
            },
            [6] = {
                Id = "61317",
                Icon = "inv_misc_book_10",
                Name = IJ_LOOT_NAME_61317,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 5,
                LevelRequirement = 44,
            },
            [7] = {
                Id = "113",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_113,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 5,
            },
        }
    },
    [6] = { -- NOTE: Missing abilities
        Id = "61605",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "levvin" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "levvin" .. IMPF,
        Name = IJ_DB_DUNGEON_GC_BOSS_NAME_61605,
        Story = IJ_DB_DUNGEON_GC_BOSS_STORY_61605,
        MapCoordinateX = 29.0,
        MapCoordinateY = 19.2,
        Loot = {
            [1] = {
                Id = "83157",
                Icon = "ability_mount_ridinghorse",
                Name = IJ_LOOT_NAME_83157,
                Quality = IQ.Epic,
                ItemSlot = IS.Mount,
                DropChance = 1,
            },
            [2] = {
                Id = "61737",
                Icon = "inv_misc_lantern_01",
                Name = IJ_LOOT_NAME_61737,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 25,
                LevelRequirement = 44,
            },
            [3] = {
                Id = "61736",
                Icon = "inv_misc_pelt_bear_ruin_03",
                Name = IJ_LOOT_NAME_61736,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 44,
            },
            [4] = {
                Id = "61735",
                Icon = "inv_staff_08",
                Name = IJ_LOOT_NAME_61735,
                Quality = IQ.Uncommon,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 25,
                LevelRequirement = 44,
            },
            [5] = {
                Id = "61734",
                Icon = "inv_belt_09",
                Name = IJ_LOOT_NAME_61734,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 44,
            },
        }
    },
    [7] = { -- NOTE: Missing abilities
        Id = "61263",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "family" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "family" .. IMPF,
        Name = IJ_DB_DUNGEON_GC_BOSS_NAME_61263,
        Story = IJ_DB_DUNGEON_GC_BOSS_STORY_61263,
        MapCoordinateX = 28.1,
        MapCoordinateY = 23.8,
        Loot = {
            [1] = {
                Id = "61318",
                Icon = "inv_throwingaxe_06",
                Name = IJ_LOOT_NAME_61318,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 24,
                LevelRequirement = 44,
            },
            [2] = {
                Id = "61319",
                Icon = "inv_chest_cloth_04",
                Name = IJ_LOOT_NAME_61319,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 24,
                LevelRequirement = 44,
            },
            [3] = {
                Id = "61320",
                Icon = "inv_misc_desecrated_mailpants",
                Name = IJ_LOOT_NAME_61320,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 24,
                LevelRequirement = 44,
            },
            [4] = {
                Id = "61321",
                Icon = "inv_bracer_08",
                Name = IJ_LOOT_NAME_61321,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 24,
                LevelRequirement = 44,
            },
            [5] = {
                Id = "61322",
                Icon = "inv_jewelry_necklace_16",
                Name = IJ_LOOT_NAME_61322,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 5,
                LevelRequirement = 44,
            },
        }
    },
    [8] = { -- NOTE: Missing abilities
        Id = "61418",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "genn" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "genn" .. IMPF,
        Name = IJ_DB_DUNGEON_GC_BOSS_NAME_61418,
        Story = IJ_DB_DUNGEON_GC_BOSS_STORY_61418,
        MapCoordinateX = 26.1,
        MapCoordinateY = 20.9,
        Loot = {
            [1] = {
                Id = "61323",
                Icon = "inv_helmet_53",
                Name = IJ_LOOT_NAME_61323,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 46,
            },
            [2] = {
                Id = "61324",
                Icon = "inv_shoulder_12",
                Name = IJ_LOOT_NAME_61324,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 46,
            },
            [3] = {
                Id = "61325",
                Icon = "inv_chest_plate04",
                Name = IJ_LOOT_NAME_61325,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 46,
            },
            [4] = {
                Id = "61326",
                Icon = "inv_chest_cloth_04",
                Name = IJ_LOOT_NAME_61326,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 46,
            },
            [5] = {
                Id = "61327",
                Icon = "inv_boots_07",
                Name = IJ_LOOT_NAME_61327,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 46,
            },
            [6] = {
                Id = "61328",
                Icon = "inv_sword_17",
                Name = IJ_LOOT_NAME_61328,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 14,
                LevelRequirement = 46,
            },
            [7] = {
                Id = "61329",
                Icon = "inv_misc_bag_10_red",
                Name = IJ_LOOT_NAME_61329,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 14,
                LevelRequirement = 46,
            },
            [8] = {
                Id = "69000",
                Icon = "inv_weapon_shortblade_16",
                Name = IJ_LOOT_NAME_69000,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Pet,
                DropChance = 2,
            },
            [9] = {
                Id = "61406",
                Icon = "inv_jewelry_necklace_22",
                Name = IJ_LOOT_NAME_61406,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 1,
                LevelRequirement = 46,
            },
            [10] = {
                Id = "61738",
                Icon = "inv_misc_note_01",
                Name = IJ_LOOT_NAME_61738,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 6,
            },
        }
    },
}

IJDB.DG.GC = GC
