IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "hq\\"

local HQ = {}

HQ.Name = IJ_DB_DUNGEON_HQ_NAME
HQ.Story = IJ_DB_DUNGEON_HQ_STORY
HQ.Type = IJLib.InstanceType.Dungeon
HQ.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
HQ.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
HQ.MapId = IMI.HateforgeQuarry
HQ.IconScale = 0.9
HQ.MinLevel = 51
HQ.MaxLevel = 60
HQ.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.BurningSteppes,
        MapCoordinateX = 97.5,
        MapCoordinateY = 59.1,
    },
}
HQ.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "60735",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "bargul" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "bargul" .. IMPF,
        Name = IJ_DB_DUNGEON_HQ_BOSS_NAME_60735,
        Story = IJ_DB_DUNGEON_HQ_BOSS_STORY_60735,
        MapCoordinateX = 56.5,
        MapCoordinateY = 82.8, 
        Loot = {
            [1] = {
                Id = "60565",
                Icon = "inv_axe_14",
                Name = IJ_LOOT_NAME_60565,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Axe,
                DropChance = 20,
                LevelRequirement = 51,
            },
            [2] = {
                Id = "60566",
                Icon = "inv_helmet_11",
                Name = IJ_LOOT_NAME_60566,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 51,
            },
            [3] = {
                Id = "60567",
                Icon = "inv_shoulder_11",
                Name = IJ_LOOT_NAME_60567,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 51,
            },
            [4] = {
                Id = "60568",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_60568,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 51,
            },
            [5] = {
                Id = "60569",
                Icon = "inv_jewelry_necklace_06",
                Name = IJ_LOOT_NAME_60569,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 51,
            },
            [6] = {
                Id = "60570",
                Icon = "inv_misc_net_01",
                Name = IJ_LOOT_NAME_60570,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 15,
                LevelRequirement = 51,
            },
            [7] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [8] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [2] = { -- NOTE: Missing abilities
        Id = "60736",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "figgles" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "figgles" .. IMPF,
        Name = IJ_DB_DUNGEON_HQ_BOSS_NAME_60736,
        Story = IJ_DB_DUNGEON_HQ_BOSS_STORY_60736,
        MapCoordinateX = 57.7,
        MapCoordinateY = 44.6, 
        Loot = {
            [1] = {
                Id = "60540",
                Icon = "inv_helmet_47",
                Name = IJ_LOOT_NAME_60540,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 51,
            },
            [2] = {
                Id = "60541",
                Icon = "inv_gauntlets_05",
                Name = IJ_LOOT_NAME_60541,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 51,
            },
            [3] = {
                Id = "60542",
                Icon = "inv_shirt_14",
                Name = IJ_LOOT_NAME_60542,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 51,
            },
            [4] = {
                Id = "60543",
                Icon = "inv_misc_wrench_01",
                Name = IJ_LOOT_NAME_60543,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 20,
                LevelRequirement = 51,
            },
            [5] = {
                Id = "60545",
                Icon = "inv_weapon_rifle_06",
                Name = IJ_LOOT_NAME_60545,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Gun,
                DropChance = 20,
                LevelRequirement = 51,
            },
            [6] = {
                Id = "60539",
                Icon = "inv_gizmo_goblingtonkcontroller",
                Name = IJ_LOOT_NAME_60539,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 15,
                LevelRequirement = 51,
            },
            [7] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [8] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [9] = {
                Id = "13325",
                Icon = "ability_mount_mechastrider",
                Name = IJ_LOOT_NAME_13325,
                Quality = IQ.Epic,
                ItemSlot = IS.Mount,
                DropChance = 1,
            },
        }
    },
    [3] = { -- NOTE: Missing abilities
        Id = "60829",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "corrosis" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "corrosis" .. IMPF,
        Name = IJ_DB_DUNGEON_HQ_BOSS_NAME_60829,
        Story = IJ_DB_DUNGEON_HQ_BOSS_STORY_60829,
        MapCoordinateX = 72.7,
        MapCoordinateY = 73.3,
        Loot = {
            [1] = {
                Id = "80670",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_80670,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 48,
            },
            [2] = {
                Id = "80671",
                Icon = "inv_weapon_shortblade_15",
                Name = IJ_LOOT_NAME_80671,
                Quality = IQ.Uncommon,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 20,
                LevelRequirement = 48,
            },
            [3] = {
                Id = "80674",
                Icon = "ability_creature_poison_06",
                Name = IJ_LOOT_NAME_80674,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 48,
            },
            [4] = {
                Id = "80673",
                Icon = "inv_pants_10",
                Name = IJ_LOOT_NAME_80673,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 48,
            },
            [5] = {
                Id = "80672",
                Icon = "inv_helmet_32",
                Name = IJ_LOOT_NAME_80672,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 48,
            },
        }
    },
    [4] = { -- NOTE: Missing abilities
        Id = "60734",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "hatereaver" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "hatereaver" .. IMPF,
        Name = IJ_DB_DUNGEON_HQ_BOSS_NAME_60734,
        Story = IJ_DB_DUNGEON_HQ_BOSS_STORY_60734,
        MapCoordinateX = 75.1,
        MapCoordinateY = 18.4,   
        Loot = {
            [1] = {
                Id = "60559",
                Icon = "inv_gizmo_02",
                Name = IJ_LOOT_NAME_60559,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 52,
            },
            [2] = {
                Id = "60561",
                Icon = "inv_misc_gear_04",
                Name = IJ_LOOT_NAME_60561,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 52,
            },
            [3] = {
                Id = "60562",
                Icon = "inv_helmet_19",
                Name = IJ_LOOT_NAME_60562,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 52,
            },
            [4] = {
                Id = "60563",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_60563,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 52,
            },
            [5] = {
                Id = "60564",
                Icon = "inv_misc_gem_pearl_04",
                Name = IJ_LOOT_NAME_60564,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 52,
            },
            [6] = {
                Id = "60560",
                Icon = "inv_mace_14",
                Name = IJ_LOOT_NAME_60560,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 15,
                LevelRequirement = 52,
            },
            [7] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [8] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [5] = { -- NOTE: Missing abilities
        Id = "60737",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "hargesh" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "hargesh" .. IMPF,
        Name = IJ_DB_DUNGEON_HQ_BOSS_NAME_60737,
        Story = IJ_DB_DUNGEON_HQ_BOSS_STORY_60737,
        MapCoordinateX = 94.6,
        MapCoordinateY = 79.0,
        Loot = {
            [1] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [2] = {
                Id = "51045",
                Icon = "btnenchantednecklace",
                Name = IJ_LOOT_NAME_51045,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 25,
                LevelRequirement = 54,
            },
            [3] = {
                Id = "51046",
                Icon = "inv_sword_37",
                Name = IJ_LOOT_NAME_51046,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Sword,
                DropChance = 25,
                LevelRequirement = 54,
            },
            [4] = {
                Id = "60551",
                Icon = "spell_shadow_antishadow",
                Name = IJ_LOOT_NAME_60551,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 2,
                LevelRequirement = 54,
            },
            [5] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 3,
            },
            [6] = {
                Id = "60550",
                Icon = "inv_belt_09",
                Name = IJ_LOOT_NAME_60550,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [7] = {
                Id = "60549",
                Icon = "inv_misc_cape_02",
                Name = IJ_LOOT_NAME_60549,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [8] = {
                Id = "60548",
                Icon = "inv_bracer_10",
                Name = IJ_LOOT_NAME_60548,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [9] = {
                Id = "60547",
                Icon = "inv_jewelry_ring_25",
                Name = IJ_LOOT_NAME_60547,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [10] = {
                Id = "60546",
                Icon = "inv_staff_13",
                Name = IJ_LOOT_NAME_60546,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [11] = {
                Id = "51048",
                Icon = "btnfreezinghotcloak",
                Name = IJ_LOOT_NAME_51048,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 54,
            },
            [12] = {
                Id = "51047",
                Icon = "inv_shoulder_24",
                Name = IJ_LOOT_NAME_51047,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 54,
            },
        }
    },
}

IJDB.DG.HQ = HQ
