IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "kc\\"

local KC = {}

KC.Name = IJ_DB_DUNGEON_KC_NAME
KC.Story = IJ_DB_DUNGEON_KC_STORY
KC.Type = IJLib.InstanceType.Dungeon
KC.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
KC.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
KC.MapId = IMI.KarazhanCrypt
KC.IconScale = 0.8
KC.MinLevel = 60
KC.MaxLevel = 60
KC.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.DeadwindPass,
        MapCoordinateX = 39.6,
        MapCoordinateY = 73.1,
    },
}
KC.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "91920",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "marrowspike" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "marrowspike" .. IMPF,
        Name = IJ_DB_DUNGEON_KC_BOSS_NAME_91920,
        Story = IJ_DB_DUNGEON_KC_BOSS_STORY_91920,
        MapCoordinateX = 89.2,
        MapCoordinateY = 77.8,
        MapIsBelow = true,
        Loot = {
            [1] = {
                Id = "83441",
                Icon = "inv_chest_chain_15",
                Name = IJ_LOOT_NAME_83441,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "83442",
                Icon = "inv_boots_08",
                Name = IJ_LOOT_NAME_83442,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "83443",
                Icon = "inv_helmet_06",
                Name = IJ_LOOT_NAME_83443,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Mail,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "83444",
                Icon = "inv_shield_02",
                Name = IJ_LOOT_NAME_83444,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "83445",
                Icon = "inv_misc_monsterclaw_01",
                Name = IJ_LOOT_NAME_83445,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.FistWeapon,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "83440",
                Icon = "inv_mace_09",
                Name = IJ_LOOT_NAME_83440,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [8] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [2] = { -- NOTE: Missing abilities
        Id = "91929",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "hivaxxis" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "hivaxxis" .. IMPF,
        Name = IJ_DB_DUNGEON_KC_BOSS_NAME_91929,
        Story = IJ_DB_DUNGEON_KC_BOSS_STORY_91929,
        MapCoordinateX = 81.8,
        MapCoordinateY = 86.8,
        Loot = {
            [1] = {
                Id = "83447",
                Icon = "inv_belt_12",
                Name = IJ_LOOT_NAME_83447,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "83448",
                Icon = "inv_shoulder_09",
                Name = IJ_LOOT_NAME_83448,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "83449",
                Icon = "inv_jewelry_ring_24",
                Name = IJ_LOOT_NAME_83449,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "83450",
                Icon = "inv_misc_gem_pearl_06",
                Name = IJ_LOOT_NAME_83450,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "83451",
                Icon = "inv_helmet_41",
                Name = IJ_LOOT_NAME_83451,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "83446",
                Icon = "inv_weapon_shortblade_16",
                Name = IJ_LOOT_NAME_83446,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [8] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [3] = { -- NOTE: Missing abilities
        Id = "91917",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "corpsemuncher" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "corpsemuncher" .. IMPF,
        Name = IJ_DB_DUNGEON_KC_BOSS_NAME_91917,
        Story = IJ_DB_DUNGEON_KC_BOSS_STORY_91917,
        MapCoordinateX = 21.0,
        MapCoordinateY = 78.1,
        Loot = {
            [1] = {
                Id = "70057",
                Icon = "inv_helmet_19",
                Name = IJ_LOOT_NAME_70057,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "83459",
                Icon = "inv_bracer_03",
                Name = IJ_LOOT_NAME_83459,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "83460",
                Icon = "inv_jewelry_ring_26",
                Name = IJ_LOOT_NAME_83460,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "83461",
                Icon = "inv_spear_06",
                Name = IJ_LOOT_NAME_83461,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "83462",
                Icon = "inv_chest_plate08",
                Name = IJ_LOOT_NAME_83462,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "83463",
                Icon = "inv_gauntlets_23",
                Name = IJ_LOOT_NAME_83463,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "83458",
                Icon = "inv_misc_organ_01",
                Name = IJ_LOOT_NAME_83458,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [9] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [4] = { -- NOTE: Missing abilities
        Id = "92935",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "gort" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "gort" .. IMPF,
        Name = IJ_DB_DUNGEON_KC_BOSS_NAME_92935,
        Story = IJ_DB_DUNGEON_KC_BOSS_STORY_92935,
        MapCoordinateX = 55.6,
        MapCoordinateY = 78.4,
        Loot = {
            [1] = {
                Id = "60792",
                Icon = "inv_shoulder_22",
                Name = IJ_LOOT_NAME_60792,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "60793",
                Icon = "inv_jewelry_ring_43",
                Name = IJ_LOOT_NAME_60793,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "60794",
                Icon = "inv_chest_cloth_04",
                Name = IJ_LOOT_NAME_60794,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "60795",
                Icon = "inv_bracer_09",
                Name = IJ_LOOT_NAME_60795,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "60790",
                Icon = "inv_jewelry_necklace_04",
                Name = IJ_LOOT_NAME_60790,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "60791",
                Icon = "inv_gauntlets_31",
                Name = IJ_LOOT_NAME_60791,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [8] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [5] = { -- NOTE: Missing abilities
        Id = "91916",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "enkhraz" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "enkhraz" .. IMPF,
        Name = IJ_DB_DUNGEON_KC_BOSS_NAME_91916,
        Story = IJ_DB_DUNGEON_KC_BOSS_STORY_91916,
        MapCoordinateX = 90.0,
        MapCoordinateY = 72.1,
        Loot = {
            [1] = {
                Id = "83453",
                Icon = "inv_misc_book_09",
                Name = IJ_LOOT_NAME_83453,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "83454",
                Icon = "inv_pants_11",
                Name = IJ_LOOT_NAME_83454,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "83455",
                Icon = "inv_boots_plate_02",
                Name = IJ_LOOT_NAME_83455,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "83456",
                Icon = "inv_chest_cloth_14",
                Name = IJ_LOOT_NAME_83456,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "83457",
                Icon = "inv_jewelry_necklace_03",
                Name = IJ_LOOT_NAME_83457,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "83452",
                Icon = "inv_weapon_bow_01",
                Name = IJ_LOOT_NAME_83452,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [8] = {
                Id = "80010",
                Icon = "inv_box_petcarrier_01",
                Name = IJ_LOOT_NAME_80010,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Pet,
                DropChance = 5,
            },
            [9] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [6] = { -- NOTE: Missing abilities
        Id = "91919",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "andreon" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "andreon" .. IMPF,
        Name = IJ_DB_DUNGEON_KC_BOSS_NAME_91919,
        Story = IJ_DB_DUNGEON_KC_BOSS_STORY_91919,
        MapCoordinateX = 46.5,
        MapCoordinateY = 36.1,
        Loot = {
            [1] = {
                Id = "50188",
                Icon = "inv_belt_03",
                Name = IJ_LOOT_NAME_50188,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "50189",
                Icon = "inv_belt_27",
                Name = IJ_LOOT_NAME_50189,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "50190",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_50190,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "50191",
                Icon = "inv_gauntlets_09",
                Name = IJ_LOOT_NAME_50191,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "50192",
                Icon = "inv_jewelry_ring_35",
                Name = IJ_LOOT_NAME_50192,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "50193",
                Icon = "inv_shoulder_24",
                Name = IJ_LOOT_NAME_50193,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [8] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [7] = { -- NOTE: Missing abilities
        Id = "91928",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "alarus" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "alarus" .. IMPF,
        Name = IJ_DB_DUNGEON_KC_BOSS_NAME_91928,
        Story = IJ_DB_DUNGEON_KC_BOSS_STORY_91928,
        MapCoordinateX = 85.4,
        MapCoordinateY = 43.9,
        Loot = {
            [1] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [2] = {
                Id = "83465",
                Icon = "inv_misc_cape_21",
                Name = IJ_LOOT_NAME_83465,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "83466",
                Icon = "inv_pants_plate_20",
                Name = IJ_LOOT_NAME_83466,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "83467",
                Icon = "inv_wand_03",
                Name = IJ_LOOT_NAME_83467,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "83468",
                Icon = "inv_jewelry_ring_09",
                Name = IJ_LOOT_NAME_83468,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "83469",
                Icon = "inv_crown_01",
                Name = IJ_LOOT_NAME_83469,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 21,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "83470",
                Icon = "inv_pants_03",
                Name = IJ_LOOT_NAME_83470,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 21,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "83471",
                Icon = "inv_staff_08",
                Name = IJ_LOOT_NAME_83471,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 21,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "83472",
                Icon = "inv_misc_bone_taurenskull_01",
                Name = IJ_LOOT_NAME_83472,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 21,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "83571",
                Icon = "inv_misc_book_05",
                Name = IJ_LOOT_NAME_83571,
                Quality = IQ.Rare,
                ItemSlot = IS.Ability,
                DropChance = 15,
                LevelRequirement = 58,
                ClassRestriction = { IMCL.Priest, },
            },
            [11] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 3,
            },
            [12] = {
                Id = "83464",
                Icon = "inv_shoulder_11",
                Name = IJ_LOOT_NAME_83464,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 1,
                LevelRequirement = 60,
            },
        }
    },
}

IJDB.DG.KC = KC
