IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "lbrs\\"

local LBRS = {}

LBRS.Name = IJ_DB_DUNGEON_LBRS_NAME
LBRS.Story = IJ_DB_DUNGEON_LBRS_STORY
LBRS.Type = IJLib.InstanceType.Dungeon
LBRS.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
LBRS.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
LBRS.MapId = IMI.BlackrockSpire
LBRS.IconScale = 0.9
LBRS.MinLevel = 55
LBRS.MaxLevel = 60
LBRS.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.BlackrockMountain,
        MapCoordinateX = 81.7,
        MapCoordinateY = 43.4,
    },
}
LBRS.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "9219",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "butcher" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "butcher" .. IMPF,
        Name = IJ_DB_DUNGEON_LBRS_BOSS_NAME_9219,
        Story = IJ_DB_DUNGEON_LBRS_BOSS_STORY_9219,
        IsRare = true,
        Loot = {
            [1] = {
                Id = "12608",
                Icon = "inv_misc_cape_18",
                Name = IJ_LOOT_NAME_12608,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 50,
                LevelRequirement = 53,
            },
            [2] = {
                Id = "13286",
                Icon = "inv_pick_05",
                Name = IJ_LOOT_NAME_13286,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Axe,
                DropChance = 50,
                LevelRequirement = 53,
            },
        }
    },
    [2] = { -- NOTE: Missing abilities
        Id = "9196",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "omokk" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "omokk" .. IMPF,
        Name = IJ_DB_DUNGEON_LBRS_BOSS_NAME_9196,
        Story = IJ_DB_DUNGEON_LBRS_BOSS_STORY_9196,
        Loot = {
            [1] = {
                Id = "13166",
                Icon = "inv_shoulder_23",
                Name = IJ_LOOT_NAME_13166,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 55,
            },
            [2] = {
                Id = "13167",
                Icon = "inv_hammer_04",
                Name = IJ_LOOT_NAME_13167,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 17,
                LevelRequirement = 55,
            },
            [3] = {
                Id = "13168",
                Icon = "inv_chest_plate13",
                Name = IJ_LOOT_NAME_13168,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 55,
            },
            [4] = {
                Id = "13169",
                Icon = "inv_pants_09",
                Name = IJ_LOOT_NAME_13169,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 55,
            },
            [5] = {
                Id = "13170",
                Icon = "inv_pants_13",
                Name = IJ_LOOT_NAME_13170,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 55,
            },
            [6] = {
                Id = "16670",
                Icon = "inv_boots_wolf",
                Name = IJ_LOOT_NAME_16670,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 17,
                LevelRequirement = 54,
            },
            [7] = {
                Id = "12336",
                Icon = "inv_misc_gem_diamond_02",
                Name = IJ_LOOT_NAME_12336,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Quest,
                DropChance = 25,
            },
            [8] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [9] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [3] = { -- NOTE: Missing abilities
        Id = "9218",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "battlelord" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "battlelord" .. IMPF,
        Name = IJ_DB_DUNGEON_LBRS_BOSS_NAME_9218,
        Story = IJ_DB_DUNGEON_LBRS_BOSS_STORY_9218,
        IsRare = true,
        Loot = {
            [1] = {
                Id = "13285",
                Icon = "inv_weapon_halberd_11",
                Name = IJ_LOOT_NAME_13285,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 60,
                LevelRequirement = 53,
            },
            [2] = {
                Id = "13284",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_13284,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 40,
                LevelRequirement = 53,
            },
        }
    },
    [4] = { -- NOTE: Missing abilities
        Id = "9217",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "magus" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "magus" .. IMPF,
        Name = IJ_DB_DUNGEON_LBRS_BOSS_NAME_9217,
        Story = IJ_DB_DUNGEON_LBRS_BOSS_STORY_9217,
        IsRare = true,
        Loot = {
            [1] = {
                Id = "13261",
                Icon = "inv_wand_09",
                Name = IJ_LOOT_NAME_13261,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 33,
                LevelRequirement = 54,
            },
            [2] = {
                Id = "13282",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_13282,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 54,
            },
            [3] = {
                Id = "13283",
                Icon = "spell_holy_innerfire",
                Name = IJ_LOOT_NAME_13283,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 33,
                LevelRequirement = 54,
            },
        }
    },
    [5] = { -- NOTE: Missing abilities
        Id = "9236",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "voshgajin" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "voshgajin" .. IMPF,
        Name = IJ_DB_DUNGEON_LBRS_BOSS_NAME_9236,
        Story = IJ_DB_DUNGEON_LBRS_BOSS_STORY_9236,
        Loot = {
            [1] = {
                Id = "12626",
                Icon = "inv_bracer_07",
                Name = IJ_LOOT_NAME_12626,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 54,
            },
            [2] = {
                Id = "12651",
                Icon = "inv_weapon_crossbow_04",
                Name = IJ_LOOT_NAME_12651,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Crossbow,
                DropChance = 17,
                LevelRequirement = 54,
            },
            [3] = {
                Id = "12653",
                Icon = "inv_weapon_bow_08",
                Name = IJ_LOOT_NAME_12653,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 17,
                LevelRequirement = 54,
            },
            [4] = {
                Id = "13255",
                Icon = "inv_gauntlets_30",
                Name = IJ_LOOT_NAME_13255,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 17,
                LevelRequirement = 54,
            },
            [5] = {
                Id = "13257",
                Icon = "inv_shoulder_07",
                Name = IJ_LOOT_NAME_13257,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 54,
            },
            [6] = {
                Id = "16712",
                Icon = "inv_gauntlets_24",
                Name = IJ_LOOT_NAME_16712,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 54,
            },
            [7] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [8] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [6] = { -- NOTE: Missing abilities
        Id = "9237",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "voone" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "voone" .. IMPF,
        Name = IJ_DB_DUNGEON_LBRS_BOSS_NAME_9237,
        Story = IJ_DB_DUNGEON_LBRS_BOSS_STORY_9237,
        MapCoordinateX = 52.4,
        MapCoordinateY = 54.8,
        Loot = {
            [1] = {
                Id = "13173",
                Icon = "inv_throwingaxe_06",
                Name = IJ_LOOT_NAME_13173,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.ThrownWeapon,
                DropChance = 100,
                LevelRequirement = 55,
            },
            [2] = {
                Id = "12335",
                Icon = "inv_misc_gem_opal_01",
                Name = IJ_LOOT_NAME_12335,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Quest,
                DropChance = 20,
            },
            [3] = {
                Id = "12582",
                Icon = "inv_weapon_shortblade_12",
                Name = IJ_LOOT_NAME_12582,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [4] = {
                Id = "13177",
                Icon = "inv_jewelry_amulet_04",
                Name = IJ_LOOT_NAME_13177,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [5] = {
                Id = "13179",
                Icon = "inv_bracer_09",
                Name = IJ_LOOT_NAME_13179,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [6] = {
                Id = "16676",
                Icon = "inv_gauntlets_10",
                Name = IJ_LOOT_NAME_16676,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [7] = {
                Id = "22231",
                Icon = "inv_boots_cloth_02",
                Name = IJ_LOOT_NAME_22231,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [8] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [9] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [10] = {
                Id = "13175",
                Icon = "inv_weapon_bow_10",
                Name = IJ_LOOT_NAME_13175,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 1,
                LevelRequirement = 55,
            },
        }
    },
    [7] = { -- NOTE: Missing abilities
        Id = "9596",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "bannok" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "bannok" .. IMPF,
        Name = IJ_DB_DUNGEON_LBRS_BOSS_NAME_9596,
        Story = IJ_DB_DUNGEON_LBRS_BOSS_STORY_9596,
        MapCoordinateX = 47.9,
        MapCoordinateY = 60.0,
        IsRare = true,
        Loot = {
            [1] = {
                Id = "12621",
                Icon = "inv_weapon_halberd_11",
                Name = IJ_LOOT_NAME_12621,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Axe,
                DropChance = 33,
                LevelRequirement = 54,
            },
            [2] = {
                Id = "12634",
                Icon = "inv_belt_13",
                Name = IJ_LOOT_NAME_12634,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 33,
                LevelRequirement = 55,
            },
            [3] = {
                Id = "12637",
                Icon = "inv_gauntlets_26",
                Name = IJ_LOOT_NAME_12637,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 33,
                LevelRequirement = 55,
            },
            [4] = {
                Id = "12838",
                Icon = "inv_scroll_03",
                Name = IJ_LOOT_NAME_12838,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 7,
            },
        }
    },
    [8] = { -- NOTE: Missing abilities
        Id = "10596",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "mother" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "mother" .. IMPF,
        Name = IJ_DB_DUNGEON_LBRS_BOSS_NAME_10596,
        Story = IJ_DB_DUNGEON_LBRS_BOSS_STORY_10596,
        Loot = {
            [1] = {
                Id = "13183",
                Icon = "inv_wand_10",
                Name = IJ_LOOT_NAME_13183,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [2] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [3] = {
                Id = "13244",
                Icon = "inv_gauntlets_29",
                Name = IJ_LOOT_NAME_13244,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [4] = {
                Id = "16715",
                Icon = "inv_boots_08",
                Name = IJ_LOOT_NAME_16715,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [5] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [6] = {
                Id = "13213",
                Icon = "inv_misc_gem_pearl_01",
                Name = IJ_LOOT_NAME_13213,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [7] = {
                Id = "80758",
                Icon = "inv_chest_leather_03",
                Name = IJ_LOOT_NAME_80758,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 56,
            },
        }
    },
    [9] = { -- NOTE: Missing abilities
        Id = "10376",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "fang" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "fang" .. IMPF,
        Name = IJ_DB_DUNGEON_LBRS_BOSS_NAME_10376,
        Story = IJ_DB_DUNGEON_LBRS_BOSS_STORY_10376,
        IsRare = true,
        Loot = {
            [1] = {
                Id = "13184",
                Icon = "inv_gauntlets_13",
                Name = IJ_LOOT_NAME_13184,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 33,
                LevelRequirement = 56,
            },
            [2] = {
                Id = "13185",
                Icon = "inv_shoulder_02",
                Name = IJ_LOOT_NAME_13185,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 56,
            },
            [3] = {
                Id = "13218",
                Icon = "inv_weapon_shortblade_16",
                Name = IJ_LOOT_NAME_13218,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 33,
                LevelRequirement = 56,
            },
        }
    },
    [10] = { -- NOTE: Missing abilities
        Id = "10584",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "urok" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "urok" .. IMPF,
        Name = IJ_DB_DUNGEON_LBRS_BOSS_NAME_10584,
        Story = IJ_DB_DUNGEON_LBRS_BOSS_STORY_10584,
        Loot = {
            [1] = {
                Id = "13178",
                Icon = "inv_jewelry_ring_22",
                Name = IJ_LOOT_NAME_13178,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 55,
            },
            [2] = {
                Id = "13258",
                Icon = "inv_gauntlets_22",
                Name = IJ_LOOT_NAME_13258,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 56,
            },
            [3] = {
                Id = "13259",
                Icon = "inv_boots_plate_08",
                Name = IJ_LOOT_NAME_13259,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "22232",
                Icon = "inv_belt_18",
                Name = IJ_LOOT_NAME_22232,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 56,
            },
            [5] = {
                Id = "18784",
                Icon = "inv_misc_note_04",
                Name = IJ_LOOT_NAME_18784,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 16,
                LevelRequirement = 50,
            },
            [6] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [7] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [11] = { -- NOTE: Missing abilities
        Id = "9736",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "zigris" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "zigris" .. IMPF,
        Name = IJ_DB_DUNGEON_LBRS_BOSS_NAME_9736,
        Story = IJ_DB_DUNGEON_LBRS_BOSS_STORY_9736,
        Loot = {
            [1] = {
                Id = "56101",
                Icon = "inv_misc_note_03",
                Name = IJ_LOOT_NAME_56101,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Jewelcrafting,
                DropChance = 30,
                LevelRequirement = 50,
            },
            [2] = {
                Id = "12835",
                Icon = "inv_scroll_03",
                Name = IJ_LOOT_NAME_12835,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 10,
            },
            [3] = {
                Id = "13252",
                Icon = "inv_belt_10",
                Name = IJ_LOOT_NAME_13252,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 10,
                LevelRequirement = 55,
            },
            [4] = {
                Id = "13253",
                Icon = "inv_gauntlets_14",
                Name = IJ_LOOT_NAME_13253,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 55,
            },
            [5] = {
                Id = "80759",
                Icon = "inv_misc_cape_21",
                Name = IJ_LOOT_NAME_80759,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 55,
            },
            [6] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [7] = {
                Id = "16673",
                Icon = "inv_belt_16",
                Name = IJ_LOOT_NAME_16673,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 2,
                LevelRequirement = 53,
            },
            [8] = {
                Id = "16703",
                Icon = "inv_bracer_13",
                Name = IJ_LOOT_NAME_16703,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 2,
                LevelRequirement = 52,
            },
            [9] = {
                Id = "16713",
                Icon = "inv_belt_03",
                Name = IJ_LOOT_NAME_16713,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 2,
                LevelRequirement = 53,
            },
            [10] = {
                Id = "16716",
                Icon = "inv_belt_15",
                Name = IJ_LOOT_NAME_16716,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 2,
                LevelRequirement = 53,
            },
            [11] = {
                Id = "16735",
                Icon = "inv_bracer_18",
                Name = IJ_LOOT_NAME_16735,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 2,
                LevelRequirement = 52,
            },
            [12] = {
                Id = "70221",
                Icon = "inv_misc_note_01",
                Name = IJ_LOOT_NAME_70221,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Jewelcrafting,
                DropChance = 2,
            },
            [13] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [12] = { -- NOTE: Missing abilities
        Id = "10220",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "halycon" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "halycon" .. IMPF,
        Name = IJ_DB_DUNGEON_LBRS_BOSS_NAME_10220,
        Story = IJ_DB_DUNGEON_LBRS_BOSS_STORY_10220,
        Loot = {
            [1] = {
                Id = "13210",
                Icon = "inv_boots_wolf",
                Name = IJ_LOOT_NAME_13210,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 55,
            },
            [2] = {
                Id = "13211",
                Icon = "inv_bracer_07",
                Name = IJ_LOOT_NAME_13211,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 55,
            },
            [3] = {
                Id = "13212",
                Icon = "inv_belt_14",
                Name = IJ_LOOT_NAME_13212,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 25,
                LevelRequirement = 55,
            },
            [4] = {
                Id = "22313",
                Icon = "inv_bracer_13",
                Name = IJ_LOOT_NAME_22313,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 56,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [5] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [6] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [13] = { -- NOTE: Missing abilities
        Id = "10268",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "gizrul" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "gizrul" .. IMPF,
        Name = IJ_DB_DUNGEON_LBRS_BOSS_NAME_10268,
        Story = IJ_DB_DUNGEON_LBRS_BOSS_STORY_10268,
        Loot = {
            [1] = {
                Id = "13205",
                Icon = "inv_shield_14",
                Name = IJ_LOOT_NAME_13205,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 25,
                LevelRequirement = 56,
            },
            [2] = {
                Id = "13206",
                Icon = "inv_pants_06",
                Name = IJ_LOOT_NAME_13206,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 56,
            },
            [3] = {
                Id = "13208",
                Icon = "inv_bracer_07",
                Name = IJ_LOOT_NAME_13208,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "16718",
                Icon = "inv_shoulder_01",
                Name = IJ_LOOT_NAME_16718,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 55,
            },
            [5] = {
                Id = "83573",
                Icon = "inv_misc_book_02",
                Name = IJ_LOOT_NAME_83573,
                Quality = IQ.Rare,
                ItemSlot = IS.Ability,
                DropChance = 15,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Druid, },
            },
            [6] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [7] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [14] = { -- NOTE: Missing abilities
        Id = "9718",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "ghok" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "ghok" .. IMPF,
        Name = IJ_DB_DUNGEON_LBRS_BOSS_NAME_9718,
        Story = IJ_DB_DUNGEON_LBRS_BOSS_STORY_9718,
        IsRare = true,
        Loot = {
            [1] = {
                Id = "13198",
                Icon = "inv_gauntlets_11",
                Name = IJ_LOOT_NAME_13198,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.FistWeapon,
                DropChance = 33,
                LevelRequirement = 55,
            },
            [2] = {
                Id = "13203",
                Icon = "inv_misc_cape_19",
                Name = IJ_LOOT_NAME_13203,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 55,
            },
            [3] = {
                Id = "13204",
                Icon = "inv_mace_15",
                Name = IJ_LOOT_NAME_13204,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 33,
                LevelRequirement = 55,
            },
        }
    },
    [15] = { -- NOTE: Missing abilities
        Id = "9568",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "wyrmthalak" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "wyrmthalak" .. IMPF,
        Name = IJ_DB_DUNGEON_LBRS_BOSS_NAME_9568,
        Story = IJ_DB_DUNGEON_LBRS_BOSS_STORY_9568,
        Loot = {
            [1] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [2] = {
                Id = "12337",
                Icon = "inv_misc_gem_bloodstone_01",
                Name = IJ_LOOT_NAME_12337,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Quest,
                DropChance = 30,
            },
            [3] = {
                Id = "13148",
                Icon = "inv_spear_05",
                Name = IJ_LOOT_NAME_13148,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 13,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "13161",
                Icon = "inv_staff_29",
                Name = IJ_LOOT_NAME_13161,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 13,
                LevelRequirement = 56,
            },
            [5] = {
                Id = "13162",
                Icon = "inv_gauntlets_29",
                Name = IJ_LOOT_NAME_13162,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 13,
                LevelRequirement = 56,
            },
            [6] = {
                Id = "13163",
                Icon = "inv_sword_18",
                Name = IJ_LOOT_NAME_13163,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 13,
                LevelRequirement = 57,
            },
            [7] = {
                Id = "13164",
                Icon = "inv_misc_gem_bloodstone_01",
                Name = IJ_LOOT_NAME_13164,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 13,
                LevelRequirement = 56,
            },
            [8] = {
                Id = "16679",
                Icon = "inv_shoulder_10",
                Name = IJ_LOOT_NAME_16679,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 13,
                LevelRequirement = 55,
            },
            [9] = {
                Id = "22321",
                Icon = "inv_misc_gem_bloodstone_01",
                Name = IJ_LOOT_NAME_22321,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 13,
                LevelRequirement = 56,
            },
            [10] = {
                Id = "80760",
                Icon = "inv_jewelry_ring_14",
                Name = IJ_LOOT_NAME_80760,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 13,
                LevelRequirement = 56,
            },
            [11] = {
                Id = "47413",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_47413,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [12] = {
                Id = "47415",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_47415,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [13] = {
                Id = "56097",
                Icon = "inv_misc_note_06",
                Name = IJ_LOOT_NAME_56097,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Jewelcrafting,
                DropChance = 6,
                LevelRequirement = 50,
            },
            [14] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 3,
            },
            [15] = {
                Id = "13143",
                Icon = "inv_jewelry_ring_17",
                Name = IJ_LOOT_NAME_13143,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 2,
                LevelRequirement = 56,
            },
        }
    },
}

IJDB.DG.LBRS = LBRS
