IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "mara\\"

local MARA = {}

MARA.Name = IJ_DB_DUNGEON_MARA_NAME
MARA.Story = IJ_DB_DUNGEON_MARA_STORY
MARA.Type = IJLib.InstanceType.Dungeon
MARA.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
MARA.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
MARA.MapId = IMI.Maraudon
MARA.IconScale = 0.6
MARA.MinLevel = 43
MARA.MaxLevel = 54
MARA.Entrances = {
    [1] = {
        MapContinentId = IMI.Kalimdor,
        MapZoneId = IZI.Maraudon,
        MapCoordinateX = 72.0,
        MapCoordinateY = 73.6,
    },
    [2] = {
        MapContinentId = IMI.Kalimdor,
        MapZoneId = IZI.Maraudon,
        MapCoordinateX = 45.3,
        MapCoordinateY = 20.8,
    },
}
MARA.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "13282",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "noxxion" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "noxxion" .. IMPF,
        Name = IJ_DB_DUNGEON_MARA_BOSS_NAME_13282,
        Story = IJ_DB_DUNGEON_MARA_BOSS_STORY_13282,
        MapCoordinateX = 32.3,
        MapCoordinateY = 4.7,
        Loot = {
            [1] = {
                Id = "17746",
                Icon = "inv_bracer_06",
                Name = IJ_LOOT_NAME_17746,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 33,
                LevelRequirement = 46,
            },
            [2] = {
                Id = "17745",
                Icon = "inv_wand_04",
                Name = IJ_LOOT_NAME_17745,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 33,
                LevelRequirement = 46,
            },
            [3] = {
                Id = "17744",
                Icon = "inv_misc_gem_pearl_06",
                Name = IJ_LOOT_NAME_17744,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 33,
                LevelRequirement = 46,
            },
        }
    },
    [2] = { -- NOTE: Missing abilities
        Id = "12258",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "razorlash" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "razorlash" .. IMPF,
        Name = IJ_DB_DUNGEON_MARA_BOSS_NAME_12258,
        Story = IJ_DB_DUNGEON_MARA_BOSS_STORY_12258,
        MapCoordinateX = 23.1,
        MapCoordinateY = 15.5,
        Loot = {
            [1] = {
                Id = "17748",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_17748,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 46,
            },
            [2] = {
                Id = "17749",
                Icon = "inv_shoulder_06",
                Name = IJ_LOOT_NAME_17749,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 46,
            },
            [3] = {
                Id = "51802",
                Icon = "inv_relics_idolofrejuvenation",
                Name = IJ_LOOT_NAME_51802,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Idol,
                DropChance = 8,
                LevelRequirement = 46,
            },
            [4] = {
                Id = "17751",
                Icon = "inv_pants_05",
                Name = IJ_LOOT_NAME_17751,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 46,
            },
            [5] = {
                Id = "17750",
                Icon = "inv_belt_25",
                Name = IJ_LOOT_NAME_17750,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 46,
            },
            [6] = {
                Id = "60780",
                Icon = "inv_scroll_05",
                Name = IJ_LOOT_NAME_60780,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Leatherworking,
                DropChance = 3,
            },
        }
    },
    [3] = { -- NOTE: Missing abilities
        Id = "12237",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "meshlok" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "meshlok" .. IMPF,
        Name = IJ_DB_DUNGEON_MARA_BOSS_NAME_12237,
        Story = IJ_DB_DUNGEON_MARA_BOSS_STORY_12237,
        MapCoordinateX = 26.2,
        MapCoordinateY = 30.6,
        IsRare = true,
        Loot = {
            [1] = {
                Id = "60780",
                Icon = "inv_scroll_05",
                Name = IJ_LOOT_NAME_60780,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Leatherworking,
                DropChance = 10,
            },
            [2] = {
                Id = "17767",
                Icon = "inv_helmet_17",
                Name = IJ_LOOT_NAME_17767,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Mail,
                DropChance = 33,
                LevelRequirement = 46,
            },
            [3] = {
                Id = "17742",
                Icon = "inv_chest_leather_08",
                Name = IJ_LOOT_NAME_17742,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 33,
                LevelRequirement = 46,
            },
            [4] = {
                Id = "17741",
                Icon = "inv_chest_cloth_15",
                Name = IJ_LOOT_NAME_17741,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 46,
            },
        }
    },
    [4] = { -- NOTE: Missing abilities
        Id = "12236",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "vyletongue" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "vyletongue" .. IMPF,
        Name = IJ_DB_DUNGEON_MARA_BOSS_NAME_12236,
        Story = IJ_DB_DUNGEON_MARA_BOSS_STORY_12236,
        MapCoordinateX = 33.0,
        MapCoordinateY = 32.8,
        Loot = {
            [1] = {
                Id = "17752",
                Icon = "inv_weapon_shortblade_09",
                Name = IJ_LOOT_NAME_17752,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 33,
                LevelRequirement = 45,
            },
            [2] = {
                Id = "17754",
                Icon = "inv_pants_wolf",
                Name = IJ_LOOT_NAME_17754,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 33,
                LevelRequirement = 45,
            },
            [3] = {
                Id = "17755",
                Icon = "inv_belt_24",
                Name = IJ_LOOT_NAME_17755,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 45,
            },
            [4] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 1,
            },
        }
    },
    [5] = { -- NOTE: Missing abilities
        Id = "12225",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "celebras" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "celebras" .. IMPF,
        Name = IJ_DB_DUNGEON_MARA_BOSS_NAME_12225,
        Story = IJ_DB_DUNGEON_MARA_BOSS_STORY_12225,
        MapCoordinateX = 19.1,
        MapCoordinateY = 32.9,
        Loot = {
            [1] = {
                Id = "17738",
                Icon = "ability_whirlwind",
                Name = IJ_LOOT_NAME_17738,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.FistWeapon,
                DropChance = 33,
                LevelRequirement = 47,
            },
            [2] = {
                Id = "17739",
                Icon = "inv_misc_cape_17",
                Name = IJ_LOOT_NAME_17739,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 47,
            },
            [3] = {
                Id = "17740",
                Icon = "inv_helmet_12",
                Name = IJ_LOOT_NAME_17740,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 33,
                LevelRequirement = 47,
            },
            [4] = {
                Id = "60780",
                Icon = "inv_scroll_05",
                Name = IJ_LOOT_NAME_60780,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Leatherworking,
                DropChance = 3,
            },
            [5] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 1,
            },
        }
    },
    [6] = { -- NOTE: Missing abilities
        Id = "13601",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "gizlock" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "gizlock" .. IMPF,
        Name = IJ_DB_DUNGEON_MARA_BOSS_NAME_13601,
        Story = IJ_DB_DUNGEON_MARA_BOSS_STORY_13601,
        MapCoordinateX = 32.2,
        MapCoordinateY = 60.3,
        Loot = {
            [1] = {
                Id = "17717",
                Icon = "inv_weapon_rifle_05",
                Name = IJ_LOOT_NAME_17717,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Gun,
                DropChance = 33,
                LevelRequirement = 48,
            },
            [2] = {
                Id = "17718",
                Icon = "inv_shield_10",
                Name = IJ_LOOT_NAME_17718,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 33,
                LevelRequirement = 48,
            },
            [3] = {
                Id = "17719",
                Icon = "inv_sword_14",
                Name = IJ_LOOT_NAME_17719,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 33,
                LevelRequirement = 48,
            },
            [4] = {
                Id = "40083",
                Icon = "inv_scroll_03",
                Name = IJ_LOOT_NAME_40083,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Engineering,
                DropChance = 8,
            },
            [5] = {
                Id = "51809",
                Icon = "inv_scroll_05",
                Name = IJ_LOOT_NAME_51809,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Engineering,
                DropChance = 8,
            },
        }
    },
    [7] = { -- NOTE: Missing abilities
        Id = "12203",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "landslide" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "landslide" .. IMPF,
        Name = IJ_DB_DUNGEON_MARA_BOSS_NAME_12203,
        Story = IJ_DB_DUNGEON_MARA_BOSS_STORY_12203,
        MapCoordinateX = 32.2,
        MapCoordinateY = 60.3,
        Loot = {
            [1] = {
                Id = "17734",
                Icon = "inv_helmet_20",
                Name = IJ_LOOT_NAME_17734,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [2] = {
                Id = "17736",
                Icon = "inv_gauntlets_28",
                Name = IJ_LOOT_NAME_17736,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [3] = {
                Id = "17737",
                Icon = "inv_misc_orb_01",
                Name = IJ_LOOT_NAME_17737,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 25,
                LevelRequirement = 48,
            },
            [4] = {
                Id = "17943",
                Icon = "inv_hammer_17",
                Name = IJ_LOOT_NAME_17943,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 25,
                LevelRequirement = 48,
            },
        }
    },
    [8] = { -- NOTE: Missing abilities
        Id = "13596",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "rotgrip" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "rotgrip" .. IMPF,
        Name = IJ_DB_DUNGEON_MARA_BOSS_NAME_13596,
        Story = IJ_DB_DUNGEON_MARA_BOSS_STORY_13596,
        MapCoordinateX = 32.1,
        MapCoordinateY = 86.1,
        Loot = {
            [1] = {
                Id = "17728",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_17728,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 33,
                LevelRequirement = 48,
            },
            [2] = {
                Id = "17730",
                Icon = "inv_axe_04",
                Name = IJ_LOOT_NAME_17730,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 33,
                LevelRequirement = 48,
            },
            [3] = {
                Id = "17732",
                Icon = "inv_shoulder_05",
                Name = IJ_LOOT_NAME_17732,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 48,
            },
        }
    },
    [9] = { -- NOTE: Missing abilities
        Id = "12201",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "princess" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "princess" .. IMPF,
        Name = IJ_DB_DUNGEON_MARA_BOSS_NAME_12201,
        Story = IJ_DB_DUNGEON_MARA_BOSS_STORY_12201,
        MapCoordinateX = 20.2,
        MapCoordinateY = 83.1,
        Loot = {
            [1] = {
                Id = "17707",
                Icon = "inv_stone_01",
                Name = IJ_LOOT_NAME_17707,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 14,
                LevelRequirement = 49,
            },
            [2] = {
                Id = "17710",
                Icon = "inv_weapon_shortblade_14",
                Name = IJ_LOOT_NAME_17710,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Dagger,
                DropChance = 14,
                LevelRequirement = 49,
            },
            [3] = {
                Id = "17711",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_17711,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 49,
            },
            [4] = {
                Id = "17713",
                Icon = "inv_jewelry_ring_17",
                Name = IJ_LOOT_NAME_17713,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 14,
                LevelRequirement = 49,
            },
            [5] = {
                Id = "17714",
                Icon = "inv_bracer_14",
                Name = IJ_LOOT_NAME_17714,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 49,
            },
            [6] = {
                Id = "17715",
                Icon = "inv_crown_01",
                Name = IJ_LOOT_NAME_17715,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 49,
            },
            [7] = {
                Id = "17766",
                Icon = "inv_hammer_10",
                Name = IJ_LOOT_NAME_17766,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 14,
                LevelRequirement = 49,
            },
            [8] = {
                Id = "17780",
                Icon = "inv_sword_09",
                Name = IJ_LOOT_NAME_17780,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.Dagger,
                DropChance = 1,
                LevelRequirement = 49,
            },
            [9] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
        }
    },
}

IJDB.DG.MARA = MARA
