IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "scholo\\"

local SCHOLO = {}

SCHOLO.Name = IJ_DB_DUNGEON_SCHOLO_NAME
SCHOLO.Story = IJ_DB_DUNGEON_SCHOLO_STORY
SCHOLO.Type = IJLib.InstanceType.Dungeon
SCHOLO.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
SCHOLO.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
SCHOLO.MapId = IMI.Scholomance
SCHOLO.IconScale = 0.9
SCHOLO.MinLevel = 58
SCHOLO.MaxLevel = 60
SCHOLO.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.WesternPlaguelands,
        MapCoordinateX = 69.0,
        MapCoordinateY = 74.9,
    },
}
SCHOLO.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "10506",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "kirtonos" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "kirtonos" .. IMPF,
        Name = IJ_DB_DUNGEON_SCHOLO_BOSS_NAME_10506,
        Story = IJ_DB_DUNGEON_SCHOLO_BOSS_STORY_10506,
        Loot = {
            [1] = {
                Id = "13955",
                Icon = "inv_shoulder_25",
                Name = IJ_LOOT_NAME_13955,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [2] = {
                Id = "13956",
                Icon = "inv_belt_12",
                Name = IJ_LOOT_NAME_13956,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [3] = {
                Id = "13957",
                Icon = "inv_gauntlets_09",
                Name = IJ_LOOT_NAME_13957,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "13960",
                Icon = "inv_misc_orb_03",
                Name = IJ_LOOT_NAME_13960,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [5] = {
                Id = "13967",
                Icon = "inv_boots_plate_04",
                Name = IJ_LOOT_NAME_13967,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [6] = {
                Id = "13969",
                Icon = "inv_bracer_16",
                Name = IJ_LOOT_NAME_13969,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [7] = {
                Id = "13983",
                Icon = "inv_weapon_halberd_09",
                Name = IJ_LOOT_NAME_13983,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 11,
                LevelRequirement = 57,
            },
            [8] = {
                Id = "14024",
                Icon = "inv_weapon_shortblade_16",
                Name = IJ_LOOT_NAME_14024,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [9] = {
                Id = "16734",
                Icon = "inv_boots_plate_03",
                Name = IJ_LOOT_NAME_16734,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 54,
            },
            [10] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
        }
    },
    [2] = { -- NOTE: Missing abilities
        Id = "10503",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "jandice" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "jandice" .. IMPF,
        Name = IJ_DB_DUNGEON_SCHOLO_BOSS_NAME_10503,
        Story = IJ_DB_DUNGEON_SCHOLO_BOSS_STORY_10503,
        Loot = {
            [1] = {
                Id = "14541",
                Icon = "inv_sword_03",
                Name = IJ_LOOT_NAME_14541,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 14,
                LevelRequirement = 56,
            },
            [2] = {
                Id = "14545",
                Icon = "inv_pants_11",
                Name = IJ_LOOT_NAME_14545,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [3] = {
                Id = "14548",
                Icon = "inv_shoulder_11",
                Name = IJ_LOOT_NAME_14548,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [4] = {
                Id = "16701",
                Icon = "inv_misc_bone_taurenskull_01",
                Name = IJ_LOOT_NAME_16701,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 55,
            },
            [5] = {
                Id = "18689",
                Icon = "inv_misc_cape_20",
                Name = IJ_LOOT_NAME_18689,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [6] = {
                Id = "18690",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_18690,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [7] = {
                Id = "22394",
                Icon = "inv_staff_29",
                Name = IJ_LOOT_NAME_22394,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [8] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [9] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [3] = { -- NOTE: Missing abilities
        Id = "11622",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "rattlegore" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "rattlegore" .. IMPF,
        Name = IJ_DB_DUNGEON_SCHOLO_BOSS_NAME_11622,
        Story = IJ_DB_DUNGEON_SCHOLO_BOSS_STORY_11622,
        Loot = {
            [1] = {
                Id = "18782",
                Icon = "inv_misc_note_03",
                Name = IJ_LOOT_NAME_18782,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 40,
                LevelRequirement = 50,
            },
            [2] = {
                Id = "14528",
                Icon = "inv_shield_02",
                Name = IJ_LOOT_NAME_14528,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [3] = {
                Id = "14531",
                Icon = "inv_hammer_13",
                Name = IJ_LOOT_NAME_14531,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 14,
                LevelRequirement = 54,
            },
            [4] = {
                Id = "14537",
                Icon = "inv_boots_plate_09",
                Name = IJ_LOOT_NAME_14537,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [5] = {
                Id = "14538",
                Icon = "inv_shoulder_02",
                Name = IJ_LOOT_NAME_14538,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [6] = {
                Id = "14539",
                Icon = "inv_helmet_14",
                Name = IJ_LOOT_NAME_14539,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [7] = {
                Id = "16711",
                Icon = "inv_boots_08",
                Name = IJ_LOOT_NAME_16711,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 54,
            },
            [8] = {
                Id = "18686",
                Icon = "inv_shoulder_03",
                Name = IJ_LOOT_NAME_18686,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [9] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [10] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [4] = { -- NOTE: Missing abilities
        Id = "14516",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "darkreaver" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "darkreaver" .. IMPF,
        Name = IJ_DB_DUNGEON_SCHOLO_BOSS_NAME_14516,
        Story = IJ_DB_DUNGEON_SCHOLO_BOSS_STORY_14516,
        Loot = {
            [1] = {
                Id = "18758",
                Icon = "inv_weapon_shortblade_18",
                Name = IJ_LOOT_NAME_18758,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 25,
                LevelRequirement = 57,
            },
            [2] = {
                Id = "18759",
                Icon = "inv_axe_18",
                Name = IJ_LOOT_NAME_18759,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 25,
                LevelRequirement = 57,
            },
            [3] = {
                Id = "18760",
                Icon = "inv_jewelry_ring_09",
                Name = IJ_LOOT_NAME_18760,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 57,
            },
            [4] = {
                Id = "18761",
                Icon = "inv_wand_12",
                Name = IJ_LOOT_NAME_18761,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 25,
                LevelRequirement = 57,
            },
        }
    },
    [5] = { -- NOTE: Missing abilities
        Id = "10433",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "marduk" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "marduk" .. IMPF,
        Name = IJ_DB_DUNGEON_SCHOLO_BOSS_NAME_10433,
        Story = IJ_DB_DUNGEON_SCHOLO_BOSS_STORY_10433,
        Loot = {
            [1] = {
                Id = "14576",
                Icon = "inv_sword_15",
                Name = IJ_LOOT_NAME_14576,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Sword,
                DropChance = 7,
                LevelRequirement = 54,
            },
            [2] = {
                Id = "18692",
                Icon = "inv_boots_plate_08",
                Name = IJ_LOOT_NAME_18692,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 54,
            },
            [3] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [4] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [6] = { -- NOTE: Missing abilities
        Id = "10432",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "vectus" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "vectus" .. IMPF,
        Name = IJ_DB_DUNGEON_SCHOLO_BOSS_NAME_10432,
        Story = IJ_DB_DUNGEON_SCHOLO_BOSS_STORY_10432,
        Loot = {
            [1] = {
                Id = "14577",
                Icon = "inv_pants_08",
                Name = IJ_LOOT_NAME_14577,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 56,
            },
            [2] = {
                Id = "18691",
                Icon = "inv_jewelry_necklace_06",
                Name = IJ_LOOT_NAME_18691,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 7,
                LevelRequirement = 56,
            },
            [3] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [4] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [7] = { -- NOTE: Missing abilities
        Id = "10508",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "ras" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "ras" .. IMPF,
        Name = IJ_DB_DUNGEON_SCHOLO_BOSS_NAME_10508,
        Story = IJ_DB_DUNGEON_SCHOLO_BOSS_STORY_10508,
        Loot = {
            [1] = {
                Id = "13952",
                Icon = "inv_axe_03",
                Name = IJ_LOOT_NAME_13952,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Axe,
                DropChance = 8,
                LevelRequirement = 57,
            },
            [2] = {
                Id = "14340",
                Icon = "inv_chest_cloth_46",
                Name = IJ_LOOT_NAME_14340,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 8,
                LevelRequirement = 57,
            },
            [3] = {
                Id = "14487",
                Icon = "inv_hammer_13",
                Name = IJ_LOOT_NAME_14487,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 8,
                LevelRequirement = 57,
            },
            [4] = {
                Id = "14502",
                Icon = "inv_belt_10",
                Name = IJ_LOOT_NAME_14502,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 8,
                LevelRequirement = 57,
            },
            [5] = {
                Id = "14503",
                Icon = "inv_shoulder_25",
                Name = IJ_LOOT_NAME_14503,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 8,
                LevelRequirement = 57,
            },
            [6] = {
                Id = "14522",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_14522,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 8,
                LevelRequirement = 57,
            },
            [7] = {
                Id = "14525",
                Icon = "inv_gauntlets_29",
                Name = IJ_LOOT_NAME_14525,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 8,
                LevelRequirement = 57,
            },
            [8] = {
                Id = "16689",
                Icon = "inv_shoulder_23",
                Name = IJ_LOOT_NAME_16689,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 8,
                LevelRequirement = 55,
            },
            [9] = {
                Id = "18693",
                Icon = "inv_gauntlets_16",
                Name = IJ_LOOT_NAME_18693,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 8,
                LevelRequirement = 57,
            },
            [10] = {
                Id = "18694",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_18694,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 8,
                LevelRequirement = 57,
            },
            [11] = {
                Id = "18695",
                Icon = "inv_misc_book_06",
                Name = IJ_LOOT_NAME_18695,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 8,
                LevelRequirement = 57,
            },
            [12] = {
                Id = "18696",
                Icon = "inv_shield_02",
                Name = IJ_LOOT_NAME_18696,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 8,
                LevelRequirement = 57,
            },
            [13] = {
                Id = "13314",
                Icon = "inv_chest_cloth_12",
                Name = IJ_LOOT_NAME_13314,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 2,
                LevelRequirement = 57,
            },
            [14] = {
                Id = "13521",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_13521,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 3,
            },
            [15] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [16] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [8] = { -- NOTE: Missing abilities
        Id = "16118",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "kormok" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "kormok" .. IMPF,
        Name = IJ_DB_DUNGEON_SCHOLO_BOSS_NAME_16118,
        Story = IJ_DB_DUNGEON_SCHOLO_BOSS_STORY_16118,
        Loot = {
            [1] = {
                Id = "22303",
                Icon = "inv_pants_08",
                Name = IJ_LOOT_NAME_22303,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 57,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [2] = {
                Id = "22326",
                Icon = "inv_jewelry_ring_19",
                Name = IJ_LOOT_NAME_22326,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 58,
            },
            [3] = {
                Id = "22331",
                Icon = "inv_jewelry_ring_33",
                Name = IJ_LOOT_NAME_22331,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 57,
            },
            [4] = {
                Id = "22332",
                Icon = "inv_sword_25",
                Name = IJ_LOOT_NAME_22332,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Sword,
                DropChance = 20,
                LevelRequirement = 57,
            },
            [5] = {
                Id = "22333",
                Icon = "inv_hammer_04",
                Name = IJ_LOOT_NAME_22333,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 20,
                LevelRequirement = 57,
            },
        }
    },
    [9] = { -- NOTE: Missing abilities
        Id = "10505",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "malicia" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "malicia" .. IMPF,
        Name = IJ_DB_DUNGEON_SCHOLO_BOSS_NAME_10505,
        Story = IJ_DB_DUNGEON_SCHOLO_BOSS_STORY_10505,
        Loot = {
            [1] = {
                Id = "12753",
                Icon = "inv_misc_shadowegg",
                Name = IJ_LOOT_NAME_12753,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Reagent,
                DropChance = 17,
            },
            [2] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [3] = {
                Id = "14611",
                Icon = "inv_chest_leather_05",
                Name = IJ_LOOT_NAME_14611,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "14612",
                Icon = "inv_pants_06",
                Name = IJ_LOOT_NAME_14612,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [5] = {
                Id = "14614",
                Icon = "inv_belt_23",
                Name = IJ_LOOT_NAME_14614,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [6] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [7] = {
                Id = "16710",
                Icon = "inv_bracer_07",
                Name = IJ_LOOT_NAME_16710,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 52,
            },
            [8] = {
                Id = "23201",
                Icon = "inv_relics_libramofhope",
                Name = IJ_LOOT_NAME_23201,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Libram,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "23200",
                Icon = "inv_relics_totemoflife",
                Name = IJ_LOOT_NAME_23200,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Totem,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "18683",
                Icon = "inv_hammer_13",
                Name = IJ_LOOT_NAME_18683,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [11] = {
                Id = "18684",
                Icon = "inv_jewelry_ring_15",
                Name = IJ_LOOT_NAME_18684,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [12] = {
                Id = "18682",
                Icon = "inv_pants_02",
                Name = IJ_LOOT_NAME_18682,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [13] = {
                Id = "18681",
                Icon = "inv_shoulder_05",
                Name = IJ_LOOT_NAME_18681,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [14] = {
                Id = "18680",
                Icon = "inv_weapon_bow_08",
                Name = IJ_LOOT_NAME_18680,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [15] = {
                Id = "14641",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_14641,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [16] = {
                Id = "14640",
                Icon = "inv_gauntlets_15",
                Name = IJ_LOOT_NAME_14640,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [17] = {
                Id = "14638",
                Icon = "inv_pants_07",
                Name = IJ_LOOT_NAME_14638,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [18] = {
                Id = "14637",
                Icon = "inv_chest_leather_03",
                Name = IJ_LOOT_NAME_14637,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [19] = {
                Id = "14636",
                Icon = "inv_belt_16",
                Name = IJ_LOOT_NAME_14636,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [20] = {
                Id = "14633",
                Icon = "inv_shoulder_02",
                Name = IJ_LOOT_NAME_14633,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [21] = {
                Id = "14632",
                Icon = "inv_pants_08",
                Name = IJ_LOOT_NAME_14632,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [22] = {
                Id = "14631",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_14631,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [23] = {
                Id = "14629",
                Icon = "inv_bracer_07",
                Name = IJ_LOOT_NAME_14629,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [24] = {
                Id = "14626",
                Icon = "inv_chest_cloth_43",
                Name = IJ_LOOT_NAME_14626,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [25] = {
                Id = "14624",
                Icon = "inv_chest_chain_15",
                Name = IJ_LOOT_NAME_14624,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [26] = {
                Id = "14623",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_14623,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [27] = {
                Id = "14622",
                Icon = "inv_gauntlets_28",
                Name = IJ_LOOT_NAME_14622,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [28] = {
                Id = "14621",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_14621,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [29] = {
                Id = "14620",
                Icon = "inv_belt_12",
                Name = IJ_LOOT_NAME_14620,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [30] = {
                Id = "14616",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_14616,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [31] = {
                Id = "14615",
                Icon = "inv_gauntlets_26",
                Name = IJ_LOOT_NAME_14615,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
        }
    },
    [10] = { -- NOTE: Missing abilities
        Id = "11261",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "krastinov" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "krastinov" .. IMPF,
        Name = IJ_DB_DUNGEON_SCHOLO_BOSS_NAME_11261,
        Story = IJ_DB_DUNGEON_SCHOLO_BOSS_STORY_11261,
        Loot = {
            [1] = {
                Id = "16684",
                Icon = "inv_gauntlets_17",
                Name = IJ_LOOT_NAME_16684,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 54,
            },
            [2] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [3] = {
                Id = "14612",
                Icon = "inv_pants_06",
                Name = IJ_LOOT_NAME_14612,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "14614",
                Icon = "inv_belt_23",
                Name = IJ_LOOT_NAME_14614,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [5] = {
                Id = "14611",
                Icon = "inv_chest_leather_05",
                Name = IJ_LOOT_NAME_14611,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [6] = {
                Id = "14615",
                Icon = "inv_gauntlets_26",
                Name = IJ_LOOT_NAME_14615,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [7] = {
                Id = "14616",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_14616,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [8] = {
                Id = "14620",
                Icon = "inv_belt_12",
                Name = IJ_LOOT_NAME_14620,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [9] = {
                Id = "14621",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_14621,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [10] = {
                Id = "14622",
                Icon = "inv_gauntlets_28",
                Name = IJ_LOOT_NAME_14622,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [11] = {
                Id = "14623",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_14623,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [12] = {
                Id = "14626",
                Icon = "inv_chest_cloth_43",
                Name = IJ_LOOT_NAME_14626,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [13] = {
                Id = "14624",
                Icon = "inv_chest_chain_15",
                Name = IJ_LOOT_NAME_14624,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [14] = {
                Id = "14629",
                Icon = "inv_bracer_07",
                Name = IJ_LOOT_NAME_14629,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [15] = {
                Id = "14631",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_14631,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [16] = {
                Id = "14632",
                Icon = "inv_pants_08",
                Name = IJ_LOOT_NAME_14632,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [17] = {
                Id = "14633",
                Icon = "inv_shoulder_02",
                Name = IJ_LOOT_NAME_14633,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [18] = {
                Id = "14636",
                Icon = "inv_belt_16",
                Name = IJ_LOOT_NAME_14636,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [19] = {
                Id = "14637",
                Icon = "inv_chest_leather_03",
                Name = IJ_LOOT_NAME_14637,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [20] = {
                Id = "14638",
                Icon = "inv_pants_07",
                Name = IJ_LOOT_NAME_14638,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [21] = {
                Id = "14640",
                Icon = "inv_gauntlets_15",
                Name = IJ_LOOT_NAME_14640,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [22] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [23] = {
                Id = "14617",
                Icon = "inv_shirt_red_01",
                Name = IJ_LOOT_NAME_14617,
                Quality = IQ.Common,
                ItemSlot = IS.Shirt,
                DropChance = 2,
            },
            [24] = {
                Id = "23201",
                Icon = "inv_relics_libramofhope",
                Name = IJ_LOOT_NAME_23201,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Libram,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [25] = {
                Id = "23200",
                Icon = "inv_relics_totemoflife",
                Name = IJ_LOOT_NAME_23200,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Totem,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [26] = {
                Id = "18684",
                Icon = "inv_jewelry_ring_15",
                Name = IJ_LOOT_NAME_18684,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [27] = {
                Id = "18683",
                Icon = "inv_hammer_13",
                Name = IJ_LOOT_NAME_18683,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [28] = {
                Id = "18681",
                Icon = "inv_shoulder_05",
                Name = IJ_LOOT_NAME_18681,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [29] = {
                Id = "18682",
                Icon = "inv_pants_02",
                Name = IJ_LOOT_NAME_18682,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [30] = {
                Id = "18680",
                Icon = "inv_weapon_bow_08",
                Name = IJ_LOOT_NAME_18680,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [31] = {
                Id = "14641",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_14641,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
        }
    },
    [11] = { -- NOTE: Missing abilities
        Id = "10901",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "polkelt" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "polkelt" .. IMPF,
        Name = IJ_DB_DUNGEON_SCHOLO_BOSS_NAME_10901,
        Story = IJ_DB_DUNGEON_SCHOLO_BOSS_STORY_10901,
        Loot = {
            [1] = {
                Id = "12753",
                Icon = "inv_misc_shadowegg",
                Name = IJ_LOOT_NAME_12753,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Reagent,
                DropChance = 17,
            },
            [2] = {
                Id = "16705",
                Icon = "inv_gauntlets_32",
                Name = IJ_LOOT_NAME_16705,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 54,
            },
            [3] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [4] = {
                Id = "14611",
                Icon = "inv_chest_leather_05",
                Name = IJ_LOOT_NAME_14611,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [5] = {
                Id = "14612",
                Icon = "inv_pants_06",
                Name = IJ_LOOT_NAME_14612,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [6] = {
                Id = "14614",
                Icon = "inv_belt_23",
                Name = IJ_LOOT_NAME_14614,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [7] = {
                Id = "14615",
                Icon = "inv_gauntlets_26",
                Name = IJ_LOOT_NAME_14615,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [8] = {
                Id = "14616",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_14616,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [9] = {
                Id = "14620",
                Icon = "inv_belt_12",
                Name = IJ_LOOT_NAME_14620,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [10] = {
                Id = "14621",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_14621,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [11] = {
                Id = "14622",
                Icon = "inv_gauntlets_28",
                Name = IJ_LOOT_NAME_14622,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [12] = {
                Id = "14623",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_14623,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [13] = {
                Id = "14624",
                Icon = "inv_chest_chain_15",
                Name = IJ_LOOT_NAME_14624,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [14] = {
                Id = "14626",
                Icon = "inv_chest_cloth_43",
                Name = IJ_LOOT_NAME_14626,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [15] = {
                Id = "14629",
                Icon = "inv_bracer_07",
                Name = IJ_LOOT_NAME_14629,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [16] = {
                Id = "14631",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_14631,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [17] = {
                Id = "14632",
                Icon = "inv_pants_08",
                Name = IJ_LOOT_NAME_14632,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [18] = {
                Id = "14633",
                Icon = "inv_shoulder_02",
                Name = IJ_LOOT_NAME_14633,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [19] = {
                Id = "14636",
                Icon = "inv_belt_16",
                Name = IJ_LOOT_NAME_14636,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [20] = {
                Id = "14637",
                Icon = "inv_chest_leather_03",
                Name = IJ_LOOT_NAME_14637,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [21] = {
                Id = "14638",
                Icon = "inv_pants_07",
                Name = IJ_LOOT_NAME_14638,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [22] = {
                Id = "14640",
                Icon = "inv_gauntlets_15",
                Name = IJ_LOOT_NAME_14640,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [23] = {
                Id = "14641",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_14641,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [24] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [25] = {
                Id = "23201",
                Icon = "inv_relics_libramofhope",
                Name = IJ_LOOT_NAME_23201,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Libram,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [26] = {
                Id = "23200",
                Icon = "inv_relics_totemoflife",
                Name = IJ_LOOT_NAME_23200,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Totem,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [27] = {
                Id = "18684",
                Icon = "inv_jewelry_ring_15",
                Name = IJ_LOOT_NAME_18684,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [28] = {
                Id = "18683",
                Icon = "inv_hammer_13",
                Name = IJ_LOOT_NAME_18683,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [29] = {
                Id = "18682",
                Icon = "inv_pants_02",
                Name = IJ_LOOT_NAME_18682,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [30] = {
                Id = "18681",
                Icon = "inv_shoulder_05",
                Name = IJ_LOOT_NAME_18681,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [31] = {
                Id = "18680",
                Icon = "inv_weapon_bow_08",
                Name = IJ_LOOT_NAME_18680,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 4,
                LevelRequirement = 56,
            },
        }
    },
    [12] = { -- NOTE: Missing abilities
        Id = "10507",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "ravenian" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "ravenian" .. IMPF,
        Name = IJ_DB_DUNGEON_SCHOLO_BOSS_NAME_10507,
        Story = IJ_DB_DUNGEON_SCHOLO_BOSS_STORY_10507,
        Loot = {
            [1] = {
                Id = "12753",
                Icon = "inv_misc_shadowegg",
                Name = IJ_LOOT_NAME_12753,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Reagent,
                DropChance = 17,
            },
            [2] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [3] = {
                Id = "14611",
                Icon = "inv_chest_leather_05",
                Name = IJ_LOOT_NAME_14611,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "14612",
                Icon = "inv_pants_06",
                Name = IJ_LOOT_NAME_14612,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [5] = {
                Id = "14614",
                Icon = "inv_belt_23",
                Name = IJ_LOOT_NAME_14614,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [6] = {
                Id = "14615",
                Icon = "inv_gauntlets_26",
                Name = IJ_LOOT_NAME_14615,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [7] = {
                Id = "14616",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_14616,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [8] = {
                Id = "14620",
                Icon = "inv_belt_12",
                Name = IJ_LOOT_NAME_14620,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [9] = {
                Id = "14621",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_14621,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [10] = {
                Id = "14622",
                Icon = "inv_gauntlets_28",
                Name = IJ_LOOT_NAME_14622,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [11] = {
                Id = "14623",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_14623,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [12] = {
                Id = "14624",
                Icon = "inv_chest_chain_15",
                Name = IJ_LOOT_NAME_14624,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [13] = {
                Id = "14626",
                Icon = "inv_chest_cloth_43",
                Name = IJ_LOOT_NAME_14626,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [14] = {
                Id = "14629",
                Icon = "inv_bracer_07",
                Name = IJ_LOOT_NAME_14629,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [15] = {
                Id = "14631",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_14631,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [16] = {
                Id = "14632",
                Icon = "inv_pants_08",
                Name = IJ_LOOT_NAME_14632,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [17] = {
                Id = "14633",
                Icon = "inv_shoulder_02",
                Name = IJ_LOOT_NAME_14633,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [18] = {
                Id = "14636",
                Icon = "inv_belt_16",
                Name = IJ_LOOT_NAME_14636,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [19] = {
                Id = "14637",
                Icon = "inv_chest_leather_03",
                Name = IJ_LOOT_NAME_14637,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [20] = {
                Id = "14638",
                Icon = "inv_pants_07",
                Name = IJ_LOOT_NAME_14638,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [21] = {
                Id = "14640",
                Icon = "inv_gauntlets_15",
                Name = IJ_LOOT_NAME_14640,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [22] = {
                Id = "14641",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_14641,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [23] = {
                Id = "18680",
                Icon = "inv_weapon_bow_08",
                Name = IJ_LOOT_NAME_18680,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [24] = {
                Id = "18681",
                Icon = "inv_shoulder_05",
                Name = IJ_LOOT_NAME_18681,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [25] = {
                Id = "18682",
                Icon = "inv_pants_02",
                Name = IJ_LOOT_NAME_18682,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [26] = {
                Id = "18683",
                Icon = "inv_hammer_13",
                Name = IJ_LOOT_NAME_18683,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [27] = {
                Id = "23200",
                Icon = "inv_relics_totemoflife",
                Name = IJ_LOOT_NAME_23200,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Totem,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [28] = {
                Id = "18684",
                Icon = "inv_jewelry_ring_15",
                Name = IJ_LOOT_NAME_18684,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [29] = {
                Id = "23201",
                Icon = "inv_relics_libramofhope",
                Name = IJ_LOOT_NAME_23201,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Libram,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [30] = {
                Id = "16716",
                Icon = "inv_belt_15",
                Name = IJ_LOOT_NAME_16716,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 53,
            },
            [31] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [13] = { -- NOTE: Missing abilities
        Id = "10504",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "alexei" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "alexei" .. IMPF,
        Name = IJ_DB_DUNGEON_SCHOLO_BOSS_NAME_10504,
        Story = IJ_DB_DUNGEON_SCHOLO_BOSS_STORY_10504,
        Loot = {
            [1] = {
                Id = "16722",
                Icon = "inv_bracer_14",
                Name = IJ_LOOT_NAME_16722,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 5,
                LevelRequirement = 52,
            },
            [2] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [3] = {
                Id = "14611",
                Icon = "inv_chest_leather_05",
                Name = IJ_LOOT_NAME_14611,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "14612",
                Icon = "inv_pants_06",
                Name = IJ_LOOT_NAME_14612,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [5] = {
                Id = "14615",
                Icon = "inv_gauntlets_26",
                Name = IJ_LOOT_NAME_14615,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [6] = {
                Id = "14614",
                Icon = "inv_belt_23",
                Name = IJ_LOOT_NAME_14614,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [7] = {
                Id = "14616",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_14616,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [8] = {
                Id = "14620",
                Icon = "inv_belt_12",
                Name = IJ_LOOT_NAME_14620,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [9] = {
                Id = "14621",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_14621,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [10] = {
                Id = "14622",
                Icon = "inv_gauntlets_28",
                Name = IJ_LOOT_NAME_14622,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [11] = {
                Id = "14623",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_14623,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [12] = {
                Id = "14624",
                Icon = "inv_chest_chain_15",
                Name = IJ_LOOT_NAME_14624,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [13] = {
                Id = "14626",
                Icon = "inv_chest_cloth_43",
                Name = IJ_LOOT_NAME_14626,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [14] = {
                Id = "14629",
                Icon = "inv_bracer_07",
                Name = IJ_LOOT_NAME_14629,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [15] = {
                Id = "14631",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_14631,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [16] = {
                Id = "14632",
                Icon = "inv_pants_08",
                Name = IJ_LOOT_NAME_14632,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [17] = {
                Id = "14633",
                Icon = "inv_shoulder_02",
                Name = IJ_LOOT_NAME_14633,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [18] = {
                Id = "14636",
                Icon = "inv_belt_16",
                Name = IJ_LOOT_NAME_14636,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [19] = {
                Id = "14638",
                Icon = "inv_pants_07",
                Name = IJ_LOOT_NAME_14638,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [20] = {
                Id = "14640",
                Icon = "inv_gauntlets_15",
                Name = IJ_LOOT_NAME_14640,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [21] = {
                Id = "14637",
                Icon = "inv_chest_leather_03",
                Name = IJ_LOOT_NAME_14637,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [22] = {
                Id = "14641",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_14641,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [23] = {
                Id = "18680",
                Icon = "inv_weapon_bow_08",
                Name = IJ_LOOT_NAME_18680,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [24] = {
                Id = "18681",
                Icon = "inv_shoulder_05",
                Name = IJ_LOOT_NAME_18681,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [25] = {
                Id = "18682",
                Icon = "inv_pants_02",
                Name = IJ_LOOT_NAME_18682,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [26] = {
                Id = "18683",
                Icon = "inv_hammer_13",
                Name = IJ_LOOT_NAME_18683,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [27] = {
                Id = "18684",
                Icon = "inv_jewelry_ring_15",
                Name = IJ_LOOT_NAME_18684,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [28] = {
                Id = "23200",
                Icon = "inv_relics_totemoflife",
                Name = IJ_LOOT_NAME_23200,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Totem,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [29] = {
                Id = "23201",
                Icon = "inv_relics_libramofhope",
                Name = IJ_LOOT_NAME_23201,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Libram,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [30] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [14] = { -- NOTE: Missing abilities
        Id = "10502",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "illucia" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "illucia" .. IMPF,
        Name = IJ_DB_DUNGEON_SCHOLO_BOSS_NAME_10502,
        Story = IJ_DB_DUNGEON_SCHOLO_BOSS_STORY_10502,
        Loot = {
            [1] = {
                Id = "12753",
                Icon = "inv_misc_shadowegg",
                Name = IJ_LOOT_NAME_12753,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Reagent,
                DropChance = 19,
            },
            [2] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [3] = {
                Id = "14611",
                Icon = "inv_chest_leather_05",
                Name = IJ_LOOT_NAME_14611,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "14612",
                Icon = "inv_pants_06",
                Name = IJ_LOOT_NAME_14612,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [5] = {
                Id = "14614",
                Icon = "inv_belt_23",
                Name = IJ_LOOT_NAME_14614,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [6] = {
                Id = "14615",
                Icon = "inv_gauntlets_26",
                Name = IJ_LOOT_NAME_14615,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [7] = {
                Id = "14616",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_14616,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [8] = {
                Id = "14620",
                Icon = "inv_belt_12",
                Name = IJ_LOOT_NAME_14620,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [9] = {
                Id = "14621",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_14621,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [10] = {
                Id = "14622",
                Icon = "inv_gauntlets_28",
                Name = IJ_LOOT_NAME_14622,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [11] = {
                Id = "14623",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_14623,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [12] = {
                Id = "14624",
                Icon = "inv_chest_chain_15",
                Name = IJ_LOOT_NAME_14624,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [13] = {
                Id = "14626",
                Icon = "inv_chest_cloth_43",
                Name = IJ_LOOT_NAME_14626,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [14] = {
                Id = "14629",
                Icon = "inv_bracer_07",
                Name = IJ_LOOT_NAME_14629,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [15] = {
                Id = "14631",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_14631,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [16] = {
                Id = "14632",
                Icon = "inv_pants_08",
                Name = IJ_LOOT_NAME_14632,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [17] = {
                Id = "14633",
                Icon = "inv_shoulder_02",
                Name = IJ_LOOT_NAME_14633,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [18] = {
                Id = "14636",
                Icon = "inv_belt_16",
                Name = IJ_LOOT_NAME_14636,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [19] = {
                Id = "14637",
                Icon = "inv_chest_leather_03",
                Name = IJ_LOOT_NAME_14637,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [20] = {
                Id = "14638",
                Icon = "inv_pants_07",
                Name = IJ_LOOT_NAME_14638,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [21] = {
                Id = "14640",
                Icon = "inv_gauntlets_15",
                Name = IJ_LOOT_NAME_14640,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [22] = {
                Id = "14641",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_14641,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [23] = {
                Id = "18680",
                Icon = "inv_weapon_bow_08",
                Name = IJ_LOOT_NAME_18680,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [24] = {
                Id = "18681",
                Icon = "inv_shoulder_05",
                Name = IJ_LOOT_NAME_18681,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [25] = {
                Id = "18682",
                Icon = "inv_pants_02",
                Name = IJ_LOOT_NAME_18682,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [26] = {
                Id = "18683",
                Icon = "inv_hammer_13",
                Name = IJ_LOOT_NAME_18683,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [27] = {
                Id = "18684",
                Icon = "inv_jewelry_ring_15",
                Name = IJ_LOOT_NAME_18684,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 4,
                LevelRequirement = 56,
            },
            [28] = {
                Id = "23200",
                Icon = "inv_relics_totemoflife",
                Name = IJ_LOOT_NAME_23200,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Totem,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [29] = {
                Id = "23201",
                Icon = "inv_relics_libramofhope",
                Name = IJ_LOOT_NAME_23201,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Libram,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [30] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [15] = { -- NOTE: Missing abilities
        Id = "1853",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "gandling" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "gandling" .. IMPF,
        Name = IJ_DB_DUNGEON_SCHOLO_BOSS_NAME_1853,
        Story = IJ_DB_DUNGEON_SCHOLO_BOSS_STORY_1853,
        Loot = {
            [1] = {
                Id = "56107",
                Icon = "inv_misc_note_03",
                Name = IJ_LOOT_NAME_56107,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Jewelcrafting,
                DropChance = 30,
                LevelRequirement = 50,
            },
            [2] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [3] = {
                Id = "13398",
                Icon = "inv_boots_08",
                Name = IJ_LOOT_NAME_13398,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [4] = {
                Id = "13938",
                Icon = "inv_misc_bone_taurenskull_01",
                Name = IJ_LOOT_NAME_13938,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [5] = {
                Id = "13944",
                Icon = "inv_chest_chain_17",
                Name = IJ_LOOT_NAME_13944,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [6] = {
                Id = "13951",
                Icon = "inv_bracer_18",
                Name = IJ_LOOT_NAME_13951,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [7] = {
                Id = "13953",
                Icon = "inv_sword_41",
                Name = IJ_LOOT_NAME_13953,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Sword,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [8] = {
                Id = "13964",
                Icon = "inv_weapon_shortblade_25",
                Name = IJ_LOOT_NAME_13964,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [9] = {
                Id = "22433",
                Icon = "inv_jewelry_ring_16",
                Name = IJ_LOOT_NAME_22433,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 14,
                LevelRequirement = 58,
            },
            [10] = {
                Id = "16667",
                Icon = "inv_helmet_04",
                Name = IJ_LOOT_NAME_16667,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 57,
            },
            [11] = {
                Id = "16677",
                Icon = "inv_helmet_24",
                Name = IJ_LOOT_NAME_16677,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 57,
            },
            [12] = {
                Id = "16686",
                Icon = "inv_crown_02",
                Name = IJ_LOOT_NAME_16686,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 57,
            },
            [13] = {
                Id = "16693",
                Icon = "inv_crown_01",
                Name = IJ_LOOT_NAME_16693,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 57,
            },
            [14] = {
                Id = "16698",
                Icon = "inv_helmet_29",
                Name = IJ_LOOT_NAME_16698,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 57,
            },
            [15] = {
                Id = "16707",
                Icon = "inv_helmet_41",
                Name = IJ_LOOT_NAME_16707,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 57,
            },
            [16] = {
                Id = "16720",
                Icon = "inv_helmet_27",
                Name = IJ_LOOT_NAME_16720,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 57,
            },
            [17] = {
                Id = "16727",
                Icon = "inv_helmet_08",
                Name = IJ_LOOT_NAME_16727,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 57,
            },
            [18] = {
                Id = "16731",
                Icon = "inv_helmet_02",
                Name = IJ_LOOT_NAME_16731,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 57,
            },
            [19] = {
                Id = "13501",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_13501,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [20] = {
                Id = "47413",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_47413,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [21] = {
                Id = "47415",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_47415,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [22] = {
                Id = "14514",
                Icon = "inv_scroll_03",
                Name = IJ_LOOT_NAME_14514,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Tailoring,
                DropChance = 7,
            },
            [23] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 3,
            },
            [24] = {
                Id = "13937",
                Icon = "inv_jewelry_talisman_12",
                Name = IJ_LOOT_NAME_13937,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 1,
                LevelRequirement = 57,
            },
        }
    },
}

IJDB.DG.SCHOLO = SCHOLO
