IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "st\\"

local ST = {}

ST.Name = IJ_DB_DUNGEON_ST_NAME
ST.Story = IJ_DB_DUNGEON_ST_STORY
ST.Type = IJLib.InstanceType.Dungeon
ST.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
ST.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
ST.MapId = IMI.TheTempleOfAtalHakkar
ST.IconScale = 0.9
ST.MinLevel = 46
ST.MaxLevel = 54
ST.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.SwampOfSorrows,
        MapCoordinateX = 70.1,
        MapCoordinateY = 54.6,
    },
}
ST.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "8580",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "atalalarion" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "atalalarion" .. IMPF,
        Name = IJ_DB_DUNGEON_ST_BOSS_NAME_8580,
        Story = IJ_DB_DUNGEON_ST_BOSS_STORY_8580,
        MapCoordinateX = 50.0,
        MapCoordinateY = 45.5,
        MapIsBelow = true,
        Loot = {
            [1] = {
                Id = "10798",
                Icon = "inv_belt_15",
                Name = IJ_LOOT_NAME_10798,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 33,
                LevelRequirement = 46,
            },
            [2] = {
                Id = "10799",
                Icon = "inv_spear_06",
                Name = IJ_LOOT_NAME_10799,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 33,
                LevelRequirement = 46,
            },
            [3] = {
                Id = "10800",
                Icon = "inv_bracer_08",
                Name = IJ_LOOT_NAME_10800,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 33,
                LevelRequirement = 47,
            },
            [4] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [5] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [2] = { -- NOTE: Missing abilities
        Id = "5708",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "spawn" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "spawn" .. IMPF,
        Name = IJ_DB_DUNGEON_ST_BOSS_NAME_5708,
        Story = IJ_DB_DUNGEON_ST_BOSS_STORY_5708,
        MapCoordinateX = 50.0,
        MapCoordinateY = 66.3,
        MapIsBelow = true,
        Loot = {
            [1] = {
                Id = "10801",
                Icon = "inv_boots_07",
                Name = IJ_LOOT_NAME_10801,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 47,
                LevelRequirement = 47,
            },
            [2] = {
                Id = "10802",
                Icon = "inv_misc_cape_02",
                Name = IJ_LOOT_NAME_10802,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 26,
                LevelRequirement = 47,
            },
        }
    },
    [3] = { -- NOTE: Missing abilities
        Id = "5713",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "gasher" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "gasher" .. IMPF,
        Name = IJ_DB_DUNGEON_ST_BOSS_NAME_5713,
        Story = IJ_DB_DUNGEON_ST_BOSS_STORY_5713,
        MapCoordinateX = 55.1,
        MapCoordinateY = 32.6,
        Loot = {
            [1] = {
                Id = "10783",
                Icon = "inv_shoulder_18",
                Name = IJ_LOOT_NAME_10783,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [2] = {
                Id = "10784",
                Icon = "inv_chest_chain_05",
                Name = IJ_LOOT_NAME_10784,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [3] = {
                Id = "10785",
                Icon = "inv_pants_07",
                Name = IJ_LOOT_NAME_10785,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [4] = {
                Id = "10786",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_10786,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [5] = {
                Id = "10787",
                Icon = "inv_bracer_18",
                Name = IJ_LOOT_NAME_10787,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [6] = {
                Id = "10788",
                Icon = "inv_belt_15",
                Name = IJ_LOOT_NAME_10788,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [7] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [4] = { -- NOTE: Missing abilities
        Id = "5717",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "mijan" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "mijan" .. IMPF,
        Name = IJ_DB_DUNGEON_ST_BOSS_NAME_5717,
        Story = IJ_DB_DUNGEON_ST_BOSS_STORY_5717,
        MapCoordinateX = 60.4,
        MapCoordinateY = 45.9,
        Loot = {
            [1] = {
                Id = "10783",
                Icon = "inv_shoulder_18",
                Name = IJ_LOOT_NAME_10783,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [2] = {
                Id = "10784",
                Icon = "inv_chest_chain_05",
                Name = IJ_LOOT_NAME_10784,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [3] = {
                Id = "10785",
                Icon = "inv_pants_07",
                Name = IJ_LOOT_NAME_10785,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [4] = {
                Id = "10786",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_10786,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [5] = {
                Id = "10787",
                Icon = "inv_bracer_18",
                Name = IJ_LOOT_NAME_10787,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [6] = {
                Id = "10788",
                Icon = "inv_belt_15",
                Name = IJ_LOOT_NAME_10788,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [7] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [5] = { -- NOTE: Missing abilities
        Id = "5712",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "zolo" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "zolo" .. IMPF,
        Name = IJ_DB_DUNGEON_ST_BOSS_NAME_5712,
        Story = IJ_DB_DUNGEON_ST_BOSS_STORY_5712,
        MapCoordinateX = 55.3,
        MapCoordinateY = 59.2,
        Loot = {
            [1] = {
                Id = "10783",
                Icon = "inv_shoulder_18",
                Name = IJ_LOOT_NAME_10783,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [2] = {
                Id = "10784",
                Icon = "inv_chest_chain_05",
                Name = IJ_LOOT_NAME_10784,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [3] = {
                Id = "10785",
                Icon = "inv_pants_07",
                Name = IJ_LOOT_NAME_10785,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [4] = {
                Id = "10786",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_10786,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [5] = {
                Id = "10787",
                Icon = "inv_bracer_18",
                Name = IJ_LOOT_NAME_10787,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [6] = {
                Id = "10788",
                Icon = "inv_belt_15",
                Name = IJ_LOOT_NAME_10788,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [7] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [6] = { -- NOTE: Missing abilities
        Id = "5716",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "zullor" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "zullor" .. IMPF,
        Name = IJ_DB_DUNGEON_ST_BOSS_NAME_5716,
        Story = IJ_DB_DUNGEON_ST_BOSS_STORY_5716,
        MapCoordinateX = 45.0,
        MapCoordinateY = 59.4,
        Loot = {
            [1] = {
                Id = "10783",
                Icon = "inv_shoulder_18",
                Name = IJ_LOOT_NAME_10783,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [2] = {
                Id = "10784",
                Icon = "inv_chest_chain_05",
                Name = IJ_LOOT_NAME_10784,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [3] = {
                Id = "10785",
                Icon = "inv_pants_07",
                Name = IJ_LOOT_NAME_10785,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [4] = {
                Id = "10786",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_10786,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [5] = {
                Id = "10787",
                Icon = "inv_bracer_18",
                Name = IJ_LOOT_NAME_10787,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [6] = {
                Id = "10788",
                Icon = "inv_belt_15",
                Name = IJ_LOOT_NAME_10788,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [7] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [7] = { -- NOTE: Missing abilities
        Id = "5715",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "hukku" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "hukku" .. IMPF,
        Name = IJ_DB_DUNGEON_ST_BOSS_NAME_5715,
        Story = IJ_DB_DUNGEON_ST_BOSS_STORY_5715,
        MapCoordinateX = 39.6,
        MapCoordinateY = 45.8,
        Loot = {
            [1] = {
                Id = "10783",
                Icon = "inv_shoulder_18",
                Name = IJ_LOOT_NAME_10783,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [2] = {
                Id = "10784",
                Icon = "inv_chest_chain_05",
                Name = IJ_LOOT_NAME_10784,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [3] = {
                Id = "10785",
                Icon = "inv_pants_07",
                Name = IJ_LOOT_NAME_10785,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [4] = {
                Id = "10786",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_10786,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [5] = {
                Id = "10787",
                Icon = "inv_bracer_18",
                Name = IJ_LOOT_NAME_10787,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [6] = {
                Id = "10788",
                Icon = "inv_belt_15",
                Name = IJ_LOOT_NAME_10788,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [7] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [8] = { -- NOTE: Missing abilities
        Id = "5714",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "loro" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "loro" .. IMPF,
        Name = IJ_DB_DUNGEON_ST_BOSS_NAME_5714,
        Story = IJ_DB_DUNGEON_ST_BOSS_STORY_5714,
        MapCoordinateX = 45.0,
        MapCoordinateY = 32.2,
        Loot = {
            [1] = {
                Id = "10783",
                Icon = "inv_shoulder_18",
                Name = IJ_LOOT_NAME_10783,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [2] = {
                Id = "10784",
                Icon = "inv_chest_chain_05",
                Name = IJ_LOOT_NAME_10784,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [3] = {
                Id = "10785",
                Icon = "inv_pants_07",
                Name = IJ_LOOT_NAME_10785,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [4] = {
                Id = "10786",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_10786,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [5] = {
                Id = "10787",
                Icon = "inv_bracer_18",
                Name = IJ_LOOT_NAME_10787,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [6] = {
                Id = "10788",
                Icon = "inv_belt_15",
                Name = IJ_LOOT_NAME_10788,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 47,
            },
            [7] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [9] = { -- NOTE: Missing abilities
        Id = "5710",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "jammalan" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "jammalan" .. IMPF,
        Name = IJ_DB_DUNGEON_ST_BOSS_NAME_5710,
        Story = IJ_DB_DUNGEON_ST_BOSS_STORY_5710,
        MapCoordinateX = 76.0,
        MapCoordinateY = 45.5,
        Loot = {
            [1] = {
                Id = "10806",
                Icon = "inv_chest_cloth_38",
                Name = IJ_LOOT_NAME_10806,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 50,
            },
            [2] = {
                Id = "10807",
                Icon = "inv_pants_11",
                Name = IJ_LOOT_NAME_10807,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 50,
            },
            [3] = {
                Id = "10808",
                Icon = "inv_gauntlets_17",
                Name = IJ_LOOT_NAME_10808,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 50,
            },
            [4] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [5] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [6] = {
                Id = "10803",
                Icon = "inv_sword_38",
                Name = IJ_LOOT_NAME_10803,
                Quality = IQ.Uncommon,
                ItemSlot = IS.MainHand,
                ItemType = IT.Sword,
                DropChance = 33,
                LevelRequirement = 49,
            },
            [7] = {
                Id = "10804",
                Icon = "inv_hammer_11",
                Name = IJ_LOOT_NAME_10804,
                Quality = IQ.Uncommon,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 33,
                LevelRequirement = 49,
            },
            [8] = {
                Id = "10805",
                Icon = "inv_axe_07",
                Name = IJ_LOOT_NAME_10805,
                Quality = IQ.Uncommon,
                ItemSlot = IS.MainHand,
                ItemType = IT.Axe,
                DropChance = 33,
                LevelRequirement = 49,
            },
        }
    },
    [10] = { -- NOTE: Missing abilities
        Id = "5721",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "dreamscythe" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "dreamscythe" .. IMPF,
        Name = IJ_DB_DUNGEON_ST_BOSS_NAME_5721,
        Story = IJ_DB_DUNGEON_ST_BOSS_STORY_5721,
        MapCoordinateX = 43.2,
        MapCoordinateY = 39.7,
        Loot = {
            [1] = {
                Id = "10795",
                Icon = "inv_jewelry_ring_04",
                Name = IJ_LOOT_NAME_10795,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 5,
                LevelRequirement = 49,
            },
            [2] = {
                Id = "10796",
                Icon = "inv_misc_orb_03",
                Name = IJ_LOOT_NAME_10796,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 5,
                LevelRequirement = 49,
            },
            [3] = {
                Id = "10797",
                Icon = "inv_sword_09",
                Name = IJ_LOOT_NAME_10797,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [4] = {
                Id = "12243",
                Icon = "inv_weapon_halberd_04",
                Name = IJ_LOOT_NAME_12243,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 5,
                LevelRequirement = 49,
            },
            [5] = {
                Id = "12463",
                Icon = "inv_sword_19",
                Name = IJ_LOOT_NAME_12463,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [6] = {
                Id = "12464",
                Icon = "inv_gauntlets_19",
                Name = IJ_LOOT_NAME_12464,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [7] = {
                Id = "12465",
                Icon = "inv_misc_cape_05",
                Name = IJ_LOOT_NAME_12465,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [8] = {
                Id = "12466",
                Icon = "inv_belt_11",
                Name = IJ_LOOT_NAME_12466,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [9] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [10] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [11] = { -- NOTE: Missing abilities
        Id = "5720",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "weaver" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "weaver" .. IMPF,
        Name = IJ_DB_DUNGEON_ST_BOSS_NAME_5720,
        Story = IJ_DB_DUNGEON_ST_BOSS_STORY_5720,
        MapCoordinateX = 56.0,
        MapCoordinateY = 51.4,
        Loot = {
            [1] = {
                Id = "10795",
                Icon = "inv_jewelry_ring_04",
                Name = IJ_LOOT_NAME_10795,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 5,
                LevelRequirement = 49,
            },
            [2] = {
                Id = "10796",
                Icon = "inv_misc_orb_03",
                Name = IJ_LOOT_NAME_10796,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 5,
                LevelRequirement = 49,
            },
            [3] = {
                Id = "10797",
                Icon = "inv_sword_09",
                Name = IJ_LOOT_NAME_10797,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [4] = {
                Id = "12243",
                Icon = "inv_weapon_halberd_04",
                Name = IJ_LOOT_NAME_12243,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 5,
                LevelRequirement = 49,
            },
            [5] = {
                Id = "12463",
                Icon = "inv_sword_19",
                Name = IJ_LOOT_NAME_12463,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [6] = {
                Id = "12464",
                Icon = "inv_gauntlets_19",
                Name = IJ_LOOT_NAME_12464,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [7] = {
                Id = "12465",
                Icon = "inv_misc_cape_05",
                Name = IJ_LOOT_NAME_12465,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [8] = {
                Id = "12466",
                Icon = "inv_belt_11",
                Name = IJ_LOOT_NAME_12466,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [9] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [10] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [12] = { -- NOTE: Missing abilities
        Id = "5719",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "morphaz" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "morphaz" .. IMPF,
        Name = IJ_DB_DUNGEON_ST_BOSS_NAME_5719,
        Story = IJ_DB_DUNGEON_ST_BOSS_STORY_5719,
        MapCoordinateX = 49.9,
        MapCoordinateY = 86.8,
        Loot = {
            [1] = {
                Id = "10795",
                Icon = "inv_jewelry_ring_04",
                Name = IJ_LOOT_NAME_10795,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 5,
                LevelRequirement = 49,
            },
            [2] = {
                Id = "10796",
                Icon = "inv_misc_orb_03",
                Name = IJ_LOOT_NAME_10796,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 5,
                LevelRequirement = 49,
            },
            [3] = {
                Id = "10797",
                Icon = "inv_sword_09",
                Name = IJ_LOOT_NAME_10797,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [4] = {
                Id = "12243",
                Icon = "inv_weapon_halberd_04",
                Name = IJ_LOOT_NAME_12243,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 5,
                LevelRequirement = 49,
            },
            [5] = {
                Id = "12463",
                Icon = "inv_sword_19",
                Name = IJ_LOOT_NAME_12463,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [6] = {
                Id = "12464",
                Icon = "inv_gauntlets_19",
                Name = IJ_LOOT_NAME_12464,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [7] = {
                Id = "12465",
                Icon = "inv_misc_cape_05",
                Name = IJ_LOOT_NAME_12465,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [8] = {
                Id = "12466",
                Icon = "inv_belt_11",
                Name = IJ_LOOT_NAME_12466,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [9] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [10] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [13] = { -- NOTE: Missing abilities
        Id = "5722",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "hazzas" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "hazzas" .. IMPF,
        Name = IJ_DB_DUNGEON_ST_BOSS_NAME_5722,
        Story = IJ_DB_DUNGEON_ST_BOSS_STORY_5722,
        MapCoordinateX = 44.0,
        MapCoordinateY = 86.8,
        Loot = {
            [1] = {
                Id = "10795",
                Icon = "inv_jewelry_ring_04",
                Name = IJ_LOOT_NAME_10795,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 5,
                LevelRequirement = 49,
            },
            [2] = {
                Id = "10796",
                Icon = "inv_misc_orb_03",
                Name = IJ_LOOT_NAME_10796,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 5,
                LevelRequirement = 49,
            },
            [3] = {
                Id = "10797",
                Icon = "inv_sword_09",
                Name = IJ_LOOT_NAME_10797,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [4] = {
                Id = "12243",
                Icon = "inv_weapon_halberd_04",
                Name = IJ_LOOT_NAME_12243,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 5,
                LevelRequirement = 49,
            },
            [5] = {
                Id = "12463",
                Icon = "inv_sword_19",
                Name = IJ_LOOT_NAME_12463,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [6] = {
                Id = "12464",
                Icon = "inv_gauntlets_19",
                Name = IJ_LOOT_NAME_12464,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [7] = {
                Id = "12465",
                Icon = "inv_misc_cape_05",
                Name = IJ_LOOT_NAME_12465,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [8] = {
                Id = "12466",
                Icon = "inv_belt_11",
                Name = IJ_LOOT_NAME_12466,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 5,
                LevelRequirement = 48,
            },
            [9] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [10] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [14] = { -- NOTE: Missing abilities
        Id = "5709",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "eranikus" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "eranikus" .. IMPF,
        Name = IJ_DB_DUNGEON_ST_BOSS_NAME_5709,
        Story = IJ_DB_DUNGEON_ST_BOSS_STORY_5709,
        MapCoordinateX = 66.5,
        MapCoordinateY = 87.7,
        Loot = {
            [1] = {
                Id = "10454",
                Icon = "inv_stone_03",
                Name = IJ_LOOT_NAME_10454,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Quest,
                DropChance = 100,
                LevelRequirement = 48,
            },
            [2] = {
                Id = "10828",
                Icon = "inv_weapon_shortblade_16",
                Name = IJ_LOOT_NAME_10828,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 17,
                LevelRequirement = 51,
            },
            [3] = {
                Id = "10829",
                Icon = "inv_jewelry_amulet_04",
                Name = IJ_LOOT_NAME_10829,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 17,
                LevelRequirement = 51,
            },
            [4] = {
                Id = "10833",
                Icon = "inv_helmet_25",
                Name = IJ_LOOT_NAME_10833,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Mail,
                DropChance = 17,
                LevelRequirement = 51,
            },
            [5] = {
                Id = "10835",
                Icon = "inv_shield_04",
                Name = IJ_LOOT_NAME_10835,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 17,
                LevelRequirement = 51,
            },
            [6] = {
                Id = "10836",
                Icon = "inv_wand_04",
                Name = IJ_LOOT_NAME_10836,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 17,
                LevelRequirement = 51,
            },
            [7] = {
                Id = "10837",
                Icon = "inv_axe_07",
                Name = IJ_LOOT_NAME_10837,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Axe,
                DropChance = 17,
                LevelRequirement = 51,
            },
            [8] = {
                Id = "10847",
                Icon = "inv_sword_38",
                Name = IJ_LOOT_NAME_10847,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 1,
                LevelRequirement = 52,
            },
            [9] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 3,
            },
        }
    },
    [15] = { -- NOTE: Missing abilities
        Id = "8443",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "avatar" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "avatar" .. IMPF,
        Name = IJ_DB_DUNGEON_ST_BOSS_NAME_8443,
        Story = IJ_DB_DUNGEON_ST_BOSS_STORY_8443,
        MapCoordinateX = 24.2,
        MapCoordinateY = 45.5,
        Loot = {
            [1] = {
                Id = "10838",
                Icon = "inv_mace_06",
                Name = IJ_LOOT_NAME_10838,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 17,
                LevelRequirement = 49,
            },
            [2] = {
                Id = "10842",
                Icon = "inv_pants_14",
                Name = IJ_LOOT_NAME_10842,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 49,
            },
            [3] = {
                Id = "10843",
                Icon = "inv_misc_cape_05",
                Name = IJ_LOOT_NAME_10843,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 49,
            },
            [4] = {
                Id = "10844",
                Icon = "inv_staff_32",
                Name = IJ_LOOT_NAME_10844,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 17,
                LevelRequirement = 49,
            },
            [5] = {
                Id = "10845",
                Icon = "inv_chest_plate08",
                Name = IJ_LOOT_NAME_10845,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 49,
            },
            [6] = {
                Id = "10846",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_10846,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 17,
                LevelRequirement = 49,
            },
            [7] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [8] = {
                Id = "12462",
                Icon = "inv_chest_cloth_42",
                Name = IJ_LOOT_NAME_12462,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 2,
                LevelRequirement = 50,
            },
            [9] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
}

IJDB.DG.ST = ST
