IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "strat\\"

local STRAT = {}

STRAT.Name = IJ_DB_DUNGEON_STRAT_NAME
STRAT.Story = IJ_DB_DUNGEON_STRAT_STORY
STRAT.Type = IJLib.InstanceType.Dungeon
STRAT.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
STRAT.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
STRAT.MapId = IMI.Stratholme
STRAT.IconScale = 0.7
STRAT.MinLevel = 58
STRAT.MaxLevel = 60
STRAT.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.EasternPlaguelands,
        MapCoordinateX = 30.8,
        MapCoordinateY = 14.8,
    },
    [2] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.EasternPlaguelands,
        MapCoordinateX = 47.7,
        MapCoordinateY = 23.4,
    },
}
STRAT.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "10393",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "skul" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "skul" .. IMPF,
        Name = IJ_DB_DUNGEON_STRAT_BOSS_NAME_10393,
        Story = IJ_DB_DUNGEON_STRAT_BOSS_STORY_10393,
        MapCoordinateX = 56.4,
        MapCoordinateY = 84.9,
        IsRare = true,
        Loot = {
            [1] = {
                Id = "13395",
                Icon = "inv_gauntlets_27",
                Name = IJ_LOOT_NAME_13395,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 33,
                LevelRequirement = 54,
            },
            [2] = {
                Id = "13394",
                Icon = "inv_chest_chain_15",
                Name = IJ_LOOT_NAME_13394,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 33,
                LevelRequirement = 54,
            },
            [3] = {
                Id = "13396",
                Icon = "inv_misc_bone_elfskull_01",
                Name = IJ_LOOT_NAME_13396,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 33,
                LevelRequirement = 52,
            },
            [4] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [2] = { -- NOTE: Missing abilities
        Id = "10558",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "hearthsinger" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "hearthsinger" .. IMPF,
        Name = IJ_DB_DUNGEON_STRAT_BOSS_NAME_10558,
        Story = IJ_DB_DUNGEON_STRAT_BOSS_STORY_10558,
        MapCoordinateX = 72.5,
        MapCoordinateY = 66.0,
        IsRare = true,
        Loot = {
            [1] = {
                Id = "13378",
                Icon = "inv_chest_cloth_38",
                Name = IJ_LOOT_NAME_13378,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [2] = {
                Id = "13379",
                Icon = "inv_misc_flute_01",
                Name = IJ_LOOT_NAME_13379,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [3] = {
                Id = "13383",
                Icon = "inv_pants_14",
                Name = IJ_LOOT_NAME_13383,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [4] = {
                Id = "13384",
                Icon = "inv_belt_30",
                Name = IJ_LOOT_NAME_13384,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 53,
            },
            [5] = {
                Id = "16682",
                Icon = "inv_boots_02",
                Name = IJ_LOOT_NAME_16682,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [6] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [3] = { -- NOTE: Missing abilities
        Id = "10516",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "unforgiven" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "unforgiven" .. IMPF,
        Name = IJ_DB_DUNGEON_STRAT_BOSS_NAME_10516,
        Story = IJ_DB_DUNGEON_STRAT_BOSS_STORY_10516,
        MapCoordinateX = 66.6,
        MapCoordinateY = 57.0,
        Loot = {
            [1] = {
                Id = "13404",
                Icon = "inv_misc_bandana_01",
                Name = IJ_LOOT_NAME_13404,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 52,
            },
            [2] = {
                Id = "13405",
                Icon = "inv_shoulder_25",
                Name = IJ_LOOT_NAME_13405,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 52,
            },
            [3] = {
                Id = "13408",
                Icon = "inv_weapon_halberd_05",
                Name = IJ_LOOT_NAME_13408,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Axe,
                DropChance = 20,
                LevelRequirement = 52,
            },
            [4] = {
                Id = "13409",
                Icon = "inv_bracer_13",
                Name = IJ_LOOT_NAME_13409,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 52,
            },
            [5] = {
                Id = "16717",
                Icon = "inv_gauntlets_17",
                Name = IJ_LOOT_NAME_16717,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [6] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [7] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [4] = { -- NOTE: Missing abilities
        Id = "10808",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "timmy" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "timmy" .. IMPF,
        Name = IJ_DB_DUNGEON_STRAT_BOSS_NAME_10808,
        Story = IJ_DB_DUNGEON_STRAT_BOSS_STORY_10808,
        MapCoordinateX = 46.0,
        MapCoordinateY = 67.5,
        Loot = {
            [1] = {
                Id = "13400",
                Icon = "inv_bracer_17",
                Name = IJ_LOOT_NAME_13400,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [2] = {
                Id = "13401",
                Icon = "inv_misc_bone_elfskull_01",
                Name = IJ_LOOT_NAME_13401,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [3] = {
                Id = "13402",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_13402,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [4] = {
                Id = "13403",
                Icon = "inv_belt_02",
                Name = IJ_LOOT_NAME_13403,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [5] = {
                Id = "16724",
                Icon = "inv_gauntlets_19",
                Name = IJ_LOOT_NAME_16724,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [6] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [7] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [5] = { -- NOTE: Missing abilities
        Id = "11032",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "malor" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "malor" .. IMPF,
        Name = IJ_DB_DUNGEON_STRAT_BOSS_NAME_11032,
        Story = IJ_DB_DUNGEON_STRAT_BOSS_STORY_11032,
        MapCoordinateX = 40.9,
        MapCoordinateY = 69.2,
        Loot = {
            [1] = {
                Id = "81016",
                Icon = "inv_jewelry_necklace_15",
                Name = IJ_LOOT_NAME_81016,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [2] = {
                Id = "81017",
                Icon = "inv_belt_13",
                Name = IJ_LOOT_NAME_81017,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [3] = {
                Id = "81018",
                Icon = "inv_sword_07",
                Name = IJ_LOOT_NAME_81018,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Sword,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "81019",
                Icon = "inv_gauntlets_26",
                Name = IJ_LOOT_NAME_81019,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [5] = {
                Id = "81122",
                Icon = "inv_misc_cape_18",
                Name = IJ_LOOT_NAME_81122,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [6] = {
                Id = "81123",
                Icon = "inv_pants_mail_09",
                Name = IJ_LOOT_NAME_81123,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [7] = {
                Id = "81124",
                Icon = "inv_helmet_19",
                Name = IJ_LOOT_NAME_81124,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 57,
            },
            [8] = {
                Id = "81125",
                Icon = "inv_misc_orb_03",
                Name = IJ_LOOT_NAME_81125,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [9] = {
                Id = "81131",
                Icon = "inv_helmet_19",
                Name = IJ_LOOT_NAME_81131,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 57,
            },
            [10] = {
                Id = "83575",
                Icon = "inv_misc_book_09",
                Name = IJ_LOOT_NAME_83575,
                Quality = IQ.Rare,
                ItemSlot = IS.Ability,
                DropChance = 10,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Priest, },
            },
            [11] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [12] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [6] = { -- NOTE: Missing abilities
        Id = "11120",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "hammersmith" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "hammersmith" .. IMPF,
        Name = IJ_DB_DUNGEON_STRAT_BOSS_NAME_11120,
        Story = IJ_DB_DUNGEON_STRAT_BOSS_STORY_11120,
        MapCoordinateX = 29.8,
        MapCoordinateY = 73.5,
        Loot = {
            [1] = {
                Id = "18781",
                Icon = "inv_misc_note_03",
                Name = IJ_LOOT_NAME_18781,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 40,
                LevelRequirement = 50,
            },
            [2] = {
                Id = "124",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_124,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 6,
            },
        }
    },
    [7] = { -- NOTE: Missing abilities
        Id = "10997",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "willey" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "willey" .. IMPF,
        Name = IJ_DB_DUNGEON_STRAT_BOSS_NAME_10997,
        Story = IJ_DB_DUNGEON_STRAT_BOSS_STORY_10997,
        MapCoordinateX = 25.4,
        MapCoordinateY = 75.6,
        Loot = {
            [1] = {
                Id = "13380",
                Icon = "inv_weapon_rifle_07",
                Name = IJ_LOOT_NAME_13380,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Gun,
                DropChance = 10,
                LevelRequirement = 56,
            },
            [2] = {
                Id = "13381",
                Icon = "inv_boots_plate_09",
                Name = IJ_LOOT_NAME_13381,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 10,
                LevelRequirement = 56,
            },
            [3] = {
                Id = "13382",
                Icon = "inv_misc_bomb_04",
                Name = IJ_LOOT_NAME_13382,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 10,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "16708",
                Icon = "inv_shoulder_07",
                Name = IJ_LOOT_NAME_16708,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 10,
                LevelRequirement = 55,
            },
            [5] = {
                Id = "18721",
                Icon = "inv_belt_18",
                Name = IJ_LOOT_NAME_18721,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 10,
                LevelRequirement = 56,
            },
            [6] = {
                Id = "22403",
                Icon = "inv_jewelry_necklace_10",
                Name = IJ_LOOT_NAME_22403,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 10,
                LevelRequirement = 56,
            },
            [7] = {
                Id = "22404",
                Icon = "inv_weapon_shortblade_16",
                Name = IJ_LOOT_NAME_22404,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.FistWeapon,
                DropChance = 10,
                LevelRequirement = 56,
            },
            [8] = {
                Id = "22405",
                Icon = "inv_shoulder_02",
                Name = IJ_LOOT_NAME_22405,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 56,
            },
            [9] = {
                Id = "22406",
                Icon = "inv_staff_23",
                Name = IJ_LOOT_NAME_22406,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 10,
                LevelRequirement = 56,
            },
            [10] = {
                Id = "22407",
                Icon = "inv_helmet_41",
                Name = IJ_LOOT_NAME_22407,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 10,
                LevelRequirement = 56,
            },
            [11] = {
                Id = "12839",
                Icon = "inv_scroll_03",
                Name = IJ_LOOT_NAME_12839,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 6,
            },
            [12] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [13] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [8] = { -- NOTE: Missing abilities
        Id = "10811",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "galford" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "galford" .. IMPF,
        Name = IJ_DB_DUNGEON_STRAT_BOSS_NAME_10811,
        Story = IJ_DB_DUNGEON_STRAT_BOSS_STORY_10811,
        MapCoordinateX = 38.2,
        MapCoordinateY = 89.2,
        Loot = {
            [1] = {
                Id = "13385",
                Icon = "inv_misc_book_05",
                Name = IJ_LOOT_NAME_13385,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [2] = {
                Id = "13386",
                Icon = "inv_misc_cape_19",
                Name = IJ_LOOT_NAME_13386,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [3] = {
                Id = "13387",
                Icon = "inv_belt_21",
                Name = IJ_LOOT_NAME_13387,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "16692",
                Icon = "inv_gauntlets_14",
                Name = IJ_LOOT_NAME_16692,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [5] = {
                Id = "18716",
                Icon = "inv_boots_08",
                Name = IJ_LOOT_NAME_18716,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [6] = {
                Id = "22897",
                Icon = "inv_misc_book_07",
                Name = IJ_LOOT_NAME_22897,
                Quality = IQ.Rare,
                ItemSlot = IS.Ability,
                DropChance = 14,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, },
            },
            [7] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [8] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
        }
    },
    [9] = { -- NOTE: Missing abilities
        Id = "10812",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "dathrohan" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "dathrohan" .. IMPF,
        Name = IJ_DB_DUNGEON_STRAT_BOSS_NAME_10812,
        Story = IJ_DB_DUNGEON_STRAT_BOSS_STORY_10812,
        MapCoordinateX = 35.1,
        MapCoordinateY = 93.4,
        Loot = {
            [1] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [2] = {
                Id = "83501",
                Icon = "inv_scroll_04",
                Name = IJ_LOOT_NAME_83501,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 17,
            },
            [3] = {
                Id = "83502",
                Icon = "inv_scroll_04",
                Name = IJ_LOOT_NAME_83502,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 17,
            },
            [4] = {
                Id = "83504",
                Icon = "inv_scroll_04",
                Name = IJ_LOOT_NAME_83504,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 17,
            },
            [5] = {
                Id = "83505",
                Icon = "inv_scroll_04",
                Name = IJ_LOOT_NAME_83505,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 17,
            },
            [6] = {
                Id = "83503",
                Icon = "inv_scroll_04",
                Name = IJ_LOOT_NAME_83503,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 17,
            },
            [7] = {
                Id = "83506",
                Icon = "inv_scroll_04",
                Name = IJ_LOOT_NAME_83506,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 17,
            },
            [8] = {
                Id = "12103",
                Icon = "inv_jewelry_talisman_08",
                Name = IJ_LOOT_NAME_12103,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [9] = {
                Id = "13348",
                Icon = "inv_sword_14",
                Name = IJ_LOOT_NAME_13348,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [10] = {
                Id = "13358",
                Icon = "inv_shoulder_24",
                Name = IJ_LOOT_NAME_13358,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [11] = {
                Id = "13359",
                Icon = "inv_helmet_03",
                Name = IJ_LOOT_NAME_13359,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Mail,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [12] = {
                Id = "13360",
                Icon = "inv_weapon_shortblade_15",
                Name = IJ_LOOT_NAME_13360,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [13] = {
                Id = "13369",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_13369,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [14] = {
                Id = "16725",
                Icon = "inv_boots_plate_03",
                Name = IJ_LOOT_NAME_16725,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 10,
                LevelRequirement = 54,
            },
            [15] = {
                Id = "18717",
                Icon = "inv_hammer_06",
                Name = IJ_LOOT_NAME_18717,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [16] = {
                Id = "18718",
                Icon = "inv_helmet_10",
                Name = IJ_LOOT_NAME_18718,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [17] = {
                Id = "18720",
                Icon = "inv_shoulder_23",
                Name = IJ_LOOT_NAME_18720,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [18] = {
                Id = "47413",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_47413,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [19] = {
                Id = "47415",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_47415,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [20] = {
                Id = "14512",
                Icon = "inv_scroll_03",
                Name = IJ_LOOT_NAME_14512,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Tailoring,
                DropChance = 6,
            },
            [21] = {
                Id = "83500",
                Icon = "inv_scroll_05",
                Name = IJ_LOOT_NAME_83500,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 5,
            },
            [22] = {
                Id = "13520",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_13520,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 3,
            },
            [23] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 3,
            },
            [24] = {
                Id = "13353",
                Icon = "inv_misc_book_06",
                Name = IJ_LOOT_NAME_13353,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 2,
                LevelRequirement = 58,
            },
        }
    },
    [10] = { -- NOTE: Missing abilities
        Id = "10435",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "barthilas" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "barthilas" .. IMPF,
        Name = IJ_DB_DUNGEON_STRAT_BOSS_NAME_10435,
        Story = IJ_DB_DUNGEON_STRAT_BOSS_STORY_10435,
        MapCoordinateX = 81.6,
        MapCoordinateY = 62.5,
        Loot = {
            [1] = {
                Id = "12382",
                Icon = "inv_misc_key_13",
                Name = IJ_LOOT_NAME_12382,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Key,
                DropChance = 100,
            },
            [2] = {
                Id = "13376",
                Icon = "inv_misc_cape_14",
                Name = IJ_LOOT_NAME_13376,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 54,
            },
            [3] = {
                Id = "18722",
                Icon = "inv_gauntlets_13",
                Name = IJ_LOOT_NAME_18722,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 57,
            },
            [4] = {
                Id = "18725",
                Icon = "inv_spear_07",
                Name = IJ_LOOT_NAME_18725,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 17,
                LevelRequirement = 54,
            },
            [5] = {
                Id = "18726",
                Icon = "inv_bracer_11",
                Name = IJ_LOOT_NAME_18726,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 54,
            },
            [6] = {
                Id = "18727",
                Icon = "inv_helmet_51",
                Name = IJ_LOOT_NAME_18727,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 54,
            },
            [7] = {
                Id = "23198",
                Icon = "inv_relics_idolofferocity",
                Name = IJ_LOOT_NAME_23198,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Idol,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [9] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [11] = { -- NOTE: Missing abilities
        Id = "10809",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "stonespine" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "stonespine" .. IMPF,
        Name = IJ_DB_DUNGEON_STRAT_BOSS_NAME_10809,
        Story = IJ_DB_DUNGEON_STRAT_BOSS_STORY_10809,
        MapCoordinateX = 83.5,
        MapCoordinateY = 43.0,
        IsRare = true,
        Loot = {
            [1] = {
                Id = "13397",
                Icon = "inv_misc_cape_19",
                Name = IJ_LOOT_NAME_13397,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 56,
            },
            [2] = {
                Id = "13399",
                Icon = "inv_gauntlets_11",
                Name = IJ_LOOT_NAME_13399,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.FistWeapon,
                DropChance = 33,
                LevelRequirement = 54,
            },
            [3] = {
                Id = "13954",
                Icon = "inv_boots_08",
                Name = IJ_LOOT_NAME_13954,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 33,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [12] = { -- NOTE: Missing abilities
        Id = "10437",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "nerubenkan" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "nerubenkan" .. IMPF,
        Name = IJ_DB_DUNGEON_STRAT_BOSS_NAME_10437,
        Story = IJ_DB_DUNGEON_STRAT_BOSS_STORY_10437,
        MapCoordinateX = 75.7,
        MapCoordinateY = 38.2,
        Loot = {
            [1] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [2] = {
                Id = "13530",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_13530,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [3] = {
                Id = "13531",
                Icon = "inv_pants_09",
                Name = IJ_LOOT_NAME_13531,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "13532",
                Icon = "inv_gauntlets_31",
                Name = IJ_LOOT_NAME_13532,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [5] = {
                Id = "13533",
                Icon = "inv_shoulder_18",
                Name = IJ_LOOT_NAME_13533,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [6] = {
                Id = "13529",
                Icon = "inv_shield_02",
                Name = IJ_LOOT_NAME_13529,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [7] = {
                Id = "16675",
                Icon = "inv_boots_plate_07",
                Name = IJ_LOOT_NAME_16675,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [8] = {
                Id = "18738",
                Icon = "inv_weapon_crossbow_04",
                Name = IJ_LOOT_NAME_18738,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Crossbow,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [9] = {
                Id = "18739",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_18739,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [10] = {
                Id = "18740",
                Icon = "inv_belt_13",
                Name = IJ_LOOT_NAME_18740,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [11] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [13] = { -- NOTE: Missing abilities
        Id = "10436",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "anastari" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "anastari" .. IMPF,
        Name = IJ_DB_DUNGEON_STRAT_BOSS_NAME_10436,
        Story = IJ_DB_DUNGEON_STRAT_BOSS_STORY_10436,
        MapCoordinateX = 90.2,
        MapCoordinateY = 39.0,
        Loot = {
                        [1] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
            [2] = {
                Id = "13535",
                Icon = "inv_chest_cloth_47",
                Name = IJ_LOOT_NAME_13535,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [3] = {
                Id = "13537",
                Icon = "inv_bracer_07",
                Name = IJ_LOOT_NAME_13537,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [4] = {
                Id = "13538",
                Icon = "inv_shoulder_13",
                Name = IJ_LOOT_NAME_13538,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [5] = {
                Id = "13539",
                Icon = "inv_gauntlets_29",
                Name = IJ_LOOT_NAME_13539,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [6] = {
                Id = "13534",
                Icon = "inv_weapon_shortblade_18",
                Name = IJ_LOOT_NAME_13534,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [7] = {
                Id = "16704",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_16704,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [8] = {
                Id = "18728",
                Icon = "inv_jewelry_necklace_11",
                Name = IJ_LOOT_NAME_18728,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [9] = {
                Id = "18729",
                Icon = "inv_weapon_bow_12",
                Name = IJ_LOOT_NAME_18729,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [10] = {
                Id = "18730",
                Icon = "inv_gauntlets_16",
                Name = IJ_LOOT_NAME_18730,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [11] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
        }
    },
    [14] = { -- NOTE: Missing abilities
        Id = "10438",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "maleki" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "maleki" .. IMPF,
        Name = IJ_DB_DUNGEON_STRAT_BOSS_NAME_10438,
        Story = IJ_DB_DUNGEON_STRAT_BOSS_STORY_10438,
        MapCoordinateX = 84.4,
        MapCoordinateY = 17.4,
        Loot = {
            [1] = {
                Id = "13525",
                Icon = "inv_gauntlets_15",
                Name = IJ_LOOT_NAME_13525,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 57,
            },
            [2] = {
                Id = "13526",
                Icon = "inv_belt_09",
                Name = IJ_LOOT_NAME_13526,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 57,
            },
            [3] = {
                Id = "13527",
                Icon = "inv_boots_plate_09",
                Name = IJ_LOOT_NAME_13527,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 57,
            },
            [4] = {
                Id = "13528",
                Icon = "inv_bracer_16",
                Name = IJ_LOOT_NAME_13528,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Wrist,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 57,
            },
            [5] = {
                Id = "13524",
                Icon = "inv_misc_bone_humanskull_01",
                Name = IJ_LOOT_NAME_13524,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 20,
                LevelRequirement = 57,
            },
            [6] = {
                Id = "16691",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_16691,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [7] = {
                Id = "18734",
                Icon = "inv_misc_cape_11",
                Name = IJ_LOOT_NAME_18734,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 57,
            },
            [8] = {
                Id = "18735",
                Icon = "inv_boots_03",
                Name = IJ_LOOT_NAME_18735,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 57,
            },
            [9] = {
                Id = "18737",
                Icon = "inv_axe_11",
                Name = IJ_LOOT_NAME_18737,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Axe,
                DropChance = 20,
                LevelRequirement = 57,
            },
            [10] = {
                Id = "12833",
                Icon = "inv_scroll_03",
                Name = IJ_LOOT_NAME_12833,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 6,
            },
            [11] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [12] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [15] = { -- NOTE: Missing abilities
        Id = "10439",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "ramstein" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "ramstein" .. IMPF,
        Name = IJ_DB_DUNGEON_STRAT_BOSS_NAME_10439,
        Story = IJ_DB_DUNGEON_STRAT_BOSS_STORY_10439,
        MapCoordinateX = 65.5,
        MapCoordinateY = 16.2,
        Loot = {
            [1] = {
                Id = "13372",
                Icon = "inv_staff_08",
                Name = IJ_LOOT_NAME_13372,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 14,
                LevelRequirement = 55,
            },
            [2] = {
                Id = "13373",
                Icon = "inv_misc_bone_04",
                Name = IJ_LOOT_NAME_13373,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 14,
                LevelRequirement = 55,
            },
            [3] = {
                Id = "13374",
                Icon = "inv_shoulder_02",
                Name = IJ_LOOT_NAME_13374,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 55,
            },
            [4] = {
                Id = "13375",
                Icon = "inv_shield_19",
                Name = IJ_LOOT_NAME_13375,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 14,
                LevelRequirement = 55,
            },
            [5] = {
                Id = "13515",
                Icon = "inv_misc_gear_06",
                Name = IJ_LOOT_NAME_13515,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 14,
                LevelRequirement = 55,
            },
            [6] = {
                Id = "16737",
                Icon = "inv_gauntlets_26",
                Name = IJ_LOOT_NAME_16737,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 54,
            },
            [7] = {
                Id = "18723",
                Icon = "inv_jewelry_necklace_01",
                Name = IJ_LOOT_NAME_18723,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [8] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [9] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [16] = { -- NOTE: Missing abilities
        Id = "10440",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "rivendare" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "rivendare" .. IMPF,
        Name = IJ_DB_DUNGEON_STRAT_BOSS_NAME_10440,
        Story = IJ_DB_DUNGEON_STRAT_BOSS_STORY_10440,
        MapCoordinateX = 60.2,
        MapCoordinateY = 16.6,
        Loot = {
            [1] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [2] = {
                Id = "22408",
                Icon = "inv_wand_07",
                Name = IJ_LOOT_NAME_22408,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 20,
                LevelRequirement = 58,
            },
            [3] = {
                Id = "22409",
                Icon = "inv_chest_leather_08",
                Name = IJ_LOOT_NAME_22409,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 58,
            },
            [4] = {
                Id = "22410",
                Icon = "inv_gauntlets_11",
                Name = IJ_LOOT_NAME_22410,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 58,
            },
            [5] = {
                Id = "22411",
                Icon = "inv_helmet_01",
                Name = IJ_LOOT_NAME_22411,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 58,
            },
            [6] = {
                Id = "22412",
                Icon = "inv_shoulder_02",
                Name = IJ_LOOT_NAME_22412,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 58,
            },
            [7] = {
                Id = "13340",
                Icon = "inv_misc_cape_20",
                Name = IJ_LOOT_NAME_13340,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 58,
            },
            [8] = {
                Id = "13344",
                Icon = "inv_gauntlets_31",
                Name = IJ_LOOT_NAME_13344,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 58,
            },
            [9] = {
                Id = "13345",
                Icon = "inv_jewelry_ring_16",
                Name = IJ_LOOT_NAME_13345,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 14,
                LevelRequirement = 58,
            },
            [10] = {
                Id = "13346",
                Icon = "inv_chest_cloth_08",
                Name = IJ_LOOT_NAME_13346,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 58,
            },
            [11] = {
                Id = "13349",
                Icon = "inv_mace_07",
                Name = IJ_LOOT_NAME_13349,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 14,
                LevelRequirement = 58,
            },
            [12] = {
                Id = "13361",
                Icon = "inv_sword_12",
                Name = IJ_LOOT_NAME_13361,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 14,
                LevelRequirement = 58,
            },
            [13] = {
                Id = "13368",
                Icon = "inv_weapon_shortblade_12",
                Name = IJ_LOOT_NAME_13368,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [14] = {
                Id = "16668",
                Icon = "inv_pants_03",
                Name = IJ_LOOT_NAME_16668,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [15] = {
                Id = "16678",
                Icon = "inv_pants_03",
                Name = IJ_LOOT_NAME_16678,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [16] = {
                Id = "16687",
                Icon = "inv_pants_06",
                Name = IJ_LOOT_NAME_16687,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [17] = {
                Id = "16694",
                Icon = "inv_pants_08",
                Name = IJ_LOOT_NAME_16694,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [18] = {
                Id = "16699",
                Icon = "inv_pants_08",
                Name = IJ_LOOT_NAME_16699,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [19] = {
                Id = "16709",
                Icon = "inv_pants_02",
                Name = IJ_LOOT_NAME_16709,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [20] = {
                Id = "16719",
                Icon = "inv_pants_08",
                Name = IJ_LOOT_NAME_16719,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [21] = {
                Id = "16732",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_16732,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [22] = {
                Id = "16728",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_16728,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 56,
            },
            [23] = {
                Id = "47413",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_47413,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [24] = {
                Id = "47415",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_47415,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [25] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 3,
            },
            [26] = {
                Id = "13505",
                Icon = "inv_sword_17",
                Name = IJ_LOOT_NAME_13505,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 1,
                LevelRequirement = 58,
            },
            [27] = {
                Id = "13335",
                Icon = "ability_mount_undeadhorse",
                Name = IJ_LOOT_NAME_13335,
                Quality = IQ.Epic,
                ItemSlot = IS.Mount,
                DropChance = 1,
                LevelRequirement = 60,
            },
        }
    },
}

IJDB.DG.STRAT = STRAT
