IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "sv\\"

local SV = {}

SV.Name = IJ_DB_DUNGEON_SV_NAME
SV.Story = IJ_DB_DUNGEON_SV_STORY
SV.Type = IJLib.InstanceType.Dungeon
SV.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
SV.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
SV.MapId = IMI.StormwindVault
SV.IconScale = 1.0
SV.MinLevel = 60
SV.MaxLevel = 60
SV.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.StormwindCity,
        MapCoordinateX = 62.8,
        MapCoordinateY = 58.6,
    },
    [2] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.ElwynnForest,
        MapCoordinateX = 29.4,
        MapCoordinateY = 61.8,
    },
}
SV.Bosses = {
    [1] = {
        Id = "80853",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "aszosh" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "aszosh" .. IMPF,
        Name = IJ_DB_DUNGEON_SV_BOSS_NAME_80853,
        Story = IJ_DB_DUNGEON_SV_BOSS_STORY_80853,
        MapCoordinateX = 37.7,
        MapCoordinateY = 38.5,
        Abilities = {
            [1] = {
                Id = "10212",
                Icon = "Spell_Nature_StarFall",
                Name = IJ_DB_DUNGEON_SV_BOSS_80853_ABILITY_NAME_10212,
                Effect = IJ_DB_DUNGEON_SV_BOSS_80853_ABILITY_EFFECT_10212,
            },
            [2] = {
                Id = "18702",
                Icon = "Spell_Shadow_AntiShadow",
                Name = IJ_DB_DUNGEON_SV_BOSS_80853_ABILITY_NAME_18702,
                Effect = IJ_DB_DUNGEON_SV_BOSS_80853_ABILITY_EFFECT_18702,
                Flags = { IMAF.Curse, },
            },
        },
        Loot = {
            [1] = {
                Id = "60504",
                Icon = "INV_Gauntlets_18",
                Name = IJ_LOOT_NAME_60504,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "60418",
                Icon = "INV_Staff_14",
                Name = IJ_LOOT_NAME_60418,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "60419",
                Icon = "INV_misc_bone_taurenskull_01",
                Name = IJ_LOOT_NAME_60419,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "60425",
                Icon = "INV_Chest_Cloth_48",
                Name = IJ_LOOT_NAME_60425,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "60431",
                Icon = "INV_Misc_Book_06",
                Name = IJ_LOOT_NAME_60431,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "60434",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_60434,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "51217",
                Icon = "INV_Misc_Ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [8] = {
                Id = "70226",
                Icon = "INV_Misc_Bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
            },
        },
    },
    [2] = {
        Id = "80852",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "tham" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "tham" .. IMPF,
        Name = IJ_DB_DUNGEON_SV_BOSS_NAME_80852,
        Story = IJ_DB_DUNGEON_SV_BOSS_STORY_80852,
        MapCoordinateX = 68.6,
        MapCoordinateY = 90.1,
        Abilities = { -- NOTE: Something about ice block?
            [1] = {
                Id = "5246",
                Icon = "Ability_GolemThunderClap",
                Name = IJ_DB_DUNGEON_SV_BOSS_80852_ABILITY_NAME_5246,
                Effect = IJ_DB_DUNGEON_SV_BOSS_80852_ABILITY_EFFECT_5246,
                Flags = { IMAF.Important, },
            },
            [2] = {
                Id = "22859",
                Icon = "Ability_Warrior_SavageBlow",
                Name = IJ_DB_DUNGEON_SV_BOSS_80852_ABILITY_NAME_22859,
                Effect = IJ_DB_DUNGEON_SV_BOSS_80852_ABILITY_EFFECT_22859,
                Flags = { IMAF.Heal, },
            },
            [3] = {
                Id = "22857",
                Icon = "Ability_Warrior_Challange",
                Name = IJ_DB_DUNGEON_SV_BOSS_80852_ABILITY_NAME_22857,
                Effect = IJ_DB_DUNGEON_SV_BOSS_80852_ABILITY_EFFECT_22857,
                Flags = { IMAF.DPS, IMAF.Important, },
            },
        },
        Loot = {
            [1] = {
                Id = "60502",
                Icon = "INV_Belt_26",
                Name = IJ_LOOT_NAME_60502,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "60415",
                Icon = "INV_Jewelry_Ring_20",
                Name = IJ_LOOT_NAME_60415,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "60416",
                Icon = "INV_Misc_Bone_ElfSkull_01",
                Name = IJ_LOOT_NAME_60416,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "60417",
                Icon = "INV_Misc_Bone_OrcSkull_01",
                Name = IJ_LOOT_NAME_60417,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "60424",
                Icon = "INV_Gauntlets_05",
                Name = IJ_LOOT_NAME_60424,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "60435",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_60435,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "51217",
                Icon = "INV_Misc_Ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [8] = {
                Id = "70226",
                Icon = "INV_Misc_Bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
            },
        },
    },
    [3] = {
        Id = "80850",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "bride" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "bride" .. IMPF,
        Name = IJ_DB_DUNGEON_SV_BOSS_NAME_80850,
        Story = IJ_DB_DUNGEON_SV_BOSS_STORY_80850,
        MapCoordinateX = 55.9,
        MapCoordinateY = 10.8,
        Abilities = {
            [1] = {
                Id = "16867",
                Icon = "Spell_Nature_Drowsy",
                Name = IJ_DB_DUNGEON_SV_BOSS_80850_ABILITY_NAME_16867,
                Effect = IJ_DB_DUNGEON_SV_BOSS_80850_ABILITY_EFFECT_16867,
                Flags = { IMAF.Curse, },
            },
            [2] = {
                Id = "16565",
                Icon = "Spell_Shadow_ShadowBolt",
                Name = IJ_DB_DUNGEON_SV_BOSS_80850_ABILITY_NAME_16565,
                Effect = IJ_DB_DUNGEON_SV_BOSS_80850_ABILITY_EFFECT_16565,
            },
            [3] = {
                Id = "17244",
                Icon = "Spell_Shadow_Charm",
                Name = IJ_DB_DUNGEON_SV_BOSS_80850_ABILITY_NAME_17244,
                Effect = IJ_DB_DUNGEON_SV_BOSS_80850_ABILITY_EFFECT_17244,
                Flags = { IMAF.Important, },
            },
            [4] = {
                Id = "18327",
                Icon = "Spell_Holy_Silence",
                Name = IJ_DB_DUNGEON_SV_BOSS_80850_ABILITY_NAME_18327,
                Effect = IJ_DB_DUNGEON_SV_BOSS_80850_ABILITY_EFFECT_18327,
                Flags = { IMAF.Magic, },
            },
        },
        Loot = {
            [1] = {
                Id = "60408",
                Icon = "INV_Helmet_11",
                Name = IJ_LOOT_NAME_60408,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "60409",
                Icon = "INV_Misc_Cape_19",
                Name = IJ_LOOT_NAME_60409,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "60410",
                Icon = "INV_Weapon_ShortBlade_16",
                Name = IJ_LOOT_NAME_60410,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.FistWeapon,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "60411",
                Icon = "INV_Boots_Cloth_03",
                Name = IJ_LOOT_NAME_60411,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "60436",
                Icon = "INV_Helmet_41",
                Name = IJ_LOOT_NAME_60436,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 58,
            },
            [6] = {
                Id = "51217",
                Icon = "INV_Misc_Ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [7] = {
                Id = "70226",
                Icon = "INV_Misc_Bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
            },
        },
    },
    [4] = {
        Id = "80851",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "volkan" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "volkan" .. IMPF,
        Name = IJ_DB_DUNGEON_SV_BOSS_NAME_80851,
        Story = IJ_DB_DUNGEON_SV_BOSS_STORY_80851,
        MapCoordinateX = 71.6,
        MapCoordinateY = 43.1,
        MapIsBelow = true,
        Abilities = {
            [1] = {
                Id = "9256",
                Icon = "Spell_Nature_Sleep",
                Name = IJ_DB_DUNGEON_SV_BOSS_80851_ABILITY_NAME_9256,
                Effect = IJ_DB_DUNGEON_SV_BOSS_80851_ABILITY_EFFECT_9256,
                Flags = { IMAF.Important, },
            },
            [2] = {
                Id = "15398",
                Icon = "Spell_Shadow_PsychicScream",
                Name = IJ_DB_DUNGEON_SV_BOSS_880851_ABILITY_NAME_15398,
                Effect = IJ_DB_DUNGEON_SV_BOSS_80851_ABILITY_EFFECT_15398,
                Flags = { IMAF.Important, },
            },
            [3] = {
                Id = "20741",
                Icon = "Spell_Shadow_ShadowBolt",
                Name = IJ_DB_DUNGEON_SV_BOSS_880851_ABILITY_NAME_20741,
                Effect = IJ_DB_DUNGEON_SV_BOSS_80851_ABILITY_EFFECT_20741,
                Flags = { IMAF.Heal, },
            },
            [4] = {
                Id = "20603",
                Icon = "Spell_Shadow_ShadowBolt",
                Name = IJ_DB_DUNGEON_SV_BOSS_880851_ABILITY_NAME_20603,
                Effect = IJ_DB_DUNGEON_SV_BOSS_80851_ABILITY_EFFECT_20603,
                Flags = { IMAF.Heal, },
            },
        },
        Loot = {
            [1] = {
                Id = "60412",
                Icon = "INV_Jewelry_Necklace_09",
                Name = IJ_LOOT_NAME_60412,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "60413",
                Icon = "inv_weapon_halberd_04",
                Name = IJ_LOOT_NAME_60413,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "60414",
                Icon = "INV_Misc_Bandana_03",
                Name = IJ_LOOT_NAME_60414,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "60432",
                Icon = "inv_gauntlets_04",
                Name = IJ_LOOT_NAME_60432,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "60503",
                Icon = "INV_Pants_03",
                Name = IJ_LOOT_NAME_60503,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "51217",
                Icon = "INV_Misc_Ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [7] = {
                Id = "70226",
                Icon = "INV_Misc_Bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
            },
        },
    },
    [5] = {
        Id = "80854",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "damian" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "damian" .. IMPF,
        Name = IJ_DB_DUNGEON_SV_BOSS_NAME_80854,
        Story = IJ_DB_DUNGEON_SV_BOSS_STORY_80854,
        MapCoordinateX = 46.5,
        MapCoordinateY = 43.4,
        Abilities = {
            [1] = {
                Id = "11700",
                Icon = "Spell_Shadow_LifeDrain02",
                Name = IJ_DB_DUNGEON_SV_BOSS_80854_ABILITY_NAME_11700,
                Effect = IJ_DB_DUNGEON_SV_BOSS_80854_ABILITY_EFFECT_11700,
                Flags = { IMAF.Interruptible, },
            },
            [2] = {
                Id = "11668",
                Icon = "Spell_Fire_Immolation",
                Name = IJ_DB_DUNGEON_SV_BOSS_80854_ABILITY_NAME_11668,
                Effect = IJ_DB_DUNGEON_SV_BOSS_80854_ABILITY_EFFECT_11668,
                Flags = { IMAF.Heal, IMAF.Magic, },
            },
            [3] = {
                Id = "1856",
                Icon = "Ability_Vanish",
                Name = IJ_DB_DUNGEON_SV_BOSS_80854_ABILITY_NAME_1856,
                Effect = IJ_DB_DUNGEON_SV_BOSS_80854_ABILITY_EFFECT_1856,
            },
        },
        Loot = {
            [1] = {
                Id = "60421",
                Icon = "INV_Chest_Leather_02",
                Name = IJ_LOOT_NAME_60421,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "60423",
                Icon = "INV_Bracer_07",
                Name = IJ_LOOT_NAME_60423,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "60427",
                Icon = "INV_Misc_Bone_ElfSkull_01",
                Name = IJ_LOOT_NAME_60427,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "60433",
                Icon = "inv_shoulder_27",
                Name = IJ_LOOT_NAME_60433,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "60500",
                Icon = "INV_Misc_Cape_11",
                Name = IJ_LOOT_NAME_60500,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "60422",
                Icon = "INV_Sword_31",
                Name = IJ_LOOT_NAME_60422,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 1,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "51217",
                Icon = "INV_Misc_Ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [8] = {
                Id = "70226",
                Icon = "INV_Misc_Bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 1,
            },
        },
    },
    [6] = { -- NOTE: Database is missing abilities
        Id = "93107",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "arc" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "arc" .. IMPF,
        Name = IJ_DB_DUNGEON_SV_BOSS_NAME_93107,
        Story = IJ_DB_DUNGEON_SV_BOSS_STORY_93107,
        MapCoordinateX = 46.4,
        MapCoordinateY = 79.3,
        Loot = {
            [1] = {
                Id = "40003",
                Icon = "INV_Shield_06",
                Name = IJ_LOOT_NAME_40003,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "60501",
                Icon = "INV_Misc_Crop_01",
                Name = IJ_LOOT_NAME_60501,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "60505",
                Icon = "INV_Jewelry_Ring_27",
                Name = IJ_LOOT_NAME_60505,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "60506",
                Icon = "INV_Weapon_Crossbow_05",
                Name = IJ_LOOT_NAME_60506,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Crossbow,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "60420",
                Icon = "INV_Jewelry_Necklace_16",
                Name = IJ_LOOT_NAME_60420,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "60426",
                Icon = "inv_chest_plate05",
                Name = IJ_LOOT_NAME_60426,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "60429",
                Icon = "INV_Bracer_19",
                Name = IJ_LOOT_NAME_60429,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "60430",
                Icon = "INV_Boots_05",
                Name = IJ_LOOT_NAME_60430,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "51217",
                Icon = "INV_Misc_Ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 80,
            },
            [10] = {
                Id = "83570",
                Icon = "INV_Scroll_02",
                Name = IJ_LOOT_NAME_83570,
                Quality = IQ.Rare,
                ItemSlot = IS.Ability,
                DropChance = 15,
                ClassRestriction = { IMCL.Warrior, },
            },
        },
    },
}

IJDB.DG.SV = SV
