IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "swr\\"

local SWR = {}

SWR.Name = IJ_DB_DUNGEON_SWR_NAME
SWR.Story = IJ_DB_DUNGEON_SWR_STORY
SWR.Type = IJLib.InstanceType.Dungeon
SWR.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
SWR.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
SWR.MapId = IMI.StormwroughtRuins
SWR.IconScale = 0.6
SWR.MinLevel = 32
SWR.MaxLevel = 44
SWR.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.Balor,
        MapCoordinateX = 57.1,
        MapCoordinateY = 60.1,
    },
    [2] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.Balor,
        MapCoordinateX = 56.2,
        MapCoordinateY = 84.9,
    },
}
SWR.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "62548",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "oronok" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "oronok" .. IMPF,
        Name = IJ_DB_DUNGEON_SWR_BOSS_NAME_62548,
        Story = IJ_DB_DUNGEON_SWR_BOSS_STORY_62548,
        MapCoordinateX = 45.1,
        MapCoordinateY = 25.7,
        Loot = {
            [1] = {
                Id = "58135",
                Icon = "inv_weapon_shortblade_15",
                Name = IJ_LOOT_NAME_58135,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 25,
                LevelRequirement = 31,
            },
            [2] = {
                Id = "58136",
                Icon = "inv_chest_cloth_14",
                Name = IJ_LOOT_NAME_58136,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 31,
            },
            [3] = {
                Id = "58137",
                Icon = "inv_staff_17",
                Name = IJ_LOOT_NAME_58137,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 25,
                LevelRequirement = 31,
            },
            [4] = {
                Id = "58177",
                Icon = "inv_chest_cloth_38",
                Name = IJ_LOOT_NAME_58177,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 35,
            },
        }
    },
    [2] = { -- NOTE: Missing abilities
        Id = "62547",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "dagar" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "dagar" .. IMPF,
        Name = IJ_DB_DUNGEON_SWR_BOSS_NAME_62547,
        Story = IJ_DB_DUNGEON_SWR_BOSS_STORY_62547,
        MapCoordinateX = 50.5,
        MapCoordinateY = 27.0,
        Loot = {
            [1] = {
                Id = "58130",
                Icon = "inv_axe_04",
                Name = IJ_LOOT_NAME_58130,
                Quality = IQ.Uncommon,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 25,
                LevelRequirement = 31,
            },
            [2] = {
                Id = "58132",
                Icon = "inv_belt_06",
                Name = IJ_LOOT_NAME_58132,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 31,
            },
            [3] = {
                Id = "58133",
                Icon = "inv_bracer_12",
                Name = IJ_LOOT_NAME_58133,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 31,
            },
            [4] = {
                Id = "58176",
                Icon = "inv_misc_cape_04",
                Name = IJ_LOOT_NAME_58176,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 35,
            },
        }
    },
    [3] = { -- NOTE: Missing abilities
        Id = "62552",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "theodorus" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "theodorus" .. IMPF,
        Name = IJ_DB_DUNGEON_SWR_BOSS_NAME_62552,
        Story = IJ_DB_DUNGEON_SWR_BOSS_STORY_62552,
        MapCoordinateX = 47.4,
        MapCoordinateY = 35.9,
        Loot = {
            [1] = {
                Id = "58138",
                Icon = "inv_misc_book_09",
                Name = IJ_LOOT_NAME_58138,
                Quality = IQ.Uncommon,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 25,
                LevelRequirement = 32,
            },
            [2] = {
                Id = "58139",
                Icon = "inv_misc_book_13",
                Name = IJ_LOOT_NAME_58139,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Libram,
                DropChance = 25,
                LevelRequirement = 32,
            },
            [3] = {
                Id = "58140",
                Icon = "inv_helmet_44",
                Name = IJ_LOOT_NAME_58140,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 32,
            },
            [4] = {
                Id = "58141",
                Icon = "inv_boots_03",
                Name = IJ_LOOT_NAME_58141,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 32,
            },
        }
    },
    [4] = { -- NOTE: Missing abilities
        Id = "62549",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "balor" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "balor" .. IMPF,
        Name = IJ_DB_DUNGEON_SWR_BOSS_NAME_62549,
        Story = IJ_DB_DUNGEON_SWR_BOSS_STORY_62549,
        MapCoordinateX = 50.4,
        MapCoordinateY = 39.5,
        Loot = {
            [1] = {
                Id = "58145",
                Icon = "inv_misc_book_07",
                Name = IJ_LOOT_NAME_58145,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 25,
                LevelRequirement = 33,
            },
            [2] = {
                Id = "58144",
                Icon = "inv_pants_06",
                Name = IJ_LOOT_NAME_58144,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 33,
            },
            [3] = {
                Id = "58143",
                Icon = "inv_shield_04",
                Name = IJ_LOOT_NAME_58143,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 25,
                LevelRequirement = 33,
            },
            [4] = {
                Id = "58142",
                Icon = "inv_chest_cloth_04",
                Name = IJ_LOOT_NAME_58142,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 33,
            },
        }
    },
    [5] = { -- NOTE: Missing abilities
        Id = "62551",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "stormsong" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "stormsong" .. IMPF,
        Name = IJ_DB_DUNGEON_SWR_BOSS_NAME_62551,
        Story = IJ_DB_DUNGEON_SWR_BOSS_STORY_62551,
        MapCoordinateX = 39.5,
        MapCoordinateY = 47.9,
        Loot = {
            [1] = {
                Id = "75",
                Icon = "inv_scroll_03",
                Name = IJ_LOOT_NAME_75,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Tailoring,
                DropChance = 6,
            },
            [2] = {
                Id = "58149",
                Icon = "inv_jewelry_ring_39",
                Name = IJ_LOOT_NAME_58149,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 33,
            },
            [3] = {
                Id = "58148",
                Icon = "inv_boots_01",
                Name = IJ_LOOT_NAME_58148,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 33,
            },
            [4] = {
                Id = "58147",
                Icon = "inv_shoulder_14",
                Name = IJ_LOOT_NAME_58147,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 33,
            },
            [5] = {
                Id = "58146",
                Icon = "inv_qirajidol_life",
                Name = IJ_LOOT_NAME_58146,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Totem,
                DropChance = 25,
                LevelRequirement = 33,
            },
        }
    },
    [6] = { -- NOTE: Missing abilities
        Id = "62550",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "tidebane" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "tidebane" .. IMPF,
        Name = IJ_DB_DUNGEON_SWR_BOSS_NAME_62550,
        Story = IJ_DB_DUNGEON_SWR_BOSS_STORY_62550,
        MapCoordinateX = 32.7,
        MapCoordinateY = 66.9,
        Loot = {
            [1] = {
                Id = "58150",
                Icon = "inv_sword_36",
                Name = IJ_LOOT_NAME_58150,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 25,
                LevelRequirement = 35,
            },
            [2] = {
                Id = "58151",
                Icon = "inv_misc_pocketwatch_02",
                Name = IJ_LOOT_NAME_58151,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 25,
                LevelRequirement = 35,
            },
            [3] = {
                Id = "58152",
                Icon = "inv_misc_cape_07",
                Name = IJ_LOOT_NAME_58152,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 35,
            },
            [4] = {
                Id = "58153",
                Icon = "inv_jewelry_ring_31",
                Name = IJ_LOOT_NAME_58153,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 35,
            },
            [5] = {
                Id = "24",
                Icon = "inv_misc_note_01",
                Name = IJ_LOOT_NAME_24,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 6,
            },
            [6] = {
                Id = "58276",
                Icon = "inv_shield_16",
                Name = IJ_LOOT_NAME_58276,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 1,
                LevelRequirement = 35,
            },
            [7] = {
                Id = "70",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_70,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 6,
            },
            [8] = {
                Id = "950",
                Icon = "ability_mount_undeadhorse",
                Name = IJ_LOOT_NAME_950,
                Quality = IQ.Epic,
                ItemSlot = IS.Mount,
                DropChance = 1,
                LevelRequirement = 60,
            },
        }
    },
    [7] = { -- NOTE: Missing abilities
        Id = "62652",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "halthas" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "halthas" .. IMPF,
        Name = IJ_DB_DUNGEON_SWR_BOSS_NAME_62652,
        Story = IJ_DB_DUNGEON_SWR_BOSS_STORY_62652,
        MapCoordinateX = 32.8,
        MapCoordinateY = 91.9,
        Loot = {
            [1] = {
                Id = "58183",
                Icon = "inv_staff_25",
                Name = IJ_LOOT_NAME_58183,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 25,
                LevelRequirement = 34,
            },
            [2] = {
                Id = "58184",
                Icon = "inv_belt_35",
                Name = IJ_LOOT_NAME_58184,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 34,
            },
            [3] = {
                Id = "58185",
                Icon = "ability_creature_poison_04",
                Name = IJ_LOOT_NAME_58185,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 34,
            },
            [4] = {
                Id = "58186",
                Icon = "inv_crown_01",
                Name = IJ_LOOT_NAME_58186,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 34,
            },
            [5] = {
                Id = "83",
                Icon = "inv_scroll_05",
                Name = IJ_LOOT_NAME_83,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 6,
            },
        }
    },
    [8] = { -- NOTE: Missing abilities
        Id = "62664",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "mycellakos" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "mycellakos" .. IMPF,
        Name = IJ_DB_DUNGEON_SWR_BOSS_NAME_62664,
        Story = IJ_DB_DUNGEON_SWR_BOSS_STORY_62664,
        MapCoordinateX = 23.9,
        MapCoordinateY = 38.3,
        Loot = {
            [1] = {
                Id = "58179",
                Icon = "inv_gauntlets_07",
                Name = IJ_LOOT_NAME_58179,
                Quality = IQ.Rare,
                ItemSlot = IS.Relic,
                ItemType = IT.Idol,
                DropChance = 25,
                LevelRequirement = 33,
            },
            [2] = {
                Id = "58180",
                Icon = "inv_misc_gem_pearl_06",
                Name = IJ_LOOT_NAME_58180,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 25,
                LevelRequirement = 33,
            },
            [3] = {
                Id = "58181",
                Icon = "inv_jewelry_necklace_03",
                Name = IJ_LOOT_NAME_58181,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 25,
                LevelRequirement = 33,
            },
            [4] = {
                Id = "58182",
                Icon = "inv_generic_anchor",
                Name = IJ_LOOT_NAME_58182,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 25,
                LevelRequirement = 33,
            },
        }
    },
    [9] = { -- NOTE: Missing abilities
        Id = "62661",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "eldermaw" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "eldermaw" .. IMPF,
        Name = IJ_DB_DUNGEON_SWR_BOSS_NAME_62661,
        Story = IJ_DB_DUNGEON_SWR_BOSS_STORY_62661,
        MapCoordinateX = 22.5,
        MapCoordinateY = 25.7,
        Loot = {
            [1] = {
                Id = "58190",
                Icon = "inv_misc_cape_20",
                Name = IJ_LOOT_NAME_58190,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 34,
            },
            [2] = {
                Id = "58189",
                Icon = "inv_pants_mail_11",
                Name = IJ_LOOT_NAME_58189,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 34,
            },
            [3] = {
                Id = "58188",
                Icon = "inv_sword_19",
                Name = IJ_LOOT_NAME_58188,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 25,
                LevelRequirement = 34,
            },
            [4] = {
                Id = "58187",
                Icon = "inv_shoulder_12",
                Name = IJ_LOOT_NAME_58187,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 34,
            },
        }
    },
    [10] = { -- NOTE: Missing abilities
        Id = "62665",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "drazare" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "drazare" .. IMPF,
        Name = IJ_DB_DUNGEON_SWR_BOSS_NAME_62665,
        Story = IJ_DB_DUNGEON_SWR_BOSS_STORY_62665,
        MapCoordinateX = 30.7,
        MapCoordinateY = 19.3,
        Loot = {
            [1] = {
                Id = "58194",
                Icon = "inv_axe_11",
                Name = IJ_LOOT_NAME_58194,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Axe,
                DropChance = 25,
                LevelRequirement = 35,
            },
            [2] = {
                Id = "58193",
                Icon = "genbow_twow3f",
                Name = IJ_LOOT_NAME_58193,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 25,
                LevelRequirement = 35,
            },
            [3] = {
                Id = "58192",
                Icon = "inv_chest_leather_03",
                Name = IJ_LOOT_NAME_58192,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 35,
            },
            [4] = {
                Id = "58191",
                Icon = "inv_misc_root_02",
                Name = IJ_LOOT_NAME_58191,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 25,
                LevelRequirement = 35,
            },
        }
    },
    [11] = { -- NOTE: Missing abilities
        Id = "62670",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "remains" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "remains" .. IMPF,
        Name = IJ_DB_DUNGEON_SWR_BOSS_NAME_62670,
        Story = IJ_DB_DUNGEON_SWR_BOSS_STORY_62670,
        MapCoordinateX = 26.4,
        MapCoordinateY = 10.2,
        Loot = {
            [1] = {
                Id = "58195",
                Icon = "inv_jewelry_ring_03",
                Name = IJ_LOOT_NAME_58195,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 35,
            },
            [2] = {
                Id = "58196",
                Icon = "inv_misc_book_01",
                Name = IJ_LOOT_NAME_58196,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 25,
                LevelRequirement = 35,
            },
            [3] = {
                Id = "58197",
                Icon = "inv_pants_03",
                Name = IJ_LOOT_NAME_58197,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 35,
            },
            [4] = {
                Id = "58198",
                Icon = "inv_sword_36",
                Name = IJ_LOOT_NAME_58198,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 25,
                LevelRequirement = 35,
            },
        }
    },
    [12] = { -- NOTE: Missing abilities
        Id = "62673",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "mergothid" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "mergothid" .. IMPF,
        Name = IJ_DB_DUNGEON_SWR_BOSS_NAME_62673,
        Story = IJ_DB_DUNGEON_SWR_BOSS_STORY_62673,
        MapCoordinateX = 30.7,
        MapCoordinateY = 5.9,
        Loot = {
            [1] = {
                Id = "58199",
                Icon = "inv_weirdogreheadstick_3",
                Name = IJ_LOOT_NAME_58199,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 1,
                LevelRequirement = 37,
            },
            [2] = {
                Id = "58204",
                Icon = "inv_boots_08",
                Name = IJ_LOOT_NAME_58204,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 37,
            },
            [3] = {
                Id = "58203",
                Icon = "inv_chest_plate16",
                Name = IJ_LOOT_NAME_58203,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 37,
            },
            [4] = {
                Id = "58202",
                Icon = "inv_misc_gem_amethyst_02",
                Name = IJ_LOOT_NAME_58202,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 37,
            },
            [5] = {
                Id = "58201",
                Icon = "inv_misc_cape_22",
                Name = IJ_LOOT_NAME_58201,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 37,
            },
            [6] = {
                Id = "58200",
                Icon = "inv_helmet_19",
                Name = IJ_LOOT_NAME_58200,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 37,
            },
        }
    },
}

IJDB.DG.SWR = SWR
