IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "ubrs\\"

local UBRS = {}

UBRS.Name = IJ_DB_DUNGEON_UBRS_NAME
UBRS.Story = IJ_DB_DUNGEON_UBRS_STORY
UBRS.Type = IJLib.InstanceType.Dungeon
UBRS.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
UBRS.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
UBRS.MapId = IMI.BlackrockSpire
UBRS.IconScale = 0.8
UBRS.MinLevel = 60
UBRS.MaxLevel = 60
UBRS.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.BlackrockMountain,
        MapCoordinateX = 79.0,
        MapCoordinateY = 33.0,
    },
}
UBRS.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "9816",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "pyroguard" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "pyroguard" .. IMPF,
        Name = IJ_DB_DUNGEON_UBRS_BOSS_NAME_9816,
        Story = IJ_DB_DUNGEON_UBRS_BOSS_STORY_9816,
        Loot = {
            [1] = {
                Id = "58199",
                Icon = "inv_weirdogreheadstick_3",
                Name = IJ_LOOT_NAME_58199,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 1,
                LevelRequirement = 37,
            },
            [2] = {
                Id = "58204",
                Icon = "inv_boots_08",
                Name = IJ_LOOT_NAME_58204,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 37,
            },
            [3] = {
                Id = "58203",
                Icon = "inv_chest_plate16",
                Name = IJ_LOOT_NAME_58203,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 37,
            },
            [4] = {
                Id = "58202",
                Icon = "inv_misc_gem_amethyst_02",
                Name = IJ_LOOT_NAME_58202,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 37,
            },
            [5] = {
                Id = "58201",
                Icon = "inv_misc_cape_22",
                Name = IJ_LOOT_NAME_58201,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 37,
            },
            [6] = {
                Id = "58200",
                Icon = "inv_helmet_19",
                Name = IJ_LOOT_NAME_58200,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 37,
            },
            [7] = {
                Id = "12905",
                Icon = "inv_chest_cloth_16",
                Name = IJ_LOOT_NAME_12905,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [8] = {
                Id = "12926",
                Icon = "spell_holy_innerfire",
                Name = IJ_LOOT_NAME_12926,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [9] = {
                Id = "12927",
                Icon = "inv_shoulder_10",
                Name = IJ_LOOT_NAME_12927,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [10] = {
                Id = "12929",
                Icon = "inv_jewelry_necklace_05",
                Name = IJ_LOOT_NAME_12929,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [11] = {
                Id = "16672",
                Icon = "inv_gauntlets_11",
                Name = IJ_LOOT_NAME_16672,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 54,
            },
            [12] = {
                Id = "23320",
                Icon = "inv_misc_stonetablet_11",
                Name = IJ_LOOT_NAME_23320,
                Quality = IQ.Rare,
                ItemSlot = IS.Ability,
                DropChance = 8,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Shaman, },
            },
            [13] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [14] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [2] = { -- NOTE: Missing abilities
        Id = "10264",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "solakar" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "solakar" .. IMPF,
        Name = IJ_DB_DUNGEON_UBRS_BOSS_NAME_10264,
        Story = IJ_DB_DUNGEON_UBRS_BOSS_STORY_10264,
        Loot = {
            [1] = {
                Id = "12589",
                Icon = "inv_belt_11",
                Name = IJ_LOOT_NAME_12589,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [2] = {
                Id = "12603",
                Icon = "inv_chest_plate06",
                Name = IJ_LOOT_NAME_12603,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [3] = {
                Id = "12606",
                Icon = "inv_belt_10",
                Name = IJ_LOOT_NAME_12606,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [4] = {
                Id = "12609",
                Icon = "inv_chest_cloth_17",
                Name = IJ_LOOT_NAME_12609,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 56,
            },
            [5] = {
                Id = "16695",
                Icon = "inv_shoulder_02",
                Name = IJ_LOOT_NAME_16695,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [6] = {
                Id = "18657",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_18657,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Engineering,
                DropChance = 6,
            },
            [7] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [8] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [3] = { -- NOTE: Missing abilities
        Id = "10509",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "jed" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "jed" .. IMPF,
        Name = IJ_DB_DUNGEON_UBRS_BOSS_NAME_10509,
        Story = IJ_DB_DUNGEON_UBRS_BOSS_STORY_10509,
        IsRare = true,
        Loot = {
            [1] = {
                Id = "12604",
                Icon = "inv_crown_02",
                Name = IJ_LOOT_NAME_12604,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 33,
                LevelRequirement = 55,
            },
            [2] = {
                Id = "12605",
                Icon = "inv_misc_bone_elfskull_01",
                Name = IJ_LOOT_NAME_12605,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 33,
                LevelRequirement = 51,
            },
            [3] = {
                Id = "12930",
                Icon = "inv_misc_root_02",
                Name = IJ_LOOT_NAME_12930,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 33,
                LevelRequirement = 55,
            },
            [4] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [4] = { -- NOTE: Missing abilities
        Id = "10899",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "goraluk" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "goraluk" .. IMPF,
        Name = IJ_DB_DUNGEON_UBRS_BOSS_NAME_10899,
        Story = IJ_DB_DUNGEON_UBRS_BOSS_STORY_10899,
        Loot = {
            [1] = {
                Id = "18779",
                Icon = "inv_misc_note_06",
                Name = IJ_LOOT_NAME_18779,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 15,
                LevelRequirement = 50,
            },
            [2] = {
                Id = "12728",
                Icon = "inv_scroll_03",
                Name = IJ_LOOT_NAME_12728,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 14,
            },
            [3] = {
                Id = "12834",
                Icon = "inv_scroll_03",
                Name = IJ_LOOT_NAME_12834,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 14,
            },
            [4] = {
                Id = "12837",
                Icon = "inv_scroll_03",
                Name = IJ_LOOT_NAME_12837,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 14,
            },
            [5] = {
                Id = "13498",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_13498,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 55,
            },
            [6] = {
                Id = "13502",
                Icon = "inv_belt_23",
                Name = IJ_LOOT_NAME_13502,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 58,
            },
            [7] = {
                Id = "18047",
                Icon = "inv_boots_02",
                Name = IJ_LOOT_NAME_18047,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 57,
            },
            [8] = {
                Id = "18048",
                Icon = "inv_hammer_06",
                Name = IJ_LOOT_NAME_18048,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 14,
                LevelRequirement = 55,
            },
            [9] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [5] = { -- NOTE: Missing abilities
        Id = "10429",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "rend" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "rend" .. IMPF,
        Name = IJ_DB_DUNGEON_UBRS_BOSS_NAME_10429,
        Story = IJ_DB_DUNGEON_UBRS_BOSS_STORY_10429,
        Loot = {
            [1] = {
                Id = "12587",
                Icon = "inv_helmet_46",
                Name = IJ_LOOT_NAME_12587,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 23,
                LevelRequirement = 58,
            },
            [2] = {
                Id = "12935",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_12935,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 23,
                LevelRequirement = 58,
            },
            [3] = {
                Id = "18102",
                Icon = "inv_boots_05",
                Name = IJ_LOOT_NAME_18102,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 23,
                LevelRequirement = 58,
            },
            [4] = {
                Id = "18103",
                Icon = "inv_jewelry_ring_16",
                Name = IJ_LOOT_NAME_18103,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 23,
                LevelRequirement = 58,
            },
            [5] = {
                Id = "12588",
                Icon = "inv_shoulder_11",
                Name = IJ_LOOT_NAME_12588,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 17,
                LevelRequirement = 58,
            },
            [6] = {
                Id = "12936",
                Icon = "inv_bracer_17",
                Name = IJ_LOOT_NAME_12936,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 58,
            },
            [7] = {
                Id = "16733",
                Icon = "inv_shoulder_30",
                Name = IJ_LOOT_NAME_16733,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 55,
            },
            [8] = {
                Id = "18104",
                Icon = "inv_belt_03",
                Name = IJ_LOOT_NAME_18104,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 17,
                LevelRequirement = 58,
            },
            [9] = {
                Id = "22247",
                Icon = "inv_boots_cloth_03",
                Name = IJ_LOOT_NAME_22247,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 58,
            },
            [10] = {
                Id = "12583",
                Icon = "inv_weapon_halberd_04",
                Name = IJ_LOOT_NAME_12583,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 8,
                LevelRequirement = 58,
            },
            [11] = {
                Id = "12940",
                Icon = "inv_sword_43",
                Name = IJ_LOOT_NAME_12940,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Sword,
                DropChance = 8,
                LevelRequirement = 58,
            },
            [12] = {
                Id = "12939",
                Icon = "inv_sword_40",
                Name = IJ_LOOT_NAME_12939,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Sword,
                DropChance = 8,
                LevelRequirement = 58,
            },
            [13] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [14] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 3,
            },
            [15] = {
                Id = "12590",
                Icon = "inv_weapon_shortblade_25",
                Name = IJ_LOOT_NAME_12590,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 1,
                LevelRequirement = 58,
            },
            [16] = {
                Id = "12952",
                Icon = "inv_helmet_23",
                Name = IJ_LOOT_NAME_12952,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [17] = {
                Id = "12953",
                Icon = "inv_helmet_39",
                Name = IJ_LOOT_NAME_12953,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [18] = {
                Id = "12960",
                Icon = "inv_helmet_24",
                Name = IJ_LOOT_NAME_12960,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [19] = {
                Id = "16669",
                Icon = "inv_shoulder_29",
                Name = IJ_LOOT_NAME_16669,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [20] = {
                Id = "22225",
                Icon = "inv_helmet_27",
                Name = IJ_LOOT_NAME_22225,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 55,
            },
            [21] = {
                Id = "12871",
                Icon = "inv_shield_21",
                Name = IJ_LOOT_NAME_12871,
                Quality = IQ.Epic,
                ItemSlot = IS.Reagent,
                DropChance = 4,
            },
            [22] = {
                Id = "13522",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_13522,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 3,
            },
        }
    },
    [6] = { -- NOTE: Missing abilities
        Id = "10430",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "beast" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "beast" .. IMPF,
        Name = IJ_DB_DUNGEON_UBRS_BOSS_NAME_10430,
        Story = IJ_DB_DUNGEON_UBRS_BOSS_STORY_10430,
        Loot = {
            [1] = {
                Id = "24101",
                Icon = "inv_misc_book_02",
                Name = IJ_LOOT_NAME_24101,
                Quality = IQ.Rare,
                ItemSlot = IS.Ability,
                DropChance = 13,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Druid, },
            },
            [2] = {
                Id = "12709",
                Icon = "inv_sword_33",
                Name = IJ_LOOT_NAME_12709,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Dagger,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [3] = {
                Id = "12963",
                Icon = "inv_pants_06",
                Name = IJ_LOOT_NAME_12963,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [4] = {
                Id = "12964",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_12964,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [5] = {
                Id = "12965",
                Icon = "inv_pants_06",
                Name = IJ_LOOT_NAME_12965,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [6] = {
                Id = "12966",
                Icon = "inv_bracer_07",
                Name = IJ_LOOT_NAME_12966,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [7] = {
                Id = "12967",
                Icon = "inv_misc_cape_05",
                Name = IJ_LOOT_NAME_12967,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [8] = {
                Id = "12968",
                Icon = "inv_misc_cape_18",
                Name = IJ_LOOT_NAME_12968,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [9] = {
                Id = "12969",
                Icon = "inv_hammer_17",
                Name = IJ_LOOT_NAME_12969,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [10] = {
                Id = "16729",
                Icon = "inv_shoulder_10",
                Name = IJ_LOOT_NAME_16729,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 10,
                LevelRequirement = 55,
            },
            [11] = {
                Id = "22311",
                Icon = "inv_boots_cloth_05",
                Name = IJ_LOOT_NAME_22311,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 56,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [12] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
            [13] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 2,
            },
        }
    },
    [7] = { -- NOTE: Missing abilities
        Id = "16042",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "valthalak" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "valthalak" .. IMPF,
        Name = IJ_DB_DUNGEON_UBRS_BOSS_NAME_16042,
        Story = IJ_DB_DUNGEON_UBRS_BOSS_STORY_16042,
        Loot = {
            [1] = {
                Id = "22302",
                Icon = "inv_helmet_30",
                Name = IJ_LOOT_NAME_22302,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 58,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [2] = {
                Id = "22336",
                Icon = "inv_shield_02",
                Name = IJ_LOOT_NAME_22336,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 25,
                LevelRequirement = 58,
            },
            [3] = {
                Id = "22339",
                Icon = "inv_jewelry_ring_35",
                Name = IJ_LOOT_NAME_22339,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 58,
            },
            [4] = {
                Id = "22342",
                Icon = "inv_pants_09",
                Name = IJ_LOOT_NAME_22342,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 58,
            },
            [5] = {
                Id = "22335",
                Icon = "inv_staff_07",
                Name = IJ_LOOT_NAME_22335,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 25,
                LevelRequirement = 58,
            },
            [6] = {
                Id = "22337",
                Icon = "inv_misc_cape_19",
                Name = IJ_LOOT_NAME_22337,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 58,
            },
            [7] = {
                Id = "22340",
                Icon = "inv_jewelry_necklace_04",
                Name = IJ_LOOT_NAME_22340,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 25,
                LevelRequirement = 58,
            },
            [8] = {
                Id = "22343",
                Icon = "inv_gauntlets_11",
                Name = IJ_LOOT_NAME_22343,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 58,
            },
            [9] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 5,
            },
        }
    },
    [8] = { -- NOTE: Missing abilities
        Id = "10363",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "drakkisath" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "drakkisath" .. IMPF,
        Name = IJ_DB_DUNGEON_UBRS_BOSS_NAME_10363,
        Story = IJ_DB_DUNGEON_UBRS_BOSS_STORY_10363,
        Loot = {
            [1] = {
                Id = "51217",
                Icon = "inv_misc_ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [2] = {
                Id = "22253",
                Icon = "inv_misc_book_06",
                Name = IJ_LOOT_NAME_22253,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 25,
                LevelRequirement = 58,
            },
            [3] = {
                Id = "22267",
                Icon = "inv_helmet_62",
                Name = IJ_LOOT_NAME_22267,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "22268",
                Icon = "inv_jewelry_talisman_09",
                Name = IJ_LOOT_NAME_22268,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 25,
                LevelRequirement = 58,
            },
            [5] = {
                Id = "22269",
                Icon = "inv_misc_cape_20",
                Name = IJ_LOOT_NAME_22269,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 58,
            },
            [6] = {
                Id = "12602",
                Icon = "inv_shield_20",
                Name = IJ_LOOT_NAME_12602,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 25,
                LevelRequirement = 58,
            },
            [7] = {
                Id = "13098",
                Icon = "inv_jewelry_ring_18",
                Name = IJ_LOOT_NAME_13098,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 58,
            },
            [8] = {
                Id = "13141",
                Icon = "inv_jewelry_necklace_09",
                Name = IJ_LOOT_NAME_13141,
                Quality = IQ.Rare,
                ItemSlot = IS.Neck,
                DropChance = 25,
                LevelRequirement = 58,
            },
            [9] = {
                Id = "13142",
                Icon = "inv_belt_33",
                Name = IJ_LOOT_NAME_13142,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 58,
            },
            [10] = {
                Id = "16666",
                Icon = "inv_chest_chain_11",
                Name = IJ_LOOT_NAME_16666,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 58,
            },
            [11] = {
                Id = "16674",
                Icon = "inv_chest_chain_03",
                Name = IJ_LOOT_NAME_16674,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 58,
            },
            [12] = {
                Id = "16688",
                Icon = "inv_chest_cloth_25",
                Name = IJ_LOOT_NAME_16688,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 58,
            },
            [13] = {
                Id = "16690",
                Icon = "inv_chest_cloth_11",
                Name = IJ_LOOT_NAME_16690,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 58,
            },
            [14] = {
                Id = "16700",
                Icon = "inv_chest_cloth_49",
                Name = IJ_LOOT_NAME_16700,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 58,
            },
            [15] = {
                Id = "16706",
                Icon = "inv_chest_plate06",
                Name = IJ_LOOT_NAME_16706,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 58,
            },
            [16] = {
                Id = "16721",
                Icon = "inv_chest_leather_07",
                Name = IJ_LOOT_NAME_16721,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 58,
            },
            [17] = {
                Id = "16726",
                Icon = "inv_chest_plate03",
                Name = IJ_LOOT_NAME_16726,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 58,
            },
            [18] = {
                Id = "16730",
                Icon = "inv_chest_plate03",
                Name = IJ_LOOT_NAME_16730,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 58,
            },
            [19] = {
                Id = "13090",
                Icon = "inv_chest_chain_16",
                Name = IJ_LOOT_NAME_13090,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 10,
                LevelRequirement = 58,
            },
            [20] = {
                Id = "47413",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_47413,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [21] = {
                Id = "47415",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_47415,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 10,
            },
            [22] = {
                Id = "15730",
                Icon = "inv_scroll_03",
                Name = IJ_LOOT_NAME_15730,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Leatherworking,
                DropChance = 4,
            },
            [23] = {
                Id = "70226",
                Icon = "inv_misc_bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 3,
            },
            [24] = {
                Id = "13519",
                Icon = "inv_scroll_06",
                Name = IJ_LOOT_NAME_13519,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 3,
            },
            [25] = {
                Id = "12592",
                Icon = "inv_sword_29",
                Name = IJ_LOOT_NAME_12592,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 1,
                LevelRequirement = 58,
            },
        }
    },
}

IJDB.DG.UBRS = UBRS
