IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IC = IJLib.Challenges
local IMP = IJLib.MediaPath
local IMPD = IJLib.MediaPathDungeons
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "whc\\"

local WHC = {}

WHC.Name = IJ_DB_DUNGEON_WHC_NAME
WHC.Story = IJ_DB_DUNGEON_WHC_STORY
WHC.Type = IJLib.InstanceType.Dungeon
WHC.Background = IMP .. IMPD .. instanceMediaAcronym .. "background"
WHC.GridBackground = IMP .. IMPD .. instanceMediaAcronym .. "grid-background"
WHC.MapId = IMI.WindhornCanyon
WHC.IconScale = 1.0
WHC.MinLevel = 26
WHC.MaxLevel = 30
WHC.Entrances = {
    [1] = {
        MapContinentId = IMI.Kalimdor,
        MapZoneId = IZI.WindhornCaverns,
        MapCoordinateX = 68.7,
        MapCoordinateY = 25.7,
    },
}
WHC.Bosses = {
    [1] = { -- NOTE: Missing abilities, Missing Loot
        Id = "pathun",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "pathun" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "pathun" .. IMPF,
        Name = IJ_DB_DUNGEON_WHC_BOSS_NAME_pathun,
        Story = IJ_DB_DUNGEON_WHC_BOSS_STORY_pathun,
        MapCoordinateX = 33.1,
        MapCoordinateY = 44.3,
        Loot = {
            [1] = {
                Id = "33025",
                Icon = "INV_Weapon_Bow_05",
                Name = IJ_LOOT_NAME_33025,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 25,
                LevelRequirement = 22,
            },
            [2] = {
                Id = "33026",
                Icon = "INV_Shoulder_04",
                Name = IJ_LOOT_NAME_33026,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 22,
            },
            [3] = {
                Id = "33028",
                Icon = "INV_Axe_01",
                Name = IJ_LOOT_NAME_33028,
                Quality = IQ.Uncommon,
                ItemSlot = IS.OneHand,
                ItemType = IT.Axe,
                DropChance = 25,
                LevelRequirement = 22,
            },
            [4] = {
                Id = "33027",
                Icon = "INV_Misc_Horn_01",
                Name = IJ_LOOT_NAME_33027,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 25,
                LevelRequirement = 22,
            },
        },
    },
    [2] = { -- NOTE: Missing abilities, Missing Loot
        Id = "ahgktos",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "ahgktos" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "ahgktos" .. IMPF,
        Name = IJ_DB_DUNGEON_WHC_BOSS_NAME_ahgktos,
        Story = IJ_DB_DUNGEON_WHC_BOSS_STORY_ahgktos,
        MapCoordinateX = 26.3,
        MapCoordinateY = 9.7,
        Loot = {
            [1] = {
                Id = "33024",
                Icon = "INV_Weapon_ShortBlade_02",
                Name = IJ_LOOT_NAME_33024,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 25,
                LevelRequirement = 21,
            },
            [2] = {
                Id = "33022",
                Icon = "INV_Chest_Leather_05",
                Name = IJ_LOOT_NAME_33022,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 21,
            },
            [3] = {
                Id = "33023",
                Icon = "INV_Jewelry_Ring_22",
                Name = IJ_LOOT_NAME_33023,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 21,
            },
            [4] = {
                Id = "33021",
                Icon = "INV_Gauntlets_18",
                Name = IJ_LOOT_NAME_33021,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 21,
            },
        },
    },
    [3] = { -- NOTE: Missing abilities, Missing Loot
        Id = "vortalus",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "vortalus" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "vortalus" .. IMPF,
        Name = IJ_DB_DUNGEON_WHC_BOSS_NAME_vortalus,
        Story = IJ_DB_DUNGEON_WHC_BOSS_STORY_vortalus,
        MapCoordinateX = 36.8,
        MapCoordinateY = 62.0,
        MapIsBelow = true,
        Loot = {
            [1] = {
                Id = "33030",
                Icon = "INV_Gauntlets_04",
                Name = IJ_LOOT_NAME_33030,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 23,
            },
            [2] = {
                Id = "33031",
                Icon = "INV_Axe_21",
                Name = IJ_LOOT_NAME_33031,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 25,
                LevelRequirement = 23,
            },
            [3] = {
                Id = "33029",
                Icon = "INV_Boots_Wolf",
                Name = IJ_LOOT_NAME_33029,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 23,
            },
            [4] = {
                Id = "33032",
                Icon = "INV_Bracer_06",
                Name = IJ_LOOT_NAME_33032,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 23,
            },
        },
        Abilities = {
            [1] = {
                Id = "6982",
                Icon = "spell_nature_earthbind",
                Name = IJ_DB_DUNGEON_WHC_BOSS_vortalus_ABILITY_NAME_6982,
                Effect = IJ_DB_DUNGEON_WHC_BOSS_vortalus_ABILITY_EFFECT_6982,
                Flags = { IMAF.Interruptible, IMAF.Important, },
            },
            [2] = {
                Id = "vortaluschainlightning",
                Icon = "spell_nature_chainlightning",
                Name = IJ_DB_DUNGEON_WHC_BOSS_vortalus_ABILITY_NAME_vortaluschainlightning,
                Effect = IJ_DB_DUNGEON_WHC_BOSS_vortalus_ABILITY_EFFECT_vortaluschainlightning,
                Flags = { IMAF.Interruptible, },
            },
        },
    },
    [4] = { -- NOTE: Missing abilities, Missing Loot
        Id = "walgan",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "walgan" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "walgan" .. IMPF,
        Name = IJ_DB_DUNGEON_WHC_BOSS_NAME_walgan,
        Story = IJ_DB_DUNGEON_WHC_BOSS_STORY_walgan,
        MapCoordinateX = 18.2,
        MapCoordinateY = 68.7,
        Loot = {
            [1] = {
                Id = "33082",
                Icon = "INV_Weapon_Rifle_05",
                Name = IJ_LOOT_NAME_33082,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 25,
                LevelRequirement = 24,
            },
            [2] = {
                Id = "33035",
                Icon = "Inv_pants_wolf",
                Name = IJ_LOOT_NAME_33035,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 24,
            },
            [3] = {
                Id = "42275",
                Icon = "INV_Gauntlets_25",
                Name = IJ_LOOT_NAME_42275,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 24,
            },
            [4] = {
                Id = "33033",
                Icon = "INV_Bracer_08",
                Name = IJ_LOOT_NAME_33033,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 24,
            },
        },
    },
    [5] = { -- NOTE: Missing abilities, Missing Loot
        Id = "narlgom",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "narlgom" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "narlgom" .. IMPF,
        Name = IJ_DB_DUNGEON_WHC_BOSS_NAME_narlgom,
        Story = IJ_DB_DUNGEON_WHC_BOSS_STORY_narlgom,
        MapCoordinateX = 36.8,
        MapCoordinateY = 56.8,
        MapIsBelow = true,
        Loot = {
            [1] = {
                Id = "42276",
                Icon = "INV_Pants_12",
                Name = IJ_LOOT_NAME_42276,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 24,
            },
            [2] = {
                Id = "33040",
                Icon = "INV_Misc_Bone_09",
                Name = IJ_LOOT_NAME_33040,
                Quality = IQ.Rare,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 24,
            },
            [3] = {
                Id = "33038",
                Icon = "INV_Staff_21",
                Name = IJ_LOOT_NAME_33038,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 25,
                LevelRequirement = 24,
            },
            [4] = {
                Id = "33037",
                Icon = "INV_Chest_Leather_01",
                Name = IJ_LOOT_NAME_33037,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 24,
            },
        },
    },
    [6] = { -- NOTE: Missing abilities, Missing Loot
        Id = "stormhoof",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "stormhoof" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "stormhoof" .. IMPF,
        Name = IJ_DB_DUNGEON_WHC_BOSS_NAME_stormhoof,
        Story = IJ_DB_DUNGEON_WHC_BOSS_STORY_stormhoof,
        MapCoordinateX = 40.5,
        MapCoordinateY = 56.0,
        MapIsBelow = true,
        Loot = {
            [1] = {
                Id = "33043",
                Icon = "INV_Banner_01",
                Name = IJ_LOOT_NAME_33043,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 25,
            },
            [2] = {
                Id = "33042",
                Icon = "INV_Helmet_24",
                Name = IJ_LOOT_NAME_33042,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 25,
            },
            [3] = {
                Id = "33044",
                Icon = "INV_Jewelry_Ring_27",
                Name = IJ_LOOT_NAME_33044,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 25,
            },
            [4] = {
                Id = "33041",
                Icon = "INV_Staff_02",
                Name = IJ_LOOT_NAME_33041,
                Quality = IQ.Rare,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 25,
                LevelRequirement = 25,
            },
            [5] = {
                Id = "70244",
                Icon = "INV_Scroll_06",
                Name = IJ_LOOT_NAME_70244,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 100,
            },
        },
        Abilities = {
            [1] = {
                Id = "stormhoofcorruption",
                Icon = "spell_shadow_abominationexplosion",
                Name = IJ_DB_DUNGEON_WHC_BOSS_stormhoof_ABILITY_NAME_stormhoofcorruption,
                Effect = IJ_DB_DUNGEON_WHC_BOSS_stormhoof_ABILITY_EFFECT_stormhoofcorruption,
                Flags = { IMAF.Curse, },
            },
        },
    },
    [7] = { -- NOTE: Missing abilities, Missing Loot
        Id = "shalk",
        Portrait = IMP .. IMPD .. instanceMediaAcronym .. "shalk" .. IMPP,
        Frame = IMP .. IMPD .. instanceMediaAcronym .. "shalk" .. IMPF,
        Name = IJ_DB_DUNGEON_WHC_BOSS_NAME_shalk,
        Story = IJ_DB_DUNGEON_WHC_BOSS_STORY_shalk,
        MapCoordinateX = 48.6,
        MapCoordinateY = 44.0,
        Loot = {
            [1] = {
                Id = "33047",
                Icon = "INV_Axe_05",
                Name = IJ_LOOT_NAME_33047,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Axe,
                DropChance = 33,
                LevelRequirement = 26,
            },
            [2] = {
                Id = "33046",
                Icon = "INV_Shield_06",
                Name = IJ_LOOT_NAME_33046,
                Quality = IQ.Rare,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 33,
                LevelRequirement = 26,
            },
            [3] = {
                Id = "33045",
                Icon = "ability_smash",
                Name = IJ_LOOT_NAME_33045,
                Quality = IQ.Rare,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 33,
                LevelRequirement = 26,
            },
            [4] = {
                Id = "42277",
                Icon = "INV_Helmet_04",
                Name = IJ_LOOT_NAME_42277,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 1,
                LevelRequirement = 26,
            },
        },
    },
}

IJDB.DG.WHC = WHC
