IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPR = IJLib.MediaPathRaids
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "aq40\\"

local AQ40 = {}

AQ40.Name = IJ_DB_RAID_AQ40_NAME
AQ40.Story = IJ_DB_RAID_AQ40_STORY
AQ40.Type = IJLib.InstanceType.Raid
AQ40.Background = IMP .. IMPR .. instanceMediaAcronym .. "background"
AQ40.GridBackground = IMP .. IMPR .. instanceMediaAcronym .. "grid-background"
AQ40.MapId = IMI.TempleOfAhnQiraj
AQ40.ZoneId = IZI.AQ402
AQ40.IconScale = 0.8
AQ40.MinLevel = 60
AQ40.MaxLevel = 60
AQ40.Entrances = {
    [1] = {
        MapContinentId = IMI.Kalimdor,
        MapZoneId = IZI.GatesOfAhnQiraj,
        MapCoordinateX = 46.4,
        MapCoordinateY = 7.7,
        MapDestinationZoneId = IZI.AQ402,
    },
}
AQ40.Links = {
    [1] = {
        OriginMapContinentId = IMI.TempleOfAhnQiraj,
        OriginMapZoneId = IZI.AQ402,
        OriginMapCoordinateX = 49.1,
        OriginMapCoordinateY = 62.9,
        DestinationMapContinentId = IMI.TempleOfAhnQiraj,
        DestinationMapZoneId = IZI.AQ401,
        Type = IJLib.EntranceIconType.Up,
        Name = IJ_DB_RAID_AQ40_LINK_AQ,
    },
    [2] = {
        OriginMapContinentId = IMI.TempleOfAhnQiraj,
        OriginMapZoneId = IZI.AQ401,
        OriginMapCoordinateX = 32.2,
        OriginMapCoordinateY = 45.7,
        DestinationMapContinentId = IMI.TempleOfAhnQiraj,
        DestinationMapZoneId = IZI.AQ402,
        Type = IJLib.EntranceIconType.Up,
        Name = IJ_DB_RAID_AQ40_LINK_AQ,
    },
}
AQ40.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "15263",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "skeram" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "skeram" .. IMPF,
        Name = IJ_DB_RAID_AQ40_BOSS_NAME_15263,
        Story = IJ_DB_RAID_AQ40_BOSS_STORY_15263,
        MapCoordinateX = 46.0,
        MapCoordinateY = 51.7,
        MapId = IZI.AQ402,
        Loot = {
            [1] = {
                Id = "22222",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_22222,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 15,
            },
            [2] = {
                Id = "20727",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20727,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [3] = {
                Id = "20728",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20728,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [4] = {
                Id = "20729",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20729,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [5] = {
                Id = "20730",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20730,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [6] = {
                Id = "20731",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20731,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [7] = {
                Id = "20734",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20734,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [8] = {
                Id = "20736",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20736,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [9] = {
                Id = "21128",
                Icon = "INV_Staff_01",
                Name = IJ_LOOT_NAME_21128,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "21698",
                Icon = "INV_Pants_Leather_11",
                Name = IJ_LOOT_NAME_21698,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "21699",
                Icon = "INV_Shoulder_14",
                Name = IJ_LOOT_NAME_21699,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "21700",
                Icon = "INV_Jewelry_Necklace_AhnQiraj_01",
                Name = IJ_LOOT_NAME_21700,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "21701",
                Icon = "INV_Misc_Cape_02",
                Name = IJ_LOOT_NAME_21701,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "21702",
                Icon = "INV_Jewelry_Necklace_12",
                Name = IJ_LOOT_NAME_21702,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "21703",
                Icon = "INV_Mace_21",
                Name = IJ_LOOT_NAME_21703,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "21704",
                Icon = "INV_Boots_Plate_08",
                Name = IJ_LOOT_NAME_21704,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "21705",
                Icon = "INV_Boots_Chain_06",
                Name = IJ_LOOT_NAME_21705,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "21706",
                Icon = "INV_Boots_Plate_06",
                Name = IJ_LOOT_NAME_21706,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "21707",
                Icon = "INV_Jewelry_Ring_AhnQiraj_04",
                Name = IJ_LOOT_NAME_21707,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [20] = {
                Id = "21708",
                Icon = "INV_Bracer_12",
                Name = IJ_LOOT_NAME_21708,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [21] = {
                Id = "21814",
                Icon = "INV_Chest_Plate02",
                Name = IJ_LOOT_NAME_21814,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [22] = {
                Id = "21232",
                Icon = "INV_Staff_24",
                Name = IJ_LOOT_NAME_21232,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [23] = {
                Id = "21237",
                Icon = "INV_Staff_20",
                Name = IJ_LOOT_NAME_21237,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 4,
                LevelRequirement = 60,
            },
        },
    },
    [2] = { -- NOTE: Missing abilities
        Id = "15544",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "trio" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "trio" .. IMPF,
        Name = IJ_DB_RAID_AQ40_BOSS_NAME_15544,
        Story = IJ_DB_RAID_AQ40_BOSS_STORY_15544,
        MapCoordinateX = 28.5,
        MapCoordinateY = 49.6,
        MapId = IZI.AQ401,
        Loot = {
            [1] = {
                Id = "21688",
                Icon = "INV_Boots_Plate_01",
                Name = IJ_LOOT_NAME_21688,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 60,
                Note = IJ_NOTES_VEM,
            },
            [2] = {
                Id = "21689",
                Icon = "INV_Gauntlets_23",
                Name = IJ_LOOT_NAME_21689,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 60,
                Note = IJ_NOTES_VEM,
            },
            [3] = {
                Id = "21690",
                Icon = "INV_Jewelry_Necklace_20",
                Name = IJ_LOOT_NAME_21690,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 25,
                LevelRequirement = 60,
                Note = IJ_NOTES_VEM,
            },
            [4] = {
                Id = "21691",
                Icon = "INV_Gauntlets_11",
                Name = IJ_LOOT_NAME_21691,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 60,
                Note = IJ_NOTES_VEM,
            },
            [5] = {
                Id = "21682",
                Icon = "INV_Gauntlets_21",
                Name = IJ_LOOT_NAME_21682,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 60,
                Note = IJ_NOTES_YAUJ,
            },
            [6] = {
                Id = "21683",
                Icon = "INV_Shoulder_29",
                Name = IJ_LOOT_NAME_21683,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 60,
                Note = IJ_NOTES_YAUJ,
            },
            [7] = {
                Id = "21684",
                Icon = "INV_Shoulder_16",
                Name = IJ_LOOT_NAME_21684,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 60,
                Note = IJ_NOTES_YAUJ,
            },
            [8] = {
                Id = "21686",
                Icon = "INV_Shoulder_02",
                Name = IJ_LOOT_NAME_21686,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
                Note = IJ_NOTES_YAUJ,
            },
            [9] = {
                Id = "21687",
                Icon = "INV_Jewelry_Ring_24",
                Name = IJ_LOOT_NAME_21687,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 60,
                Note = IJ_NOTES_YAUJ,
            },
            [10] = {
                Id = "21603",
                Icon = "INV_Wand_06",
                Name = IJ_LOOT_NAME_21603,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 25,
                LevelRequirement = 60,
                Note = IJ_NOTES_KRI,
            },
            [11] = {
                Id = "21680",
                Icon = "INV_Chest_Cloth_45",
                Name = IJ_LOOT_NAME_21680,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 60,
                Note = IJ_NOTES_KRI,
            },
            [12] = {
                Id = "21681",
                Icon = "INV_Jewelry_Ring_AhnQiraj_05",
                Name = IJ_LOOT_NAME_21681,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 60,
                Note = IJ_NOTES_KRI,
            },
            [13] = {
                Id = "21685",
                Icon = "INV_Misc_AhnQirajTrinket_01",
                Name = IJ_LOOT_NAME_21685,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 25,
                LevelRequirement = 60,
                Note = IJ_NOTES_KRI,
            },
            [14] = {
                Id = "20727",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20727,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [15] = {
                Id = "20728",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20728,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [16] = {
                Id = "20729",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20729,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [17] = {
                Id = "20730",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20730,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [18] = {
                Id = "20731",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20731,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [19] = {
                Id = "20734",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20734,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [20] = {
                Id = "20736",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20736,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [21] = {
                Id = "21232",
                Icon = "INV_Staff_24",
                Name = IJ_LOOT_NAME_21232,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [22] = {
                Id = "21237",
                Icon = "INV_Staff_20",
                Name = IJ_LOOT_NAME_21237,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [23] = {
                Id = "21692",
                Icon = "INV_Belt_18",
                Name = IJ_LOOT_NAME_21692,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [24] = {
                Id = "21693",
                Icon = "INV_Helmet_06",
                Name = IJ_LOOT_NAME_21693,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [25] = {
                Id = "21694",
                Icon = "INV_Shoulder_05",
                Name = IJ_LOOT_NAME_21694,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [26] = {
                Id = "21695",
                Icon = "INV_Jewelry_Ring_AhnQiraj_04",
                Name = IJ_LOOT_NAME_21695,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [27] = {
                Id = "21696",
                Icon = "INV_Chest_Cloth_22",
                Name = IJ_LOOT_NAME_21696,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [28] = {
                Id = "21697",
                Icon = "INV_Misc_Cape_18",
                Name = IJ_LOOT_NAME_21697,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
        },
    },
    [3] = { -- NOTE: Missing abilities
        Id = "15516",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "sartura" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "sartura" .. IMPF,
        Name = IJ_DB_RAID_AQ40_BOSS_NAME_15516,
        Story = IJ_DB_RAID_AQ40_BOSS_STORY_15516,
        MapCoordinateX = 44.6,
        MapCoordinateY = 33.6,
        MapId = IZI.AQ401,
        Loot = {
            [1] = {
                Id = "20727",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20727,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [2] = {
                Id = "20728",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20728,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [3] = {
                Id = "20729",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20729,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [4] = {
                Id = "20730",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20730,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [5] = {
                Id = "20731",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20731,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [6] = {
                Id = "20734",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20734,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [7] = {
                Id = "20736",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20736,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [8] = {
                Id = "21232",
                Icon = "INV_Staff_24",
                Name = IJ_LOOT_NAME_21232,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "21237",
                Icon = "INV_Staff_20",
                Name = IJ_LOOT_NAME_21237,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "21666",
                Icon = "INV_QirajIdol_War",
                Name = IJ_LOOT_NAME_21666,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "21667",
                Icon = "INV_Pants_Plate_11",
                Name = IJ_LOOT_NAME_21667,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "21668",
                Icon = "INV_Pants_Mail_15",
                Name = IJ_LOOT_NAME_21668,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "21669",
                Icon = "INV_Helmet_01",
                Name = IJ_LOOT_NAME_21669,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "21670",
                Icon = "INV_Misc_AhnQirajTrinket_04",
                Name = IJ_LOOT_NAME_21670,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "21671",
                Icon = "INV_Chest_Cloth_26",
                Name = IJ_LOOT_NAME_21671,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "21672",
                Icon = "INV_Gauntlets_17",
                Name = IJ_LOOT_NAME_21672,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "21648",
                Icon = "INV_Boots_Cloth_07",
                Name = IJ_LOOT_NAME_21648,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "21673",
                Icon = "INV_Misc_MonsterClaw_03",
                Name = IJ_LOOT_NAME_21673,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.FistWeapon,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "21674",
                Icon = "INV_Gauntlets_31",
                Name = IJ_LOOT_NAME_21674,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [20] = {
                Id = "21675",
                Icon = "INV_Belt_15",
                Name = IJ_LOOT_NAME_21675,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [21] = {
                Id = "21676",
                Icon = "INV_Pants_Cloth_02",
                Name = IJ_LOOT_NAME_21676,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [22] = {
                Id = "21678",
                Icon = "INV_Jewelry_Necklace_AhnQiraj_04",
                Name = IJ_LOOT_NAME_21678,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 18,
                LevelRequirement = 60,
            },
        },
    },
    [4] = { -- NOTE: Missing abilities
        Id = "15510",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "fankriss" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "fankriss" .. IMPF,
        Name = IJ_DB_RAID_AQ40_BOSS_NAME_15510,
        Story = IJ_DB_RAID_AQ40_BOSS_STORY_15510,
        MapCoordinateX = 62.2,
        MapCoordinateY = 22.6,
        MapId = IZI.AQ401,
        Loot = {
            [1] = {
                Id = "20727",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20727,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [2] = {
                Id = "20728",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20728,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [3] = {
                Id = "20729",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20729,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [4] = {
                Id = "20730",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20730,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [5] = {
                Id = "20731",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20731,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [6] = {
                Id = "20734",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20734,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [7] = {
                Id = "20736",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20736,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [8] = {
                Id = "21232",
                Icon = "INV_Staff_24",
                Name = IJ_LOOT_NAME_21232,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "21237",
                Icon = "INV_Staff_20",
                Name = IJ_LOOT_NAME_21237,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "21650",
                Icon = "INV_Sword_59",
                Name = IJ_LOOT_NAME_21650,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "21651",
                Icon = "INV_Pants_Mail_10",
                Name = IJ_LOOT_NAME_21651,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "21652",
                Icon = "INV_Chest_Plate09",
                Name = IJ_LOOT_NAME_21652,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "21663",
                Icon = "INV_Chest_Cloth_23",
                Name = IJ_LOOT_NAME_21663,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "21664",
                Icon = "INV_Jewelry_Necklace_AhnQiraj_02",
                Name = IJ_LOOT_NAME_21664,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "21665",
                Icon = "INV_Shoulder_30",
                Name = IJ_LOOT_NAME_21665,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "21627",
                Icon = "INV_Misc_Cape_20",
                Name = IJ_LOOT_NAME_21627,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "21635",
                Icon = "INV_Weapon_Halberd_AhnQiraj",
                Name = IJ_LOOT_NAME_21635,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "21639",
                Icon = "INV_Shoulder_29",
                Name = IJ_LOOT_NAME_21639,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "21645",
                Icon = "INV_Boots_04",
                Name = IJ_LOOT_NAME_21645,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [20] = {
                Id = "21647",
                Icon = "INV_Misc_AhnQirajTrinket_03",
                Name = IJ_LOOT_NAME_21647,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [21] = {
                Id = "22396",
                Icon = "INV_Relics_TotemofLife",
                Name = IJ_LOOT_NAME_22396,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Totem,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [22] = {
                Id = "22402",
                Icon = "INV_Relics_LibramofGrace",
                Name = IJ_LOOT_NAME_22402,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Libram,
                DropChance = 15,
                LevelRequirement = 60,
            },
        },
    },
    [5] = { -- NOTE: Missing abilities
        Id = "15299",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "viscidus" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "viscidus" .. IMPF,
        Name = IJ_DB_RAID_AQ40_BOSS_NAME_15299,
        Story = IJ_DB_RAID_AQ40_BOSS_STORY_15299,
        MapCoordinateX = 72.2,
        MapCoordinateY = 17.9,
        MapId = IZI.AQ401,
        Loot = {
            [1] = {
                Id = "20928",
                Icon = "INV_Qiraj_BindingsCommand",
                Name = IJ_LOOT_NAME_20928,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, IMCL.Hunter, IMCL.Priest, },
            },
            [2] = {
                Id = "20932",
                Icon = "INV_Qiraj_BindingsDominance",
                Name = IJ_LOOT_NAME_20932,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [3] = {
                Id = "20727",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20727,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [4] = {
                Id = "20728",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20728,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [5] = {
                Id = "20729",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20729,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [6] = {
                Id = "20730",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20730,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [7] = {
                Id = "20731",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20731,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [8] = {
                Id = "20734",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20734,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [9] = {
                Id = "20736",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20736,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [10] = {
                Id = "21232",
                Icon = "INV_Staff_24",
                Name = IJ_LOOT_NAME_21232,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "21237",
                Icon = "INV_Staff_20",
                Name = IJ_LOOT_NAME_21237,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "21622",
                Icon = "INV_Sword_58",
                Name = IJ_LOOT_NAME_21622,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.Sword,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "21623",
                Icon = "INV_Gauntlets_26",
                Name = IJ_LOOT_NAME_21623,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "21624",
                Icon = "INV_Gauntlets_26",
                Name = IJ_LOOT_NAME_21624,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "21625",
                Icon = "INV_Misc_AhnQirajTrinket_06",
                Name = IJ_LOOT_NAME_21625,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "21626",
                Icon = "INV_Pants_Mail_11",
                Name = IJ_LOOT_NAME_21626,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "21677",
                Icon = "INV_jewelry_ring_AhnQiraj_01",
                Name = IJ_LOOT_NAME_21677,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "22399",
                Icon = "INV_Relics_IdolofHealth",
                Name = IJ_LOOT_NAME_22399,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Idol,
                DropChance = 14,
                LevelRequirement = 60,
            },
        },
    },
    [6] = { -- NOTE: Missing abilities
        Id = "15509",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "huhuran" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "huhuran" .. IMPF,
        Name = IJ_DB_RAID_AQ40_BOSS_NAME_15509,
        Story = IJ_DB_RAID_AQ40_BOSS_STORY_15509,
        MapCoordinateX = 43.5,
        MapCoordinateY = 50.1,
        MapId = IZI.AQ401,
        Loot = {
            [1] = {
                Id = "20928",
                Icon = "INV_Qiraj_BindingsCommand",
                Name = IJ_LOOT_NAME_20928,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, IMCL.Hunter, IMCL.Priest, },
            },
            [2] = {
                Id = "20932",
                Icon = "INV_Qiraj_BindingsDominance",
                Name = IJ_LOOT_NAME_20932,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [3] = {
                Id = "20727",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20727,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [4] = {
                Id = "20728",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20728,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [5] = {
                Id = "20729",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20729,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [6] = {
                Id = "20730",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20730,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [7] = {
                Id = "20731",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20731,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [8] = {
                Id = "20734",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20734,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [9] = {
                Id = "20736",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20736,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [10] = {
                Id = "21232",
                Icon = "INV_Staff_24",
                Name = IJ_LOOT_NAME_21232,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "21237",
                Icon = "INV_Staff_20",
                Name = IJ_LOOT_NAME_21237,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "21616",
                Icon = "INV_Weapon_Bow_14",
                Name = IJ_LOOT_NAME_21616,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "21617",
                Icon = "INV_Gauntlets_17",
                Name = IJ_LOOT_NAME_21617,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "21618",
                Icon = "INV_Bracer_02",
                Name = IJ_LOOT_NAME_21618,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "21619",
                Icon = "INV_Gauntlets_17",
                Name = IJ_LOOT_NAME_21619,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "21620",
                Icon = "INV_jewelry_ring_AhnQiraj_01",
                Name = IJ_LOOT_NAME_21620,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "21621",
                Icon = "INV_Misc_Cape_01",
                Name = IJ_LOOT_NAME_21621,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
        },
    },
    [7] = { -- NOTE: Missing abilities
        Id = "15276",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "twins" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "twins" .. IMPF,
        Name = IJ_DB_RAID_AQ40_BOSS_NAME_15276,
        Story = IJ_DB_RAID_AQ40_BOSS_STORY_15276,
        MapCoordinateX = 60.7,
        MapCoordinateY = 69.9,
        MapId = IZI.AQ401,
        Loot = {
            [1] = {
                Id = "20735",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20735,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 6,
            },
            [2] = {
                Id = "20930",
                Icon = "INV_Bracer_18",
                Name = IJ_LOOT_NAME_20930,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                ClassRestriction = { IMCL.Rogue, IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [3] = {
                Id = "21232",
                Icon = "INV_Staff_24",
                Name = IJ_LOOT_NAME_21232,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "21237",
                Icon = "INV_Staff_20",
                Name = IJ_LOOT_NAME_21237,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "21597",
                Icon = "INV_Wand_10",
                Name = IJ_LOOT_NAME_21597,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "21598",
                Icon = "INV_Belt_31",
                Name = IJ_LOOT_NAME_21598,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "21599",
                Icon = "INV_Gauntlets_28",
                Name = IJ_LOOT_NAME_21599,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "21600",
                Icon = "INV_Boots_Cloth_05",
                Name = IJ_LOOT_NAME_21600,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "21601",
                Icon = "INV_jewelry_ring_AhnQiraj_01",
                Name = IJ_LOOT_NAME_21601,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "21602",
                Icon = "INV_Bracer_13",
                Name = IJ_LOOT_NAME_21602,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "20726",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20726,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 6,
            },
            [12] = {
                Id = "20926",
                Icon = "INV_Bracer_18",
                Name = IJ_LOOT_NAME_20926,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                ClassRestriction = { IMCL.Warrior, IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [13] = {
                Id = "21604",
                Icon = "INV_Bracer_13",
                Name = IJ_LOOT_NAME_21604,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "21605",
                Icon = "INV_Gauntlets_19",
                Name = IJ_LOOT_NAME_21605,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "21606",
                Icon = "INV_Belt_34",
                Name = IJ_LOOT_NAME_21606,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "21607",
                Icon = "INV_Belt_32",
                Name = IJ_LOOT_NAME_21607,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "21608",
                Icon = "INV_Jewelry_Necklace_AhnQiraj_01",
                Name = IJ_LOOT_NAME_21608,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "21609",
                Icon = "INV_Belt_11",
                Name = IJ_LOOT_NAME_21609,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "21679",
                Icon = "Inv_sword_53",
                Name = IJ_LOOT_NAME_21679,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 14,
                LevelRequirement = 60,
            },
        },
    },
    [8] = { -- NOTE: Missing abilities
        Id = "15517",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "ouro" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "ouro" .. IMPF,
        Name = IJ_DB_RAID_AQ40_BOSS_NAME_15517,
        Story = IJ_DB_RAID_AQ40_BOSS_STORY_15517,
        MapCoordinateX = 30.4,
        MapCoordinateY = 81.4,
        MapId = IZI.AQ401,
        Loot = {
            [1] = {
                Id = "20927",
                Icon = "INV_Qiraj_OuroHide",
                Name = IJ_LOOT_NAME_20927,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                ClassRestriction = { IMCL.Warrior, IMCL.Mage, IMCL.Rogue, IMCL.Priest, },
            },
            [2] = {
                Id = "20931",
                Icon = "INV_Qiraj_SkinSandworm",
                Name = IJ_LOOT_NAME_20931,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                ClassRestriction = { IMCL.Hunter, IMCL.Warlock, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [3] = {
                Id = "20727",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20727,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [4] = {
                Id = "20728",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20728,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [5] = {
                Id = "20729",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20729,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [6] = {
                Id = "20730",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20730,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [7] = {
                Id = "20731",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20731,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [8] = {
                Id = "20734",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20734,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [9] = {
                Id = "20736",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_20736,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [10] = {
                Id = "21232",
                Icon = "INV_Staff_24",
                Name = IJ_LOOT_NAME_21232,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "21237",
                Icon = "INV_Staff_20",
                Name = IJ_LOOT_NAME_21237,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 4,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "21610",
                Icon = "INV_Shield_24",
                Name = IJ_LOOT_NAME_21610,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "21611",
                Icon = "INV_Bracer_13",
                Name = IJ_LOOT_NAME_21611,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "21615",
                Icon = "INV_Helmet_51",
                Name = IJ_LOOT_NAME_21615,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "23557",
                Icon = "INV_Weapon_Rifle_10",
                Name = IJ_LOOT_NAME_23557,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Gun,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "23558",
                Icon = "INV_Shield_23",
                Name = IJ_LOOT_NAME_23558,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "23570",
                Icon = "INV_Misc_EngGizmos_19",
                Name = IJ_LOOT_NAME_23570,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "21612",
                Icon = "INV_Boots_Chain_08",
                Name = IJ_LOOT_NAME_21612,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "21613",
                Icon = "INV_Boots_04",
                Name = IJ_LOOT_NAME_21613,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [20] = {
                Id = "21614",
                Icon = "INV_Helmet_09",
                Name = IJ_LOOT_NAME_21614,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [21] = {
                Id = "55553",
                Icon = "inv_gauntlets_23",
                Name = IJ_LOOT_NAME_55553,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [22] = {
                Id = "55554",
                Icon = "INV_Gauntlets_26",
                Name = IJ_LOOT_NAME_55554,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [23] = {
                Id = "55555",
                Icon = "INV_Hammer_25",
                Name = IJ_LOOT_NAME_55555,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 17,
                LevelRequirement = 60,
            },
        },
    },
    [9] = { -- NOTE: Missing abilities
        Id = "15727",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "cthun" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "cthun" .. IMPF,
        Name = IJ_DB_RAID_AQ40_BOSS_NAME_15727,
        Story = IJ_DB_RAID_AQ40_BOSS_STORY_15727,
        MapCoordinateX = 33.3,
        MapCoordinateY = 49.1,
        MapId = IZI.AQ401,
        Loot = {
            [1] = {
                Id = "20929",
                Icon = "INV_Qiraj_CarapaceOldGod",
                Name = IJ_LOOT_NAME_20929,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, IMCL.Hunter, IMCL.Paladin, IMCL.Shaman, },
            },
            [2] = {
                Id = "20933",
                Icon = "INV_Qiraj_HuskOldGod",
                Name = IJ_LOOT_NAME_20933,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [3] = {
                Id = "21221",
                Icon = "Spell_Shadow_DetectInvisibility",
                Name = IJ_LOOT_NAME_21221,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "21126",
                Icon = "INV_Weapon_Shortblade_33",
                Name = IJ_LOOT_NAME_21126,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 8,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "21585",
                Icon = "INV_Gauntlets_17",
                Name = IJ_LOOT_NAME_21585,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "21586",
                Icon = "INV_Belt_26",
                Name = IJ_LOOT_NAME_21586,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "21596",
                Icon = "INV_Jewelry_Ring_AhnQiraj_06",
                Name = IJ_LOOT_NAME_21596,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "22730",
                Icon = "INV_Belt_12",
                Name = IJ_LOOT_NAME_22730,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "22731",
                Icon = "INV_Misc_Cape_18",
                Name = IJ_LOOT_NAME_22731,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 18,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "21134",
                Icon = "Inv_axe_25",
                Name = IJ_LOOT_NAME_21134,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 8,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "21581",
                Icon = "INV_Gauntlets_31",
                Name = IJ_LOOT_NAME_21581,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 21,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "21582",
                Icon = "INV_Belt_31",
                Name = IJ_LOOT_NAME_21582,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 21,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "21583",
                Icon = "INV_Misc_Cape_02",
                Name = IJ_LOOT_NAME_21583,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 21,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "21839",
                Icon = "INV_Mace22",
                Name = IJ_LOOT_NAME_21839,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 8,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "22732",
                Icon = "INV_Jewelry_Necklace_AhnQiraj_04",
                Name = IJ_LOOT_NAME_22732,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 21,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "36550",
                Icon = "Ability_Hunter_BeastCall",
                Name = IJ_LOOT_NAME_36550,
                Quality = IQ.Epic,
                ItemSlot = IS.Mount,
                DropChance = 1,
            },
            [17] = {
                Id = "21579",
                Icon = "INV_Misc_AhnQirajTrinket_05",
                Name = IJ_LOOT_NAME_21579,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 15,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "41077",
                Icon = "INV_Helmet_Illidari_01",
                Name = IJ_LOOT_NAME_41077,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 8,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "60003",
                Icon = "INV_WEAPON_HAND_07",
                Name = IJ_LOOT_NAME_60003,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.FistWeapon,
                DropChance = 8,
                LevelRequirement = 60,
            },
        },
    },
}

IJDB.R.AQ40 = AQ40
