IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPR = IJLib.MediaPathRaids
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "bwl\\"

local BWL = {}

BWL.Name = IJ_DB_RAID_BWL_NAME
BWL.Story = IJ_DB_RAID_BWL_STORY
BWL.Type = IJLib.InstanceType.Raid
BWL.Background = IMP .. IMPR .. instanceMediaAcronym .. "background"
BWL.GridBackground = IMP .. IMPR .. instanceMediaAcronym .. "grid-background"
BWL.MapId = IMI.BlackwingLair
BWL.IconScale = 1.0
BWL.MinLevel = 60
BWL.MaxLevel = 60
BWL.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.BlackrockMountain,
        MapCoordinateX = 64.1,
        MapCoordinateY = 71.7,
    },
}
BWL.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "12435",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "razorgore" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "razorgore" .. IMPF,
        Name = IJ_DB_RAID_BWL_BOSS_NAME_12435,
        Story = IJ_DB_RAID_BWL_BOSS_STORY_12435,
        MapCoordinateX = 54.1,
        MapCoordinateY = 72.5,
        MapIsBelow = true,
        Loot = {
            [1] = {
                Id = "16904",
                Icon = "INV_Bracer_03",
                Name = IJ_LOOT_NAME_16904,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Druid, },
            },
            [2] = {
                Id = "16911",
                Icon = "INV_Bracer_02",
                Name = IJ_LOOT_NAME_16911,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Rogue, },
            },
            [3] = {
                Id = "16918",
                Icon = "INV_Bracer_09",
                Name = IJ_LOOT_NAME_16918,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, },
            },
            [4] = {
                Id = "16926",
                Icon = "INV_Bracer_09",
                Name = IJ_LOOT_NAME_16926,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Priest, },
            },
            [5] = {
                Id = "16934",
                Icon = "INV_Bracer_07",
                Name = IJ_LOOT_NAME_16934,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warlock, },
            },
            [6] = {
                Id = "16935",
                Icon = "INV_Bracer_17",
                Name = IJ_LOOT_NAME_16935,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, },
            },
            [7] = {
                Id = "16943",
                Icon = "INV_Bracer_16",
                Name = IJ_LOOT_NAME_16943,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Shaman, },
            },
            [8] = {
                Id = "16951",
                Icon = "INV_Bracer_18",
                Name = IJ_LOOT_NAME_16951,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Paladin, },
            },
            [9] = {
                Id = "16959",
                Icon = "INV_Bracer_19",
                Name = IJ_LOOT_NAME_16959,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, },
            },
            [10] = {
                Id = "19334",
                Icon = "INV_Sword_50",
                Name = IJ_LOOT_NAME_19334,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "19335",
                Icon = "INV_Mace_06",
                Name = IJ_LOOT_NAME_19335,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "19336",
                Icon = "Spell_Nature_WispSplode",
                Name = IJ_LOOT_NAME_19336,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, },
            },
            [13] = {
                Id = "19337",
                Icon = "INV_Misc_Book_06",
                Name = IJ_LOOT_NAME_19337,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warlock, },
            },
            [14] = {
                Id = "19369",
                Icon = "INV_Gauntlets_06",
                Name = IJ_LOOT_NAME_19369,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "19370",
                Icon = "INV_Shoulder_25",
                Name = IJ_LOOT_NAME_19370,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
        },
    },
    [2] = { -- NOTE: Missing abilities
        Id = "13020",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "vaelastrasz" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "vaelastrasz" .. IMPF,
        Name = IJ_DB_RAID_BWL_BOSS_NAME_13020,
        Story = IJ_DB_RAID_BWL_BOSS_STORY_13020,
        MapCoordinateX = 46.5,
        MapCoordinateY = 47.0,
        MapIsBelow = true,
        Loot = {
            [1] = {
                Id = "16818",
                Icon = "INV_Belt_22",
                Name = IJ_LOOT_NAME_16818,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, },
            },
            [2] = {
                Id = "16903",
                Icon = "INV_Belt_06",
                Name = IJ_LOOT_NAME_16903,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Druid, },
            },
            [3] = {
                Id = "16910",
                Icon = "INV_Belt_23",
                Name = IJ_LOOT_NAME_16910,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Rogue, },
            },
            [4] = {
                Id = "16925",
                Icon = "INV_Belt_22",
                Name = IJ_LOOT_NAME_16925,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Priest, },
            },
            [5] = {
                Id = "16933",
                Icon = "INV_Belt_13",
                Name = IJ_LOOT_NAME_16933,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warlock, },
            },
            [6] = {
                Id = "16936",
                Icon = "INV_Belt_28",
                Name = IJ_LOOT_NAME_16936,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, },
            },
            [7] = {
                Id = "16944",
                Icon = "INV_Belt_14",
                Name = IJ_LOOT_NAME_16944,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Shaman, },
            },
            [8] = {
                Id = "16952",
                Icon = "INV_Belt_27",
                Name = IJ_LOOT_NAME_16952,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Paladin, },
            },
            [9] = {
                Id = "16960",
                Icon = "INV_Belt_09",
                Name = IJ_LOOT_NAME_16960,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, },
            },
            [10] = {
                Id = "19339",
                Icon = "Spell_Nature_WispHeal",
                Name = IJ_LOOT_NAME_19339,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, },
            },
            [11] = {
                Id = "19340",
                Icon = "INV_Misc_Rune_06",
                Name = IJ_LOOT_NAME_19340,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Druid, },
            },
            [12] = {
                Id = "19346",
                Icon = "INV_Weapon_Shortblade_29",
                Name = IJ_LOOT_NAME_19346,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "19348",
                Icon = "INV_Shield_20",
                Name = IJ_LOOT_NAME_19348,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "19371",
                Icon = "INV_Jewelry_Necklace_12",
                Name = IJ_LOOT_NAME_19371,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "19372",
                Icon = "INV_Helmet_10",
                Name = IJ_LOOT_NAME_19372,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 60,
            },
        },
    },
    [3] = { -- NOTE: Missing abilities
        Id = "12017",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "broodlord" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "broodlord" .. IMPF,
        Name = IJ_DB_RAID_BWL_BOSS_NAME_12017,
        Story = IJ_DB_RAID_BWL_BOSS_STORY_12017,
        MapCoordinateX = 52.0,
        MapCoordinateY = 66.3,
        Loot = {
            [1] = {
                Id = "20383",
                Icon = "Spell_Shadow_CurseOfTounges",
                Name = IJ_LOOT_NAME_20383,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
            },
            [2] = {
                Id = "16898",
                Icon = "INV_Boots_08",
                Name = IJ_LOOT_NAME_16898,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Druid, },
            },
            [3] = {
                Id = "16906",
                Icon = "INV_Boots_08",
                Name = IJ_LOOT_NAME_16906,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Rogue, },
            },
            [4] = {
                Id = "16912",
                Icon = "INV_Boots_07",
                Name = IJ_LOOT_NAME_16912,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, },
            },
            [5] = {
                Id = "16919",
                Icon = "INV_Boots_07",
                Name = IJ_LOOT_NAME_16919,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Priest, },
            },
            [6] = {
                Id = "16927",
                Icon = "INV_Boots_05",
                Name = IJ_LOOT_NAME_16927,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warlock, },
            },
            [7] = {
                Id = "16941",
                Icon = "INV_Boots_Plate_07",
                Name = IJ_LOOT_NAME_16941,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, },
            },
            [8] = {
                Id = "16949",
                Icon = "INV_Boots_Plate_06",
                Name = IJ_LOOT_NAME_16949,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Shaman, },
            },
            [9] = {
                Id = "16957",
                Icon = "INV_Boots_Plate_09",
                Name = IJ_LOOT_NAME_16957,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Paladin, },
            },
            [10] = {
                Id = "16965",
                Icon = "INV_Boots_Plate_04",
                Name = IJ_LOOT_NAME_16965,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, },
            },
            [11] = {
                Id = "19341",
                Icon = "INV_Misc_Gem_Pearl_05",
                Name = IJ_LOOT_NAME_19341,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, },
            },
            [12] = {
                Id = "19342",
                Icon = "INV_Misc_Idol_03",
                Name = IJ_LOOT_NAME_19342,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Rogue, },
            },
            [13] = {
                Id = "19350",
                Icon = "INV_Weapon_Bow_09",
                Name = IJ_LOOT_NAME_19350,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "19351",
                Icon = "INV_Sword_49",
                Name = IJ_LOOT_NAME_19351,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "19373",
                Icon = "INV_Shoulder_14",
                Name = IJ_LOOT_NAME_19373,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "19374",
                Icon = "INV_Bracer_07",
                Name = IJ_LOOT_NAME_19374,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
        },
    },
    [4] = { -- NOTE: Missing abilities
        Id = "11983",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "firemaw" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "firemaw" .. IMPF,
        Name = IJ_DB_RAID_BWL_BOSS_NAME_11983,
        Story = IJ_DB_RAID_BWL_BOSS_STORY_11983,
        MapCoordinateX = 44.3,
        MapCoordinateY = 42.1,
        Loot = {
            [1] = {
                Id = "19343",
                Icon = "INV_Scroll_08",
                Name = IJ_LOOT_NAME_19343,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 12,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Paladin, },
            },
            [2] = {
                Id = "19344",
                Icon = "INV_Misc_Gem_03",
                Name = IJ_LOOT_NAME_19344,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 12,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Shaman, },
            },
            [3] = {
                Id = "19365",
                Icon = "INV_Weapon_ShortBlade_27",
                Name = IJ_LOOT_NAME_19365,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.FistWeapon,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "19398",
                Icon = "INV_Misc_Cape_18",
                Name = IJ_LOOT_NAME_19398,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "19399",
                Icon = "INV_Chest_Cloth_50",
                Name = IJ_LOOT_NAME_19399,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "19400",
                Icon = "INV_Belt_10",
                Name = IJ_LOOT_NAME_19400,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "19401",
                Icon = "INV_Pants_Mail_19",
                Name = IJ_LOOT_NAME_19401,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "19402",
                Icon = "INV_Pants_Plate_16",
                Name = IJ_LOOT_NAME_19402,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "16899",
                Icon = "INV_Gauntlets_25",
                Name = IJ_LOOT_NAME_16899,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Druid, },
            },
            [10] = {
                Id = "16907",
                Icon = "INV_Gauntlets_21",
                Name = IJ_LOOT_NAME_16907,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Rogue, },
            },
            [11] = {
                Id = "16913",
                Icon = "INV_Gauntlets_14",
                Name = IJ_LOOT_NAME_16913,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, },
            },
            [12] = {
                Id = "16920",
                Icon = "INV_Gauntlets_14",
                Name = IJ_LOOT_NAME_16920,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Priest, },
            },
            [13] = {
                Id = "16928",
                Icon = "INV_Gauntlets_19",
                Name = IJ_LOOT_NAME_16928,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warlock, },
            },
            [14] = {
                Id = "16940",
                Icon = "INV_Gauntlets_10",
                Name = IJ_LOOT_NAME_16940,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, },
            },
            [15] = {
                Id = "16948",
                Icon = "INV_Gauntlets_11",
                Name = IJ_LOOT_NAME_16948,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Shaman, },
            },
            [16] = {
                Id = "16956",
                Icon = "INV_Gauntlets_29",
                Name = IJ_LOOT_NAME_16956,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Paladin, },
            },
            [17] = {
                Id = "16964",
                Icon = "INV_Gauntlets_10",
                Name = IJ_LOOT_NAME_16964,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, },
            },
            [18] = {
                Id = "19353",
                Icon = "INV_Axe_10",
                Name = IJ_LOOT_NAME_19353,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "19355",
                Icon = "INV_Staff_13",
                Name = IJ_LOOT_NAME_19355,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [20] = {
                Id = "19394",
                Icon = "INV_Shoulder_23",
                Name = IJ_LOOT_NAME_19394,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [21] = {
                Id = "19395",
                Icon = "INV_Misc_Gem_Topaz_02",
                Name = IJ_LOOT_NAME_19395,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [22] = {
                Id = "19396",
                Icon = "INV_Belt_16",
                Name = IJ_LOOT_NAME_19396,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [23] = {
                Id = "19397",
                Icon = "INV_Jewelry_Ring_43",
                Name = IJ_LOOT_NAME_19397,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 7,
                LevelRequirement = 60,
            },
        },
    },
    [5] = { -- NOTE: Missing abilities, Missing Loot
        Id = "ezzel",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "ezzel" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "ezzel" .. IMPF,
        Name = IJ_DB_RAID_BWL_BOSS_NAME_ezzel,
        Story = IJ_DB_RAID_BWL_BOSS_STORY_ezzel,
        MapCoordinateX = 16.8,
        MapCoordinateY = 55.8,
        Loot = {
            [1] = {
                Id = "33073",
                Icon = "Spell_Shadow_GrimWard",
                Name = IJ_LOOT_NAME_33073,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "33074",
                Icon = "INV_Boots_Chain_09",
                Name = IJ_LOOT_NAME_33074,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "33075",
                Icon = "INV_Potion_11",
                Name = IJ_LOOT_NAME_33075,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "33076",
                Icon = "INV_Staff_23",
                Name = IJ_LOOT_NAME_33076,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "33077",
                Icon = "INV_Shirt_15",
                Name = IJ_LOOT_NAME_33077,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "33078",
                Icon = "INV_Potion_06",
                Name = IJ_LOOT_NAME_33078,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.ThrownWeapon,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "33079",
                Icon = "INV_Misc_Orb_03",
                Name = IJ_LOOT_NAME_33079,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "33080",
                Icon = "INV_Bracer_18",
                Name = IJ_LOOT_NAME_33080,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "33081",
                Icon = "INV_Potion_62",
                Name = IJ_LOOT_NAME_33081,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "33086",
                Icon = "INV_Misc_Book_01",
                Name = IJ_LOOT_NAME_33086,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Libram,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "33087",
                Icon = "INV_Misc_Book_07",
                Name = IJ_LOOT_NAME_33087,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Libram,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "33083",
                Icon = "elementium_sharpening_stone_1",
                Name = IJ_LOOT_NAME_33083,
                Quality = IQ.Epic,
                ItemSlot = IS.Enchantment,
                ItemType = IT.Blacksmithing,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "33084",
                Icon = "pristine_chromatic_scale_1",
                Name = IJ_LOOT_NAME_33084,
                Quality = IQ.Epic,
                ItemSlot = IS.Enchantment,
                ItemType = IT.Leatherworking,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "33085",
                Icon = "over-tinkered_lens_3",
                Name = IJ_LOOT_NAME_33085,
                Quality = IQ.Epic,
                ItemSlot = IS.Enchantment,
                ItemType = IT.Engineering,
                DropChance = 7,
                LevelRequirement = 60,
            },
        },
    },
    [6] = { -- NOTE: Missing abilities
        Id = "14601",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "ebonroc" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "ebonroc" .. IMPF,
        Name = IJ_DB_RAID_BWL_BOSS_NAME_14601,
        Story = IJ_DB_RAID_BWL_BOSS_STORY_14601,
        MapCoordinateX = 38.4,
        MapCoordinateY = 32.0,
        Loot = {
            [1] = {
                Id = "16899",
                Icon = "INV_Gauntlets_25",
                Name = IJ_LOOT_NAME_16899,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Druid, },
            },
            [2] = {
                Id = "16907",
                Icon = "INV_Gauntlets_21",
                Name = IJ_LOOT_NAME_16907,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Rogue, },
            },
            [3] = {
                Id = "16913",
                Icon = "INV_Gauntlets_14",
                Name = IJ_LOOT_NAME_16913,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, },
            },
            [4] = {
                Id = "16920",
                Icon = "INV_Gauntlets_14",
                Name = IJ_LOOT_NAME_16920,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Priest, },
            },
            [5] = {
                Id = "16928",
                Icon = "INV_Gauntlets_19",
                Name = IJ_LOOT_NAME_16928,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warlock, },
            },
            [6] = {
                Id = "16940",
                Icon = "INV_Gauntlets_10",
                Name = IJ_LOOT_NAME_16940,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, },
            },
            [7] = {
                Id = "16948",
                Icon = "INV_Gauntlets_11",
                Name = IJ_LOOT_NAME_16948,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Shaman, },
            },
            [8] = {
                Id = "16956",
                Icon = "INV_Gauntlets_29",
                Name = IJ_LOOT_NAME_16956,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Paladin, },
            },
            [9] = {
                Id = "16964",
                Icon = "INV_Gauntlets_10",
                Name = IJ_LOOT_NAME_16964,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, },
            },
            [10] = {
                Id = "19353",
                Icon = "INV_Axe_10",
                Name = IJ_LOOT_NAME_19353,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "19355",
                Icon = "INV_Staff_13",
                Name = IJ_LOOT_NAME_19355,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "19394",
                Icon = "INV_Shoulder_23",
                Name = IJ_LOOT_NAME_19394,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "19395",
                Icon = "INV_Misc_Gem_Topaz_02",
                Name = IJ_LOOT_NAME_19395,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "19396",
                Icon = "INV_Belt_16",
                Name = IJ_LOOT_NAME_19396,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "19397",
                Icon = "INV_Jewelry_Ring_43",
                Name = IJ_LOOT_NAME_19397,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "19345",
                Icon = "Spell_Holy_BlessingOfProtection",
                Name = IJ_LOOT_NAME_19345,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 17,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Priest, },
            },
            [17] = {
                Id = "19368",
                Icon = "INV_Weapon_Rifle_02",
                Name = IJ_LOOT_NAME_19368,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Gun,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "19403",
                Icon = "INV_Jewelry_Ring_34",
                Name = IJ_LOOT_NAME_19403,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "19405",
                Icon = "INV_Chest_Leather_08",
                Name = IJ_LOOT_NAME_19405,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [20] = {
                Id = "19406",
                Icon = "INV_Misc_Bone_06",
                Name = IJ_LOOT_NAME_19406,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [21] = {
                Id = "19407",
                Icon = "INV_Gauntlets_27",
                Name = IJ_LOOT_NAME_19407,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
        },
    },
    [7] = { -- NOTE: Missing abilities
        Id = "11981",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "flamegor" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "flamegor" .. IMPF,
        Name = IJ_DB_RAID_BWL_BOSS_NAME_11981,
        Story = IJ_DB_RAID_BWL_BOSS_STORY_11981,
        MapCoordinateX = 45.7,
        MapCoordinateY = 22.2,
        Loot = {
            [1] = {
                Id = "19357",
                Icon = "INV_Mace_05",
                Name = IJ_LOOT_NAME_19357,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "19367",
                Icon = "INV_Wand_11",
                Name = IJ_LOOT_NAME_19367,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "19430",
                Icon = "INV_Misc_Cape_16",
                Name = IJ_LOOT_NAME_19430,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "19431",
                Icon = "INV_Misc_ArmorKit_10",
                Name = IJ_LOOT_NAME_19431,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "19432",
                Icon = "INV_Jewelry_Ring_37",
                Name = IJ_LOOT_NAME_19432,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "19433",
                Icon = "INV_Pants_Mail_17",
                Name = IJ_LOOT_NAME_19433,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "16899",
                Icon = "INV_Gauntlets_25",
                Name = IJ_LOOT_NAME_16899,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Druid, },
            },
            [8] = {
                Id = "16907",
                Icon = "INV_Gauntlets_21",
                Name = IJ_LOOT_NAME_16907,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Rogue, },
            },
            [9] = {
                Id = "16913",
                Icon = "INV_Gauntlets_14",
                Name = IJ_LOOT_NAME_16913,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, },
            },
            [10] = {
                Id = "16920",
                Icon = "INV_Gauntlets_14",
                Name = IJ_LOOT_NAME_16920,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Priest, },
            },
            [11] = {
                Id = "16928",
                Icon = "INV_Gauntlets_19",
                Name = IJ_LOOT_NAME_16928,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warlock, },
            },
            [12] = {
                Id = "16940",
                Icon = "INV_Gauntlets_10",
                Name = IJ_LOOT_NAME_16940,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, },
            },
            [13] = {
                Id = "16948",
                Icon = "INV_Gauntlets_11",
                Name = IJ_LOOT_NAME_16948,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Shaman, },
            },
            [14] = {
                Id = "16956",
                Icon = "INV_Gauntlets_29",
                Name = IJ_LOOT_NAME_16956,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Paladin, },
            },
            [15] = {
                Id = "16964",
                Icon = "INV_Gauntlets_10",
                Name = IJ_LOOT_NAME_16964,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, },
            },
            [16] = {
                Id = "19353",
                Icon = "INV_Axe_10",
                Name = IJ_LOOT_NAME_19353,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "19355",
                Icon = "INV_Staff_13",
                Name = IJ_LOOT_NAME_19355,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "19394",
                Icon = "INV_Shoulder_23",
                Name = IJ_LOOT_NAME_19394,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "19395",
                Icon = "INV_Misc_Gem_Topaz_02",
                Name = IJ_LOOT_NAME_19395,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [20] = {
                Id = "19396",
                Icon = "INV_Belt_16",
                Name = IJ_LOOT_NAME_19396,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 7,
                LevelRequirement = 60,
            },
            [21] = {
                Id = "19397",
                Icon = "INV_Jewelry_Ring_43",
                Name = IJ_LOOT_NAME_19397,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 7,
                LevelRequirement = 60,
            },
        },
    },
    [8] = { -- NOTE: Missing abilities
        Id = "14020",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "chromaggus" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "chromaggus" .. IMPF,
        Name = IJ_DB_RAID_BWL_BOSS_NAME_14020,
        Story = IJ_DB_RAID_BWL_BOSS_STORY_14020,
        MapCoordinateX = 49.4,
        MapCoordinateY = 52.0,
        Loot = {
            [1] = {
                Id = "16832",
                Icon = "INV_Shoulder_23",
                Name = IJ_LOOT_NAME_16832,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Rogue, },
            },
            [2] = {
                Id = "16902",
                Icon = "INV_Shoulder_07",
                Name = IJ_LOOT_NAME_16902,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Druid, },
            },
            [3] = {
                Id = "16917",
                Icon = "INV_Shoulder_32",
                Name = IJ_LOOT_NAME_16917,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, },
            },
            [4] = {
                Id = "16924",
                Icon = "INV_Shoulder_02",
                Name = IJ_LOOT_NAME_16924,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Priest, },
            },
            [5] = {
                Id = "16932",
                Icon = "INV_Shoulder_19",
                Name = IJ_LOOT_NAME_16932,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warlock, },
            },
            [6] = {
                Id = "16937",
                Icon = "INV_Shoulder_10",
                Name = IJ_LOOT_NAME_16937,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, },
            },
            [7] = {
                Id = "16945",
                Icon = "INV_Shoulder_33",
                Name = IJ_LOOT_NAME_16945,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Shaman, },
            },
            [8] = {
                Id = "16953",
                Icon = "INV_Shoulder_37",
                Name = IJ_LOOT_NAME_16953,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Paladin, },
            },
            [9] = {
                Id = "16961",
                Icon = "INV_Shoulder_34",
                Name = IJ_LOOT_NAME_16961,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, },
            },
            [10] = {
                Id = "19349",
                Icon = "INV_Shield_17",
                Name = IJ_LOOT_NAME_19349,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "19352",
                Icon = "INV_Sword_51",
                Name = IJ_LOOT_NAME_19352,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "19385",
                Icon = "INV_Pants_Cloth_19",
                Name = IJ_LOOT_NAME_19385,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "19387",
                Icon = "INV_Boots_Plate_04",
                Name = IJ_LOOT_NAME_19387,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "19388",
                Icon = "INV_Belt_13",
                Name = IJ_LOOT_NAME_19388,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "19389",
                Icon = "INV_Shoulder_08",
                Name = IJ_LOOT_NAME_19389,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "19347",
                Icon = "INV_Weapon_Shortblade_28",
                Name = IJ_LOOT_NAME_19347,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "19361",
                Icon = "INV_Weapon_Crossbow_09",
                Name = IJ_LOOT_NAME_19361,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Crossbow,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "19386",
                Icon = "INV_Misc_Cape_01",
                Name = IJ_LOOT_NAME_19386,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 16,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "19390",
                Icon = "INV_Gauntlets_19",
                Name = IJ_LOOT_NAME_19390,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 16,
                LevelRequirement = 60,
            },
            [20] = {
                Id = "19391",
                Icon = "INV_Boots_Cloth_01",
                Name = IJ_LOOT_NAME_19391,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 16,
                LevelRequirement = 60,
            },
            [21] = {
                Id = "19392",
                Icon = "INV_Belt_11",
                Name = IJ_LOOT_NAME_19392,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 16,
                LevelRequirement = 60,
            },
            [22] = {
                Id = "19393",
                Icon = "INV_Belt_21",
                Name = IJ_LOOT_NAME_19393,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 16,
                LevelRequirement = 60,
            },
        },
    },
    [9] = { -- NOTE: Missing abilities
        Id = "11583",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "nefarian" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "nefarian" .. IMPF,
        Name = IJ_DB_RAID_BWL_BOSS_NAME_11583,
        Story = IJ_DB_RAID_BWL_BOSS_STORY_11583,
        MapCoordinateX = 75.4,
        MapCoordinateY = 52.1,
        Loot = {
            [1] = {
                Id = "19003",
                Icon = "INV_Misc_Head_Dragon_Black",
                Name = IJ_LOOT_NAME_19003,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "16897",
                Icon = "INV_Chest_Chain_16",
                Name = IJ_LOOT_NAME_16897,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Druid, },
            },
            [3] = {
                Id = "16905",
                Icon = "INV_Chest_Cloth_07",
                Name = IJ_LOOT_NAME_16905,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Rogue, },
            },
            [4] = {
                Id = "16916",
                Icon = "INV_Chest_Cloth_03",
                Name = IJ_LOOT_NAME_16916,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, },
            },
            [5] = {
                Id = "16923",
                Icon = "INV_Chest_Cloth_03",
                Name = IJ_LOOT_NAME_16923,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Priest, },
            },
            [6] = {
                Id = "16931",
                Icon = "INV_Chest_Leather_01",
                Name = IJ_LOOT_NAME_16931,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warlock, },
            },
            [7] = {
                Id = "16942",
                Icon = "INV_Chest_Chain_03",
                Name = IJ_LOOT_NAME_16942,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, },
            },
            [8] = {
                Id = "16950",
                Icon = "INV_Chest_Chain_11",
                Name = IJ_LOOT_NAME_16950,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Shaman, },
            },
            [9] = {
                Id = "16958",
                Icon = "INV_Chest_Plate03",
                Name = IJ_LOOT_NAME_16958,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Paladin, },
            },
            [10] = {
                Id = "16966",
                Icon = "INV_Chest_Plate16",
                Name = IJ_LOOT_NAME_16966,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, },
            },
            [11] = {
                Id = "19360",
                Icon = "INV_Mace_06",
                Name = IJ_LOOT_NAME_19360,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "19363",
                Icon = "INV_Axe_12",
                Name = IJ_LOOT_NAME_19363,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Axe,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "19375",
                Icon = "INV_Helmet_52",
                Name = IJ_LOOT_NAME_19375,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "19376",
                Icon = "INV_Jewelry_Ring_40",
                Name = IJ_LOOT_NAME_19376,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "19377",
                Icon = "INV_Jewelry_Necklace_17",
                Name = IJ_LOOT_NAME_19377,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "19378",
                Icon = "INV_Misc_Cape_20",
                Name = IJ_LOOT_NAME_19378,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "19356",
                Icon = "INV_Staff_06",
                Name = IJ_LOOT_NAME_19356,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "19364",
                Icon = "INV_Sword_50",
                Name = IJ_LOOT_NAME_19364,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "19379",
                Icon = "INV_Stone_15",
                Name = IJ_LOOT_NAME_19379,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [20] = {
                Id = "19380",
                Icon = "INV_Belt_18",
                Name = IJ_LOOT_NAME_19380,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [21] = {
                Id = "19381",
                Icon = "INV_Boots_Cloth_05",
                Name = IJ_LOOT_NAME_19381,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [22] = {
                Id = "19382",
                Icon = "INV_Jewelry_Ring_42",
                Name = IJ_LOOT_NAME_19382,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [23] = {
                Id = "36551",
                Icon = "Ability_Hunter_BeastCall",
                Name = IJ_LOOT_NAME_36551,
                Quality = IQ.Epic,
                ItemSlot = IS.Mount,
                DropChance = 1,
            },
        },
    },
}

IJDB.R.BWL = BWL
