IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPR = IJLib.MediaPathRaids
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "es\\"

local ES = {}

ES.Name = IJ_DB_RAID_ES_NAME
ES.Story = IJ_DB_RAID_ES_STORY
ES.Type = IJLib.InstanceType.Raid
ES.Background = IMP .. IMPR .. instanceMediaAcronym .. "background"
ES.GridBackground = IMP .. IMPR .. instanceMediaAcronym .. "grid-background"
ES.MapId = IMI.EmeraldSanctum
ES.IconScale = 1.0
ES.MinLevel = 60
ES.MaxLevel = 60
ES.Entrances = {
    [1] = {
        MapContinentId = IMI.Kalimdor,
        MapZoneId = IZI.Hyjal,
        MapCoordinateX = 20.6,
        MapCoordinateY = 60.6,
    },
}
ES.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "60747",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "erennius" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "erennius" .. IMPF,
        Name = IJ_DB_RAID_ES_BOSS_NAME_60747,
        Story = IJ_DB_RAID_ES_BOSS_STORY_60747,
        MapCoordinateX = 67.3,
        MapCoordinateY = 39.3,
        Loot = {
            [1] = {
                Id = "61652",
                Icon = "INV_Misc_MonsterClaw_02",
                Name = IJ_LOOT_NAME_61652,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
            },
        },
    },
    [2] = { -- NOTE: Missing abilities
        Id = "60748",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "solnius" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "solnius" .. IMPF,
        Name = IJ_DB_RAID_ES_BOSS_NAME_60748,
        Story = IJ_DB_RAID_ES_BOSS_STORY_60748,
        MapCoordinateX = 70.4,
        MapCoordinateY = 23.2,
        Loot = {
            [1] = {
                Id = "30018",
                Icon = "INV_Misc_Head_Dragon_Green",
                Name = IJ_LOOT_NAME_30018,
                Quality = IQ.Epic,
                ItemSlot = IS.Mount,
                DropChance = 2,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "61205",
                Icon = "INV_Jewelry_Ring_37",
                Name = IJ_LOOT_NAME_61205,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "61206",
                Icon = "inv_chest_leather_06",
                Name = IJ_LOOT_NAME_61206,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "61208",
                Icon = "INV_Staff_49",
                Name = IJ_LOOT_NAME_61208,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "61209",
                Icon = "INV_Enchant_EssenceMysticalLarge",
                Name = IJ_LOOT_NAME_61209,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "61211",
                Icon = "INV_Boots_Fabric_01",
                Name = IJ_LOOT_NAME_61211,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "61214",
                Icon = "inv_shoulder_13",
                Name = IJ_LOOT_NAME_61214,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "61207",
                Icon = "INV_Helmet_02",
                Name = IJ_LOOT_NAME_61207,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "61210",
                Icon = "INV_Misc_Cape_01",
                Name = IJ_LOOT_NAME_61210,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "61212",
                Icon = "INV_Bracer_09",
                Name = IJ_LOOT_NAME_61212,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "61213",
                Icon = "INV_Gauntlets_29",
                Name = IJ_LOOT_NAME_61213,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "61239",
                Icon = "INV_Pants_03",
                Name = IJ_LOOT_NAME_61239,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "61448",
                Icon = "INV_Weapon_Halberd_05",
                Name = IJ_LOOT_NAME_61448,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Axe,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "41076",
                Icon = "INV_Mace_09",
                Name = IJ_LOOT_NAME_41076,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "61203",
                Icon = "INV_Relics_LibramofGrace",
                Name = IJ_LOOT_NAME_61203,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Libram,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "61204",
                Icon = "Spell_Nature_StoneSkinTotem",
                Name = IJ_LOOT_NAME_61204,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Totem,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "61237",
                Icon = "INV_Mace_35",
                Name = IJ_LOOT_NAME_61237,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "61238",
                Icon = "INV_Shield_23",
                Name = IJ_LOOT_NAME_61238,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "61455",
                Icon = "Spell_Nature_NatureTouchDecay",
                Name = IJ_LOOT_NAME_61455,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Idol,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [20] = {
                Id = "51361",
                Icon = "INV_Misc_Note_05",
                Name = IJ_LOOT_NAME_51361,
                Quality = IQ.Rare,
                ItemSlot = IS.Ability,
                DropChance = 15,
                ClassRestriction = { IMCL.Druid, },
            },
            [21] = {
                Id = "61196",
                Icon = "INV_Misc_Bag_18",
                Name = IJ_LOOT_NAME_61196,
                Quality = IQ.Rare,
                ItemSlot = IS.Bag,
                DropChance = 25,
            },
            [22] = {
                Id = "61215",
                Icon = "inv_misc_head_dragon_green",
                Name = IJ_LOOT_NAME_61215,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
            },
            [23] = {
                Id = "61217",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61217,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 4,
            },
            [24] = {
                Id = "61218",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61218,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 4,
            },
            [25] = {
                Id = "61424",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61424,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Leatherworking,
                DropChance = 4,
            },
            [26] = {
                Id = "61428",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61428,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Leatherworking,
                DropChance = 4,
            },
            [27] = {
                Id = "61432",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61432,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Leatherworking,
                DropChance = 4,
            },
            [28] = {
                Id = "70000",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_70000,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 4,
            },
            [29] = {
                Id = "61444",
                Icon = "INV_Stone_05",
                Name = IJ_LOOT_NAME_61444,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 35,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Druid, },
            },
            [30] = {
                Id = "61733",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61733,
                Quality = IQ.Legendary,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 2,
            },
            [31] = {
                Id = "61522",
                Icon = "INV_Jewelry_Necklace_01",
                Name = IJ_LOOT_NAME_61522,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 17,
                LevelRequirement = 60,
                IsHardMode = true,
            },
            [32] = {
                Id = "61523",
                Icon = "inv_sword_38",
                Name = IJ_LOOT_NAME_61523,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 17,
                LevelRequirement = 60,
                IsHardMode = true,
            },
            [33] = {
                Id = "61524",
                Icon = "INV_Chest_Plate07",
                Name = IJ_LOOT_NAME_61524,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
                IsHardMode = true,
            },
            [34] = {
                Id = "61525",
                Icon = "INV_Weapon_Bow_04",
                Name = IJ_LOOT_NAME_61525,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 17,
                LevelRequirement = 60,
                IsHardMode = true,
            },
            [35] = {
                Id = "61526",
                Icon = "INV_Shield_21",
                Name = IJ_LOOT_NAME_61526,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 17,
                LevelRequirement = 60,
                IsHardMode = true,
            },
            [36] = {
                Id = "61527",
                Icon = "BTNOrbofChaos",
                Name = IJ_LOOT_NAME_61527,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 17,
                LevelRequirement = 60,
                IsHardMode = true,
            },
        },
    },
}

IJDB.R.ES = ES
