IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPR = IJLib.MediaPathRaids
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "kara10\\"

local KARA10 = {}

KARA10.Name = IJ_DB_RAID_KARA10_NAME
KARA10.Story = IJ_DB_RAID_KARA10_STORY
KARA10.Type = IJLib.InstanceType.Raid
KARA10.Background = IMP .. IMPR .. instanceMediaAcronym .. "background"
KARA10.GridBackground = IMP .. IMPR .. instanceMediaAcronym .. "grid-background"
KARA10.MapId = IMI.LowerKarazhanHalls
KARA10.IconScale = 1.0
KARA10.MinLevel = 60
KARA10.MaxLevel = 60
KARA10.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.DeadwindPass,
        MapCoordinateX = 43.6,
        MapCoordinateY = 75.6,
    },
}
KARA10.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "61319",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "rolfen" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "rolfen" .. IMPF,
        Name = IJ_DB_RAID_KARA10_BOSS_NAME_61319,
        Story = IJ_DB_RAID_KARA10_BOSS_STORY_61319,
        MapCoordinateX = 60.8,
        MapCoordinateY = 82.5,
        MapIsBelow = true,
        Loot = {
            [1] = {
                Id = "61805",
                Icon = "INV_Scroll_04",
                Name = IJ_LOOT_NAME_61805,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 1,
            },
            [2] = {
                Id = "61806",
                Icon = "INV_Scroll_04",
                Name = IJ_LOOT_NAME_61806,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 1,
            },
            [3] = {
                Id = "61807",
                Icon = "INV_Scroll_04",
                Name = IJ_LOOT_NAME_61807,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 1,
            },
            [4] = {
                Id = "61808",
                Icon = "INV_Scroll_04",
                Name = IJ_LOOT_NAME_61808,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 1,
            },
        },
    },
    [2] = { -- NOTE: Missing abilities
        Id = "61221",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "araxxna" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "araxxna" .. IMPF,
        Name = IJ_DB_RAID_KARA10_BOSS_NAME_61221,
        Story = IJ_DB_RAID_KARA10_BOSS_STORY_61221,
        MapCoordinateX = 82.6,
        MapCoordinateY = 25.3,
        MapIsBelow = true,
        Loot = {
            [1] = {
                Id = "8547",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_8547,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.FirstAid,
                DropChance = 1,
            },
            [2] = {
                Id = "13517",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_13517,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 1,
            },
            [3] = {
                Id = "58401",
                Icon = "INV_Scroll_06",
                Name = IJ_LOOT_NAME_58401,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Engineering,
                DropChance = 1,
            },
            [4] = {
                Id = "61177",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61177,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 1,
            },
            [5] = {
                Id = "61178",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61178,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 1,
            },
            [6] = {
                Id = "61180",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61180,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [7] = {
                Id = "61189",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61189,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 1,
            },
            [8] = {
                Id = "61190",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61190,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Tailoring,
                DropChance = 1,
            },
            [9] = {
                Id = "61191",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61191,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Engineering,
                DropChance = 1,
            },
            [10] = {
                Id = "61192",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61192,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Leatherworking,
                DropChance = 1,
            },
            [11] = {
                Id = "61219",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61219,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [12] = {
                Id = "61739",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61739,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [13] = {
                Id = "70001",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_70001,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [14] = {
                Id = "37011",
                Icon = "INV_Misc_MonsterSpiderCarapace_01",
                Name = IJ_LOOT_NAME_37011,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Pet,
                DropChance = 20,
            },
            [15] = {
                Id = "51217",
                Icon = "INV_Misc_Ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [16] = {
                Id = "58275",
                Icon = "INV_Misc_Book_10",
                Name = IJ_LOOT_NAME_58275,
                Quality = IQ.Rare,
                ItemSlot = IS.Ability,
                DropChance = 100,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Rogue, },
            },
            [17] = {
                Id = "61243",
                Icon = "INV_Potion_97",
                Name = IJ_LOOT_NAME_61243,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "61260",
                Icon = "INV_Helmet_34",
                Name = IJ_LOOT_NAME_61260,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "61268",
                Icon = "Spell_Nature_Crystalball",
                Name = IJ_LOOT_NAME_61268,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [20] = {
                Id = "61270",
                Icon = "BTNEmeraldNecklace",
                Name = IJ_LOOT_NAME_61270,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [21] = {
                Id = "61297",
                Icon = "inv_boots_cloth_04",
                Name = IJ_LOOT_NAME_61297,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [22] = {
                Id = "61244",
                Icon = "inv_pants_plate_03",
                Name = IJ_LOOT_NAME_61244,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [23] = {
                Id = "61245",
                Icon = "INV_Bracer_12",
                Name = IJ_LOOT_NAME_61245,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [24] = {
                Id = "61269",
                Icon = "INV_Chest_Cloth_01",
                Name = IJ_LOOT_NAME_61269,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [25] = {
                Id = "61272",
                Icon = "inv_boots_chain_10",
                Name = IJ_LOOT_NAME_61272,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [26] = {
                Id = "61278",
                Icon = "INV_Weapon_ShortBlade_25",
                Name = IJ_LOOT_NAME_61278,
                Quality = IQ.Rare,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [27] = {
                Id = "61283",
                Icon = "Inv_gauntlets_09",
                Name = IJ_LOOT_NAME_61283,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [28] = {
                Id = "61816",
                Icon = "INV_Shield_21",
                Name = IJ_LOOT_NAME_61816,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [29] = {
                Id = "70102",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_70102,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Jewelcrafting,
                DropChance = 1,
            },
        },
    },
    [3] = { -- NOTE: Missing abilities
        Id = "61224",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "grizikil" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "grizikil" .. IMPF,
        Name = IJ_DB_RAID_KARA10_BOSS_NAME_61224,
        Story = IJ_DB_RAID_KARA10_BOSS_STORY_61224,
        MapCoordinateX = 90.6,
        MapCoordinateY = 38.6,
        Loot = {
            [1] = {
                Id = "8547",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_8547,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.FirstAid,
                DropChance = 1,
            },
            [2] = {
                Id = "13517",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_13517,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 1,
            },
            [3] = {
                Id = "58401",
                Icon = "INV_Scroll_06",
                Name = IJ_LOOT_NAME_58401,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Engineering,
                DropChance = 1,
            },
            [4] = {
                Id = "61177",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61177,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 1,
            },
            [5] = {
                Id = "61178",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61178,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 1,
            },
            [6] = {
                Id = "61180",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61180,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [7] = {
                Id = "61189",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61189,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 1,
            },
            [8] = {
                Id = "61190",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61190,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Tailoring,
                DropChance = 1,
            },
            [9] = {
                Id = "61191",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61191,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Engineering,
                DropChance = 1,
            },
            [10] = {
                Id = "61192",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61192,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Leatherworking,
                DropChance = 1,
            },
            [11] = {
                Id = "61219",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61219,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [12] = {
                Id = "61739",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61739,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [13] = {
                Id = "70001",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_70001,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [14] = {
                Id = "51217",
                Icon = "INV_Misc_Ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [15] = {
                Id = "61251",
                Icon = "BTNRingJadeFalcon",
                Name = IJ_LOOT_NAME_61251,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "61253",
                Icon = "inv_gauntlets_30",
                Name = IJ_LOOT_NAME_61253,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "61276",
                Icon = "spell_arcane_portaldarnassus",
                Name = IJ_LOOT_NAME_61276,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "61291",
                Icon = "INV_Helmet_10",
                Name = IJ_LOOT_NAME_61291,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "61292",
                Icon = "INV_Staff_07",
                Name = IJ_LOOT_NAME_61292,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Totem,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [20] = {
                Id = "61252",
                Icon = "inv_helmet_52",
                Name = IJ_LOOT_NAME_61252,
                Quality = IQ.Rare,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [21] = {
                Id = "61261",
                Icon = "INV_Misc_Cape_18",
                Name = IJ_LOOT_NAME_61261,
                Quality = IQ.Rare,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [22] = {
                Id = "61267",
                Icon = "inv_gauntlets_26",
                Name = IJ_LOOT_NAME_61267,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [23] = {
                Id = "61288",
                Icon = "INV_Belt_15",
                Name = IJ_LOOT_NAME_61288,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [24] = {
                Id = "61289",
                Icon = "INV_Boots_Plate_03",
                Name = IJ_LOOT_NAME_61289,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [25] = {
                Id = "61298",
                Icon = "inv_gauntlets_21",
                Name = IJ_LOOT_NAME_61298,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [26] = {
                Id = "61450",
                Icon = "INV_Misc_Key_09",
                Name = IJ_LOOT_NAME_61450,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [27] = {
                Id = "70102",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_70102,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Jewelcrafting,
                DropChance = 1,
            },
        },
    },
    [4] = { -- NOTE: Missing abilities
        Id = "61223",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "clawlord" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "clawlord" .. IMPF,
        Name = IJ_DB_RAID_KARA10_BOSS_NAME_61223,
        Story = IJ_DB_RAID_KARA10_BOSS_STORY_61223,
        MapCoordinateX = 69.1,
        MapCoordinateY = 55.5,
        Loot = {
            [1] = {
                Id = "8547",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_8547,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.FirstAid,
                DropChance = 1,
            },
            [2] = {
                Id = "13517",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_13517,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 1,
            },
            [3] = {
                Id = "58401",
                Icon = "INV_Scroll_06",
                Name = IJ_LOOT_NAME_58401,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Engineering,
                DropChance = 1,
            },
            [4] = {
                Id = "61177",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61177,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 1,
            },
            [5] = {
                Id = "61178",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61178,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 1,
            },
            [6] = {
                Id = "61180",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61180,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [7] = {
                Id = "61189",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61189,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 1,
            },
            [8] = {
                Id = "61190",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61190,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Tailoring,
                DropChance = 1,
            },
            [9] = {
                Id = "61191",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61191,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Engineering,
                DropChance = 1,
            },
            [10] = {
                Id = "61192",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61192,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Leatherworking,
                DropChance = 1,
            },
            [11] = {
                Id = "61219",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61219,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [12] = {
                Id = "61739",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61739,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [13] = {
                Id = "70001",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_70001,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [14] = {
                Id = "51217",
                Icon = "INV_Misc_Ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [15] = {
                Id = "55552",
                Icon = "INV_Misc_Book_02",
                Name = IJ_LOOT_NAME_55552,
                Quality = IQ.Rare,
                ItemSlot = IS.Ability,
                DropChance = 100,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, },
            },
            [16] = {
                Id = "61248",
                Icon = "INV_Weapon_Rifle_TWoW_02_Gray",
                Name = IJ_LOOT_NAME_61248,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Gun,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "61249",
                Icon = "INV_Misc_Pelt_Bear_Ruin_03",
                Name = IJ_LOOT_NAME_61249,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "61273",
                Icon = "INV_Belt_26",
                Name = IJ_LOOT_NAME_61273,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "61281",
                Icon = "inv_boots_cloth_09",
                Name = IJ_LOOT_NAME_61281,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [20] = {
                Id = "61293",
                Icon = "INV_QirajIdol_Night",
                Name = IJ_LOOT_NAME_61293,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Idol,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [21] = {
                Id = "61250",
                Icon = "inv_shirt_06",
                Name = IJ_LOOT_NAME_61250,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [22] = {
                Id = "61263",
                Icon = "INV_Misc_MonsterFang_01",
                Name = IJ_LOOT_NAME_61263,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [23] = {
                Id = "61271",
                Icon = "INV_Boots_07",
                Name = IJ_LOOT_NAME_61271,
                Quality = IQ.Rare,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [24] = {
                Id = "61274",
                Icon = "INV_Gauntlets_24",
                Name = IJ_LOOT_NAME_61274,
                Quality = IQ.Rare,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [25] = {
                Id = "61285",
                Icon = "inv_pants_cloth_05",
                Name = IJ_LOOT_NAME_61285,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [26] = {
                Id = "61290",
                Icon = "INV_Belt_32",
                Name = IJ_LOOT_NAME_61290,
                Quality = IQ.Rare,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [27] = {
                Id = "61451",
                Icon = "INV_Enchant_EssenceEternalSmall",
                Name = IJ_LOOT_NAME_61451,
                Quality = IQ.Rare,
                ItemSlot = IS.Trinket,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [28] = {
                Id = "70102",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_70102,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Jewelcrafting,
                DropChance = 1,
            },
            [29] = {
                Id = "70226",
                Icon = "INV_Misc_Bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 3,
            },
        },
    },
    [5] = { -- NOTE: Missing abilities
        Id = "61222",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "blackwald" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "blackwald" .. IMPF,
        Name = IJ_DB_RAID_KARA10_BOSS_NAME_61222,
        Story = IJ_DB_RAID_KARA10_BOSS_STORY_61222,
        MapCoordinateX = 69.1,
        MapCoordinateY = 74.3,
        Loot = {
            [1] = {
                Id = "8547",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_8547,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.FirstAid,
                DropChance = 1,
            },
            [2] = {
                Id = "13517",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_13517,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 1,
            },
            [3] = {
                Id = "58401",
                Icon = "INV_Scroll_06",
                Name = IJ_LOOT_NAME_58401,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Engineering,
                DropChance = 1,
            },
            [4] = {
                Id = "61177",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61177,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 1,
            },
            [5] = {
                Id = "61178",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61178,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 1,
            },
            [6] = {
                Id = "61180",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61180,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [7] = {
                Id = "61189",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61189,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 1,
            },
            [8] = {
                Id = "61190",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61190,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Tailoring,
                DropChance = 1,
            },
            [9] = {
                Id = "61191",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61191,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Engineering,
                DropChance = 1,
            },
            [10] = {
                Id = "61192",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61192,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Leatherworking,
                DropChance = 1,
            },
            [11] = {
                Id = "61219",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61219,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [12] = {
                Id = "61739",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61739,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [13] = {
                Id = "70001",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_70001,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [14] = {
                Id = "51217",
                Icon = "INV_Misc_Ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [15] = {
                Id = "61184",
                Icon = "Inv_weapon_shortblade_23",
                Name = IJ_LOOT_NAME_61184,
                Quality = IQ.Legendary,
                ItemSlot = IS.Quest,
                DropChance = 2,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [16] = {
                Id = "61246",
                Icon = "inv_boots_chain_08",
                Name = IJ_LOOT_NAME_61246,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "61247",
                Icon = "INV_Sword_2H_Blood_C_02",
                Name = IJ_LOOT_NAME_61247,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "61262",
                Icon = "BTNLancelot_Ring",
                Name = IJ_LOOT_NAME_61262,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "61266",
                Icon = "INV_Gauntlets_11",
                Name = IJ_LOOT_NAME_61266,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [20] = {
                Id = "61443",
                Icon = "INV_Misc_Book_13",
                Name = IJ_LOOT_NAME_61443,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Libram,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [21] = {
                Id = "61255",
                Icon = "INV_Knife_1H_Draenei_A_03",
                Name = IJ_LOOT_NAME_61255,
                Quality = IQ.Rare,
                ItemSlot = IS.MainHand,
                ItemType = IT.Dagger,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [22] = {
                Id = "61279",
                Icon = "inv_pants_mail_13",
                Name = IJ_LOOT_NAME_61279,
                Quality = IQ.Rare,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [23] = {
                Id = "61282",
                Icon = "inv_bracer_09",
                Name = IJ_LOOT_NAME_61282,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [24] = {
                Id = "61286",
                Icon = "INV_Wand_01",
                Name = IJ_LOOT_NAME_61286,
                Quality = IQ.Rare,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [25] = {
                Id = "61287",
                Icon = "INV_Chest_Plate16",
                Name = IJ_LOOT_NAME_61287,
                Quality = IQ.Rare,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [26] = {
                Id = "61294",
                Icon = "BTNEyeRing",
                Name = IJ_LOOT_NAME_61294,
                Quality = IQ.Rare,
                ItemSlot = IS.Finger,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [27] = {
                Id = "61449",
                Icon = "inv_bracer_13",
                Name = IJ_LOOT_NAME_61449,
                Quality = IQ.Rare,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [28] = {
                Id = "70102",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_70102,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Jewelcrafting,
                DropChance = 1,
            },
            [29] = {
                Id = "70226",
                Icon = "INV_Misc_Bandage_10",
                Name = IJ_LOOT_NAME_70226,
                Quality = IQ.Rare,
                ItemSlot = IS.Quest,
                DropChance = 3,
            },
            [30] = {
                Id = "42166",
                Icon = "Ability_Hunter_BeastCall",
                Name = IJ_LOOT_NAME_42166,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 10,
                LevelRequirement = 60,
            },
        },
    },
    [6] = { -- NOTE: Missing abilities
        Id = "61225",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "moroes" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "moroes" .. IMPF,
        Name = IJ_DB_RAID_KARA10_BOSS_NAME_61225,
        Story = IJ_DB_RAID_KARA10_BOSS_STORY_61225,
        MapCoordinateX = 34.9,
        MapCoordinateY = 25.3,
        Loot = {
            [1] = {
                Id = "8547",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_8547,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.FirstAid,
                DropChance = 1,
            },
            [2] = {
                Id = "13517",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_13517,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 2,
            },
            [3] = {
                Id = "58401",
                Icon = "INV_Scroll_06",
                Name = IJ_LOOT_NAME_58401,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Engineering,
                DropChance = 1,
            },
            [4] = {
                Id = "61177",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61177,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Alchemy,
                DropChance = 1,
            },
            [5] = {
                Id = "61178",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61178,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 1,
            },
            [6] = {
                Id = "61180",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61180,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [7] = {
                Id = "61189",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61189,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 2,
            },
            [8] = {
                Id = "61190",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61190,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Tailoring,
                DropChance = 2,
            },
            [9] = {
                Id = "61191",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61191,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Engineering,
                DropChance = 2,
            },
            [10] = {
                Id = "61192",
                Icon = "INV_Scroll_05",
                Name = IJ_LOOT_NAME_61192,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Leatherworking,
                DropChance = 2,
            },
            [11] = {
                Id = "61219",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61219,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 2,
            },
            [12] = {
                Id = "61739",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_61739,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 1,
            },
            [13] = {
                Id = "70001",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_70001,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Enchanting,
                DropChance = 2,
            },
            [14] = {
                Id = "51217",
                Icon = "INV_Misc_Ribbon_01",
                Name = IJ_LOOT_NAME_51217,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Transmog,
                DropChance = 100,
            },
            [15] = {
                Id = "61256",
                Icon = "inv_pants_cloth_06",
                Name = IJ_LOOT_NAME_61256,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "61257",
                Icon = "INV_Bracer_14",
                Name = IJ_LOOT_NAME_61257,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "61264",
                Icon = "Inv_staff_07",
                Name = IJ_LOOT_NAME_61264,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "61265",
                Icon = "inv_pants_leather_18",
                Name = IJ_LOOT_NAME_61265,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "61275",
                Icon = "INV_Chest_Plate04",
                Name = IJ_LOOT_NAME_61275,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [20] = {
                Id = "61277",
                Icon = "INV_Mace_33",
                Name = IJ_LOOT_NAME_61277,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [21] = {
                Id = "61284",
                Icon = "inv_shirt_16",
                Name = IJ_LOOT_NAME_61284,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [22] = {
                Id = "61299",
                Icon = "INV_Misc_Bandage_16",
                Name = IJ_LOOT_NAME_61299,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [23] = {
                Id = "61453",
                Icon = "inv_sword_draenei_05",
                Name = IJ_LOOT_NAME_61453,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [24] = {
                Id = "61454",
                Icon = "INV_Staff_Draenei_A_01",
                Name = IJ_LOOT_NAME_61454,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [25] = {
                Id = "70102",
                Icon = "INV_Misc_Note_01",
                Name = IJ_LOOT_NAME_70102,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Jewelcrafting,
                DropChance = 2,
            },
        },
    },
}

IJDB.R.KARA10 = KARA10
