IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPR = IJLib.MediaPathRaids
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "kara40\\"

local KARA40 = {}

KARA40.Name = IJ_DB_RAID_KARA40_NAME
KARA40.Story = IJ_DB_RAID_KARA40_STORY
KARA40.Type = IJLib.InstanceType.Raid
KARA40.Background = IMP .. IMPR .. instanceMediaAcronym .. "background"
KARA40.GridBackground = IMP .. IMPR .. instanceMediaAcronym .. "grid-background"
KARA40.MapId = IMI.UpperKarazhanHalls
KARA40.ZoneId = IZI.KARA402
KARA40.IconScale = 1.0
KARA40.MinLevel = 60
KARA40.MaxLevel = 60
KARA40.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.DeadwindPass,
        MapCoordinateX = 45.9,
        MapCoordinateY = 71.1,
        MapDestinationZoneId = IZI.KARA402,
    },
}
KARA40.Links = {
    [1] = {
        OriginMapContinentId = IMI.UpperKarazhanHalls,
        OriginMapZoneId = IZI.KARA401,
        OriginMapCoordinateX = 30.9,
        OriginMapCoordinateY = 14.5,
        DestinationMapContinentId = IMI.UpperKarazhanHalls,
        DestinationMapZoneId = IZI.KARA402,
        Type = IJLib.EntranceIconType.Up,
        Name = IJ_DB_RAID_KARA40_LINK_TOWER,
    },
    [2] = {
        OriginMapContinentId = IMI.UpperKarazhanHalls,
        OriginMapZoneId = IZI.KARA402,
        OriginMapCoordinateX = 76.1,
        OriginMapCoordinateY = 8.3,
        DestinationMapContinentId = IMI.UpperKarazhanHalls,
        DestinationMapZoneId = IZI.KARA401,
        Type = IJLib.EntranceIconType.Up,
        Name = IJ_DB_RAID_KARA40_LINK_ROCK,
    },
}
KARA40.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "61939",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "gnarlmoon" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "gnarlmoon" .. IMPF,
        Name = IJ_DB_RAID_KARA40_BOSS_NAME_61939,
        Story = IJ_DB_RAID_KARA40_BOSS_STORY_61939,
        MapCoordinateX = 61.7,
        MapCoordinateY = 44.8,
        MapId = IZI.KARA402,
        Loot = {
            [1] = {
                Id = "55078",
                Icon = "INV_Jewelry_Talisman_Mana",
                Name = IJ_LOOT_NAME_55078,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "55081",
                Icon = "INV_Boots_05",
                Name = IJ_LOOT_NAME_55081,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "55084",
                Icon = "INV_Misc_Cape_10",
                Name = IJ_LOOT_NAME_55084,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "55285",
                Icon = "INV_Gauntlets_05",
                Name = IJ_LOOT_NAME_55285,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "55079",
                Icon = "INV_Chest_Leather_04",
                Name = IJ_LOOT_NAME_55079,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "55080",
                Icon = "INV_Bloodmoon",
                Name = IJ_LOOT_NAME_55080,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Axe,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "55082",
                Icon = "INV_QirajIdol_War",
                Name = IJ_LOOT_NAME_55082,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Idol,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "55083",
                Icon = "inv_helmet_24",
                Name = IJ_LOOT_NAME_55083,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 60,
            },
        },
    },
    [2] = { -- NOTE: Missing abilities
        Id = "61946",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "incantagos" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "incantagos" .. IMPF,
        Name = IJ_DB_RAID_KARA40_BOSS_NAME_61946,
        Story = IJ_DB_RAID_KARA40_BOSS_STORY_61946,
        MapCoordinateX = 49.3,
        MapCoordinateY = 80.5,
        MapId = IZI.KARA402,
        MapIsBelow = true,
        Loot = {
            [1] = {
                Id = "41403",
                Icon = "INV_Enchant_ShardGlowingSmall",
                Name = IJ_LOOT_NAME_41403,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
            },
            [2] = {
                Id = "55085",
                Icon = "INV_Pants_Cloth_13",
                Name = IJ_LOOT_NAME_55085,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "55087",
                Icon = "INV_Misc_Gem_Variety_01",
                Name = IJ_LOOT_NAME_55087,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "55090",
                Icon = "INV_Shield_23",
                Name = IJ_LOOT_NAME_55090,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "55091",
                Icon = "INV_Jewelry_Ring_Saphire",
                Name = IJ_LOOT_NAME_55091,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Priest, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [6] = {
                Id = "55086",
                Icon = "INV_Belt_22",
                Name = IJ_LOOT_NAME_55086,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "55089",
                Icon = "INV_Bracer_02",
                Name = IJ_LOOT_NAME_55089,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "55099",
                Icon = "INV_Pants_Plate_18",
                Name = IJ_LOOT_NAME_55099,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "55507",
                Icon = "INV_Jewelry_Necklace_28",
                Name = IJ_LOOT_NAME_55507,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 25,
                LevelRequirement = 60,
            },
        },
    },
    [3] = { -- NOTE: Missing abilities
        Id = "61951",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "anomalus" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "anomalus" .. IMPF,
        Name = IJ_DB_RAID_KARA40_BOSS_NAME_61951,
        Story = IJ_DB_RAID_KARA40_BOSS_STORY_61951,
        MapCoordinateX = 63.4,
        MapCoordinateY = 77.2,
        MapId = IZI.KARA402,
        Loot = {
            [1] = {
                Id = "55092",
                Icon = "INV_Boots_Plate_06",
                Name = IJ_LOOT_NAME_55092,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "55095",
                Icon = "INV_Misc_Cape_18",
                Name = IJ_LOOT_NAME_55095,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "55096",
                Icon = "INV_Weapon_Crossbow_18",
                Name = IJ_LOOT_NAME_55096,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Crossbow,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "55279",
                Icon = "INV_Staff_22",
                Name = IJ_LOOT_NAME_55279,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "55093",
                Icon = "INV_Enchant_DustSoul",
                Name = IJ_LOOT_NAME_55093,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "55097",
                Icon = "INV_Jewelry_Necklace_08",
                Name = IJ_LOOT_NAME_55097,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "55098",
                Icon = "INV_Gauntlets_05",
                Name = IJ_LOOT_NAME_55098,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "55106",
                Icon = "INV_Bracer_10",
                Name = IJ_LOOT_NAME_55106,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 60,
            },
        },
    },
    [4] = { -- NOTE: Missing abilities
        Id = "61958",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "medivh" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "medivh" .. IMPF,
        Name = IJ_DB_RAID_KARA40_BOSS_NAME_61958,
        Story = IJ_DB_RAID_KARA40_BOSS_STORY_61958,
        MapCoordinateX = 27.4,
        MapCoordinateY = 39.8,
        MapId = IZI.KARA402,
        Loot = {
            [1] = {
                Id = "55094",
                Icon = "INV_Jewelry_Ring_Jade",
                Name = IJ_LOOT_NAME_55094,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "55107",
                Icon = "INV_Gauntlets_05",
                Name = IJ_LOOT_NAME_55107,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "55111",
                Icon = "Spell_Shadow_SoulGem",
                Name = IJ_LOOT_NAME_55111,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "55112",
                Icon = "INV_Jewelry_Talisman_Health",
                Name = IJ_LOOT_NAME_55112,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "55108",
                Icon = "Inv_DemonhornShoulders",
                Name = IJ_LOOT_NAME_55108,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "55109",
                Icon = "INV_trickster_leggings",
                Name = IJ_LOOT_NAME_55109,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "55110",
                Icon = "INV_Misc_Book_07",
                Name = IJ_LOOT_NAME_55110,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Libram,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "55276",
                Icon = "Inv_Mallet",
                Name = IJ_LOOT_NAME_55276,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 25,
                LevelRequirement = 60,
            },
        },
    },
    [5] = { -- NOTE: Missing abilities
        Id = "59967",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "king" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "king" .. IMPF,
        Name = IJ_DB_RAID_KARA40_BOSS_NAME_59967,
        Story = IJ_DB_RAID_KARA40_BOSS_STORY_59967,
        MapCoordinateX = 60.3,
        MapCoordinateY = 35.5,
        MapId = IZI.KARA402,
        Loot = {
            [1] = {
                Id = "55088",
                Icon = "INV_Gauntlets_05",
                Name = IJ_LOOT_NAME_55088,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "55100",
                Icon = "INV_Checkmate",
                Name = IJ_LOOT_NAME_55100,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "55101",
                Icon = "INV_Misc_Book_11",
                Name = IJ_LOOT_NAME_55101,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "55102",
                Icon = "INV_Chest_Plate08",
                Name = IJ_LOOT_NAME_55102,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "55103",
                Icon = "BTNLancelot_Ring",
                Name = IJ_LOOT_NAME_55103,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "55104",
                Icon = "INV_Boots_Chain_05",
                Name = IJ_LOOT_NAME_55104,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "55105",
                Icon = "Inv_BishopHat",
                Name = IJ_LOOT_NAME_55105,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "55274",
                Icon = "INV_Misc_Cape_21",
                Name = IJ_LOOT_NAME_55274,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "55483",
                Icon = "INV_Boots_Cloth_01",
                Name = IJ_LOOT_NAME_55483,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 50,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [10] = {
                Id = "55484",
                Icon = "INV_Boots_Cloth_01",
                Name = IJ_LOOT_NAME_55484,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 50,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Rogue, IMCL.Hunter, IMCL.Paladin, IMCL.Shaman, },
            },
            [11] = {
                Id = "20739",
                Icon = "Ability_Mount_RidingHorse",
                Name = IJ_LOOT_NAME_20739,
                Quality = IQ.Epic,
                ItemSlot = IS.Mount,
                DropChance = 2,
            },
            [12] = {
                Id = "55482",
                Icon = "INV_Jewelry_Necklace_29",
                Name = IJ_LOOT_NAME_55482,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 20,
                LevelRequirement = 60,
            },
        },
    },
    [6] = { -- NOTE: Missing abilities
        Id = "59981",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "sanv" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "sanv" .. IMPF,
        Name = IJ_DB_RAID_KARA40_BOSS_NAME_59981,
        Story = IJ_DB_RAID_KARA40_BOSS_STORY_59981,
        MapCoordinateX = 44.7,
        MapCoordinateY = 35.6,
        MapId = IZI.KARA401,
        Loot = {
            [1] = {
                Id = "55113",
                Icon = "Inv_DemonhornHelmet",
                Name = IJ_LOOT_NAME_55113,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "55114",
                Icon = "INV_QirajIdol_Sage",
                Name = IJ_LOOT_NAME_55114,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Totem,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "55115",
                Icon = "INV_Riftcarver",
                Name = IJ_LOOT_NAME_55115,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "55116",
                Icon = "INV_DraeneiSpear",
                Name = IJ_LOOT_NAME_55116,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "55117",
                Icon = "INV_Belt_22",
                Name = IJ_LOOT_NAME_55117,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "55118",
                Icon = "INV_Misc_Cape_06",
                Name = IJ_LOOT_NAME_55118,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "55119",
                Icon = "inv_helmet_24",
                Name = IJ_LOOT_NAME_55119,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "55485",
                Icon = "INV_Shoulder_17",
                Name = IJ_LOOT_NAME_55485,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 50,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [9] = {
                Id = "55486",
                Icon = "INV_Shoulder_17",
                Name = IJ_LOOT_NAME_55486,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 50,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Rogue, IMCL.Hunter, IMCL.Paladin, IMCL.Shaman, },
            },
            [10] = {
                Id = "55482",
                Icon = "INV_Jewelry_Necklace_29",
                Name = IJ_LOOT_NAME_55482,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "69001",
                Icon = "INV_Weapon_ShortBlade_16",
                Name = IJ_LOOT_NAME_69001,
                Quality = IQ.Rare,
                ItemSlot = IS.Pet,
                DropChance = 100,
            },
        },
    },
    [7] = { -- NOTE: Missing abilities
        Id = "59961",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "rupturan" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "rupturan" .. IMPF,
        Name = IJ_DB_RAID_KARA40_BOSS_NAME_59961,
        Story = IJ_DB_RAID_KARA40_BOSS_STORY_59961,
        MapCoordinateX = 49.3,
        MapCoordinateY = 25.0,
        MapId = IZI.KARA401,
        Loot = {
            [1] = {
                Id = "55120",
                Icon = "INV_ElementalFist",
                Name = IJ_LOOT_NAME_55120,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.FistWeapon,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "55121",
                Icon = "INV_Bulwark",
                Name = IJ_LOOT_NAME_55121,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "55122",
                Icon = "INV_Pants_Mail_15",
                Name = IJ_LOOT_NAME_55122,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "55123",
                Icon = "INV_Jewelry_Ring_Bronze",
                Name = IJ_LOOT_NAME_55123,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "55124",
                Icon = "INV_Misc_Gem_Diamond_02",
                Name = IJ_LOOT_NAME_55124,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "55125",
                Icon = "INV_Gauntlets_05",
                Name = IJ_LOOT_NAME_55125,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "55126",
                Icon = "inv_shoulder_14",
                Name = IJ_LOOT_NAME_55126,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "55487",
                Icon = "INV_Helmet_57",
                Name = IJ_LOOT_NAME_55487,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 50,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [9] = {
                Id = "55488",
                Icon = "INV_Helmet_57",
                Name = IJ_LOOT_NAME_55488,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 50,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Rogue, IMCL.Hunter, IMCL.Paladin, IMCL.Shaman, },
            },
            [10] = {
                Id = "55482",
                Icon = "INV_Jewelry_Necklace_29",
                Name = IJ_LOOT_NAME_55482,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 20,
                LevelRequirement = 60,
            },
        },
    },
    [8] = { -- NOTE: Missing abilities
        Id = "59991",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "kruul" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "kruul" .. IMPF,
        Name = IJ_DB_RAID_KARA40_BOSS_NAME_59991,
        Story = IJ_DB_RAID_KARA40_BOSS_STORY_59991,
        MapCoordinateX = 48.9,
        MapCoordinateY = 75.6,
        MapId = IZI.KARA401,
        Loot = {
            [1] = {
                Id = "55127",
                Icon = "Inv_Demonaxe",
                Name = IJ_LOOT_NAME_55127,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "55128",
                Icon = "ability_thunderbolt",
                Name = IJ_LOOT_NAME_55128,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "55129",
                Icon = "INV_Desecration",
                Name = IJ_LOOT_NAME_55129,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.Sword,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "55130",
                Icon = "inv_bracer_09",
                Name = IJ_LOOT_NAME_55130,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "55131",
                Icon = "INV_Misc_StoneTablet_02",
                Name = IJ_LOOT_NAME_55131,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "55132",
                Icon = "Spell_Shadow_LifeDrain",
                Name = IJ_LOOT_NAME_55132,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "55489",
                Icon = "INV_Pants_Plate_11",
                Name = IJ_LOOT_NAME_55489,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 50,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [8] = {
                Id = "55490",
                Icon = "INV_Pants_Plate_11",
                Name = IJ_LOOT_NAME_55490,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 50,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Rogue, IMCL.Hunter, IMCL.Paladin, IMCL.Shaman, },
            },
            [9] = {
                Id = "55506",
                Icon = "INV_Belt_27",
                Name = IJ_LOOT_NAME_55506,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "55510",
                Icon = "inv_stone_10",
                Name = IJ_LOOT_NAME_55510,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.ThrownWeapon,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "55511",
                Icon = "Inv_Wand_06",
                Name = IJ_LOOT_NAME_55511,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "55482",
                Icon = "INV_Jewelry_Necklace_29",
                Name = IJ_LOOT_NAME_55482,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 20,
                LevelRequirement = 60,
            },
        },
    },
    [9] = { -- NOTE: Missing abilities
        Id = "93333",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "mephistroth" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "mephistroth" .. IMPF,
        Name = IJ_DB_RAID_KARA40_BOSS_NAME_93333,
        Story = IJ_DB_RAID_KARA40_BOSS_STORY_93333,
        MapCoordinateX = 52.2,
        MapCoordinateY = 68.1,
        MapId = IZI.KARA401,
        Loot = {
            [1] = {
                Id = "41447",
                Icon = "INV_Misc_Gem_Pearl_06",
                Name = IJ_LOOT_NAME_41447,
                Quality = IQ.Legendary,
                ItemSlot = IS.Quest,
                DropChance = 100,
            },
            [2] = {
                Id = "55346",
                Icon = "INV_Weapon_BoneBow2",
                Name = IJ_LOOT_NAME_55346,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 6,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "55347",
                Icon = "INV_Thunderfall",
                Name = IJ_LOOT_NAME_55347,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 6,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "55348",
                Icon = "INV_Kirel",
                Name = IJ_LOOT_NAME_55348,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 6,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "55349",
                Icon = "INV_Nethraka",
                Name = IJ_LOOT_NAME_55349,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 6,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "55350",
                Icon = "Inv_Censer",
                Name = IJ_LOOT_NAME_55350,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 6,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "55351",
                Icon = "INV_Belt_22",
                Name = IJ_LOOT_NAME_55351,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 8,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "55352",
                Icon = "INV_Misc_Cape_20",
                Name = IJ_LOOT_NAME_55352,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 8,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "55353",
                Icon = "INV_Jewelry_Ring_Nightbreaker",
                Name = IJ_LOOT_NAME_55353,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 8,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "55354",
                Icon = "INV_Gauntlets_05",
                Name = IJ_LOOT_NAME_55354,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 8,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "55355",
                Icon = "INV_Belt_03",
                Name = IJ_LOOT_NAME_55355,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 8,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "55356",
                Icon = "INV_Bracer_18",
                Name = IJ_LOOT_NAME_55356,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 8,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "55357",
                Icon = "INV_Belt_26",
                Name = IJ_LOOT_NAME_55357,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 8,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "55512",
                Icon = "inv_shoulder_01",
                Name = IJ_LOOT_NAME_55512,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 8,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "55513",
                Icon = "INV_Chest_Chain_07",
                Name = IJ_LOOT_NAME_55513,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 8,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "55482",
                Icon = "INV_Jewelry_Necklace_29",
                Name = IJ_LOOT_NAME_55482,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "55491",
                Icon = "INV_Chest_Cloth_45",
                Name = IJ_LOOT_NAME_55491,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [18] = {
                Id = "55492",
                Icon = "INV_Chest_Cloth_45",
                Name = IJ_LOOT_NAME_55492,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Rogue, IMCL.Hunter, IMCL.Paladin, IMCL.Shaman, },
            },
            [19] = {
                Id = "55579",
                Icon = "BTNHeartAmulet",
                Name = IJ_LOOT_NAME_55579,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
            },
            [20] = {
                Id = "92082",
                Icon = "Spell_Shadow_SummonFelHunter",
                Name = IJ_LOOT_NAME_92082,
                Quality = IQ.Epic,
                ItemSlot = IS.Mount,
                DropChance = 5,
            },
        },
    },
}

IJDB.R.KARA40 = KARA40
