IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPR = IJLib.MediaPathRaids
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "naxx\\"

local NAXX = {}

NAXX.Name = IJ_DB_RAID_NAXX_NAME
NAXX.Story = IJ_DB_RAID_NAXX_STORY
NAXX.Type = IJLib.InstanceType.Raid
NAXX.Background = IMP .. IMPR .. instanceMediaAcronym .. "background"
NAXX.GridBackground = IMP .. IMPR .. instanceMediaAcronym .. "grid-background"
NAXX.MapId = IMI.Naxxramas
NAXX.ZoneId = IZI.NAXX1
NAXX.IconScale = 0.8
NAXX.MinLevel = 60
NAXX.MaxLevel = 60
NAXX.Entrances = {
    [1] = {
        MapContinentId = IMI.EasternKingdoms,
        MapZoneId = IZI.EasternPlaguelands,
        MapCoordinateX = 41.0,
        MapCoordinateY = 29.5,
        MapDestinationZoneId = IZI.NAXX1,
    },
}
NAXX.Links = {
    [1] = {
        OriginMapContinentId = IMI.Naxxramas,
        OriginMapZoneId = IZI.NAXX1,
        OriginMapCoordinateX = 52.8,
        OriginMapCoordinateY = 49.3,
        DestinationMapContinentId = IMI.Naxxramas,
        DestinationMapZoneId = IZI.NAXX2,
        Type = IJLib.EntranceIconType.Up,
        Name = IJ_DB_RAID_NAXX_LINK_NECROPOLIS,
    },
    [2] = {
        OriginMapContinentId = IMI.Naxxramas,
        OriginMapZoneId = IZI.NAXX2,
        OriginMapCoordinateX = 73.6,
        OriginMapCoordinateY = 72.3,
        DestinationMapContinentId = IMI.Naxxramas,
        DestinationMapZoneId = IZI.NAXX1,
        Type = IJLib.EntranceIconType.Down,
        Name = IJ_DB_RAID_NAXX_LINK_NAXX,
    },
}
NAXX.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "16028",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "patchwerk" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "patchwerk" .. IMPF,
        Name = IJ_DB_RAID_NAXX_BOSS_NAME_16028,
        Story = IJ_DB_RAID_NAXX_BOSS_STORY_16028,
        MapCoordinateX = 38.3,
        MapCoordinateY = 45.7,
        MapId = IZI.NAXX1,
        Loot = {
            [1] = {
                Id = "22726",
                Icon = "INV_Qiraj_JewelBlessed",
                Name = IJ_LOOT_NAME_22726,
                Quality = IQ.Legendary,
                ItemSlot = IS.Reagent,
                DropChance = 30,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [2] = {
                Id = "22354",
                Icon = "INV_Misc_Desecrated_PlateShoulder",
                Name = IJ_LOOT_NAME_22354,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [3] = {
                Id = "22361",
                Icon = "INV_Misc_Desecrated_MailShoulder",
                Name = IJ_LOOT_NAME_22361,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [4] = {
                Id = "22368",
                Icon = "INV_Misc_Desecrated_ClothShoulder",
                Name = IJ_LOOT_NAME_22368,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [5] = {
                Id = "22815",
                Icon = "Inv_axe_2h_stratholme_d_01",
                Name = IJ_LOOT_NAME_22815,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "22818",
                Icon = "INV_Shield_27",
                Name = IJ_LOOT_NAME_22818,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "22820",
                Icon = "INV_Wand_1H_Stratholme_D_01",
                Name = IJ_LOOT_NAME_22820,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "22960",
                Icon = "INV_Misc_Cape_Naxxramas_02",
                Name = IJ_LOOT_NAME_22960,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "22961",
                Icon = "INV_Jewelry_Ring_49Naxxramas",
                Name = IJ_LOOT_NAME_22961,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 60,
            },
        },
    },
    [2] = { -- NOTE: Missing abilities
        Id = "15931",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "grobbulus" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "grobbulus" .. IMPF,
        Name = IJ_DB_RAID_NAXX_BOSS_NAME_15931,
        Story = IJ_DB_RAID_NAXX_BOSS_STORY_15931,
        MapCoordinateX = 47.0,
        MapCoordinateY = 29.6,
        MapId = IZI.NAXX1,
        Loot = {
            [1] = {
                Id = "22726",
                Icon = "INV_Qiraj_JewelBlessed",
                Name = IJ_LOOT_NAME_22726,
                Quality = IQ.Legendary,
                ItemSlot = IS.Reagent,
                DropChance = 30,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [2] = {
                Id = "22354",
                Icon = "INV_Misc_Desecrated_PlateShoulder",
                Name = IJ_LOOT_NAME_22354,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [3] = {
                Id = "22361",
                Icon = "INV_Misc_Desecrated_MailShoulder",
                Name = IJ_LOOT_NAME_22361,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [4] = {
                Id = "22368",
                Icon = "INV_Misc_Desecrated_ClothShoulder",
                Name = IJ_LOOT_NAME_22368,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [5] = {
                Id = "22803",
                Icon = "INV_knife_1h_stratholme_d_02",
                Name = IJ_LOOT_NAME_22803,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "22810",
                Icon = "INV_weapon_rifle_13",
                Name = IJ_LOOT_NAME_22810,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Gun,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "22967",
                Icon = "INV_Shoulder_14",
                Name = IJ_LOOT_NAME_22967,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Mail,
                DropChance = 20,
            },
            [8] = {
                Id = "22968",
                Icon = "INV_Shoulder_14",
                Name = IJ_LOOT_NAME_22968,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 20,
            },
            [9] = {
                Id = "22988",
                Icon = "INV_Mace_1H_Stratholme_D_02",
                Name = IJ_LOOT_NAME_22988,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 20,
                LevelRequirement = 60,
            },
        },
    },
    [3] = { -- NOTE: Missing abilities
        Id = "15932",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "gluth" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "gluth" .. IMPF,
        Name = IJ_DB_RAID_NAXX_BOSS_NAME_15932,
        Story = IJ_DB_RAID_NAXX_BOSS_STORY_15932,
        MapCoordinateX = 37.9,
        MapCoordinateY = 27.0,
        MapId = IZI.NAXX1,
        Loot = {
            [1] = {
                Id = "22726",
                Icon = "INV_Qiraj_JewelBlessed",
                Name = IJ_LOOT_NAME_22726,
                Quality = IQ.Legendary,
                ItemSlot = IS.Reagent,
                DropChance = 30,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [2] = {
                Id = "22354",
                Icon = "INV_Misc_Desecrated_PlateShoulder",
                Name = IJ_LOOT_NAME_22354,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 8,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [3] = {
                Id = "22355",
                Icon = "INV_Misc_Desecrated_PlateBracer",
                Name = IJ_LOOT_NAME_22355,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 8,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [4] = {
                Id = "22356",
                Icon = "INV_Misc_Desecrated_PlateBelt",
                Name = IJ_LOOT_NAME_22356,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 8,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [5] = {
                Id = "22358",
                Icon = "INV_Misc_Desecrated_PlateBoots",
                Name = IJ_LOOT_NAME_22358,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 8,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [6] = {
                Id = "22361",
                Icon = "INV_Misc_Desecrated_MailShoulder",
                Name = IJ_LOOT_NAME_22361,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 8,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [7] = {
                Id = "22362",
                Icon = "INV_Misc_Desecrated_MailBracer",
                Name = IJ_LOOT_NAME_22362,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 8,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [8] = {
                Id = "22363",
                Icon = "INV_Misc_Desecrated_MailBelt",
                Name = IJ_LOOT_NAME_22363,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 8,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [9] = {
                Id = "22365",
                Icon = "INV_Misc_Desecrated_MailBoots",
                Name = IJ_LOOT_NAME_22365,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 8,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [10] = {
                Id = "22368",
                Icon = "INV_Misc_Desecrated_ClothShoulder",
                Name = IJ_LOOT_NAME_22368,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 8,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [11] = {
                Id = "22369",
                Icon = "INV_Misc_Desecrated_ClothBracer",
                Name = IJ_LOOT_NAME_22369,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 8,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [12] = {
                Id = "22370",
                Icon = "INV_Misc_Desecrated_ClothBelt",
                Name = IJ_LOOT_NAME_22370,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 8,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [13] = {
                Id = "22372",
                Icon = "INV_Misc_Desecrated_ClothBoots",
                Name = IJ_LOOT_NAME_22372,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 8,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [14] = {
                Id = "22813",
                Icon = "INV_Sword_46",
                Name = IJ_LOOT_NAME_22813,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "22981",
                Icon = "INV_Jewelry_Necklace_27Naxxramas",
                Name = IJ_LOOT_NAME_22981,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "22983",
                Icon = "INV_Shoulder_05",
                Name = IJ_LOOT_NAME_22983,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "22994",
                Icon = "INV_Offhand_Stratholme_A_02",
                Name = IJ_LOOT_NAME_22994,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "23075",
                Icon = "INV_Armor_Shield_Naxxramas_D_01",
                Name = IJ_LOOT_NAME_23075,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 20,
                LevelRequirement = 60,
            },
        },
    },
    [4] = { -- NOTE: Missing abilities
        Id = "15928",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "thaddius" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "thaddius" .. IMPF,
        Name = IJ_DB_RAID_NAXX_BOSS_NAME_15928,
        Story = IJ_DB_RAID_NAXX_BOSS_STORY_15928,
        MapCoordinateX = 29.0,
        MapCoordinateY = 13.3,
        MapId = IZI.NAXX1,
        Loot = {
            [1] = {
                Id = "22353",
                Icon = "INV_Misc_Desecrated_PlateHelm",
                Name = IJ_LOOT_NAME_22353,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [2] = {
                Id = "22360",
                Icon = "INV_Misc_Desecrated_MailHelm",
                Name = IJ_LOOT_NAME_22360,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [3] = {
                Id = "22367",
                Icon = "INV_Misc_Desecrated_ClothHelm",
                Name = IJ_LOOT_NAME_22367,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [4] = {
                Id = "22801",
                Icon = "INV_Staff_31",
                Name = IJ_LOOT_NAME_22801,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "22808",
                Icon = "INV_Mace_1H_Stratholme_D_01",
                Name = IJ_LOOT_NAME_22808,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "23000",
                Icon = "INV_Chest_Chain_15",
                Name = IJ_LOOT_NAME_23000,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "23001",
                Icon = "INV_Trinket_Naxxramas02",
                Name = IJ_LOOT_NAME_23001,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "23070",
                Icon = "INV_Pants_08",
                Name = IJ_LOOT_NAME_23070,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
        },
    },
    [5] = { -- NOTE: Missing abilities
        Id = "15956",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "anubrekhan" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "anubrekhan" .. IMPF,
        Name = IJ_DB_RAID_NAXX_BOSS_NAME_15956,
        Story = IJ_DB_RAID_NAXX_BOSS_STORY_15956,
        MapCoordinateX = 54.9,
        MapCoordinateY = 29.0,
        MapId = IZI.NAXX1,
        Loot = {
            [1] = {
                Id = "22726",
                Icon = "INV_Qiraj_JewelBlessed",
                Name = IJ_LOOT_NAME_22726,
                Quality = IQ.Legendary,
                ItemSlot = IS.Reagent,
                DropChance = 30,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [2] = {
                Id = "22355",
                Icon = "INV_Misc_Desecrated_PlateBracer",
                Name = IJ_LOOT_NAME_22355,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [3] = {
                Id = "22362",
                Icon = "INV_Misc_Desecrated_MailBracer",
                Name = IJ_LOOT_NAME_22362,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [4] = {
                Id = "22369",
                Icon = "INV_Misc_Desecrated_ClothBracer",
                Name = IJ_LOOT_NAME_22369,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [5] = {
                Id = "22935",
                Icon = "INV_Jewelry_Amulet_04",
                Name = IJ_LOOT_NAME_22935,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "22936",
                Icon = "INV_Bracer_17",
                Name = IJ_LOOT_NAME_22936,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "22937",
                Icon = "INV_Offhand_Naxxramas_D_01",
                Name = IJ_LOOT_NAME_22937,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "22938",
                Icon = "INV_Misc_Cape_Naxxramas_02",
                Name = IJ_LOOT_NAME_22938,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "22939",
                Icon = "INV_Jewelry_Ring_50Naxxramas",
                Name = IJ_LOOT_NAME_22939,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "42167",
                Icon = "INV_Misc_MonsterSpiderCarapace_01",
                Name = IJ_LOOT_NAME_42167,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 20,
                LevelRequirement = 60,
            },
        },
    },
    [6] = { -- NOTE: Missing abilities
        Id = "15953",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "faerlina" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "faerlina" .. IMPF,
        Name = IJ_DB_RAID_NAXX_BOSS_NAME_15953,
        Story = IJ_DB_RAID_NAXX_BOSS_STORY_15953,
        MapCoordinateX = 62.3,
        MapCoordinateY = 23.2,
        MapId = IZI.NAXX1,
        Loot = {
            [1] = {
                Id = "22726",
                Icon = "INV_Qiraj_JewelBlessed",
                Name = IJ_LOOT_NAME_22726,
                Quality = IQ.Legendary,
                ItemSlot = IS.Reagent,
                DropChance = 30,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [2] = {
                Id = "22355",
                Icon = "INV_Misc_Desecrated_PlateBracer",
                Name = IJ_LOOT_NAME_22355,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [3] = {
                Id = "22362",
                Icon = "INV_Misc_Desecrated_MailBracer",
                Name = IJ_LOOT_NAME_22362,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [4] = {
                Id = "22369",
                Icon = "INV_Misc_Desecrated_ClothBracer",
                Name = IJ_LOOT_NAME_22369,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [5] = {
                Id = "22806",
                Icon = "INV_Sword_60",
                Name = IJ_LOOT_NAME_22806,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "22940",
                Icon = "INV_Shoulder_16",
                Name = IJ_LOOT_NAME_22940,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "22941",
                Icon = "INV_Shoulder_07",
                Name = IJ_LOOT_NAME_22941,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "22942",
                Icon = "INV_Mace_29",
                Name = IJ_LOOT_NAME_22942,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "22943",
                Icon = "INV_Jewelry_Necklace_29Naxxramas",
                Name = IJ_LOOT_NAME_22943,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 60,
            },
        },
    },
    [7] = { -- NOTE: Missing abilities
        Id = "15952",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "maexxna" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "maexxna" .. IMPF,
        Name = IJ_DB_RAID_NAXX_BOSS_NAME_15952,
        Story = IJ_DB_RAID_NAXX_BOSS_STORY_15952,
        MapCoordinateX = 75.9,
        MapCoordinateY = 11.9,
        MapId = IZI.NAXX1,
        Loot = {
            [1] = {
                Id = "22726",
                Icon = "INV_Qiraj_JewelBlessed",
                Name = IJ_LOOT_NAME_22726,
                Quality = IQ.Legendary,
                ItemSlot = IS.Reagent,
                DropChance = 30,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [2] = {
                Id = "22357",
                Icon = "INV_Misc_Desecrated_PlateGloves",
                Name = IJ_LOOT_NAME_22357,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [3] = {
                Id = "22364",
                Icon = "INV_Misc_Desecrated_MailGlove",
                Name = IJ_LOOT_NAME_22364,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [4] = {
                Id = "22371",
                Icon = "INV_Misc_Desecrated_ClothGlove",
                Name = IJ_LOOT_NAME_22371,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [5] = {
                Id = "22804",
                Icon = "INV_knife_1h_stratholme_d_01",
                Name = IJ_LOOT_NAME_22804,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "22807",
                Icon = "INV_Sword_11",
                Name = IJ_LOOT_NAME_22807,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "22947",
                Icon = "INV_Jewelry_Necklace_28Naxxramas",
                Name = IJ_LOOT_NAME_22947,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "22954",
                Icon = "INV_Trinket_Naxxramas04",
                Name = IJ_LOOT_NAME_22954,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "23220",
                Icon = "INV_Chest_Cloth_46",
                Name = IJ_LOOT_NAME_23220,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "37012",
                Icon = "INV_Misc_MonsterSpiderCarapace_01",
                Name = IJ_LOOT_NAME_37012,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Pet,
                DropChance = 30,
            },
        },
    },
    [8] = { -- NOTE: Missing abilities
        Id = "15954",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "noth" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "noth" .. IMPF,
        Name = IJ_DB_RAID_NAXX_BOSS_NAME_15954,
        Story = IJ_DB_RAID_NAXX_BOSS_STORY_15954,
        MapCoordinateX = 56.5,
        MapCoordinateY = 73.3,
        MapId = IZI.NAXX1,
        Loot = {
            [1] = {
                Id = "22726",
                Icon = "INV_Qiraj_JewelBlessed",
                Name = IJ_LOOT_NAME_22726,
                Quality = IQ.Legendary,
                ItemSlot = IS.Reagent,
                DropChance = 30,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [2] = {
                Id = "22356",
                Icon = "INV_Misc_Desecrated_PlateBelt",
                Name = IJ_LOOT_NAME_22356,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [3] = {
                Id = "22363",
                Icon = "INV_Misc_Desecrated_MailBelt",
                Name = IJ_LOOT_NAME_22363,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [4] = {
                Id = "22370",
                Icon = "INV_Misc_Desecrated_ClothBelt",
                Name = IJ_LOOT_NAME_22370,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [5] = {
                Id = "22816",
                Icon = "INV_Axe_08",
                Name = IJ_LOOT_NAME_22816,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Axe,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "23005",
                Icon = "INV_Relics_TotemofLife",
                Name = IJ_LOOT_NAME_23005,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Totem,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "23006",
                Icon = "INV_Relics_LibramofGrace",
                Name = IJ_LOOT_NAME_23006,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Libram,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "23028",
                Icon = "INV_Jewelry_Ring_35",
                Name = IJ_LOOT_NAME_23028,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "23029",
                Icon = "INV_Offhand_Naxxramas_04",
                Name = IJ_LOOT_NAME_23029,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "23030",
                Icon = "INV_Misc_Cape_Naxxramas_01",
                Name = IJ_LOOT_NAME_23030,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "23031",
                Icon = "INV_Jewelry_Ring_53Naxxramas",
                Name = IJ_LOOT_NAME_23031,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 14,
                LevelRequirement = 60,
            },
        },
    },
    [9] = { -- NOTE: Missing abilities
        Id = "15936",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "heigan" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "heigan" .. IMPF,
        Name = IJ_DB_RAID_NAXX_BOSS_NAME_15936,
        Story = IJ_DB_RAID_NAXX_BOSS_STORY_15936,
        MapCoordinateX = 65.6,
        MapCoordinateY = 67.0,
        MapId = IZI.NAXX1,
        Loot = {
            [1] = {
                Id = "22726",
                Icon = "INV_Qiraj_JewelBlessed",
                Name = IJ_LOOT_NAME_22726,
                Quality = IQ.Legendary,
                ItemSlot = IS.Reagent,
                DropChance = 30,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [2] = {
                Id = "22356",
                Icon = "INV_Misc_Desecrated_PlateBelt",
                Name = IJ_LOOT_NAME_22356,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [3] = {
                Id = "22363",
                Icon = "INV_Misc_Desecrated_MailBelt",
                Name = IJ_LOOT_NAME_22363,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [4] = {
                Id = "22370",
                Icon = "INV_Misc_Desecrated_ClothBelt",
                Name = IJ_LOOT_NAME_22370,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [5] = {
                Id = "23019",
                Icon = "INV_Helmet_06",
                Name = IJ_LOOT_NAME_23019,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "23033",
                Icon = "INV_Helmet_20",
                Name = IJ_LOOT_NAME_23033,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "23035",
                Icon = "INV_Helmet_50",
                Name = IJ_LOOT_NAME_23035,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "23036",
                Icon = "INV_Jewelry_Necklace_30Naxxramas",
                Name = IJ_LOOT_NAME_23036,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "23068",
                Icon = "INV_Pants_Plate_20",
                Name = IJ_LOOT_NAME_23068,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 20,
                LevelRequirement = 60,
            },
        },
    },
    [10] = { -- NOTE: Missing abilities
        Id = "16011",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "loatheb" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "loatheb" .. IMPF,
        Name = IJ_DB_RAID_NAXX_BOSS_NAME_16011,
        Story = IJ_DB_RAID_NAXX_BOSS_STORY_16011,
        MapCoordinateX = 81.0,
        MapCoordinateY = 56.4,
        MapId = IZI.NAXX1,
        Loot = {
            [1] = {
                Id = "22726",
                Icon = "INV_Qiraj_JewelBlessed",
                Name = IJ_LOOT_NAME_22726,
                Quality = IQ.Legendary,
                ItemSlot = IS.Reagent,
                DropChance = 30,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [2] = {
                Id = "22352",
                Icon = "INV_Misc_Desecrated_PlatePants",
                Name = IJ_LOOT_NAME_22352,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [3] = {
                Id = "22359",
                Icon = "INV_Misc_Desecrated_MailPants",
                Name = IJ_LOOT_NAME_22359,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [4] = {
                Id = "22366",
                Icon = "INV_Misc_Desecrated_ClothPants",
                Name = IJ_LOOT_NAME_22366,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [5] = {
                Id = "22800",
                Icon = "INV_Staff_13",
                Name = IJ_LOOT_NAME_22800,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "23037",
                Icon = "INV_Jewelry_Ring_52Naxxramas",
                Name = IJ_LOOT_NAME_23037,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "23038",
                Icon = "INV_Jewelry_Ring_48Naxxramas",
                Name = IJ_LOOT_NAME_23038,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "23039",
                Icon = "Inv_spear_09",
                Name = IJ_LOOT_NAME_23039,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "23042",
                Icon = "inv_trinket_naxxramas07",
                Name = IJ_LOOT_NAME_23042,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 60,
            },
        },
    },
    [11] = { -- NOTE: Missing abilities
        Id = "16061",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "razuvious" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "razuvious" .. IMPF,
        Name = IJ_DB_RAID_NAXX_BOSS_NAME_16061,
        Story = IJ_DB_RAID_NAXX_BOSS_STORY_16061,
        MapCoordinateX = 36.3,
        MapCoordinateY = 66.9,
        MapId = IZI.NAXX1,
        Loot = {
            [1] = {
                Id = "22726",
                Icon = "INV_Qiraj_JewelBlessed",
                Name = IJ_LOOT_NAME_22726,
                Quality = IQ.Legendary,
                ItemSlot = IS.Reagent,
                DropChance = 30,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [2] = {
                Id = "22358",
                Icon = "INV_Misc_Desecrated_PlateBoots",
                Name = IJ_LOOT_NAME_22358,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [3] = {
                Id = "22365",
                Icon = "INV_Misc_Desecrated_MailBoots",
                Name = IJ_LOOT_NAME_22365,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [4] = {
                Id = "22372",
                Icon = "INV_Misc_Desecrated_ClothBoots",
                Name = IJ_LOOT_NAME_22372,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [5] = {
                Id = "23004",
                Icon = "INV_Relics_IdolofHealth",
                Name = IJ_LOOT_NAME_23004,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Idol,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "23009",
                Icon = "INV_Wand_1H_Stratholme_D_01",
                Name = IJ_LOOT_NAME_23009,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "23014",
                Icon = "INV_Sword_07",
                Name = IJ_LOOT_NAME_23014,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "23017",
                Icon = "INV_Misc_Cape_Naxxramas_01",
                Name = IJ_LOOT_NAME_23017,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "23018",
                Icon = "INV_Jewelry_Ring_50Naxxramas",
                Name = IJ_LOOT_NAME_23018,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "23219",
                Icon = "INV_Belt_13",
                Name = IJ_LOOT_NAME_23219,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 60,
            },
        },
    },
    [12] = { -- NOTE: Missing abilities
        Id = "16060",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "gothik" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "gothik" .. IMPF,
        Name = IJ_DB_RAID_NAXX_BOSS_NAME_16060,
        Story = IJ_DB_RAID_NAXX_BOSS_STORY_16060,
        MapCoordinateX = 49.4,
        MapCoordinateY = 72.3,
        MapId = IZI.NAXX1,
        Loot = {
            [1] = {
                Id = "22726",
                Icon = "INV_Qiraj_JewelBlessed",
                Name = IJ_LOOT_NAME_22726,
                Quality = IQ.Legendary,
                ItemSlot = IS.Reagent,
                DropChance = 30,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [2] = {
                Id = "22358",
                Icon = "INV_Misc_Desecrated_PlateBoots",
                Name = IJ_LOOT_NAME_22358,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [3] = {
                Id = "22365",
                Icon = "INV_Misc_Desecrated_MailBoots",
                Name = IJ_LOOT_NAME_22365,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [4] = {
                Id = "22372",
                Icon = "INV_Misc_Desecrated_ClothBoots",
                Name = IJ_LOOT_NAME_22372,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [5] = {
                Id = "23020",
                Icon = "INV_Helmet_04",
                Name = IJ_LOOT_NAME_23020,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "23021",
                Icon = "INV_Bracer_07",
                Name = IJ_LOOT_NAME_23021,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "23023",
                Icon = "INV_Jewelry_Necklace_29Naxxramas",
                Name = IJ_LOOT_NAME_23023,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "23032",
                Icon = "INV_Helmet_53",
                Name = IJ_LOOT_NAME_23032,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "23073",
                Icon = "INV_Boots_08",
                Name = IJ_LOOT_NAME_23073,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 60,
            },
        },
    },
    [13] = { -- NOTE: Missing abilities
        Id = "16065",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "horsemen" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "horsemen" .. IMPF,
        Name = IJ_DB_RAID_NAXX_BOSS_NAME_16065,
        Story = IJ_DB_RAID_NAXX_BOSS_STORY_16065,
        MapCoordinateX = 28.8,
        MapCoordinateY = 85.8,
        MapId = IZI.NAXX1,
        Loot = {
            [1] = {
                Id = "22349",
                Icon = "INV_Misc_Desecrated_PlateChest",
                Name = IJ_LOOT_NAME_22349,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [2] = {
                Id = "22350",
                Icon = "INV_Misc_Desecrated_MailChest",
                Name = IJ_LOOT_NAME_22350,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [3] = {
                Id = "22351",
                Icon = "INV_Misc_Desecrated_ClothChest",
                Name = IJ_LOOT_NAME_22351,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [4] = {
                Id = "22726",
                Icon = "INV_Qiraj_JewelBlessed",
                Name = IJ_LOOT_NAME_22726,
                Quality = IQ.Legendary,
                ItemSlot = IS.Reagent,
                DropChance = 30,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, IMCL.Druid, },
            },
            [5] = {
                Id = "22691",
                Icon = "INV_Sword_2H_AshbringerCorrupt",
                Name = IJ_LOOT_NAME_22691,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "22809",
                Icon = "INV_Mace_26",
                Name = IJ_LOOT_NAME_22809,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "22811",
                Icon = "INV_Weapon_Bow_13",
                Name = IJ_LOOT_NAME_22811,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Bow,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "23025",
                Icon = "INV_Jewelry_Ring_48Naxxramas",
                Name = IJ_LOOT_NAME_23025,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "23027",
                Icon = "inv_trinket_naxxramas08",
                Name = IJ_LOOT_NAME_23027,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "23071",
                Icon = "INV_Pants_Leather_09",
                Name = IJ_LOOT_NAME_23071,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 0,
                LevelRequirement = 60,
            },
        },
    },
    [14] = { -- NOTE: Missing abilities
        Id = "15989",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "sapphiron" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "sapphiron" .. IMPF,
        Name = IJ_DB_RAID_NAXX_BOSS_NAME_15989,
        Story = IJ_DB_RAID_NAXX_BOSS_STORY_15989,
        MapCoordinateX = 56.2,
        MapCoordinateY = 67.2,
        MapId = IZI.NAXX2,
        Loot = {
            [1] = {
                Id = "23040",
                Icon = "INV_Trinket_Naxxramas05",
                Name = IJ_LOOT_NAME_23040,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "23041",
                Icon = "INV_Trinket_Naxxramas03",
                Name = IJ_LOOT_NAME_23041,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "23043",
                Icon = "INV_Shield_26",
                Name = IJ_LOOT_NAME_23043,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "23045",
                Icon = "INV_Misc_Cape_Naxxramas_03",
                Name = IJ_LOOT_NAME_23045,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "23046",
                Icon = "INV_Trinket_Naxxramas06",
                Name = IJ_LOOT_NAME_23046,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "23047",
                Icon = "INV_Trinket_Naxxramas01",
                Name = IJ_LOOT_NAME_23047,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "23048",
                Icon = "INV_Offhand_Naxxramas_02",
                Name = IJ_LOOT_NAME_23048,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "23049",
                Icon = "INV_Offhand_Naxxramas_03",
                Name = IJ_LOOT_NAME_23049,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "23050",
                Icon = "INV_Misc_Cape_Naxxramas_03",
                Name = IJ_LOOT_NAME_23050,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "23242",
                Icon = "INV_Weapon_Hand_03",
                Name = IJ_LOOT_NAME_23242,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.FistWeapon,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "23545",
                Icon = "Spell_Shadow_DarkRitual",
                Name = IJ_LOOT_NAME_23545,
                Quality = IQ.Epic,
                ItemSlot = IS.Enchantment,
                DropChance = 50,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "23547",
                Icon = "Spell_Shadow_DeadofNight",
                Name = IJ_LOOT_NAME_23547,
                Quality = IQ.Epic,
                ItemSlot = IS.Enchantment,
                DropChance = 50,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "23548",
                Icon = "Spell_Shadow_DeathPact",
                Name = IJ_LOOT_NAME_23548,
                Quality = IQ.Epic,
                ItemSlot = IS.Enchantment,
                DropChance = 50,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "23549",
                Icon = "Spell_Shadow_AntiShadow",
                Name = IJ_LOOT_NAME_23549,
                Quality = IQ.Epic,
                ItemSlot = IS.Enchantment,
                DropChance = 50,
                LevelRequirement = 60,
            },
        },
    },
    [15] = { -- NOTE: Missing abilities
        Id = "15990",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "kelthuzad" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "kelthuzad" .. IMPF,
        Name = IJ_DB_RAID_NAXX_BOSS_NAME_15990,
        Story = IJ_DB_RAID_NAXX_BOSS_STORY_15990,
        MapCoordinateX = 36.4,
        MapCoordinateY = 22.6,
        MapId = IZI.NAXX2,
        Loot = {
            [1] = {
                Id = "22520",
                Icon = "INV_Misc_Urn_01",
                Name = IJ_LOOT_NAME_22520,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "22798",
                Icon = "INV_Mace_25",
                Name = IJ_LOOT_NAME_22798,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 9,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "22799",
                Icon = "INV_Staff_15",
                Name = IJ_LOOT_NAME_22799,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 9,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "22802",
                Icon = "INV_Weapon_Shortblade_37",
                Name = IJ_LOOT_NAME_22802,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 9,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "22812",
                Icon = "INV_Weapon_Crossbow_12",
                Name = IJ_LOOT_NAME_22812,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Crossbow,
                DropChance = 9,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "22819",
                Icon = "INV_Shield_28",
                Name = IJ_LOOT_NAME_22819,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 9,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "22821",
                Icon = "INV_Wand_1H_Stratholme_D_02",
                Name = IJ_LOOT_NAME_22821,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 9,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "23053",
                Icon = "INV_Jewelry_Necklace_28Naxxramas",
                Name = IJ_LOOT_NAME_23053,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 9,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "23054",
                Icon = "INV_Sword_61",
                Name = IJ_LOOT_NAME_23054,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 9,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "23056",
                Icon = "INV_Mace_27",
                Name = IJ_LOOT_NAME_23056,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Mace,
                DropChance = 9,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "23057",
                Icon = "INV_Jewelry_Necklace_29Naxxramas",
                Name = IJ_LOOT_NAME_23057,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 9,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "23577",
                Icon = "INV_Sword_62",
                Name = IJ_LOOT_NAME_23577,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 9,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "55581",
                Icon = "INV_Jewelry_Ring_15",
                Name = IJ_LOOT_NAME_55581,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Warrior, IMCL.Rogue, },
            },
            [14] = {
                Id = "55582",
                Icon = "INV_Jewelry_Ring_27",
                Name = IJ_LOOT_NAME_55582,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Mage, IMCL.Warlock, IMCL.Priest, },
            },
            [15] = {
                Id = "55583",
                Icon = "INV_Jewelry_Ring_16",
                Name = IJ_LOOT_NAME_55583,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 33,
                LevelRequirement = 60,
                ClassRestriction = { IMCL.Hunter, IMCL.Druid, IMCL.Paladin, IMCL.Shaman, },
            },
            [16] = {
                Id = "36666",
                Icon = "INV_Misc_MonsterSpiderCarapace_01",
                Name = IJ_LOOT_NAME_36666,
                Quality = IQ.Epic,
                ItemSlot = IS.Mount,
                DropChance = 1,
            },
            [17] = {
                Id = "81283",
                Icon = "INV_Misc_Ribbon_01",
                Name = IJ_LOOT_NAME_81283,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Pet,
                DropChance = 100,
            },
        },
    },
}

IJDB.R.NAXX = NAXX
