IJDB = IJDB or {}

local IS = IJLib.ItemSlot
local IT = IJLib.ItemType
local IQ = IJLib.Quality
local IMP = IJLib.MediaPath
local IMPR = IJLib.MediaPathRaids
local IMPP = IJLib.MediaPathPortrait
local IMPF = IJLib.MediaPathFrame
local IMAF = IJLib.AbilityFlags
local IMCL = IJLib.Classes
local IMI = IJLib.MapId
local IZI = IJLib.ZoneId

local instanceMediaAcronym = "world\\"

local WORLD = {}

WORLD.Name = IJ_DB_RAID_WORLD_NAME
WORLD.Story = IJ_DB_RAID_WORLD_STORY
WORLD.Type = IJLib.InstanceType.Raid
WORLD.Background = IMP .. IMPR .. instanceMediaAcronym .. "background"
WORLD.GridBackground = IMP .. IMPR .. instanceMediaAcronym .. "grid-background"
WORLD.MapId = IMI.World
WORLD.IconScale = 0.8
WORLD.MinLevel = 60
WORLD.MaxLevel = 60
WORLD.Bosses = {
    [1] = { -- NOTE: Missing abilities
        Id = "6109",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "azuregos" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "azuregos" .. IMPF,
        Name = IJ_DB_RAID_WORLD_BOSS_NAME_6109,
        Story = IJ_DB_RAID_WORLD_BOSS_STORY_6109,
        MapCoordinateX = 53.4,
        MapCoordinateY = 81.5,
        MapId = IMI.Kalimdor,
        MapZoneId = IZI.Azshara,
        Loot = {
            [1] = {
                Id = "18704",
                Icon = "INV_Misc_Bandage_04",
                Name = IJ_LOOT_NAME_18704,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "17070",
                Icon = "INV_Weapon_ShortBlade_06",
                Name = IJ_LOOT_NAME_17070,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "18202",
                Icon = "INV_Misc_MonsterClaw_04",
                Name = IJ_LOOT_NAME_18202,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.FistWeapon,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "18208",
                Icon = "INV_Misc_Cape_04",
                Name = IJ_LOOT_NAME_18208,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "18541",
                Icon = "INV_Misc_Cape_06",
                Name = IJ_LOOT_NAME_18541,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "18542",
                Icon = "INV_Sword_41",
                Name = IJ_LOOT_NAME_18542,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedSword,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "18545",
                Icon = "INV_Pants_08",
                Name = IJ_LOOT_NAME_18545,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "18547",
                Icon = "INV_Belt_31",
                Name = IJ_LOOT_NAME_18547,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "19130",
                Icon = "INV_Wand_01",
                Name = IJ_LOOT_NAME_19130,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "19131",
                Icon = "INV_Boots_Cloth_14",
                Name = IJ_LOOT_NAME_19131,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "19132",
                Icon = "INV_Crown_01",
                Name = IJ_LOOT_NAME_19132,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 10,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "83544",
                Icon = "INV_Scroll_04",
                Name = IJ_LOOT_NAME_83544,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Leatherworking,
                DropChance = 40,
            },
        },
    },
    [2] = { -- NOTE: Missing abilities
        Id = "59963",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "clackora" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "clackora" .. IMPF,
        Name = IJ_DB_RAID_WORLD_BOSS_NAME_59963,
        Story = IJ_DB_RAID_WORLD_BOSS_STORY_59963,
        MapCoordinateX = 69.0,
        MapCoordinateY = 9.2,
        MapId = IMI.Kalimdor,
        MapZoneId = IZI.Azshara,
        Loot = {
            [1] = {
                Id = "55494",
                Icon = "inv_misc_birdbeck_02",
                Name = IJ_LOOT_NAME_55494,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.FistWeapon,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "55495",
                Icon = "inv_spear_04",
                Name = IJ_LOOT_NAME_55495,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Polearm,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "55498",
                Icon = "inv_misc_shell_03",
                Name = IJ_LOOT_NAME_55498,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "55501",
                Icon = "INV_Ore_Arcanite_02",
                Name = IJ_LOOT_NAME_55501,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "55504",
                Icon = "INV_Generic_Anchor",
                Name = IJ_LOOT_NAME_55504,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedMace,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "55496",
                Icon = "INV_Jewelry_Necklace_25",
                Name = IJ_LOOT_NAME_55496,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "55497",
                Icon = "INV_QirajIdol_Night",
                Name = IJ_LOOT_NAME_55497,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Idol,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "55499",
                Icon = "INV_Belt_35",
                Name = IJ_LOOT_NAME_55499,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "55500",
                Icon = "INV_Bracer_17",
                Name = IJ_LOOT_NAME_55500,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "55502",
                Icon = "INV_Pants_12",
                Name = IJ_LOOT_NAME_55502,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "55503",
                Icon = "INV_Jewelry_Ring_38",
                Name = IJ_LOOT_NAME_55503,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "92020",
                Icon = "INV_Misc_Birdbeck_02",
                Name = IJ_LOOT_NAME_92020,
                Quality = IQ.Rare,
                ItemSlot = IS.Pet,
                DropChance = 5,
            },
        },
    },
    [3] = { -- NOTE: Missing abilities
        Id = "92213",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "concavius" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "concavius" .. IMPF,
        Name = IJ_DB_RAID_WORLD_BOSS_NAME_92213,
        Story = IJ_DB_RAID_WORLD_BOSS_STORY_92213,
        MapCoordinateX = 82.1,
        MapCoordinateY = 79.9,
        MapId = IMI.Kalimdor,
        MapZoneId = IZI.Desolace,
        Loot = {
            [1] = {
                Id = "83233",
                Icon = "inv_archaeology_70_highborne_inertleystonecharm",
                Name = IJ_LOOT_NAME_83233,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "83234",
                Icon = "INV_Jewelry_Necklace_17",
                Name = IJ_LOOT_NAME_83234,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "83237",
                Icon = "INV_jewelry_ring_AhnQiraj_01",
                Name = IJ_LOOT_NAME_83237,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "83238",
                Icon = "INV_Jewelry_Ring_AhnQiraj_02",
                Name = IJ_LOOT_NAME_83238,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "83239",
                Icon = "INV_Jewelry_Ring_53Naxxramas",
                Name = IJ_LOOT_NAME_83239,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "83240",
                Icon = "INV_Jewelry_Ring_48Naxxramas",
                Name = IJ_LOOT_NAME_83240,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 0,
                LevelRequirement = 60,
            },
        },
    },
    [4] = { -- NOTE: Missing abilities
        Id = "80936",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "reaver" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "reaver" .. IMPF,
        Name = IJ_DB_RAID_WORLD_BOSS_NAME_80936,
        Story = IJ_DB_RAID_WORLD_BOSS_STORY_80936,
        MapCoordinateX = 48.1,
        MapCoordinateY = 75.8,
        MapId = IMI.EasternKingdoms,
        MapZoneId = IZI.DeadwindPass,
        Loot = {
            [1] = {
                Id = "51769",
                Icon = "inv_helmet_06",
                Name = IJ_LOOT_NAME_51769,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "51770",
                Icon = "INV_Shoulder_11",
                Name = IJ_LOOT_NAME_51770,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "51771",
                Icon = "inv_chest_plate08",
                Name = IJ_LOOT_NAME_51771,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Plate,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "51772",
                Icon = "INV_Gauntlets_09",
                Name = IJ_LOOT_NAME_51772,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "51773",
                Icon = "INV_Belt_13",
                Name = IJ_LOOT_NAME_51773,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "51774",
                Icon = "inv_boots_plate_05",
                Name = IJ_LOOT_NAME_51774,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "51775",
                Icon = "inv_pants_04",
                Name = IJ_LOOT_NAME_51775,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "51776",
                Icon = "INV_Pants_11",
                Name = IJ_LOOT_NAME_51776,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "51777",
                Icon = "INV_misc_bone_taurenskull_01",
                Name = IJ_LOOT_NAME_51777,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "51778",
                Icon = "INV_Staff_05",
                Name = IJ_LOOT_NAME_51778,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "51779",
                Icon = "INV_Axe_14",
                Name = IJ_LOOT_NAME_51779,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.TwoHandedAxe,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "51780",
                Icon = "INV_weapon_rifle_13",
                Name = IJ_LOOT_NAME_51780,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Gun,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "51781",
                Icon = "INV_Shoulder_02",
                Name = IJ_LOOT_NAME_51781,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Cloth,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "51782",
                Icon = "INV_Jewelry_Ring_15",
                Name = IJ_LOOT_NAME_51782,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "51783",
                Icon = "INV_Bracer_07",
                Name = IJ_LOOT_NAME_51783,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "51784",
                Icon = "INV_Belt_22",
                Name = IJ_LOOT_NAME_51784,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "51785",
                Icon = "INV_Belt_35",
                Name = IJ_LOOT_NAME_51785,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Mail,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "51786",
                Icon = "INV_Chest_Chain_17",
                Name = IJ_LOOT_NAME_51786,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [19] = {
                Id = "51787",
                Icon = "INV_Shoulder_05",
                Name = IJ_LOOT_NAME_51787,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [20] = {
                Id = "51788",
                Icon = "INV_Helmet_30",
                Name = IJ_LOOT_NAME_51788,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [21] = {
                Id = "51789",
                Icon = "INV_Helmet_13",
                Name = IJ_LOOT_NAME_51789,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [22] = {
                Id = "51796",
                Icon = "INV_Shield_02",
                Name = IJ_LOOT_NAME_51796,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [23] = {
                Id = "51797",
                Icon = "INV_Misc_MonsterClaw_03",
                Name = IJ_LOOT_NAME_51797,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.FistWeapon,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [24] = {
                Id = "51798",
                Icon = "INV_Gauntlets_08",
                Name = IJ_LOOT_NAME_51798,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Idol,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [25] = {
                Id = "51799",
                Icon = "INV_Misc_Book_04",
                Name = IJ_LOOT_NAME_51799,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Libram,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [26] = {
                Id = "51800",
                Icon = "INV_QirajIdol_Sage",
                Name = IJ_LOOT_NAME_51800,
                Quality = IQ.Epic,
                ItemSlot = IS.Relic,
                ItemType = IT.Totem,
                DropChance = 0,
                LevelRequirement = 60,
            },
        },
    },
    [5] = { -- NOTE: Missing abilities
        Id = "12397",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "kazzak" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "kazzak" .. IMPF,
        Name = IJ_DB_RAID_WORLD_BOSS_NAME_12397,
        Story = IJ_DB_RAID_WORLD_BOSS_STORY_12397,
        MapCoordinateX = 36.0,
        MapCoordinateY = 75.1,
        MapId = IMI.EasternKingdoms,
        MapZoneId = IZI.BlastedLands,
        Loot = {
            [1] = {
                Id = "17112",
                Icon = "INV_Hammer_05",
                Name = IJ_LOOT_NAME_17112,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "18204",
                Icon = "INV_Misc_Cape_07",
                Name = IJ_LOOT_NAME_18204,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "18543",
                Icon = "INV_Jewelry_Ring_20",
                Name = IJ_LOOT_NAME_18543,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "18546",
                Icon = "INV_Helmet_18",
                Name = IJ_LOOT_NAME_18546,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Mail,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "19133",
                Icon = "INV_Pants_06",
                Name = IJ_LOOT_NAME_19133,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "17111",
                Icon = "INV_Jewelry_Talisman_01",
                Name = IJ_LOOT_NAME_17111,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "17113",
                Icon = "INV_Staff_Goldfeathered_01",
                Name = IJ_LOOT_NAME_17113,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "18544",
                Icon = "INV_Gauntlets_22",
                Name = IJ_LOOT_NAME_18544,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "19134",
                Icon = "INV_Belt_16",
                Name = IJ_LOOT_NAME_19134,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "19135",
                Icon = "INV_Bracer_07",
                Name = IJ_LOOT_NAME_19135,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 20,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "16045",
                Icon = "INV_Scroll_06",
                Name = IJ_LOOT_NAME_16045,
                Quality = IQ.Rare,
                ItemSlot = IS.Profession,
                ItemType = IT.Engineering,
                DropChance = 1,
            },
            [12] = {
                Id = "83547",
                Icon = "INV_Scroll_04",
                Name = IJ_LOOT_NAME_83547,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 0,
            },
            [13] = {
                Id = "83545",
                Icon = "INV_Scroll_04",
                Name = IJ_LOOT_NAME_83545,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Tailoring,
                DropChance = 40,
            },
        },
    },
    [6] = { -- NOTE: Missing abilities
        Id = "91799",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "moo" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "moo" .. IMPF,
        Name = IJ_DB_RAID_WORLD_BOSS_NAME_91799,
        Story = IJ_DB_RAID_WORLD_BOSS_STORY_91799,
        MapCoordinateX = 50.7,
        MapCoordinateY = 54.7,
        MapId = IMI.MoomooGrove,
        Abilities = {
            [1] = {
                Id = "moomoo",
                Icon = "Spell_Nature_Polymorph_Cow",
                Name = IJ_DB_RAID_WORLD_BOSS_91799_ABILITY_NAME_moomoo,
                Effect = IJ_DB_RAID_WORLD_BOSS_91799_ABILITY_EFFECT_moomoo,
                Flags = { IMAF.Tank, IMAF.Deadly, },
            },
        },
        Loot = {
            [1] = {
                Id = "51261",
                Icon = "INV_Misc_Bell_01",
                Name = IJ_LOOT_NAME_51261,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Pet,
                DropChance = 100,
            },
            [2] = {
                Id = "60486",
                Icon = "INV_Misc_Fish_02",
                Name = IJ_LOOT_NAME_60486,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 25,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "60487",
                Icon = "INV_Misc_Cape_20",
                Name = IJ_LOOT_NAME_60487,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 50,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "60489",
                Icon = "INV_Helmet_28",
                Name = IJ_LOOT_NAME_60489,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 50,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "60490",
                Icon = "INV_Helmet_28",
                Name = IJ_LOOT_NAME_60490,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 50,
                LevelRequirement = 60,
            },
        },
    },
    [7] = { -- NOTE: Missing abilities
        Id = "16184",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "overseer" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "overseer" .. IMPF,
        Name = IJ_DB_RAID_WORLD_BOSS_NAME_16184,
        Story = IJ_DB_RAID_WORLD_BOSS_STORY_16184,
        MapCoordinateX = 9.6,
        MapCoordinateY = 35.2,
        MapId = IMI.EasternKingdoms,
        MapZoneId = IZI.EasternPlaguelands,
        Loot = {
            [1] = {
                Id = "83547",
                Icon = "INV_Scroll_04",
                Name = IJ_LOOT_NAME_83547,
                Quality = IQ.Epic,
                ItemSlot = IS.Profession,
                ItemType = IT.Blacksmithing,
                DropChance = 5,
            },
            [2] = {
                Id = "51730",
                Icon = "INV_Misc_Cape_18",
                Name = IJ_LOOT_NAME_51730,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "51731",
                Icon = "INV_Misc_Cape_01",
                Name = IJ_LOOT_NAME_51731,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "51732",
                Icon = "INV_Misc_Cape_11",
                Name = IJ_LOOT_NAME_51732,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "51733",
                Icon = "INV_Misc_Cape_20",
                Name = IJ_LOOT_NAME_51733,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "51734",
                Icon = "INV_Misc_Cape_21",
                Name = IJ_LOOT_NAME_51734,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "51735",
                Icon = "INV_Wand_01",
                Name = IJ_LOOT_NAME_51735,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Wand,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "51736",
                Icon = "inv_chest_cloth_39",
                Name = IJ_LOOT_NAME_51736,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "51737",
                Icon = "INV_Chest_Cloth_02",
                Name = IJ_LOOT_NAME_51737,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "51738",
                Icon = "INV_Chest_Leather_05",
                Name = IJ_LOOT_NAME_51738,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Leather,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "51740",
                Icon = "INV_Helmet_06",
                Name = IJ_LOOT_NAME_51740,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "51739",
                Icon = "INV_Fabric_Wool_02",
                Name = IJ_LOOT_NAME_51739,
                Quality = IQ.Uncommon,
                ItemSlot = IS.Pet,
                DropChance = 100,
            },
        },
    },
    [8] = { -- NOTE: Missing abilities
        Id = "80935",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "ostarius" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "ostarius" .. IMPF,
        Name = IJ_DB_RAID_WORLD_BOSS_NAME_80935,
        Story = IJ_DB_RAID_WORLD_BOSS_STORY_80935,
        MapCoordinateX = 36.5,
        MapCoordinateY = 80.7,
        MapId = IMI.Kalimdor,
        MapZoneId = IZI.Tanaris,
        Loot = {
            [1] = {
                Id = "83480",
                Icon = "INV_Misc_Book_07",
                Name = IJ_LOOT_NAME_83480,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "83481",
                Icon = "INV_Mace_08",
                Name = IJ_LOOT_NAME_83481,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "83482",
                Icon = "INV_Wand_06",
                Name = IJ_LOOT_NAME_83482,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "83483",
                Icon = "INV_Helmet_03",
                Name = IJ_LOOT_NAME_83483,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Plate,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "83484",
                Icon = "INV_Jewelry_Necklace_14",
                Name = IJ_LOOT_NAME_83484,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "83532",
                Icon = "INV_Bracer_07",
                Name = IJ_LOOT_NAME_83532,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "83485",
                Icon = "INV_Gauntlets_16",
                Name = IJ_LOOT_NAME_83485,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "83486",
                Icon = "INV_Misc_Cape_07",
                Name = IJ_LOOT_NAME_83486,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "83487",
                Icon = "INV_Sword_01",
                Name = IJ_LOOT_NAME_83487,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.Sword,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "83488",
                Icon = "INV_Boots_Chain_02",
                Name = IJ_LOOT_NAME_83488,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "83530",
                Icon = "INV_Helmet_63",
                Name = IJ_LOOT_NAME_83530,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 0,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "83531",
                Icon = "INV_Belt_17",
                Name = IJ_LOOT_NAME_83531,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Leather,
                DropChance = 0,
                LevelRequirement = 60,
            },
        },
    },
    [9] = { -- NOTE: Missing abilities
        Id = "14889",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "emeriss" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "emeriss" .. IMPF,
        Name = IJ_DB_RAID_WORLD_BOSS_NAME_14889,
        Story = IJ_DB_RAID_WORLD_BOSS_STORY_14889,
        MapCoordinateX = 46.4,
        MapCoordinateY = 36.1,
        MapId = IMI.EasternKingdoms,
        MapZoneId = IZI.Duskwood,
        Loot = {
            [1] = {
                Id = "20644",
                Icon = "Spell_Shadow_Haunting",
                Name = IJ_LOOT_NAME_20644,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "20579",
                Icon = "INV_Misc_Cape_17",
                Name = IJ_LOOT_NAME_20579,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "20580",
                Icon = "INV_Mace_20",
                Name = IJ_LOOT_NAME_20580,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "20581",
                Icon = "INV_Staff_36",
                Name = IJ_LOOT_NAME_20581,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "20582",
                Icon = "INV_Misc_Orb_01",
                Name = IJ_LOOT_NAME_20582,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "20615",
                Icon = "INV_Bracer_15",
                Name = IJ_LOOT_NAME_20615,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "20616",
                Icon = "INV_Bracer_14",
                Name = IJ_LOOT_NAME_20616,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "20617",
                Icon = "INV_Pants_Mail_08",
                Name = IJ_LOOT_NAME_20617,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "20618",
                Icon = "INV_Gauntlets_17",
                Name = IJ_LOOT_NAME_20618,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "20619",
                Icon = "INV_Boots_Plate_04",
                Name = IJ_LOOT_NAME_20619,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "20599",
                Icon = "INV_Weapon_Crossbow_11",
                Name = IJ_LOOT_NAME_20599,
                Quality = IQ.Epic,
                ItemSlot = IS.Ranged,
                ItemType = IT.Crossbow,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "20621",
                Icon = "INV_Boots_Chain_11",
                Name = IJ_LOOT_NAME_20621,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "20622",
                Icon = "INV_Jewelry_Necklace_18",
                Name = IJ_LOOT_NAME_20622,
                Quality = IQ.Epic,
                ItemSlot = IS.Neck,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "20623",
                Icon = "INV_Helmet_17",
                Name = IJ_LOOT_NAME_20623,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "20624",
                Icon = "INV_Jewelry_Ring_38",
                Name = IJ_LOOT_NAME_20624,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "65100",
                Icon = "INV_Boots_Cloth_04",
                Name = IJ_LOOT_NAME_65100,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "65101",
                Icon = "INV_Belt_16",
                Name = IJ_LOOT_NAME_65101,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 60,
            },
        },
    },
    [10] = { -- NOTE: Missing abilities
        Id = "14888",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "lethon" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "lethon" .. IMPF,
        Name = IJ_DB_RAID_WORLD_BOSS_NAME_14888,
        Story = IJ_DB_RAID_WORLD_BOSS_STORY_14888,
        MapCoordinateX = 51.2,
        MapCoordinateY = 10.9,
        MapId = IMI.Kalimdor,
        MapZoneId = IZI.Feralas,
        Loot = {
            [1] = {
                Id = "20644",
                Icon = "Spell_Shadow_Haunting",
                Name = IJ_LOOT_NAME_20644,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "20625",
                Icon = "INV_Belt_15",
                Name = IJ_LOOT_NAME_20625,
                Quality = IQ.Epic,
                ItemSlot = IS.Waist,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "20626",
                Icon = "INV_Bracer_07",
                Name = IJ_LOOT_NAME_20626,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "20627",
                Icon = "INV_Pants_Leather_11",
                Name = IJ_LOOT_NAME_20627,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "20628",
                Icon = "INV_Helmet_43",
                Name = IJ_LOOT_NAME_20628,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Leather,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "20629",
                Icon = "INV_Boots_Chain_08",
                Name = IJ_LOOT_NAME_20629,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Mail,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "20630",
                Icon = "INV_Gauntlets_29",
                Name = IJ_LOOT_NAME_20630,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Plate,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "65102",
                Icon = "INV_Helmet_04",
                Name = IJ_LOOT_NAME_65102,
                Quality = IQ.Epic,
                ItemSlot = IS.Head,
                ItemType = IT.Cloth,
                DropChance = 14,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "20579",
                Icon = "INV_Misc_Cape_17",
                Name = IJ_LOOT_NAME_20579,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "20580",
                Icon = "INV_Mace_20",
                Name = IJ_LOOT_NAME_20580,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "20581",
                Icon = "INV_Staff_36",
                Name = IJ_LOOT_NAME_20581,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "20582",
                Icon = "INV_Misc_Orb_01",
                Name = IJ_LOOT_NAME_20582,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "20615",
                Icon = "INV_Bracer_15",
                Name = IJ_LOOT_NAME_20615,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "20616",
                Icon = "INV_Bracer_14",
                Name = IJ_LOOT_NAME_20616,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "20617",
                Icon = "INV_Pants_Mail_08",
                Name = IJ_LOOT_NAME_20617,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "20618",
                Icon = "INV_Gauntlets_17",
                Name = IJ_LOOT_NAME_20618,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "20619",
                Icon = "INV_Boots_Plate_04",
                Name = IJ_LOOT_NAME_20619,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
            },
        },
    },
    [11] = { -- NOTE: Missing abilities
        Id = "14890",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "taerar" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "taerar" .. IMPF,
        Name = IJ_DB_RAID_WORLD_BOSS_NAME_14890,
        Story = IJ_DB_RAID_WORLD_BOSS_STORY_14890,
        MapCoordinateX = 94.2,
        MapCoordinateY = 35.7,
        MapId = IMI.Kalimdor,
        MapZoneId = IZI.Ashenvale,
        Loot = {
            [1] = {
                Id = "20644",
                Icon = "Spell_Shadow_Haunting",
                Name = IJ_LOOT_NAME_20644,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "20579",
                Icon = "INV_Misc_Cape_17",
                Name = IJ_LOOT_NAME_20579,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "20580",
                Icon = "INV_Mace_20",
                Name = IJ_LOOT_NAME_20580,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "20581",
                Icon = "INV_Staff_36",
                Name = IJ_LOOT_NAME_20581,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "20582",
                Icon = "INV_Misc_Orb_01",
                Name = IJ_LOOT_NAME_20582,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "20615",
                Icon = "INV_Bracer_15",
                Name = IJ_LOOT_NAME_20615,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "20616",
                Icon = "INV_Bracer_14",
                Name = IJ_LOOT_NAME_20616,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "20617",
                Icon = "INV_Pants_Mail_08",
                Name = IJ_LOOT_NAME_20617,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "20618",
                Icon = "INV_Gauntlets_17",
                Name = IJ_LOOT_NAME_20618,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "20619",
                Icon = "INV_Boots_Plate_04",
                Name = IJ_LOOT_NAME_20619,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "20577",
                Icon = "INV_Sword_44",
                Name = IJ_LOOT_NAME_20577,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Sword,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "20631",
                Icon = "INV_Boots_Cloth_05",
                Name = IJ_LOOT_NAME_20631,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Cloth,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "20632",
                Icon = "INV_Jewelry_Ring_04",
                Name = IJ_LOOT_NAME_20632,
                Quality = IQ.Epic,
                ItemSlot = IS.Finger,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "20633",
                Icon = "INV_Shoulder_29",
                Name = IJ_LOOT_NAME_20633,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "20634",
                Icon = "INV_Boots_08",
                Name = IJ_LOOT_NAME_20634,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Leather,
                DropChance = 17,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "65105",
                Icon = "INV_Misc_MonsterScales_11",
                Name = IJ_LOOT_NAME_65105,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 17,
                LevelRequirement = 60,
            },
        },
    },
    [12] = { -- NOTE: Missing abilities
        Id = "14887",
        Portrait = IMP .. IMPR .. instanceMediaAcronym .. "ysondre" .. IMPP,
        Frame = IMP .. IMPR .. instanceMediaAcronym .. "ysondre" .. IMPF,
        Name = IJ_DB_RAID_WORLD_BOSS_NAME_14887,
        Story = IJ_DB_RAID_WORLD_BOSS_STORY_14887,
        MapCoordinateX = 62.3,
        MapCoordinateY = 23.3,
        MapId = IMI.EasternKingdoms,
        MapZoneId = IZI.TheHinterlands,
        Loot = {
            [1] = {
                Id = "20644",
                Icon = "Spell_Shadow_Haunting",
                Name = IJ_LOOT_NAME_20644,
                Quality = IQ.Epic,
                ItemSlot = IS.Quest,
                DropChance = 100,
                LevelRequirement = 60,
            },
            [2] = {
                Id = "20578",
                Icon = "INV_Weapon_ShortBlade_22",
                Name = IJ_LOOT_NAME_20578,
                Quality = IQ.Epic,
                ItemSlot = IS.OneHand,
                ItemType = IT.Dagger,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [3] = {
                Id = "20635",
                Icon = "INV_Chest_Cloth_39",
                Name = IJ_LOOT_NAME_20635,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Cloth,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [4] = {
                Id = "20636",
                Icon = "INV_Misc_Gem_Stone_01",
                Name = IJ_LOOT_NAME_20636,
                Quality = IQ.Epic,
                ItemSlot = IS.Trinket,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [5] = {
                Id = "20637",
                Icon = "INV_Shoulder_11",
                Name = IJ_LOOT_NAME_20637,
                Quality = IQ.Epic,
                ItemSlot = IS.Shoulder,
                ItemType = IT.Plate,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [6] = {
                Id = "20638",
                Icon = "INV_Pants_Mail_15",
                Name = IJ_LOOT_NAME_20638,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [7] = {
                Id = "20639",
                Icon = "INV_Pants_Plate_05",
                Name = IJ_LOOT_NAME_20639,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Plate,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [8] = {
                Id = "65103",
                Icon = "INV_Shield_21",
                Name = IJ_LOOT_NAME_65103,
                Quality = IQ.Epic,
                ItemSlot = IS.OffHand,
                ItemType = IT.Shield,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [9] = {
                Id = "65104",
                Icon = "INV_Chest_Plate07",
                Name = IJ_LOOT_NAME_65104,
                Quality = IQ.Epic,
                ItemSlot = IS.Chest,
                ItemType = IT.Mail,
                DropChance = 12,
                LevelRequirement = 60,
            },
            [10] = {
                Id = "20579",
                Icon = "INV_Misc_Cape_17",
                Name = IJ_LOOT_NAME_20579,
                Quality = IQ.Epic,
                ItemSlot = IS.Back,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [11] = {
                Id = "20580",
                Icon = "INV_Mace_20",
                Name = IJ_LOOT_NAME_20580,
                Quality = IQ.Epic,
                ItemSlot = IS.MainHand,
                ItemType = IT.Mace,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [12] = {
                Id = "20581",
                Icon = "INV_Staff_36",
                Name = IJ_LOOT_NAME_20581,
                Quality = IQ.Epic,
                ItemSlot = IS.TwoHand,
                ItemType = IT.Staff,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [13] = {
                Id = "20582",
                Icon = "INV_Misc_Orb_01",
                Name = IJ_LOOT_NAME_20582,
                Quality = IQ.Epic,
                ItemSlot = IS.HeldInOffHand,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [14] = {
                Id = "20615",
                Icon = "INV_Bracer_15",
                Name = IJ_LOOT_NAME_20615,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Leather,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [15] = {
                Id = "20616",
                Icon = "INV_Bracer_14",
                Name = IJ_LOOT_NAME_20616,
                Quality = IQ.Epic,
                ItemSlot = IS.Wrist,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [16] = {
                Id = "20617",
                Icon = "INV_Pants_Mail_08",
                Name = IJ_LOOT_NAME_20617,
                Quality = IQ.Epic,
                ItemSlot = IS.Legs,
                ItemType = IT.Mail,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [17] = {
                Id = "20618",
                Icon = "INV_Gauntlets_17",
                Name = IJ_LOOT_NAME_20618,
                Quality = IQ.Epic,
                ItemSlot = IS.Hands,
                ItemType = IT.Cloth,
                DropChance = 11,
                LevelRequirement = 60,
            },
            [18] = {
                Id = "20619",
                Icon = "INV_Boots_Plate_04",
                Name = IJ_LOOT_NAME_20619,
                Quality = IQ.Epic,
                ItemSlot = IS.Feet,
                ItemType = IT.Plate,
                DropChance = 11,
                LevelRequirement = 60,
            },
        },
    },
}

IJDB.R.WORLD = WORLD
